from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class ABBFNMPEFPJ(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    ABBFNMPEFPJ_NONE: _ClassVar[ABBFNMPEFPJ]
    ABBFNMPEFPJ_CREATE_CONNECT: _ClassVar[ABBFNMPEFPJ]
    ABBFNMPEFPJ_START_GAME: _ClassVar[ABBFNMPEFPJ]
    ABBFNMPEFPJ_PING: _ClassVar[ABBFNMPEFPJ]
    ABBFNMPEFPJ_FINISH_GAME: _ClassVar[ABBFNMPEFPJ]
    ABBFNMPEFPJ_SNAP_SHOT: _ClassVar[ABBFNMPEFPJ]
    ABBFNMPEFPJ_ACTION: _ClassVar[ABBFNMPEFPJ]
    ABBFNMPEFPJ_SNAP_SHOT_FOR_DEBUG_LOG: _ClassVar[ABBFNMPEFPJ]
ABBFNMPEFPJ_NONE: ABBFNMPEFPJ
ABBFNMPEFPJ_CREATE_CONNECT: ABBFNMPEFPJ
ABBFNMPEFPJ_START_GAME: ABBFNMPEFPJ
ABBFNMPEFPJ_PING: ABBFNMPEFPJ
ABBFNMPEFPJ_FINISH_GAME: ABBFNMPEFPJ
ABBFNMPEFPJ_SNAP_SHOT: ABBFNMPEFPJ
ABBFNMPEFPJ_ACTION: ABBFNMPEFPJ
ABBFNMPEFPJ_SNAP_SHOT_FOR_DEBUG_LOG: ABBFNMPEFPJ
