# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/ABHOCFILGJL.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/ABHOCFILGJL.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import EMEAJKNIEFA_pb2 as genshin_dot_packet_dot_proto_dot_EMEAJKNIEFA__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/ABHOCFILGJL.proto\x1a&genshin/packet/proto/EMEAJKNIEFA.proto\"\xa8\x03\n\x0b\x41\x42HOCFILGJL\x12\x32\n\x0bIPFOIMLFPIK\x18\r \x03(\x0b\x32\x1d.ABHOCFILGJL.IPFOIMLFPIKEntry\x12\x32\n\x0b\x43\x44JJOHNDCHN\x18\n \x03(\x0b\x32\x1d.ABHOCFILGJL.CDJJOHNDCHNEntry\x12\x13\n\x0b\x45\x43\x43KEBKEIOG\x18\x0b \x03(\r\x12!\n\x0bMGMGOLJINMN\x18\x02 \x03(\x0b\x32\x0c.EMEAJKNIEFA\x12\x13\n\x0bNGHBFMBJGCL\x18\x08 \x01(\x04\x12\x13\n\x0bKKLADHFCBFJ\x18\x0f \x01(\r\x12\x13\n\x0b\x41IPKCNHFDFN\x18\x05 \x01(\r\x12\x13\n\x0b\x42\x45GLAPFGFAF\x18\x06 \x01(\r\x12\x13\n\x0bPNNMIHFHFNK\x18\t \x01(\x04\x12\x13\n\x0bNMGAMKNNOJD\x18\x07 \x01(\r\x12\x13\n\x0bGPCDKNKNMNL\x18\x01 \x01(\r\x1a\x32\n\x10IPFOIMLFPIKEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x1a\x32\n\x10\x43\x44JJOHNDCHNEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.ABHOCFILGJL_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ABHOCFILGJL_IPFOIMLFPIKENTRY']._loaded_options = None
  _globals['_ABHOCFILGJL_IPFOIMLFPIKENTRY']._serialized_options = b'8\001'
  _globals['_ABHOCFILGJL_CDJJOHNDCHNENTRY']._loaded_options = None
  _globals['_ABHOCFILGJL_CDJJOHNDCHNENTRY']._serialized_options = b'8\001'
  _globals['_ABHOCFILGJL']._serialized_start=83
  _globals['_ABHOCFILGJL']._serialized_end=507
  _globals['_ABHOCFILGJL_IPFOIMLFPIKENTRY']._serialized_start=405
  _globals['_ABHOCFILGJL_IPFOIMLFPIKENTRY']._serialized_end=455
  _globals['_ABHOCFILGJL_CDJJOHNDCHNENTRY']._serialized_start=457
  _globals['_ABHOCFILGJL_CDJJOHNDCHNENTRY']._serialized_end=507
# @@protoc_insertion_point(module_scope)
