# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/AbilityMixinRecoverInfo.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/AbilityMixinRecoverInfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import MassivePropSyncInfo_pb2 as genshin_dot_packet_dot_proto_dot_MassivePropSyncInfo__pb2
from genshin.packet.proto import BreakoutSnapShot_pb2 as genshin_dot_packet_dot_proto_dot_BreakoutSnapShot__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2genshin/packet/proto/AbilityMixinRecoverInfo.proto\x1a.genshin/packet/proto/MassivePropSyncInfo.proto\x1a+genshin/packet/proto/BreakoutSnapShot.proto\"\x89\x02\n\x17\x41\x62ilityMixinRecoverInfo\x12\x10\n\x08local_id\x18\x03 \x01(\r\x12\x11\n\tdata_list\x18\x04 \x03(\r\x12\x1e\n\x16is_serverbuff_modifier\x18\x05 \x01(\x08\x12/\n\x11massive_prop_list\x18\x06 \x03(\x0b\x32\x14.MassivePropSyncInfo\x12-\n\x12\x62reakout_snap_shot\x18\x07 \x01(\x0b\x32\x11.BreakoutSnapShot\x12\x1e\n\x14instanced_ability_id\x18\x01 \x01(\rH\x00\x12\x1f\n\x15instanced_modifier_id\x18\x02 \x01(\rH\x00\x42\x08\n\x06SourceB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.AbilityMixinRecoverInfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_ABILITYMIXINRECOVERINFO']._serialized_start=148
  _globals['_ABILITYMIXINRECOVERINFO']._serialized_end=413
# @@protoc_insertion_point(module_scope)
