# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/AbilitySyncStateInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import AbilityAppliedAbility_pb2 as genshin_dot_packet_dot_proto_dot_AbilityAppliedAbility__pb2
from genshin.packet.proto import AbilityAppliedModifier_pb2 as genshin_dot_packet_dot_proto_dot_AbilityAppliedModifier__pb2
from genshin.packet.proto import AbilityMixinRecoverInfo_pb2 as genshin_dot_packet_dot_proto_dot_AbilityMixinRecoverInfo__pb2
from genshin.packet.proto import AbilityScalarValueEntry_pb2 as genshin_dot_packet_dot_proto_dot_AbilityScalarValueEntry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/genshin/packet/proto/AbilitySyncStateInfo.proto\x1a\x30genshin/packet/proto/AbilityAppliedAbility.proto\x1a\x31genshin/packet/proto/AbilityAppliedModifier.proto\x1a\x32genshin/packet/proto/AbilityMixinRecoverInfo.proto\x1a\x32genshin/packet/proto/AbilityScalarValueEntry.proto\"\xb5\x02\n\x14\x41\x62ilitySyncStateInfo\x12\x11\n\tis_inited\x18\x01 \x01(\x08\x12\x33\n\x11\x64ynamic_value_map\x18\x02 \x03(\x0b\x32\x18.AbilityScalarValueEntry\x12\x31\n\x11\x61pplied_abilities\x18\x03 \x03(\x0b\x32\x16.AbilityAppliedAbility\x12\x32\n\x11\x61pplied_modifiers\x18\x04 \x03(\x0b\x32\x17.AbilityAppliedModifier\x12\x35\n\x13mixin_recover_infos\x18\x05 \x03(\x0b\x32\x18.AbilityMixinRecoverInfo\x12\x37\n\x15sgv_dynamic_value_map\x18\x06 \x03(\x0b\x32\x18.AbilityScalarValueEntryB\x16\n\x14org.sorapointa.protob\x06proto3')



_ABILITYSYNCSTATEINFO = DESCRIPTOR.message_types_by_name['AbilitySyncStateInfo']
AbilitySyncStateInfo = _reflection.GeneratedProtocolMessageType('AbilitySyncStateInfo', (_message.Message,), {
  'DESCRIPTOR' : _ABILITYSYNCSTATEINFO,
  '__module__' : 'genshin.packet.proto.AbilitySyncStateInfo_pb2'
  # @@protoc_insertion_point(class_scope:AbilitySyncStateInfo)
  })
_sym_db.RegisterMessage(AbilitySyncStateInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _ABILITYSYNCSTATEINFO._serialized_start=257
  _ABILITYSYNCSTATEINFO._serialized_end=566
# @@protoc_insertion_point(module_scope)
