# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/AbilityString.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(genshin/packet/proto/AbilityString.proto\"6\n\rAbilityString\x12\r\n\x03str\x18\x01 \x01(\tH\x00\x12\x0e\n\x04hash\x18\x02 \x01(\rH\x00\x42\x06\n\x04typeB\x16\n\x14org.sorapointa.protob\x06proto3')



_ABILITYSTRING = DESCRIPTOR.message_types_by_name['AbilityString']
AbilityString = _reflection.GeneratedProtocolMessageType('AbilityString', (_message.Message,), {
  'DESCRIPTOR' : _ABILITYSTRING,
  '__module__' : 'genshin.packet.proto.AbilityString_pb2'
  # @@protoc_insertion_point(class_scope:AbilityString)
  })
_sym_db.RegisterMessage(AbilityString)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _ABILITYSTRING._serialized_start=44
  _ABILITYSTRING._serialized_end=98
# @@protoc_insertion_point(module_scope)
