# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/AbilityActionDestroyTile.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import Vector_pb2 as genshin_dot_packet_dot_proto_dot_Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3genshin/packet/proto/AbilityActionDestroyTile.proto\x1a!genshin/packet/proto/Vector.proto\"F\n\x18\x41\x62ilityActionDestroyTile\x12\x14\n\x03rot\x18\x03 \x01(\x0b\x32\x07.Vector\x12\x14\n\x03pos\x18\x01 \x01(\x0b\x32\x07.VectorB\x16\n\x14org.sorapointa.protob\x06proto3')



_ABILITYACTIONDESTROYTILE = DESCRIPTOR.message_types_by_name['AbilityActionDestroyTile']
AbilityActionDestroyTile = _reflection.GeneratedProtocolMessageType('AbilityActionDestroyTile', (_message.Message,), {
  'DESCRIPTOR' : _ABILITYACTIONDESTROYTILE,
  '__module__' : 'genshin.packet.proto.AbilityActionDestroyTile_pb2'
  # @@protoc_insertion_point(class_scope:AbilityActionDestroyTile)
  })
_sym_db.RegisterMessage(AbilityActionDestroyTile)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _ABILITYACTIONDESTROYTILE._serialized_start=90
  _ABILITYACTIONDESTROYTILE._serialized_end=160
# @@protoc_insertion_point(module_scope)
