from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class ABPKOLENHAP(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    ABPKOLENHAP_GCG_LEVEL_NONE: _ClassVar[ABPKOLENHAP]
    ABPKOLENHAP_GCG_LEVEL_CONST: _ClassVar[ABPKOLENHAP]
    ABPKOLENHAP_GCG_LEVEL_WEEK: _ClassVar[ABPKOLENHAP]
    ABPKOLENHAP_GCG_LEVEL_WORLD: _ClassVar[ABPKOLENHAP]
    ABPKOLENHAP_GCG_LEVEL_BOSS: _ClassVar[ABPKOLENHAP]
    ABPKOLENHAP_GCG_LEVEL_CHARACTER: _ClassVar[ABPKOLENHAP]
    ABPKOLENHAP_GCG_LEVEL_BREAK: _ClassVar[ABPKOLENHAP]
    ABPKOLENHAP_GCG_LEVEL_QUEST: _ClassVar[ABPKOLENHAP]
    ABPKOLENHAP_GCG_LEVEL_GUIDE_GROUP: _ClassVar[ABPKOLENHAP]
    ABPKOLENHAP_GCG_LEVEL_OTHER: _ClassVar[ABPKOLENHAP]
    ABPKOLENHAP_GCG_LEVEL_JOURNEY: _ClassVar[ABPKOLENHAP]
    ABPKOLENHAP_GCG_LEVEL_PVE: _ClassVar[ABPKOLENHAP]
    ABPKOLENHAP_GCG_LEVEL_PVE_INFINITE: _ClassVar[ABPKOLENHAP]
    ABPKOLENHAP_GCG_LEVEL_PVE_PUZZLE: _ClassVar[ABPKOLENHAP]
ABPKOLENHAP_GCG_LEVEL_NONE: ABPKOLENHAP
ABPKOLENHAP_GCG_LEVEL_CONST: ABPKOLENHAP
ABPKOLENHAP_GCG_LEVEL_WEEK: ABPKOLENHAP
ABPKOLENHAP_GCG_LEVEL_WORLD: ABPKOLENHAP
ABPKOLENHAP_GCG_LEVEL_BOSS: ABPKOLENHAP
ABPKOLENHAP_GCG_LEVEL_CHARACTER: ABPKOLENHAP
ABPKOLENHAP_GCG_LEVEL_BREAK: ABPKOLENHAP
ABPKOLENHAP_GCG_LEVEL_QUEST: ABPKOLENHAP
ABPKOLENHAP_GCG_LEVEL_GUIDE_GROUP: ABPKOLENHAP
ABPKOLENHAP_GCG_LEVEL_OTHER: ABPKOLENHAP
ABPKOLENHAP_GCG_LEVEL_JOURNEY: ABPKOLENHAP
ABPKOLENHAP_GCG_LEVEL_PVE: ABPKOLENHAP
ABPKOLENHAP_GCG_LEVEL_PVE_INFINITE: ABPKOLENHAP
ABPKOLENHAP_GCG_LEVEL_PVE_PUZZLE: ABPKOLENHAP
