# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/ABPKOLENHAP.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/ABPKOLENHAP.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/ABPKOLENHAP.proto*\xee\x03\n\x0b\x41\x42PKOLENHAP\x12\x1e\n\x1a\x41\x42PKOLENHAP_GCG_LEVEL_NONE\x10\x00\x12\x1f\n\x1b\x41\x42PKOLENHAP_GCG_LEVEL_CONST\x10\x01\x12\x1e\n\x1a\x41\x42PKOLENHAP_GCG_LEVEL_WEEK\x10\x02\x12\x1f\n\x1b\x41\x42PKOLENHAP_GCG_LEVEL_WORLD\x10\x03\x12\x1e\n\x1a\x41\x42PKOLENHAP_GCG_LEVEL_BOSS\x10\x04\x12#\n\x1f\x41\x42PKOLENHAP_GCG_LEVEL_CHARACTER\x10\x05\x12\x1f\n\x1b\x41\x42PKOLENHAP_GCG_LEVEL_BREAK\x10\x06\x12\x1f\n\x1b\x41\x42PKOLENHAP_GCG_LEVEL_QUEST\x10\x07\x12%\n!ABPKOLENHAP_GCG_LEVEL_GUIDE_GROUP\x10\x08\x12\x1f\n\x1b\x41\x42PKOLENHAP_GCG_LEVEL_OTHER\x10\t\x12!\n\x1d\x41\x42PKOLENHAP_GCG_LEVEL_JOURNEY\x10\n\x12\x1d\n\x19\x41\x42PKOLENHAP_GCG_LEVEL_PVE\x10\x0b\x12&\n\"ABPKOLENHAP_GCG_LEVEL_PVE_INFINITE\x10\x0c\x12$\n ABPKOLENHAP_GCG_LEVEL_PVE_PUZZLE\x10\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.ABPKOLENHAP_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ABPKOLENHAP']._serialized_start=43
  _globals['_ABPKOLENHAP']._serialized_end=537
# @@protoc_insertion_point(module_scope)
