# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/ACIAFKOACAO.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/ACIAFKOACAO.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/ACIAFKOACAO.proto*p\n\x0b\x41\x43IAFKOACAO\x12\x14\n\x10\x41\x43IAFKOACAO_NONE\x10\x00\x12\x17\n\x13\x41\x43IAFKOACAO_STARRED\x10\x01\x12\x18\n\x14\x41\x43IAFKOACAO_OFFICIAL\x10\x02\x12\x18\n\x14\x41\x43IAFKOACAO_TEMPLATE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.ACIAFKOACAO_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACIAFKOACAO']._serialized_start=42
  _globals['_ACIAFKOACAO']._serialized_end=154
# @@protoc_insertion_point(module_scope)
