# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/ActivityShopSheetInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0genshin/packet/proto/ActivityShopSheetInfo.proto\"O\n\x15\x41\x63tivityShopSheetInfo\x12\x10\n\x08\x65nd_time\x18\x01 \x01(\r\x12\x12\n\nbegin_time\x18\x0c \x01(\r\x12\x10\n\x08sheet_id\x18\x02 \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_ACTIVITYSHOPSHEETINFO = DESCRIPTOR.message_types_by_name['ActivityShopSheetInfo']
ActivityShopSheetInfo = _reflection.GeneratedProtocolMessageType('ActivityShopSheetInfo', (_message.Message,), {
  'DESCRIPTOR' : _ACTIVITYSHOPSHEETINFO,
  '__module__' : 'genshin.packet.proto.ActivityShopSheetInfo_pb2'
  # @@protoc_insertion_point(class_scope:ActivityShopSheetInfo)
  })
_sym_db.RegisterMessage(ActivityShopSheetInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _ACTIVITYSHOPSHEETINFO._serialized_start=52
  _ACTIVITYSHOPSHEETINFO._serialized_end=131
# @@protoc_insertion_point(module_scope)
