# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/AFFCGEJBALJ.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/AFFCGEJBALJ.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import JKBBEKKCCEE_pb2 as genshin_dot_packet_dot_proto_dot_JKBBEKKCCEE__pb2
from genshin.packet.proto import ACIAFKOACAO_pb2 as genshin_dot_packet_dot_proto_dot_ACIAFKOACAO__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/AFFCGEJBALJ.proto\x1a&genshin/packet/proto/JKBBEKKCCEE.proto\x1a&genshin/packet/proto/ACIAFKOACAO.proto\"}\n\x0b\x41\x46\x46\x43GEJBALJ\x12\x13\n\x0bKLMDAPCLGAP\x18\x02 \x01(\r\x12!\n\x0bKGCONLDGJPG\x18\x05 \x01(\x0e\x32\x0c.JKBBEKKCCEE\x12!\n\x0b\x46NBMMFBMKDO\x18\n \x01(\x0e\x32\x0c.ACIAFKOACAO\x12\x13\n\x0bMCPPEKNBHFK\x18\x01 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.AFFCGEJBALJ_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AFFCGEJBALJ']._serialized_start=122
  _globals['_AFFCGEJBALJ']._serialized_end=247
# @@protoc_insertion_point(module_scope)
