from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class AFOGMHLHODN(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    AFOGMHLHODN_CLIENT_RECONNNECT_NONE: _ClassVar[AFOGMHLHODN]
    AFOGMHLHODN_CLIENT_RECONNNECT_QUIT_MP: _ClassVar[AFOGMHLHODN]
    AFOGMHLHODN_CLIENT_RECONNNECT_SCENE_TIME_CHECK_FAIL: _ClassVar[AFOGMHLHODN]
    AFOGMHLHODN_CLIENT_RECONNNECT_ENTER_QUEST_FOCUS: _ClassVar[AFOGMHLHODN]
AFOGMHLHODN_CLIENT_RECONNNECT_NONE: AFOGMHLHODN
AFOGMHLHODN_CLIENT_RECONNNECT_QUIT_MP: AFOGMHLHODN
AFOGMHLHODN_CLIENT_RECONNNECT_SCENE_TIME_CHECK_FAIL: AFOGMHLHODN
AFOGMHLHODN_CLIENT_RECONNNECT_ENTER_QUEST_FOCUS: AFOGMHLHODN
