# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/AGFJKGLGGCK.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/AGFJKGLGGCK.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/AGFJKGLGGCK.proto\"v\n\x0b\x41GFJKGLGGCK\x12\x13\n\x0bIHGJLFCGFIN\x18\x03 \x01(\x04\x12\x13\n\x0bGGCFIEHANKK\x18\x08 \x01(\r\x12\x13\n\x0bJEMMGILNBPA\x18\x07 \x01(\x08\x12\x13\n\x0bOMENIAMEDCE\x18\x01 \x01(\x08\x12\x13\n\x0b\x45JNINFFFKJP\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.AGFJKGLGGCK_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGFJKGLGGCK']._serialized_start=42
  _globals['_AGFJKGLGGCK']._serialized_end=160
# @@protoc_insertion_point(module_scope)
