# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/AHJHICPGINI.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/AHJHICPGINI.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/AHJHICPGINI.proto\"a\n\x0b\x41HJHICPGINI\x12\x13\n\x0b\x46MDOLMMAJCG\x18\x0b \x03(\r\x12\x13\n\x0b\x46MEEOOMMCAF\x18\x05 \x03(\r\x12\x13\n\x0bJBFDOGPAKKC\x18\x03 \x01(\r\x12\x13\n\x0bMPNJAOCKMAH\x18\x06 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.AHJHICPGINI_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AHJHICPGINI']._serialized_start=42
  _globals['_AHJHICPGINI']._serialized_end=139
# @@protoc_insertion_point(module_scope)
