from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class AIGMBJEBMNN(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    AIGMBJEBMNN_ACTION_TYPE_NONE: _ClassVar[AIGMBJEBMNN]
    AIGMBJEBMNN_ACTION_TYPE_PLAYER_MOVE: _ClassVar[AIGMBJEBMNN]
    AIGMBJEBMNN_ACTION_TYPE_SPAWN_WAVE: _ClassVar[AIGMBJEBMNN]
    AIGMBJEBMNN_ACTION_TYPE_ADD_OBSTACLE: _ClassVar[AIGMBJEBMNN]
    AIGMBJEBMNN_ACTION_TYPE_REMOVE_OBSTACLE: _ClassVar[AIGMBJEBMNN]
    AIGMBJEBMNN_ACTION_TYPE_TEAM_SCORE: _ClassVar[AIGMBJEBMNN]
    AIGMBJEBMNN_ACTION_TYPE_COLLECT_OBSTACLES: _ClassVar[AIGMBJEBMNN]
AIGMBJEBMNN_ACTION_TYPE_NONE: AIGMBJEBMNN
AIGMBJEBMNN_ACTION_TYPE_PLAYER_MOVE: AIGMBJEBMNN
AIGMBJEBMNN_ACTION_TYPE_SPAWN_WAVE: AIGMBJEBMNN
AIGMBJEBMNN_ACTION_TYPE_ADD_OBSTACLE: AIGMBJEBMNN
AIGMBJEBMNN_ACTION_TYPE_REMOVE_OBSTACLE: AIGMBJEBMNN
AIGMBJEBMNN_ACTION_TYPE_TEAM_SCORE: AIGMBJEBMNN
AIGMBJEBMNN_ACTION_TYPE_COLLECT_OBSTACLES: AIGMBJEBMNN
