from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class AIPIIHKMOGO(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    AIPIIHKMOGO_TRY_CUSTOM_DUNGEON_NONE: _ClassVar[AIPIIHKMOGO]
    AIPIIHKMOGO_TRY_CUSTOM_DUNGEON_ROOM: _ClassVar[AIPIIHKMOGO]
    AIPIIHKMOGO_TRY_CUSTOM_DUNGEON_ALL: _ClassVar[AIPIIHKMOGO]
    AIPIIHKMOGO_TRY_CUSTOM_DUNGEON_OFFICIAL_PLAY: _ClassVar[AIPIIHKMOGO]
AIPIIHKMOGO_TRY_CUSTOM_DUNGEON_NONE: AIPIIHKMOGO
AIPIIHKMOGO_TRY_CUSTOM_DUNGEON_ROOM: AIPIIHKMOGO
AIPIIHKMOGO_TRY_CUSTOM_DUNGEON_ALL: AIPIIHKMOGO
AIPIIHKMOGO_TRY_CUSTOM_DUNGEON_OFFICIAL_PLAY: AIPIIHKMOGO
