from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class AJPMIIOMCDO(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    AJPMIIOMCDO_PROT_ENTITY_NONE: _ClassVar[AJPMIIOMCDO]
    AJPMIIOMCDO_PROT_ENTITY_AVATAR: _ClassVar[AJPMIIOMCDO]
    AJPMIIOMCDO_PROT_ENTITY_MONSTER: _ClassVar[AJPMIIOMCDO]
    AJPMIIOMCDO_PROT_ENTITY_NPC: _ClassVar[AJPMIIOMCDO]
    AJPMIIOMCDO_PROT_ENTITY_GADGET: _ClassVar[AJPMIIOMCDO]
    AJPMIIOMCDO_PROT_ENTITY_REGION: _ClassVar[AJPMIIOMCDO]
    AJPMIIOMCDO_PROT_ENTITY_WEAPON: _ClassVar[AJPMIIOMCDO]
    AJPMIIOMCDO_PROT_ENTITY_WEATHER: _ClassVar[AJPMIIOMCDO]
    AJPMIIOMCDO_PROT_ENTITY_SCENE: _ClassVar[AJPMIIOMCDO]
    AJPMIIOMCDO_PROT_ENTITY_TEAM: _ClassVar[AJPMIIOMCDO]
    AJPMIIOMCDO_PROT_ENTITY_MP_LEVEL: _ClassVar[AJPMIIOMCDO]
    AJPMIIOMCDO_PROT_ENTITY_PLAY_TEAM_ENTITY: _ClassVar[AJPMIIOMCDO]
    AJPMIIOMCDO_PROT_ENTITY_EYE_POINT: _ClassVar[AJPMIIOMCDO]
    AJPMIIOMCDO_PROT_ENTITY_MAX: _ClassVar[AJPMIIOMCDO]
AJPMIIOMCDO_PROT_ENTITY_NONE: AJPMIIOMCDO
AJPMIIOMCDO_PROT_ENTITY_AVATAR: AJPMIIOMCDO
AJPMIIOMCDO_PROT_ENTITY_MONSTER: AJPMIIOMCDO
AJPMIIOMCDO_PROT_ENTITY_NPC: AJPMIIOMCDO
AJPMIIOMCDO_PROT_ENTITY_GADGET: AJPMIIOMCDO
AJPMIIOMCDO_PROT_ENTITY_REGION: AJPMIIOMCDO
AJPMIIOMCDO_PROT_ENTITY_WEAPON: AJPMIIOMCDO
AJPMIIOMCDO_PROT_ENTITY_WEATHER: AJPMIIOMCDO
AJPMIIOMCDO_PROT_ENTITY_SCENE: AJPMIIOMCDO
AJPMIIOMCDO_PROT_ENTITY_TEAM: AJPMIIOMCDO
AJPMIIOMCDO_PROT_ENTITY_MP_LEVEL: AJPMIIOMCDO
AJPMIIOMCDO_PROT_ENTITY_PLAY_TEAM_ENTITY: AJPMIIOMCDO
AJPMIIOMCDO_PROT_ENTITY_EYE_POINT: AJPMIIOMCDO
AJPMIIOMCDO_PROT_ENTITY_MAX: AJPMIIOMCDO
