# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/ANCDJKNFELI.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/ANCDJKNFELI.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import HFHJKHOPLMN_pb2 as genshin_dot_packet_dot_proto_dot_HFHJKHOPLMN__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/ANCDJKNFELI.proto\x1a&genshin/packet/proto/HFHJKHOPLMN.proto\"\xd8\x01\n\x0b\x41NCDJKNFELI\x12!\n\x0bHCEJPKIAJAP\x18\x01 \x03(\x0b\x32\x0c.HFHJKHOPLMN\x12\x13\n\x0bODCMKOFFKKL\x18\n \x01(\r\x12\x13\n\x0bMPNJAOCKMAH\x18\x04 \x01(\r\x12\x13\n\x0b\x45\x44NALCKIJPG\x18\x03 \x01(\r\x12\x13\n\x0b\x46\x45\x44JBGPLMHI\x18\x0b \x01(\r\x12\x13\n\x0bMONEJDBPOLB\x18\x08 \x01(\r\x12\x13\n\x0b\x44PBDBMIIOMP\x18\x02 \x01(\r\x12\x13\n\x0bJCHHJFLDLGA\x18\x07 \x01(\x08\x12\x13\n\x0bOMENIAMEDCE\x18\x0f \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.ANCDJKNFELI_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANCDJKNFELI']._serialized_start=83
  _globals['_ANCDJKNFELI']._serialized_end=299
# @@protoc_insertion_point(module_scope)
