# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/ArenaChallengeMonsterLevel.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5genshin/packet/proto/ArenaChallengeMonsterLevel.proto\"W\n\x1a\x41renaChallengeMonsterLevel\x12\x1d\n\x15\x61rena_challenge_level\x18\x07 \x01(\r\x12\x1a\n\x12\x61rena_challenge_id\x18\x0f \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_ARENACHALLENGEMONSTERLEVEL = DESCRIPTOR.message_types_by_name['ArenaChallengeMonsterLevel']
ArenaChallengeMonsterLevel = _reflection.GeneratedProtocolMessageType('ArenaChallengeMonsterLevel', (_message.Message,), {
  'DESCRIPTOR' : _ARENACHALLENGEMONSTERLEVEL,
  '__module__' : 'genshin.packet.proto.ArenaChallengeMonsterLevel_pb2'
  # @@protoc_insertion_point(class_scope:ArenaChallengeMonsterLevel)
  })
_sym_db.RegisterMessage(ArenaChallengeMonsterLevel)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _ARENACHALLENGEMONSTERLEVEL._serialized_start=57
  _ARENACHALLENGEMONSTERLEVEL._serialized_end=144
# @@protoc_insertion_point(module_scope)
