# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/AsterLittleDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import AsterLittleStageState_pb2 as genshin_dot_packet_dot_proto_dot_AsterLittleStageState__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0genshin/packet/proto/AsterLittleDetailInfo.proto\x1a\x30genshin/packet/proto/AsterLittleStageState.proto\"\x95\x01\n\x15\x41sterLittleDetailInfo\x12\x0f\n\x07is_open\x18\x04 \x01(\x08\x12+\n\x0bstage_state\x18\x07 \x01(\x0e\x32\x16.AsterLittleStageState\x12\x10\n\x08stage_id\x18\x01 \x01(\r\x12\x12\n\nbegin_time\x18\x06 \x01(\r\x12\x18\n\x10stage_begin_time\x18\x05 \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_ASTERLITTLEDETAILINFO = DESCRIPTOR.message_types_by_name['AsterLittleDetailInfo']
AsterLittleDetailInfo = _reflection.GeneratedProtocolMessageType('AsterLittleDetailInfo', (_message.Message,), {
  'DESCRIPTOR' : _ASTERLITTLEDETAILINFO,
  '__module__' : 'genshin.packet.proto.AsterLittleDetailInfo_pb2'
  # @@protoc_insertion_point(class_scope:AsterLittleDetailInfo)
  })
_sym_db.RegisterMessage(AsterLittleDetailInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _ASTERLITTLEDETAILINFO._serialized_start=103
  _ASTERLITTLEDETAILINFO._serialized_end=252
# @@protoc_insertion_point(module_scope)
