# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/AsterProgressDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2genshin/packet/proto/AsterProgressDetailInfo.proto\"D\n\x17\x41sterProgressDetailInfo\x12\x1a\n\x12last_auto_add_time\x18\x03 \x01(\r\x12\r\n\x05\x63ount\x18\x01 \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_ASTERPROGRESSDETAILINFO = DESCRIPTOR.message_types_by_name['AsterProgressDetailInfo']
AsterProgressDetailInfo = _reflection.GeneratedProtocolMessageType('AsterProgressDetailInfo', (_message.Message,), {
  'DESCRIPTOR' : _ASTERPROGRESSDETAILINFO,
  '__module__' : 'genshin.packet.proto.AsterProgressDetailInfo_pb2'
  # @@protoc_insertion_point(class_scope:AsterProgressDetailInfo)
  })
_sym_db.RegisterMessage(AsterProgressDetailInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _ASTERPROGRESSDETAILINFO._serialized_start=54
  _ASTERPROGRESSDETAILINFO._serialized_end=122
# @@protoc_insertion_point(module_scope)
