# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/AvatarBuffAddNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/AvatarBuffAddNotify.proto\";\n\x13\x41vatarBuffAddNotify\x12\x13\n\x0b\x61vatar_guid\x18\n \x01(\x04\x12\x0f\n\x07\x62uff_id\x18\x06 \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_AVATARBUFFADDNOTIFY = DESCRIPTOR.message_types_by_name['AvatarBuffAddNotify']
AvatarBuffAddNotify = _reflection.GeneratedProtocolMessageType('AvatarBuffAddNotify', (_message.Message,), {
  'DESCRIPTOR' : _AVATARBUFFADDNOTIFY,
  '__module__' : 'genshin.packet.proto.AvatarBuffAddNotify_pb2'
  # @@protoc_insertion_point(class_scope:AvatarBuffAddNotify)
  })
_sym_db.RegisterMessage(AvatarBuffAddNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _AVATARBUFFADDNOTIFY._serialized_start=50
  _AVATARBUFFADDNOTIFY._serialized_end=109
# @@protoc_insertion_point(module_scope)
