# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/AvatarEnterElementViewNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7genshin/packet/proto/AvatarEnterElementViewNotify.proto\"M\n\x1c\x41vatarEnterElementViewNotify\x12\x13\n\x0bis_triggerd\x18\x03 \x01(\x08\x12\x18\n\x10\x61vatar_entity_id\x18\x0c \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_AVATARENTERELEMENTVIEWNOTIFY = DESCRIPTOR.message_types_by_name['AvatarEnterElementViewNotify']
AvatarEnterElementViewNotify = _reflection.GeneratedProtocolMessageType('AvatarEnterElementViewNotify', (_message.Message,), {
  'DESCRIPTOR' : _AVATARENTERELEMENTVIEWNOTIFY,
  '__module__' : 'genshin.packet.proto.AvatarEnterElementViewNotify_pb2'
  # @@protoc_insertion_point(class_scope:AvatarEnterElementViewNotify)
  })
_sym_db.RegisterMessage(AvatarEnterElementViewNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _AVATARENTERELEMENTVIEWNOTIFY._serialized_start=59
  _AVATARENTERELEMENTVIEWNOTIFY._serialized_end=136
# @@protoc_insertion_point(module_scope)
