# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/AvatarChangeCostumeReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1genshin/packet/proto/AvatarChangeCostumeReq.proto\"A\n\x16\x41vatarChangeCostumeReq\x12\x12\n\ncostume_id\x18\x04 \x01(\r\x12\x13\n\x0b\x61vatar_guid\x18\x02 \x01(\x04\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')



_AVATARCHANGECOSTUMEREQ = DESCRIPTOR.message_types_by_name['AvatarChangeCostumeReq']
AvatarChangeCostumeReq = _reflection.GeneratedProtocolMessageType('AvatarChangeCostumeReq', (_message.Message,), {
  'DESCRIPTOR' : _AVATARCHANGECOSTUMEREQ,
  '__module__' : 'genshin.packet.proto.AvatarChangeCostumeReq_pb2'
  # @@protoc_insertion_point(class_scope:AvatarChangeCostumeReq)
  })
_sym_db.RegisterMessage(AvatarChangeCostumeReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _AVATARCHANGECOSTUMEREQ._serialized_start=53
  _AVATARCHANGECOSTUMEREQ._serialized_end=118
# @@protoc_insertion_point(module_scope)
