# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/AvatarLifeStateChangeNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import PlayerDieType_pb2 as genshin_dot_packet_dot_proto_dot_PlayerDieType__pb2
from genshin.packet.proto import ServerBuff_pb2 as genshin_dot_packet_dot_proto_dot_ServerBuff__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6genshin/packet/proto/AvatarLifeStateChangeNotify.proto\x1a(genshin/packet/proto/PlayerDieType.proto\x1a%genshin/packet/proto/ServerBuff.proto\"\xd8\x01\n\x1b\x41vatarLifeStateChangeNotify\x12\x12\n\nlife_state\x18\r \x01(\r\x12\x12\n\nattack_tag\x18\n \x01(\t\x12 \n\x08\x64ie_type\x18\x02 \x01(\x0e\x32\x0e.PlayerDieType\x12%\n\x10server_buff_list\x18\x0c \x03(\x0b\x32\x0b.ServerBuff\x12\x19\n\x11move_reliable_seq\x18\x05 \x01(\r\x12\x18\n\x10source_entity_id\x18\x03 \x01(\r\x12\x13\n\x0b\x61vatar_guid\x18\x0b \x01(\x04\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')



_AVATARLIFESTATECHANGENOTIFY = DESCRIPTOR.message_types_by_name['AvatarLifeStateChangeNotify']
AvatarLifeStateChangeNotify = _reflection.GeneratedProtocolMessageType('AvatarLifeStateChangeNotify', (_message.Message,), {
  'DESCRIPTOR' : _AVATARLIFESTATECHANGENOTIFY,
  '__module__' : 'genshin.packet.proto.AvatarLifeStateChangeNotify_pb2'
  # @@protoc_insertion_point(class_scope:AvatarLifeStateChangeNotify)
  })
_sym_db.RegisterMessage(AvatarLifeStateChangeNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _AVATARLIFESTATECHANGENOTIFY._serialized_start=140
  _AVATARLIFESTATECHANGENOTIFY._serialized_end=356
# @@protoc_insertion_point(module_scope)
