# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/AvatarTeam.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%genshin/packet/proto/AvatarTeam.proto\"9\n\nAvatarTeam\x12\x18\n\x10\x61vatar_guid_list\x18\x07 \x03(\x04\x12\x11\n\tteam_name\x18\x0e \x01(\tB\x16\n\x14org.sorapointa.protob\x06proto3')



_AVATARTEAM = DESCRIPTOR.message_types_by_name['AvatarTeam']
AvatarTeam = _reflection.GeneratedProtocolMessageType('AvatarTeam', (_message.Message,), {
  'DESCRIPTOR' : _AVATARTEAM,
  '__module__' : 'genshin.packet.proto.AvatarTeam_pb2'
  # @@protoc_insertion_point(class_scope:AvatarTeam)
  })
_sym_db.RegisterMessage(AvatarTeam)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _AVATARTEAM._serialized_start=41
  _AVATARTEAM._serialized_end=98
# @@protoc_insertion_point(module_scope)
