# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/AvatarFightPropUpdateNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6genshin/packet/proto/AvatarFightPropUpdateNotify.proto\"\xaf\x01\n\x1b\x41vatarFightPropUpdateNotify\x12\x46\n\x0e\x66ight_prop_map\x18\x0f \x03(\x0b\x32..AvatarFightPropUpdateNotify.FightPropMapEntry\x12\x13\n\x0b\x61vatar_guid\x18\r \x01(\x04\x1a\x33\n\x11\x46ightPropMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')



_AVATARFIGHTPROPUPDATENOTIFY = DESCRIPTOR.message_types_by_name['AvatarFightPropUpdateNotify']
_AVATARFIGHTPROPUPDATENOTIFY_FIGHTPROPMAPENTRY = _AVATARFIGHTPROPUPDATENOTIFY.nested_types_by_name['FightPropMapEntry']
AvatarFightPropUpdateNotify = _reflection.GeneratedProtocolMessageType('AvatarFightPropUpdateNotify', (_message.Message,), {

  'FightPropMapEntry' : _reflection.GeneratedProtocolMessageType('FightPropMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _AVATARFIGHTPROPUPDATENOTIFY_FIGHTPROPMAPENTRY,
    '__module__' : 'genshin.packet.proto.AvatarFightPropUpdateNotify_pb2'
    # @@protoc_insertion_point(class_scope:AvatarFightPropUpdateNotify.FightPropMapEntry)
    })
  ,
  'DESCRIPTOR' : _AVATARFIGHTPROPUPDATENOTIFY,
  '__module__' : 'genshin.packet.proto.AvatarFightPropUpdateNotify_pb2'
  # @@protoc_insertion_point(class_scope:AvatarFightPropUpdateNotify)
  })
_sym_db.RegisterMessage(AvatarFightPropUpdateNotify)
_sym_db.RegisterMessage(AvatarFightPropUpdateNotify.FightPropMapEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _AVATARFIGHTPROPUPDATENOTIFY_FIGHTPROPMAPENTRY._options = None
  _AVATARFIGHTPROPUPDATENOTIFY_FIGHTPROPMAPENTRY._serialized_options = b'8\001'
  _AVATARFIGHTPROPUPDATENOTIFY._serialized_start=59
  _AVATARFIGHTPROPUPDATENOTIFY._serialized_end=234
  _AVATARFIGHTPROPUPDATENOTIFY_FIGHTPROPMAPENTRY._serialized_start=183
  _AVATARFIGHTPROPUPDATENOTIFY_FIGHTPROPMAPENTRY._serialized_end=234
# @@protoc_insertion_point(module_scope)
