# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/AvatarChangeAnimHashReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2genshin/packet/proto/AvatarChangeAnimHashReq.proto\"A\n\x17\x41vatarChangeAnimHashReq\x12\x11\n\tanim_hash\x18\x06 \x01(\r\x12\x13\n\x0b\x61vatar_guid\x18\x03 \x01(\x04\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_AVATARCHANGEANIMHASHREQ = DESCRIPTOR.message_types_by_name['AvatarChangeAnimHashReq']
AvatarChangeAnimHashReq = _reflection.GeneratedProtocolMessageType('AvatarChangeAnimHashReq', (_message.Message,), {
  'DESCRIPTOR' : _AVATARCHANGEANIMHASHREQ,
  '__module__' : 'genshin.packet.proto.AvatarChangeAnimHashReq_pb2'
  # @@protoc_insertion_point(class_scope:AvatarChangeAnimHashReq)
  })
_sym_db.RegisterMessage(AvatarChangeAnimHashReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _AVATARCHANGEANIMHASHREQ._serialized_start=54
  _AVATARCHANGEANIMHASHREQ._serialized_end=119
# @@protoc_insertion_point(module_scope)
