# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/AvatarEquipAffixStartNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import AvatarEquipAffixInfo_pb2 as genshin_dot_packet_dot_proto_dot_AvatarEquipAffixInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6genshin/packet/proto/AvatarEquipAffixStartNotify.proto\x1a/genshin/packet/proto/AvatarEquipAffixInfo.proto\"c\n\x1b\x41vatarEquipAffixStartNotify\x12\x13\n\x0b\x61vatar_guid\x18\x04 \x01(\x04\x12/\n\x10\x65quip_affix_info\x18\x0c \x01(\x0b\x32\x15.AvatarEquipAffixInfoB\x16\n\x14org.sorapointa.protob\x06proto3')



_AVATAREQUIPAFFIXSTARTNOTIFY = DESCRIPTOR.message_types_by_name['AvatarEquipAffixStartNotify']
AvatarEquipAffixStartNotify = _reflection.GeneratedProtocolMessageType('AvatarEquipAffixStartNotify', (_message.Message,), {
  'DESCRIPTOR' : _AVATAREQUIPAFFIXSTARTNOTIFY,
  '__module__' : 'genshin.packet.proto.AvatarEquipAffixStartNotify_pb2'
  # @@protoc_insertion_point(class_scope:AvatarEquipAffixStartNotify)
  })
_sym_db.RegisterMessage(AvatarEquipAffixStartNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _AVATAREQUIPAFFIXSTARTNOTIFY._serialized_start=107
  _AVATAREQUIPAFFIXSTARTNOTIFY._serialized_end=206
# @@protoc_insertion_point(module_scope)
