# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/AvatarSkillDepotChangeNotify.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/AvatarSkillDepotChangeNotify.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7genshin/packet/proto/AvatarSkillDepotChangeNotify.proto\"\xd2\x03\n\x1c\x41vatarSkillDepotChangeNotify\x12\x11\n\tentity_id\x18\x0b \x01(\r\x12\x1e\n\x16\x63ore_proud_skill_level\x18\x06 \x01(\r\x12_\n\x1bproud_skill_extra_level_map\x18\x08 \x03(\x0b\x32:.AvatarSkillDepotChangeNotify.ProudSkillExtraLevelMapEntry\x12\x13\n\x0b\x61vatar_guid\x18\r \x01(\x04\x12I\n\x0fskill_level_map\x18\x01 \x03(\x0b\x32\x30.AvatarSkillDepotChangeNotify.SkillLevelMapEntry\x12\x18\n\x10proud_skill_list\x18\x0c \x03(\r\x12\x16\n\x0etalent_id_list\x18\t \x03(\r\x12\x16\n\x0eskill_depot_id\x18\x03 \x01(\r\x1a>\n\x1cProudSkillExtraLevelMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x1a\x34\n\x12SkillLevelMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.AvatarSkillDepotChangeNotify_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_AVATARSKILLDEPOTCHANGENOTIFY_PROUDSKILLEXTRALEVELMAPENTRY']._loaded_options = None
  _globals['_AVATARSKILLDEPOTCHANGENOTIFY_PROUDSKILLEXTRALEVELMAPENTRY']._serialized_options = b'8\001'
  _globals['_AVATARSKILLDEPOTCHANGENOTIFY_SKILLLEVELMAPENTRY']._loaded_options = None
  _globals['_AVATARSKILLDEPOTCHANGENOTIFY_SKILLLEVELMAPENTRY']._serialized_options = b'8\001'
  _globals['_AVATARSKILLDEPOTCHANGENOTIFY']._serialized_start=60
  _globals['_AVATARSKILLDEPOTCHANGENOTIFY']._serialized_end=526
  _globals['_AVATARSKILLDEPOTCHANGENOTIFY_PROUDSKILLEXTRALEVELMAPENTRY']._serialized_start=410
  _globals['_AVATARSKILLDEPOTCHANGENOTIFY_PROUDSKILLEXTRALEVELMAPENTRY']._serialized_end=472
  _globals['_AVATARSKILLDEPOTCHANGENOTIFY_SKILLLEVELMAPENTRY']._serialized_start=474
  _globals['_AVATARSKILLDEPOTCHANGENOTIFY_SKILLLEVELMAPENTRY']._serialized_end=526
# @@protoc_insertion_point(module_scope)
