# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/BAENJDFENNH.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/BAENJDFENNH.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import GJNAEALCBFF_pb2 as genshin_dot_packet_dot_proto_dot_GJNAEALCBFF__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/BAENJDFENNH.proto\x1a&genshin/packet/proto/GJNAEALCBFF.proto\"\xf4\x04\n\x0b\x42\x41\x45NJDFENNH\x12\x13\n\x0bOMCKIGHPPBC\x18\x03 \x01(\t\x12\"\n\x0b\x42\x41LNPBDEEOJ\x18\x91\x0c \x03(\x0b\x32\x0c.GJNAEALCBFF\x12\x13\n\x0b\x45PFAPKBPNPE\x18\x01 \x01(\t\x12\x14\n\x0b\x45HGCBGPEFJK\x18\x89\n \x03(\r\x12\x14\n\x0bMCNPJLMHCJH\x18\xaa\x02 \x01(\t\x12\x14\n\x0bIGINMGPPIMP\x18\x89\x0e \x03(\r\x12\x14\n\x0b\x44JMKACEPJBN\x18\xbd\x01 \x03(\r\x12\x14\n\x0b\x45\x41MCFGDPHAF\x18\xf1\x02 \x01(\t\x12\x13\n\x0bGGAIONKIFCE\x18\x04 \x01(\t\x12\x14\n\x0b\x44GIACEIAOPL\x18\xd4\x02 \x01(\t\x12\x13\n\x0b\x41HLGECBCGJN\x18\x02 \x01(\t\x12\x13\n\x0bIIBDNLHOMFN\x18\x0f \x01(\r\x12\x13\n\x0bJABGACILLEC\x18\x07 \x01(\r\x12\x14\n\x0bKAALKOCAOHK\x18\xa6\x0f \x01(\r\x12\x14\n\x0bGLLEBFHMBBE\x18\xa3\x05 \x01(\r\x12\x13\n\x0bLAOGNPOPLPJ\x18\x0c \x01(\r\x12\x13\n\x0b\x41\x41KLCMPDPEG\x18\r \x01(\r\x12\x14\n\x0bHADJCAFOOFE\x18\x8e\x06 \x01(\r\x12\x14\n\x0bJKOALMBCJFE\x18\x84\x06 \x01(\r\x12\x13\n\x0bMAMIMJHEFLO\x18\x0e \x01(\r\x12\x13\n\x0b\x45OIHALLMGAL\x18\x06 \x01(\r\x12\x13\n\x0bOJIFAACGKGM\x18\x05 \x01(\r\x12\x14\n\x0bJNPBIMPGNNO\x18\xfb\x05 \x01(\x08\x12\x14\n\x0bNHJNMGAMPPE\x18\xbc\x05 \x01(\x08\x12\x13\n\x0bJHLNIBAMGAA\x18\x08 \x01(\r\x12\x13\n\x0b\x44NBEFLJLAMB\x18\x0b \x01(\r\x12\x13\n\x0bLKOFKODPMGO\x18\n \x01(\r\x12\x13\n\x0bPNBFDEJOOPD\x18\t \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.BAENJDFENNH_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BAENJDFENNH']._serialized_start=83
  _globals['_BAENJDFENNH']._serialized_end=711
# @@protoc_insertion_point(module_scope)
