# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/BalloonGalleryInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import Unk2700_ONCHFHBBCBN_pb2 as genshin_dot_packet_dot_proto_dot_Unk2700__ONCHFHBBCBN__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-genshin/packet/proto/BalloonGalleryInfo.proto\x1a.genshin/packet/proto/Unk2700_ONCHFHBBCBN.proto\"?\n\x12\x42\x61lloonGalleryInfo\x12)\n\x0brecord_list\x18\x0f \x03(\x0b\x32\x14.Unk2700_ONCHFHBBCBNB\x16\n\x14org.sorapointa.protob\x06proto3')



_BALLOONGALLERYINFO = DESCRIPTOR.message_types_by_name['BalloonGalleryInfo']
BalloonGalleryInfo = _reflection.GeneratedProtocolMessageType('BalloonGalleryInfo', (_message.Message,), {
  'DESCRIPTOR' : _BALLOONGALLERYINFO,
  '__module__' : 'genshin.packet.proto.BalloonGalleryInfo_pb2'
  # @@protoc_insertion_point(class_scope:BalloonGalleryInfo)
  })
_sym_db.RegisterMessage(BalloonGalleryInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _BALLOONGALLERYINFO._serialized_start=97
  _BALLOONGALLERYINFO._serialized_end=160
# @@protoc_insertion_point(module_scope)
