# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/BalloonSettleInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import OnlinePlayerInfo_pb2 as genshin_dot_packet_dot_proto_dot_OnlinePlayerInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,genshin/packet/proto/BalloonSettleInfo.proto\x1a+genshin/packet/proto/OnlinePlayerInfo.proto\"\x85\x01\n\x11\x42\x61lloonSettleInfo\x12\x0b\n\x03uid\x18\x03 \x01(\r\x12\x13\n\x0bshoot_count\x18\x0c \x01(\r\x12\x11\n\tmax_combo\x18\t \x01(\r\x12\x13\n\x0b\x66inal_score\x18\x07 \x01(\r\x12&\n\x0bplayer_info\x18\x02 \x01(\x0b\x32\x11.OnlinePlayerInfoB\x16\n\x14org.sorapointa.protob\x06proto3')



_BALLOONSETTLEINFO = DESCRIPTOR.message_types_by_name['BalloonSettleInfo']
BalloonSettleInfo = _reflection.GeneratedProtocolMessageType('BalloonSettleInfo', (_message.Message,), {
  'DESCRIPTOR' : _BALLOONSETTLEINFO,
  '__module__' : 'genshin.packet.proto.BalloonSettleInfo_pb2'
  # @@protoc_insertion_point(class_scope:BalloonSettleInfo)
  })
_sym_db.RegisterMessage(BalloonSettleInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _BALLOONSETTLEINFO._serialized_start=94
  _BALLOONSETTLEINFO._serialized_end=227
# @@protoc_insertion_point(module_scope)
