from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class BDCDECGDJGF(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    BDCDECGDJGF_UGC_RECORD_USAGE_NONE: _ClassVar[BDCDECGDJGF]
    BDCDECGDJGF_UGC_RECORD_USAGE_IMPORT: _ClassVar[BDCDECGDJGF]
    BDCDECGDJGF_UGC_RECORD_USAGE_PLAY: _ClassVar[BDCDECGDJGF]
    BDCDECGDJGF_UGC_RECORD_USAGE_TRIAL: _ClassVar[BDCDECGDJGF]
    BDCDECGDJGF_UGC_RECORD_USAGE_COMPARE: _ClassVar[BDCDECGDJGF]
BDCDECGDJGF_UGC_RECORD_USAGE_NONE: BDCDECGDJGF
BDCDECGDJGF_UGC_RECORD_USAGE_IMPORT: BDCDECGDJGF
BDCDECGDJGF_UGC_RECORD_USAGE_PLAY: BDCDECGDJGF
BDCDECGDJGF_UGC_RECORD_USAGE_TRIAL: BDCDECGDJGF
BDCDECGDJGF_UGC_RECORD_USAGE_COMPARE: BDCDECGDJGF
