from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class BGOCFKDGOGK(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    BGOCFKDGOGK_ROGUE_CELL_NONE: _ClassVar[BGOCFKDGOGK]
    BGOCFKDGOGK_ROGUE_CELL_BATTLE: _ClassVar[BGOCFKDGOGK]
    BGOCFKDGOGK_ROGUE_CELL_SUCCESS: _ClassVar[BGOCFKDGOGK]
    BGOCFKDGOGK_ROGUE_CELL_FINISH: _ClassVar[BGOCFKDGOGK]
    BGOCFKDGOGK_ROGUE_CELL_TAKEN_CHEST: _ClassVar[BGOCFKDGOGK]
BGOCFKDGOGK_ROGUE_CELL_NONE: BGOCFKDGOGK
BGOCFKDGOGK_ROGUE_CELL_BATTLE: BGOCFKDGOGK
BGOCFKDGOGK_ROGUE_CELL_SUCCESS: BGOCFKDGOGK
BGOCFKDGOGK_ROGUE_CELL_FINISH: BGOCFKDGOGK
BGOCFKDGOGK_ROGUE_CELL_TAKEN_CHEST: BGOCFKDGOGK
