from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class BKEODGBCBKI(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    BKEODGBCBKI_TRIBAL_CHAPTER_NONE: _ClassVar[BKEODGBCBKI]
    BKEODGBCBKI_TRIBAL_CHAPTER_NOT_OPEN: _ClassVar[BKEODGBCBKI]
    BKEODGBCBKI_TRIBAL_CHAPTER_LOCK: _ClassVar[BKEODGBCBKI]
    BKEODGBCBKI_TRIBAL_CHAPTER_UNLOCK: _ClassVar[BKEODGBCBKI]
    BKEODGBCBKI_TRIBAL_CHAPTER_FINISH: _ClassVar[BKEODGBCBKI]
BKEODGBCBKI_TRIBAL_CHAPTER_NONE: BKEODGBCBKI
BKEODGBCBKI_TRIBAL_CHAPTER_NOT_OPEN: BKEODGBCBKI
BKEODGBCBKI_TRIBAL_CHAPTER_LOCK: BKEODGBCBKI
BKEODGBCBKI_TRIBAL_CHAPTER_UNLOCK: BKEODGBCBKI
BKEODGBCBKI_TRIBAL_CHAPTER_FINISH: BKEODGBCBKI
