# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/BlessingRecvPicRecord.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import ProfilePicture_pb2 as genshin_dot_packet_dot_proto_dot_ProfilePicture__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0genshin/packet/proto/BlessingRecvPicRecord.proto\x1a)genshin/packet/proto/ProfilePicture.proto\"\xcb\x01\n\x15\x42lessingRecvPicRecord\x12\x10\n\x08nickname\x18\x01 \x01(\t\x12\x13\n\x0bremark_name\x18\x02 \x01(\t\x12\x0e\n\x06pic_id\x18\x03 \x01(\r\x12\x0b\n\x03uid\x18\x05 \x01(\r\x12\x11\n\tavatar_id\x18\x06 \x01(\r\x12\x11\n\tsignature\x18\n \x01(\t\x12\r\n\x05index\x18\x0e \x01(\r\x12\x0f\n\x07is_recv\x18\x07 \x01(\x08\x12(\n\x0fprofile_picture\x18\t \x01(\x0b\x32\x0f.ProfilePictureB\x16\n\x14org.sorapointa.protob\x06proto3')



_BLESSINGRECVPICRECORD = DESCRIPTOR.message_types_by_name['BlessingRecvPicRecord']
BlessingRecvPicRecord = _reflection.GeneratedProtocolMessageType('BlessingRecvPicRecord', (_message.Message,), {
  'DESCRIPTOR' : _BLESSINGRECVPICRECORD,
  '__module__' : 'genshin.packet.proto.BlessingRecvPicRecord_pb2'
  # @@protoc_insertion_point(class_scope:BlessingRecvPicRecord)
  })
_sym_db.RegisterMessage(BlessingRecvPicRecord)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _BLESSINGRECVPICRECORD._serialized_start=96
  _BLESSINGRECVPICRECORD._serialized_end=299
# @@protoc_insertion_point(module_scope)
