# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/BlessingGetAllRecvPicRecordListRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import BlessingRecvPicRecord_pb2 as genshin_dot_packet_dot_proto_dot_BlessingRecvPicRecord__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=genshin/packet/proto/BlessingGetAllRecvPicRecordListRsp.proto\x1a\x30genshin/packet/proto/BlessingRecvPicRecord.proto\"k\n\"BlessingGetAllRecvPicRecordListRsp\x12\x34\n\x14recv_pic_record_list\x18\x0f \x03(\x0b\x32\x16.BlessingRecvPicRecord\x12\x0f\n\x07retcode\x18\t \x01(\x05\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_BLESSINGGETALLRECVPICRECORDLISTRSP = DESCRIPTOR.message_types_by_name['BlessingGetAllRecvPicRecordListRsp']
BlessingGetAllRecvPicRecordListRsp = _reflection.GeneratedProtocolMessageType('BlessingGetAllRecvPicRecordListRsp', (_message.Message,), {
  'DESCRIPTOR' : _BLESSINGGETALLRECVPICRECORDLISTRSP,
  '__module__' : 'genshin.packet.proto.BlessingGetAllRecvPicRecordListRsp_pb2'
  # @@protoc_insertion_point(class_scope:BlessingGetAllRecvPicRecordListRsp)
  })
_sym_db.RegisterMessage(BlessingGetAllRecvPicRecordListRsp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _BLESSINGGETALLRECVPICRECORDLISTRSP._serialized_start=115
  _BLESSINGGETALLRECVPICRECORDLISTRSP._serialized_end=222
# @@protoc_insertion_point(module_scope)
