# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/BlossomChestInfoNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import BlossomChestInfo_pb2 as genshin_dot_packet_dot_proto_dot_BlossomChestInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1genshin/packet/proto/BlossomChestInfoNotify.proto\x1a+genshin/packet/proto/BlossomChestInfo.proto\"Z\n\x16\x42lossomChestInfoNotify\x12\x11\n\tentity_id\x18\t \x01(\r\x12-\n\x12\x62lossom_chest_info\x18\x03 \x01(\x0b\x32\x11.BlossomChestInfoB\x16\n\x14org.sorapointa.protob\x06proto3')



_BLOSSOMCHESTINFONOTIFY = DESCRIPTOR.message_types_by_name['BlossomChestInfoNotify']
BlossomChestInfoNotify = _reflection.GeneratedProtocolMessageType('BlossomChestInfoNotify', (_message.Message,), {
  'DESCRIPTOR' : _BLOSSOMCHESTINFONOTIFY,
  '__module__' : 'genshin.packet.proto.BlossomChestInfoNotify_pb2'
  # @@protoc_insertion_point(class_scope:BlossomChestInfoNotify)
  })
_sym_db.RegisterMessage(BlossomChestInfoNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _BLOSSOMCHESTINFONOTIFY._serialized_start=98
  _BLOSSOMCHESTINFONOTIFY._serialized_end=188
# @@protoc_insertion_point(module_scope)
