from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class BMIDAFBCOMP(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    BMIDAFBCOMP_MSG_UNKNOWN: _ClassVar[BMIDAFBCOMP]
    BMIDAFBCOMP_MSG_BLOCK_REFRESH_COUNTDOWN: _ClassVar[BMIDAFBCOMP]
    BMIDAFBCOMP_MSG_AVATAR_REVIVE_BY_STATUE: _ClassVar[BMIDAFBCOMP]
    BMIDAFBCOMP_MSG_DAILY_TASK_REWARD_MAX_NUM: _ClassVar[BMIDAFBCOMP]
    BMIDAFBCOMP_MSG_ROUTINE_TYPE_NOT_OPEN: _ClassVar[BMIDAFBCOMP]
    BMIDAFBCOMP_MSG_ROUTINE_TYPE_REWARD_MAX_NUM: _ClassVar[BMIDAFBCOMP]
BMIDAFBCOMP_MSG_UNKNOWN: BMIDAFBCOMP
BMIDAFBCOMP_MSG_BLOCK_REFRESH_COUNTDOWN: BMIDAFBCOMP
BMIDAFBCOMP_MSG_AVATAR_REVIVE_BY_STATUE: BMIDAFBCOMP
BMIDAFBCOMP_MSG_DAILY_TASK_REWARD_MAX_NUM: BMIDAFBCOMP
BMIDAFBCOMP_MSG_ROUTINE_TYPE_NOT_OPEN: BMIDAFBCOMP
BMIDAFBCOMP_MSG_ROUTINE_TYPE_REWARD_MAX_NUM: BMIDAFBCOMP
