# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/BonusActivityUpdateNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import BonusActivityInfo_pb2 as genshin_dot_packet_dot_proto_dot_BonusActivityInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4genshin/packet/proto/BonusActivityUpdateNotify.proto\x1a,genshin/packet/proto/BonusActivityInfo.proto\"Q\n\x19\x42onusActivityUpdateNotify\x12\x34\n\x18\x62onus_activity_info_list\x18\x08 \x03(\x0b\x32\x12.BonusActivityInfoB\x16\n\x14org.sorapointa.protob\x06proto3')



_BONUSACTIVITYUPDATENOTIFY = DESCRIPTOR.message_types_by_name['BonusActivityUpdateNotify']
BonusActivityUpdateNotify = _reflection.GeneratedProtocolMessageType('BonusActivityUpdateNotify', (_message.Message,), {
  'DESCRIPTOR' : _BONUSACTIVITYUPDATENOTIFY,
  '__module__' : 'genshin.packet.proto.BonusActivityUpdateNotify_pb2'
  # @@protoc_insertion_point(class_scope:BonusActivityUpdateNotify)
  })
_sym_db.RegisterMessage(BonusActivityUpdateNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _BONUSACTIVITYUPDATENOTIFY._serialized_start=102
  _BONUSACTIVITYUPDATENOTIFY._serialized_end=183
# @@protoc_insertion_point(module_scope)
