# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/BreakoutSnapShot.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/BreakoutSnapShot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import BreakoutPhysicalObject_pb2 as genshin_dot_packet_dot_proto_dot_BreakoutPhysicalObject__pb2
from genshin.packet.proto import BreakoutAction_pb2 as genshin_dot_packet_dot_proto_dot_BreakoutAction__pb2
from genshin.packet.proto import BreakoutSpawnPoint_pb2 as genshin_dot_packet_dot_proto_dot_BreakoutSpawnPoint__pb2
from genshin.packet.proto import BreakoutElementReactionCounter_pb2 as genshin_dot_packet_dot_proto_dot_BreakoutElementReactionCounter__pb2
from genshin.packet.proto import BreakoutSyncConnectUidInfo_pb2 as genshin_dot_packet_dot_proto_dot_BreakoutSyncConnectUidInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+genshin/packet/proto/BreakoutSnapShot.proto\x1a\x31genshin/packet/proto/BreakoutPhysicalObject.proto\x1a)genshin/packet/proto/BreakoutAction.proto\x1a-genshin/packet/proto/BreakoutSpawnPoint.proto\x1a\x39genshin/packet/proto/BreakoutElementReactionCounter.proto\x1a\x35genshin/packet/proto/BreakoutSyncConnectUidInfo.proto\"\xc9\x05\n\x10\x42reakoutSnapShot\x12\x18\n\x10\x63lient_game_time\x18\x01 \x01(\x04\x12\x18\n\x10server_game_time\x18\x02 \x01(\x04\x12*\n\tball_list\x18\x03 \x03(\x0b\x32\x17.BreakoutPhysicalObject\x12\x35\n\x14physical_object_list\x18\x04 \x03(\x0b\x32\x17.BreakoutPhysicalObject\x12$\n\x0b\x61\x63tion_list\x18\x05 \x03(\x0b\x32\x0f.BreakoutAction\x12\x12\n\nwave_index\x18\x06 \x01(\r\x12\x11\n\tis_finish\x18\x07 \x01(\x08\x12\r\n\x05score\x18\x08 \x01(\r\x12\r\n\x05\x63ombo\x18\t \x01(\r\x12\x11\n\tmax_combo\x18\n \x01(\r\x12\x12\n\nlife_count\x18\x0b \x01(\r\x12\x18\n\x10wave_suite_index\x18\x0c \x01(\r\x12-\n\x10spawn_point_list\x18\r \x03(\x0b\x32\x13.BreakoutSpawnPoint\x12\x19\n\x11remaining_boss_hp\x18\x0e \x01(\r\x12\x44\n\x1b\x62rick_element_reaction_list\x18\x0f \x03(\x0b\x32\x1f.BreakoutElementReactionCounter\x12\x43\n\x1a\x62\x61ll_element_reaction_list\x18\x10 \x03(\x0b\x32\x1f.BreakoutElementReactionCounter\x12\x32\n\ruid_info_list\x18\x11 \x03(\x0b\x32\x1b.BreakoutSyncConnectUidInfo\x12\x34\n\x13\x64ynamic_object_list\x18\x12 \x03(\x0b\x32\x17.BreakoutPhysicalObject\x12\x15\n\rid_index_list\x18\x13 \x03(\r\x12\x1c\n\x14raw_client_game_time\x18\x14 \x01(\x05\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.BreakoutSnapShot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_BREAKOUTSNAPSHOT']._serialized_start=303
  _globals['_BREAKOUTSNAPSHOT']._serialized_end=1016
# @@protoc_insertion_point(module_scope)
