# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/CancelFinishParentQuestNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8genshin/packet/proto/CancelFinishParentQuestNotify.proto\"8\n\x1d\x43\x61ncelFinishParentQuestNotify\x12\x17\n\x0fparent_quest_id\x18\x06 \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_CANCELFINISHPARENTQUESTNOTIFY = DESCRIPTOR.message_types_by_name['CancelFinishParentQuestNotify']
CancelFinishParentQuestNotify = _reflection.GeneratedProtocolMessageType('CancelFinishParentQuestNotify', (_message.Message,), {
  'DESCRIPTOR' : _CANCELFINISHPARENTQUESTNOTIFY,
  '__module__' : 'genshin.packet.proto.CancelFinishParentQuestNotify_pb2'
  # @@protoc_insertion_point(class_scope:CancelFinishParentQuestNotify)
  })
_sym_db.RegisterMessage(CancelFinishParentQuestNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _CANCELFINISHPARENTQUESTNOTIFY._serialized_start=60
  _CANCELFINISHPARENTQUESTNOTIFY._serialized_end=116
# @@protoc_insertion_point(module_scope)
