# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/CEBJOFGFONG.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/CEBJOFGFONG.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import LKDGPHDKHLL_pb2 as genshin_dot_packet_dot_proto_dot_LKDGPHDKHLL__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/CEBJOFGFONG.proto\x1a&genshin/packet/proto/LKDGPHDKHLL.proto\"0\n\x0b\x43\x45\x42JOFGFONG\x12!\n\x0b\x42\x43KNOEPPDBM\x18\x08 \x01(\x0b\x32\x0c.LKDGPHDKHLLb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.CEBJOFGFONG_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CEBJOFGFONG']._serialized_start=82
  _globals['_CEBJOFGFONG']._serialized_end=130
# @@protoc_insertion_point(module_scope)
