from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class CGHBPGPBEMP(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    CGHBPGPBEMP_COMBAT_NONE: _ClassVar[CGHBPGPBEMP]
    CGHBPGPBEMP_COMBAT_EVT_BEING_HIT: _ClassVar[CGHBPGPBEMP]
    CGHBPGPBEMP_COMBAT_ANIMATOR_STATE_CHANGED: _ClassVar[CGHBPGPBEMP]
    CGHBPGPBEMP_COMBAT_FACE_TO_DIR: _ClassVar[CGHBPGPBEMP]
    CGHBPGPBEMP_COMBAT_SET_ATTACK_TARGET: _ClassVar[CGHBPGPBEMP]
    CGHBPGPBEMP_COMBAT_RUSH_MOVE: _ClassVar[CGHBPGPBEMP]
    CGHBPGPBEMP_COMBAT_ANIMATOR_PARAMETER_CHANGED: _ClassVar[CGHBPGPBEMP]
    CGHBPGPBEMP_ENTITY_MOVE: _ClassVar[CGHBPGPBEMP]
    CGHBPGPBEMP_SYNC_ENTITY_POSITION: _ClassVar[CGHBPGPBEMP]
    CGHBPGPBEMP_COMBAT_STEER_MOTION_INFO: _ClassVar[CGHBPGPBEMP]
    CGHBPGPBEMP_COMBAT_FORCE_SET_POS_INFO: _ClassVar[CGHBPGPBEMP]
    CGHBPGPBEMP_COMBAT_COMPENSATE_POS_DIFF: _ClassVar[CGHBPGPBEMP]
    CGHBPGPBEMP_COMBAT_MONSTER_DO_BLINK: _ClassVar[CGHBPGPBEMP]
    CGHBPGPBEMP_COMBAT_FIXED_RUSH_MOVE: _ClassVar[CGHBPGPBEMP]
    CGHBPGPBEMP_COMBAT_SYNC_TRANSFORM: _ClassVar[CGHBPGPBEMP]
    CGHBPGPBEMP_COMBAT_LIGHT_CORE_MOVE: _ClassVar[CGHBPGPBEMP]
    CGHBPGPBEMP_COMBAT_BEING_HEALED_NTF: _ClassVar[CGHBPGPBEMP]
    CGHBPGPBEMP_COMBAT_SKILL_ANCHOR_POSITION_NTF: _ClassVar[CGHBPGPBEMP]
    CGHBPGPBEMP_COMBAT_GRAPPLING_HOOK_MOVE: _ClassVar[CGHBPGPBEMP]
    CGHBPGPBEMP_COMBAT_SPECIAL_MOTION_INFO: _ClassVar[CGHBPGPBEMP]
    CGHBPGPBEMP_COMBAT_FIXED_AVATAR_FLASH_MOVE: _ClassVar[CGHBPGPBEMP]
    CGHBPGPBEMP_COMBAT_MULTI_OVERRIDE_ANIM: _ClassVar[CGHBPGPBEMP]
    CGHBPGPBEMP_COMBAT_DEBUG_SYNC_MOTION: _ClassVar[CGHBPGPBEMP]
CGHBPGPBEMP_COMBAT_NONE: CGHBPGPBEMP
CGHBPGPBEMP_COMBAT_EVT_BEING_HIT: CGHBPGPBEMP
CGHBPGPBEMP_COMBAT_ANIMATOR_STATE_CHANGED: CGHBPGPBEMP
CGHBPGPBEMP_COMBAT_FACE_TO_DIR: CGHBPGPBEMP
CGHBPGPBEMP_COMBAT_SET_ATTACK_TARGET: CGHBPGPBEMP
CGHBPGPBEMP_COMBAT_RUSH_MOVE: CGHBPGPBEMP
CGHBPGPBEMP_COMBAT_ANIMATOR_PARAMETER_CHANGED: CGHBPGPBEMP
CGHBPGPBEMP_ENTITY_MOVE: CGHBPGPBEMP
CGHBPGPBEMP_SYNC_ENTITY_POSITION: CGHBPGPBEMP
CGHBPGPBEMP_COMBAT_STEER_MOTION_INFO: CGHBPGPBEMP
CGHBPGPBEMP_COMBAT_FORCE_SET_POS_INFO: CGHBPGPBEMP
CGHBPGPBEMP_COMBAT_COMPENSATE_POS_DIFF: CGHBPGPBEMP
CGHBPGPBEMP_COMBAT_MONSTER_DO_BLINK: CGHBPGPBEMP
CGHBPGPBEMP_COMBAT_FIXED_RUSH_MOVE: CGHBPGPBEMP
CGHBPGPBEMP_COMBAT_SYNC_TRANSFORM: CGHBPGPBEMP
CGHBPGPBEMP_COMBAT_LIGHT_CORE_MOVE: CGHBPGPBEMP
CGHBPGPBEMP_COMBAT_BEING_HEALED_NTF: CGHBPGPBEMP
CGHBPGPBEMP_COMBAT_SKILL_ANCHOR_POSITION_NTF: CGHBPGPBEMP
CGHBPGPBEMP_COMBAT_GRAPPLING_HOOK_MOVE: CGHBPGPBEMP
CGHBPGPBEMP_COMBAT_SPECIAL_MOTION_INFO: CGHBPGPBEMP
CGHBPGPBEMP_COMBAT_FIXED_AVATAR_FLASH_MOVE: CGHBPGPBEMP
CGHBPGPBEMP_COMBAT_MULTI_OVERRIDE_ANIM: CGHBPGPBEMP
CGHBPGPBEMP_COMBAT_DEBUG_SYNC_MOTION: CGHBPGPBEMP
