# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/ChannelerSlabOneOffDungeonInfoReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<genshin/packet/proto/ChannelerSlabOneOffDungeonInfoReq.proto\"#\n!ChannelerSlabOneOffDungeonInfoReqB\x16\n\x14org.sorapointa.protob\x06proto3')



_CHANNELERSLABONEOFFDUNGEONINFOREQ = DESCRIPTOR.message_types_by_name['ChannelerSlabOneOffDungeonInfoReq']
ChannelerSlabOneOffDungeonInfoReq = _reflection.GeneratedProtocolMessageType('ChannelerSlabOneOffDungeonInfoReq', (_message.Message,), {
  'DESCRIPTOR' : _CHANNELERSLABONEOFFDUNGEONINFOREQ,
  '__module__' : 'genshin.packet.proto.ChannelerSlabOneOffDungeonInfoReq_pb2'
  # @@protoc_insertion_point(class_scope:ChannelerSlabOneOffDungeonInfoReq)
  })
_sym_db.RegisterMessage(ChannelerSlabOneOffDungeonInfoReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _CHANNELERSLABONEOFFDUNGEONINFOREQ._serialized_start=64
  _CHANNELERSLABONEOFFDUNGEONINFOREQ._serialized_end=99
# @@protoc_insertion_point(module_scope)
