from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class CHDGOJIPKBE(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    CHDGOJIPKBE_EXPEDITION_NONE: _ClassVar[CHDGOJIPKBE]
    CHDGOJIPKBE_EXPEDITION_STARTED: _ClassVar[CHDGOJIPKBE]
    CHDGOJIPKBE_EXPEDITION_FINISHED: _ClassVar[CHDGOJIPKBE]
    CHDGOJIPKBE_EXPEDITION_REWARDED: _ClassVar[CHDGOJIPKBE]
    CHDGOJIPKBE_EXPEDITION_LOCKED: _ClassVar[CHDGOJIPKBE]
CHDGOJIPKBE_EXPEDITION_NONE: CHDGOJIPKBE
CHDGOJIPKBE_EXPEDITION_STARTED: CHDGOJIPKBE
CHDGOJIPKBE_EXPEDITION_FINISHED: CHDGOJIPKBE
CHDGOJIPKBE_EXPEDITION_REWARDED: CHDGOJIPKBE
CHDGOJIPKBE_EXPEDITION_LOCKED: CHDGOJIPKBE
