# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/CHGNHDCHNDD.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/CHGNHDCHNDD.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import FDIGDFDCNJC_pb2 as genshin_dot_packet_dot_proto_dot_FDIGDFDCNJC__pb2
from genshin.packet.proto import HJKIGLGDDON_pb2 as genshin_dot_packet_dot_proto_dot_HJKIGLGDDON__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/CHGNHDCHNDD.proto\x1a&genshin/packet/proto/FDIGDFDCNJC.proto\x1a&genshin/packet/proto/HJKIGLGDDON.proto\"h\n\x0b\x43HGNHDCHNDD\x12!\n\x0b\x41MBDAFCLIAG\x18\x0b \x01(\x0e\x32\x0c.FDIGDFDCNJC\x12\x13\n\x0b\x44\x44IGGFPIFNB\x18\t \x01(\r\x12!\n\x0bPEMALBHPMKF\x18\x0e \x01(\x0e\x32\x0c.HJKIGLGDDONb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.CHGNHDCHNDD_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHGNHDCHNDD']._serialized_start=122
  _globals['_CHGNHDCHNDD']._serialized_end=226
# @@protoc_insertion_point(module_scope)
