# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/CHNDGMMBKDI.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/CHNDGMMBKDI.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import ACEKDEBFIMC_pb2 as genshin_dot_packet_dot_proto_dot_ACEKDEBFIMC__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/CHNDGMMBKDI.proto\x1a&genshin/packet/proto/ACEKDEBFIMC.proto\"o\n\x0b\x43HNDGMMBKDI\x12!\n\x0bNFMBFOGNCNL\x18\x0f \x03(\x0b\x32\x0c.ACEKDEBFIMC\x12\x13\n\x0bHGGJIHMNEBA\x18\r \x03(\r\x12\x13\n\x0b\x43\x44\x46IKAPILPF\x18\x05 \x01(\r\x12\x13\n\x0bMNCBKGJGGLL\x18\x06 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.CHNDGMMBKDI_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHNDGMMBKDI']._serialized_start=82
  _globals['_CHNDGMMBKDI']._serialized_end=193
# @@protoc_insertion_point(module_scope)
