from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class CJONIADFAOC(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    CJONIADFAOC_MOVING_PLATFORM_NONE: _ClassVar[CJONIADFAOC]
    CJONIADFAOC_MOVING_PLATFORM_USE_CONFIG: _ClassVar[CJONIADFAOC]
    CJONIADFAOC_MOVING_PLATFORM_ABILITY: _ClassVar[CJONIADFAOC]
    CJONIADFAOC_MOVING_PLATFORM_ROUTE: _ClassVar[CJONIADFAOC]
CJONIADFAOC_MOVING_PLATFORM_NONE: CJONIADFAOC
CJONIADFAOC_MOVING_PLATFORM_USE_CONFIG: CJONIADFAOC
CJONIADFAOC_MOVING_PLATFORM_ABILITY: CJONIADFAOC
CJONIADFAOC_MOVING_PLATFORM_ROUTE: CJONIADFAOC
