# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/ClientGadgetInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+genshin/packet/proto/ClientGadgetInfo.proto\"\xc5\x01\n\x10\x43lientGadgetInfo\x12\x0f\n\x07\x63\x61mp_id\x18\x01 \x01(\r\x12\x11\n\tcamp_type\x18\x02 \x01(\r\x12\x0c\n\x04guid\x18\x03 \x01(\x04\x12\x17\n\x0fowner_entity_id\x18\x04 \x01(\r\x12\x18\n\x10target_entity_id\x18\x05 \x01(\r\x12\x12\n\nasync_load\x18\x06 \x01(\x08\x12\x1b\n\x13Unk2700_JBOPENAGGAF\x18\x07 \x01(\x08\x12\x1b\n\x13Unk2700_BELOIHEIEAN\x18\x08 \x03(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_CLIENTGADGETINFO = DESCRIPTOR.message_types_by_name['ClientGadgetInfo']
ClientGadgetInfo = _reflection.GeneratedProtocolMessageType('ClientGadgetInfo', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTGADGETINFO,
  '__module__' : 'genshin.packet.proto.ClientGadgetInfo_pb2'
  # @@protoc_insertion_point(class_scope:ClientGadgetInfo)
  })
_sym_db.RegisterMessage(ClientGadgetInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _CLIENTGADGETINFO._serialized_start=48
  _CLIENTGADGETINFO._serialized_end=245
# @@protoc_insertion_point(module_scope)
