# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/ClientLockGameTimeNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3genshin/packet/proto/ClientLockGameTimeNotify.proto\"+\n\x18\x43lientLockGameTimeNotify\x12\x0f\n\x07is_lock\x18\x05 \x01(\x08\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_CLIENTLOCKGAMETIMENOTIFY = DESCRIPTOR.message_types_by_name['ClientLockGameTimeNotify']
ClientLockGameTimeNotify = _reflection.GeneratedProtocolMessageType('ClientLockGameTimeNotify', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTLOCKGAMETIMENOTIFY,
  '__module__' : 'genshin.packet.proto.ClientLockGameTimeNotify_pb2'
  # @@protoc_insertion_point(class_scope:ClientLockGameTimeNotify)
  })
_sym_db.RegisterMessage(ClientLockGameTimeNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _CLIENTLOCKGAMETIMENOTIFY._serialized_start=55
  _CLIENTLOCKGAMETIMENOTIFY._serialized_end=98
# @@protoc_insertion_point(module_scope)
