from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class CMGOOOMLAIA(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    CMGOOOMLAIA_DEFAULT: _ClassVar[CMGOOOMLAIA]
    CMGOOOMLAIA_EFFECT: _ClassVar[CMGOOOMLAIA]
    CMGOOOMLAIA_COST: _ClassVar[CMGOOOMLAIA]
    CMGOOOMLAIA_GM: _ClassVar[CMGOOOMLAIA]
    CMGOOOMLAIA_ATTACK: _ClassVar[CMGOOOMLAIA]
    CMGOOOMLAIA_REBOOT: _ClassVar[CMGOOOMLAIA]
    CMGOOOMLAIA_PLAY_CARD: _ClassVar[CMGOOOMLAIA]
    CMGOOOMLAIA_QUICKLY_ONSTAGE: _ClassVar[CMGOOOMLAIA]
    CMGOOOMLAIA_REMOVE_AFTER_DIE: _ClassVar[CMGOOOMLAIA]
    CMGOOOMLAIA_INIT: _ClassVar[CMGOOOMLAIA]
    CMGOOOMLAIA_EFFECT_DAMAGE: _ClassVar[CMGOOOMLAIA]
    CMGOOOMLAIA_EFFECT_HEAL: _ClassVar[CMGOOOMLAIA]
    CMGOOOMLAIA_EFFECT_REVIVE: _ClassVar[CMGOOOMLAIA]
    CMGOOOMLAIA_INIT_ONSTAGE: _ClassVar[CMGOOOMLAIA]
    CMGOOOMLAIA_DIE_ONSTAGE: _ClassVar[CMGOOOMLAIA]
    CMGOOOMLAIA_SELECT_ONSTAGE: _ClassVar[CMGOOOMLAIA]
    CMGOOOMLAIA_CHARACTER_DIE: _ClassVar[CMGOOOMLAIA]
    CMGOOOMLAIA_REVIVE_WHEN_DEATH: _ClassVar[CMGOOOMLAIA]
    CMGOOOMLAIA_TRANSFER_TO_OPPONENT: _ClassVar[CMGOOOMLAIA]
    CMGOOOMLAIA_TRANSFER_DICE: _ClassVar[CMGOOOMLAIA]
    CMGOOOMLAIA_PLAY_CARD_BEING_COUNTER: _ClassVar[CMGOOOMLAIA]
    CMGOOOMLAIA_USE_VEHICLE_SKILL: _ClassVar[CMGOOOMLAIA]
    CMGOOOMLAIA_DISCOVER: _ClassVar[CMGOOOMLAIA]
CMGOOOMLAIA_DEFAULT: CMGOOOMLAIA
CMGOOOMLAIA_EFFECT: CMGOOOMLAIA
CMGOOOMLAIA_COST: CMGOOOMLAIA
CMGOOOMLAIA_GM: CMGOOOMLAIA
CMGOOOMLAIA_ATTACK: CMGOOOMLAIA
CMGOOOMLAIA_REBOOT: CMGOOOMLAIA
CMGOOOMLAIA_PLAY_CARD: CMGOOOMLAIA
CMGOOOMLAIA_QUICKLY_ONSTAGE: CMGOOOMLAIA
CMGOOOMLAIA_REMOVE_AFTER_DIE: CMGOOOMLAIA
CMGOOOMLAIA_INIT: CMGOOOMLAIA
CMGOOOMLAIA_EFFECT_DAMAGE: CMGOOOMLAIA
CMGOOOMLAIA_EFFECT_HEAL: CMGOOOMLAIA
CMGOOOMLAIA_EFFECT_REVIVE: CMGOOOMLAIA
CMGOOOMLAIA_INIT_ONSTAGE: CMGOOOMLAIA
CMGOOOMLAIA_DIE_ONSTAGE: CMGOOOMLAIA
CMGOOOMLAIA_SELECT_ONSTAGE: CMGOOOMLAIA
CMGOOOMLAIA_CHARACTER_DIE: CMGOOOMLAIA
CMGOOOMLAIA_REVIVE_WHEN_DEATH: CMGOOOMLAIA
CMGOOOMLAIA_TRANSFER_TO_OPPONENT: CMGOOOMLAIA
CMGOOOMLAIA_TRANSFER_DICE: CMGOOOMLAIA
CMGOOOMLAIA_PLAY_CARD_BEING_COUNTER: CMGOOOMLAIA
CMGOOOMLAIA_USE_VEHICLE_SKILL: CMGOOOMLAIA
CMGOOOMLAIA_DISCOVER: CMGOOOMLAIA
