# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/CNACLMKNNLB.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/CNACLMKNNLB.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/CNACLMKNNLB.proto*\xe8\x01\n\x0b\x43NACLMKNNLB\x12(\n$CNACLMKNNLB_MONSTER_CHESS_PHASE_NONE\x10\x00\x12+\n\'CNACLMKNNLB_MONSTER_CHESS_PHASE_PREPARE\x10\x01\x12+\n\'CNACLMKNNLB_MONSTER_CHESS_PHASE_UI_SHOW\x10\x02\x12)\n%CNACLMKNNLB_MONSTER_CHESS_PHASE_FIGHT\x10\x03\x12*\n&CNACLMKNNLB_MONSTER_CHESS_PHASE_SETTLE\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.CNACLMKNNLB_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CNACLMKNNLB']._serialized_start=43
  _globals['_CNACLMKNNLB']._serialized_end=275
# @@protoc_insertion_point(module_scope)
