from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class CNACLMKNNLB(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    CNACLMKNNLB_MONSTER_CHESS_PHASE_NONE: _ClassVar[CNACLMKNNLB]
    CNACLMKNNLB_MONSTER_CHESS_PHASE_PREPARE: _ClassVar[CNACLMKNNLB]
    CNACLMKNNLB_MONSTER_CHESS_PHASE_UI_SHOW: _ClassVar[CNACLMKNNLB]
    CNACLMKNNLB_MONSTER_CHESS_PHASE_FIGHT: _ClassVar[CNACLMKNNLB]
    CNACLMKNNLB_MONSTER_CHESS_PHASE_SETTLE: _ClassVar[CNACLMKNNLB]
CNACLMKNNLB_MONSTER_CHESS_PHASE_NONE: CNACLMKNNLB
CNACLMKNNLB_MONSTER_CHESS_PHASE_PREPARE: CNACLMKNNLB
CNACLMKNNLB_MONSTER_CHESS_PHASE_UI_SHOW: CNACLMKNNLB
CNACLMKNNLB_MONSTER_CHESS_PHASE_FIGHT: CNACLMKNNLB
CNACLMKNNLB_MONSTER_CHESS_PHASE_SETTLE: CNACLMKNNLB
