from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class CNDNKCNEDHP(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    CNDNKCNEDHP_ACTION_TYPE_NONE: _ClassVar[CNDNKCNEDHP]
    CNDNKCNEDHP_ACTION_TYPE_LAUNCH_BALL: _ClassVar[CNDNKCNEDHP]
    CNDNKCNEDHP_ACTION_TYPE_DESTROY_BALL: _ClassVar[CNDNKCNEDHP]
    CNDNKCNEDHP_ACTION_TYPE_FALLING_OBJECT: _ClassVar[CNDNKCNEDHP]
    CNDNKCNEDHP_ACTION_TYPE_MISSILE: _ClassVar[CNDNKCNEDHP]
CNDNKCNEDHP_ACTION_TYPE_NONE: CNDNKCNEDHP
CNDNKCNEDHP_ACTION_TYPE_LAUNCH_BALL: CNDNKCNEDHP
CNDNKCNEDHP_ACTION_TYPE_DESTROY_BALL: CNDNKCNEDHP
CNDNKCNEDHP_ACTION_TYPE_FALLING_OBJECT: CNDNKCNEDHP
CNDNKCNEDHP_ACTION_TYPE_MISSILE: CNDNKCNEDHP
