# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/CrystalLinkActivityDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import Unk2700_IOLMLCCBAKP_pb2 as genshin_dot_packet_dot_proto_dot_Unk2700__IOLMLCCBAKP__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8genshin/packet/proto/CrystalLinkActivityDetailInfo.proto\x1a.genshin/packet/proto/Unk2700_IOLMLCCBAKP.proto\"i\n\x1d\x43rystalLinkActivityDetailInfo\x12\x31\n\x13Unk2700_FIKHCFMEOAJ\x18\x03 \x03(\x0b\x32\x14.Unk2700_IOLMLCCBAKP\x12\x15\n\rdifficulty_id\x18\x07 \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_CRYSTALLINKACTIVITYDETAILINFO = DESCRIPTOR.message_types_by_name['CrystalLinkActivityDetailInfo']
CrystalLinkActivityDetailInfo = _reflection.GeneratedProtocolMessageType('CrystalLinkActivityDetailInfo', (_message.Message,), {
  'DESCRIPTOR' : _CRYSTALLINKACTIVITYDETAILINFO,
  '__module__' : 'genshin.packet.proto.CrystalLinkActivityDetailInfo_pb2'
  # @@protoc_insertion_point(class_scope:CrystalLinkActivityDetailInfo)
  })
_sym_db.RegisterMessage(CrystalLinkActivityDetailInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _CRYSTALLINKACTIVITYDETAILINFO._serialized_start=108
  _CRYSTALLINKACTIVITYDETAILINFO._serialized_end=213
# @@protoc_insertion_point(module_scope)
