from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class DCDCNNPIFFK(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    DCDCNNPIFFK_ENTER_UGC_DUNGEON_NONE: _ClassVar[DCDCNNPIFFK]
    DCDCNNPIFFK_ENTER_UGC_DUNGEON_TRIAL_IN_EDIT_DUNGEON: _ClassVar[DCDCNNPIFFK]
    DCDCNNPIFFK_ENTER_UGC_DUNGEON_TRIAL_IN_WORLD: _ClassVar[DCDCNNPIFFK]
    DCDCNNPIFFK_ENTER_UGC_DUNGEON_PLAY: _ClassVar[DCDCNNPIFFK]
    DCDCNNPIFFK_ENTER_UGC_DUNGEON_OFFICIAL: _ClassVar[DCDCNNPIFFK]
    DCDCNNPIFFK_ENTER_UGC_DUNGEON_BY_GM: _ClassVar[DCDCNNPIFFK]
    DCDCNNPIFFK_ENTER_UGC_DUNGEON_BY_EDIT: _ClassVar[DCDCNNPIFFK]
    DCDCNNPIFFK_ENTER_UGC_DUNGEON_TRIAL_ONE_ROOM: _ClassVar[DCDCNNPIFFK]
DCDCNNPIFFK_ENTER_UGC_DUNGEON_NONE: DCDCNNPIFFK
DCDCNNPIFFK_ENTER_UGC_DUNGEON_TRIAL_IN_EDIT_DUNGEON: DCDCNNPIFFK
DCDCNNPIFFK_ENTER_UGC_DUNGEON_TRIAL_IN_WORLD: DCDCNNPIFFK
DCDCNNPIFFK_ENTER_UGC_DUNGEON_PLAY: DCDCNNPIFFK
DCDCNNPIFFK_ENTER_UGC_DUNGEON_OFFICIAL: DCDCNNPIFFK
DCDCNNPIFFK_ENTER_UGC_DUNGEON_BY_GM: DCDCNNPIFFK
DCDCNNPIFFK_ENTER_UGC_DUNGEON_BY_EDIT: DCDCNNPIFFK
DCDCNNPIFFK_ENTER_UGC_DUNGEON_TRIAL_ONE_ROOM: DCDCNNPIFFK
