# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/DCNJGOKKPPC.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/DCNJGOKKPPC.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import CJONIADFAOC_pb2 as genshin_dot_packet_dot_proto_dot_CJONIADFAOC__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/DCNJGOKKPPC.proto\x1a&genshin/packet/proto/CJONIADFAOC.proto\"\x99\x01\n\x0b\x44\x43NJGOKKPPC\x12!\n\x0b\x41JCGKKPCCGD\x18\x02 \x01(\x0e\x32\x0c.CJONIADFAOC\x12\x13\n\x0bLKICAOGDMCB\x18\x08 \x01(\x08\x12\x13\n\x0bJEIEDFBEGIP\x18\x07 \x01(\r\x12\x13\n\x0b\x42IABFNLMMFE\x18\x01 \x01(\r\x12\x13\n\x0b\x44\x46JIIKEDNIG\x18\x04 \x01(\r\x12\x13\n\x0b\x43\x46\x46MDKNINHD\x18\x06 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.DCNJGOKKPPC_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DCNJGOKKPPC']._serialized_start=83
  _globals['_DCNJGOKKPPC']._serialized_end=236
# @@protoc_insertion_point(module_scope)
