# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/DelMailRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%genshin/packet/proto/DelMailRsp.proto\"3\n\nDelMailRsp\x12\x0f\n\x07retcode\x18\x0b \x01(\x05\x12\x14\n\x0cmail_id_list\x18\x05 \x03(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_DELMAILRSP = DESCRIPTOR.message_types_by_name['DelMailRsp']
DelMailRsp = _reflection.GeneratedProtocolMessageType('DelMailRsp', (_message.Message,), {
  'DESCRIPTOR' : _DELMAILRSP,
  '__module__' : 'genshin.packet.proto.DelMailRsp_pb2'
  # @@protoc_insertion_point(class_scope:DelMailRsp)
  })
_sym_db.RegisterMessage(DelMailRsp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _DELMAILRSP._serialized_start=41
  _DELMAILRSP._serialized_end=92
# @@protoc_insertion_point(module_scope)
