# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/DelScenePlayTeamEntityNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7genshin/packet/proto/DelScenePlayTeamEntityNotify.proto\"L\n\x1c\x44\x65lScenePlayTeamEntityNotify\x12\x1a\n\x12\x64\x65l_entity_id_list\x18\x02 \x03(\r\x12\x10\n\x08scene_id\x18\x04 \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_DELSCENEPLAYTEAMENTITYNOTIFY = DESCRIPTOR.message_types_by_name['DelScenePlayTeamEntityNotify']
DelScenePlayTeamEntityNotify = _reflection.GeneratedProtocolMessageType('DelScenePlayTeamEntityNotify', (_message.Message,), {
  'DESCRIPTOR' : _DELSCENEPLAYTEAMENTITYNOTIFY,
  '__module__' : 'genshin.packet.proto.DelScenePlayTeamEntityNotify_pb2'
  # @@protoc_insertion_point(class_scope:DelScenePlayTeamEntityNotify)
  })
_sym_db.RegisterMessage(DelScenePlayTeamEntityNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _DELSCENEPLAYTEAMENTITYNOTIFY._serialized_start=59
  _DELSCENEPLAYTEAMENTITYNOTIFY._serialized_end=135
# @@protoc_insertion_point(module_scope)
