# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/DFBABJJIGBB.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/DFBABJJIGBB.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import JCBDOCHFOKJ_pb2 as genshin_dot_packet_dot_proto_dot_JCBDOCHFOKJ__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/DFBABJJIGBB.proto\x1a&genshin/packet/proto/JCBDOCHFOKJ.proto\"\xc3\x01\n\x0b\x44\x46\x42\x41\x42JJIGBB\x12!\n\x0b\x42\x43\x45\x44OJDONOP\x18\x02 \x03(\x0b\x32\x0c.JCBDOCHFOKJ\x12\x13\n\x0bHGBBGLKPLFI\x18\x0f \x01(\r\x12\x13\n\x0bGIANJMCBAEC\x18\x01 \x01(\x08\x12\x13\n\x0bLAILPNOOAJC\x18\x0c \x01(\x08\x12\x13\n\x0b\x46\x42\x45JHLODCFN\x18\x08 \x01(\r\x12\x13\n\x0bMAEJLIPGDHG\x18\x04 \x01(\r\x12\x13\n\x0b\x45MNEIHDPFPM\x18\x0e \x01(\r\x12\x13\n\x0bNMIKCMLKNDM\x18\x0b \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.DFBABJJIGBB_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DFBABJJIGBB']._serialized_start=83
  _globals['_DFBABJJIGBB']._serialized_end=278
# @@protoc_insertion_point(module_scope)
