from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class DHDEBBIPIIF(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    DHDEBBIPIIF_CLIENT_PLAY_NONE_TYPE: _ClassVar[DHDEBBIPIIF]
    DHDEBBIPIIF_CLIENT_PLAY_FILMFEST_SHOOTING_TYPE: _ClassVar[DHDEBBIPIIF]
    DHDEBBIPIIF_CLIENT_PLAY_COOK_GAME_TYPE: _ClassVar[DHDEBBIPIIF]
    DHDEBBIPIIF_CLIENT_PLAY_LAN_V4_PUSH_BOX_TYPE: _ClassVar[DHDEBBIPIIF]
    DHDEBBIPIIF_CLIENT_PLAY_CATCAFE_LAYOUT_TYPE: _ClassVar[DHDEBBIPIIF]
    DHDEBBIPIIF_CLIENT_PLAY_CATCAFE_CAT_TYPE: _ClassVar[DHDEBBIPIIF]
    DHDEBBIPIIF_CLIENT_PLAY_GREAT_FESTIVAL_V2_SHEET_RESTORE_TYPE: _ClassVar[DHDEBBIPIIF]
    DHDEBBIPIIF_CLIENT_PLAY_BIRD_BALL_TYPE: _ClassVar[DHDEBBIPIIF]
    DHDEBBIPIIF_CLIENT_PLAY_FAIRY_TALES_FLYPPY_HAT_TOY_TYPE: _ClassVar[DHDEBBIPIIF]
    DHDEBBIPIIF_CLIENT_PLAY_NAHIDA_BIRTH_FLOAT_TOY_TYPE: _ClassVar[DHDEBBIPIIF]
    DHDEBBIPIIF_CLIENT_PLAY_CEREMONY_DOODLE_TYPE: _ClassVar[DHDEBBIPIIF]
DHDEBBIPIIF_CLIENT_PLAY_NONE_TYPE: DHDEBBIPIIF
DHDEBBIPIIF_CLIENT_PLAY_FILMFEST_SHOOTING_TYPE: DHDEBBIPIIF
DHDEBBIPIIF_CLIENT_PLAY_COOK_GAME_TYPE: DHDEBBIPIIF
DHDEBBIPIIF_CLIENT_PLAY_LAN_V4_PUSH_BOX_TYPE: DHDEBBIPIIF
DHDEBBIPIIF_CLIENT_PLAY_CATCAFE_LAYOUT_TYPE: DHDEBBIPIIF
DHDEBBIPIIF_CLIENT_PLAY_CATCAFE_CAT_TYPE: DHDEBBIPIIF
DHDEBBIPIIF_CLIENT_PLAY_GREAT_FESTIVAL_V2_SHEET_RESTORE_TYPE: DHDEBBIPIIF
DHDEBBIPIIF_CLIENT_PLAY_BIRD_BALL_TYPE: DHDEBBIPIIF
DHDEBBIPIIF_CLIENT_PLAY_FAIRY_TALES_FLYPPY_HAT_TOY_TYPE: DHDEBBIPIIF
DHDEBBIPIIF_CLIENT_PLAY_NAHIDA_BIRTH_FLOAT_TOY_TYPE: DHDEBBIPIIF
DHDEBBIPIIF_CLIENT_PLAY_CEREMONY_DOODLE_TYPE: DHDEBBIPIIF
