# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/DropItemReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import StoreType_pb2 as genshin_dot_packet_dot_proto_dot_StoreType__pb2
from genshin.packet.proto import Vector_pb2 as genshin_dot_packet_dot_proto_dot_Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/DropItemReq.proto\x1a$genshin/packet/proto/StoreType.proto\x1a!genshin/packet/proto/Vector.proto\"`\n\x0b\x44ropItemReq\x12\x14\n\x03pos\x18\x0b \x01(\x0b\x32\x07.Vector\x12\x1e\n\nstore_type\x18\x01 \x01(\x0e\x32\n.StoreType\x12\r\n\x05\x63ount\x18\x02 \x01(\r\x12\x0c\n\x04guid\x18\r \x01(\x04\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_DROPITEMREQ = DESCRIPTOR.message_types_by_name['DropItemReq']
DropItemReq = _reflection.GeneratedProtocolMessageType('DropItemReq', (_message.Message,), {
  'DESCRIPTOR' : _DROPITEMREQ,
  '__module__' : 'genshin.packet.proto.DropItemReq_pb2'
  # @@protoc_insertion_point(class_scope:DropItemReq)
  })
_sym_db.RegisterMessage(DropItemReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _DROPITEMREQ._serialized_start=115
  _DROPITEMREQ._serialized_end=211
# @@protoc_insertion_point(module_scope)
