# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/DungeonChallengeFinishNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import ChannelerSlabLoopDungeonResultInfo_pb2 as genshin_dot_packet_dot_proto_dot_ChannelerSlabLoopDungeonResultInfo__pb2
from genshin.packet.proto import CustomDungeonResultInfo_pb2 as genshin_dot_packet_dot_proto_dot_CustomDungeonResultInfo__pb2
from genshin.packet.proto import EffigyChallengeDungeonResultInfo_pb2 as genshin_dot_packet_dot_proto_dot_EffigyChallengeDungeonResultInfo__pb2
from genshin.packet.proto import PotionDungeonResultInfo_pb2 as genshin_dot_packet_dot_proto_dot_PotionDungeonResultInfo__pb2
from genshin.packet.proto import StrengthenPointData_pb2 as genshin_dot_packet_dot_proto_dot_StrengthenPointData__pb2
from genshin.packet.proto import Unk2700_FHOKHHBGPEG_pb2 as genshin_dot_packet_dot_proto_dot_Unk2700__FHOKHHBGPEG__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7genshin/packet/proto/DungeonChallengeFinishNotify.proto\x1a=genshin/packet/proto/ChannelerSlabLoopDungeonResultInfo.proto\x1a\x32genshin/packet/proto/CustomDungeonResultInfo.proto\x1a;genshin/packet/proto/EffigyChallengeDungeonResultInfo.proto\x1a\x32genshin/packet/proto/PotionDungeonResultInfo.proto\x1a.genshin/packet/proto/StrengthenPointData.proto\x1a.genshin/packet/proto/Unk2700_FHOKHHBGPEG.proto\"\xcb\x05\n\x1c\x44ungeonChallengeFinishNotify\x12\\\n\x19strengthen_point_data_map\x18\r \x03(\x0b\x32\x39.DungeonChallengeFinishNotify.StrengthenPointDataMapEntry\x12\x31\n\x13Unk2700_ONCDLPDHFAB\x18\t \x01(\x0e\x32\x14.Unk2700_FHOKHHBGPEG\x12\x15\n\ris_new_record\x18\n \x01(\x08\x12\x1d\n\x15\x63hallenge_record_type\x18\x07 \x01(\r\x12\x11\n\ttime_cost\x18\x04 \x01(\r\x12\x15\n\rcurrent_value\x18\x0f \x01(\r\x12\x12\n\nis_success\x18\x03 \x01(\x08\x12\x17\n\x0f\x63hallenge_index\x18\x05 \x01(\r\x12X\n(channeller_slab_loop_dungeon_result_info\x18\xf1\x0b \x01(\x0b\x32#.ChannelerSlabLoopDungeonResultInfoH\x00\x12R\n$effigy_challenge_dungeon_result_info\x18\xdb\x0c \x01(\x0b\x32!.EffigyChallengeDungeonResultInfoH\x00\x12?\n\x1apotion_dungeon_result_info\x18\xa0\x0e \x01(\x0b\x32\x18.PotionDungeonResultInfoH\x00\x12?\n\x1a\x63ustom_dungeon_result_info\x18\x80\r \x01(\x0b\x32\x18.CustomDungeonResultInfoH\x00\x1aS\n\x1bStrengthenPointDataMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.StrengthenPointData:\x02\x38\x01\x42\x08\n\x06\x64\x65tailB\x16\n\x14org.sorapointa.protob\x06proto3')



_DUNGEONCHALLENGEFINISHNOTIFY = DESCRIPTOR.message_types_by_name['DungeonChallengeFinishNotify']
_DUNGEONCHALLENGEFINISHNOTIFY_STRENGTHENPOINTDATAMAPENTRY = _DUNGEONCHALLENGEFINISHNOTIFY.nested_types_by_name['StrengthenPointDataMapEntry']
DungeonChallengeFinishNotify = _reflection.GeneratedProtocolMessageType('DungeonChallengeFinishNotify', (_message.Message,), {

  'StrengthenPointDataMapEntry' : _reflection.GeneratedProtocolMessageType('StrengthenPointDataMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _DUNGEONCHALLENGEFINISHNOTIFY_STRENGTHENPOINTDATAMAPENTRY,
    '__module__' : 'genshin.packet.proto.DungeonChallengeFinishNotify_pb2'
    # @@protoc_insertion_point(class_scope:DungeonChallengeFinishNotify.StrengthenPointDataMapEntry)
    })
  ,
  'DESCRIPTOR' : _DUNGEONCHALLENGEFINISHNOTIFY,
  '__module__' : 'genshin.packet.proto.DungeonChallengeFinishNotify_pb2'
  # @@protoc_insertion_point(class_scope:DungeonChallengeFinishNotify)
  })
_sym_db.RegisterMessage(DungeonChallengeFinishNotify)
_sym_db.RegisterMessage(DungeonChallengeFinishNotify.StrengthenPointDataMapEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _DUNGEONCHALLENGEFINISHNOTIFY_STRENGTHENPOINTDATAMAPENTRY._options = None
  _DUNGEONCHALLENGEFINISHNOTIFY_STRENGTHENPOINTDATAMAPENTRY._serialized_options = b'8\001'
  _DUNGEONCHALLENGEFINISHNOTIFY._serialized_start=384
  _DUNGEONCHALLENGEFINISHNOTIFY._serialized_end=1099
  _DUNGEONCHALLENGEFINISHNOTIFY_STRENGTHENPOINTDATAMAPENTRY._serialized_start=1006
  _DUNGEONCHALLENGEFINISHNOTIFY_STRENGTHENPOINTDATAMAPENTRY._serialized_end=1089
# @@protoc_insertion_point(module_scope)
