# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/EBLCBLOFAHH.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/EBLCBLOFAHH.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import MEMAHNAJIBF_pb2 as genshin_dot_packet_dot_proto_dot_MEMAHNAJIBF__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/EBLCBLOFAHH.proto\x1a&genshin/packet/proto/MEMAHNAJIBF.proto\"\xec\x01\n\x0b\x45\x42LCBLOFAHH\x12!\n\x0b\x41\x46IMMKIAPMH\x18\x0c \x01(\x0b\x32\x0c.MEMAHNAJIBF\x12!\n\x0bIGEAOBLJCJE\x18\x0e \x01(\x0b\x32\x0c.MEMAHNAJIBF\x12!\n\x0bKCMKCCCMMIO\x18\x05 \x01(\x0b\x32\x0c.MEMAHNAJIBF\x12\x32\n\x0bJIPMFFLHKOM\x18\x08 \x03(\x0b\x32\x1d.EBLCBLOFAHH.JIPMFFLHKOMEntry\x1a@\n\x10JIPMFFLHKOMEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.MEMAHNAJIBF:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.EBLCBLOFAHH_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EBLCBLOFAHH_JIPMFFLHKOMENTRY']._loaded_options = None
  _globals['_EBLCBLOFAHH_JIPMFFLHKOMENTRY']._serialized_options = b'8\001'
  _globals['_EBLCBLOFAHH']._serialized_start=83
  _globals['_EBLCBLOFAHH']._serialized_end=319
  _globals['_EBLCBLOFAHH_JIPMFFLHKOMENTRY']._serialized_start=255
  _globals['_EBLCBLOFAHH_JIPMFFLHKOMENTRY']._serialized_end=319
# @@protoc_insertion_point(module_scope)
