# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/EchoShellTakeRewardRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1genshin/packet/proto/EchoShellTakeRewardRsp.proto\"<\n\x16\x45\x63hoShellTakeRewardRsp\x12\x11\n\treward_id\x18\x06 \x01(\r\x12\x0f\n\x07retcode\x18\n \x01(\x05\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_ECHOSHELLTAKEREWARDRSP = DESCRIPTOR.message_types_by_name['EchoShellTakeRewardRsp']
EchoShellTakeRewardRsp = _reflection.GeneratedProtocolMessageType('EchoShellTakeRewardRsp', (_message.Message,), {
  'DESCRIPTOR' : _ECHOSHELLTAKEREWARDRSP,
  '__module__' : 'genshin.packet.proto.EchoShellTakeRewardRsp_pb2'
  # @@protoc_insertion_point(class_scope:EchoShellTakeRewardRsp)
  })
_sym_db.RegisterMessage(EchoShellTakeRewardRsp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _ECHOSHELLTAKEREWARDRSP._serialized_start=53
  _ECHOSHELLTAKEREWARDRSP._serialized_end=113
# @@protoc_insertion_point(module_scope)
