# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/ECKACOBPKBL.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/ECKACOBPKBL.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import KDEHCGJAGFJ_pb2 as genshin_dot_packet_dot_proto_dot_KDEHCGJAGFJ__pb2
from genshin.packet.proto import ANBHHDKCDEN_pb2 as genshin_dot_packet_dot_proto_dot_ANBHHDKCDEN__pb2
from genshin.packet.proto import JMDIPFDJIAI_pb2 as genshin_dot_packet_dot_proto_dot_JMDIPFDJIAI__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/ECKACOBPKBL.proto\x1a&genshin/packet/proto/KDEHCGJAGFJ.proto\x1a&genshin/packet/proto/ANBHHDKCDEN.proto\x1a&genshin/packet/proto/JMDIPFDJIAI.proto\"\xaa\x01\n\x0b\x45\x43KACOBPKBL\x12!\n\x0bGJEBAJAJPII\x18\x04 \x01(\x0b\x32\x0c.KDEHCGJAGFJ\x12 \n\nsuite_data\x18\x07 \x01(\x0b\x32\x0c.ANBHHDKCDEN\x12\x1e\n\x08npc_data\x18\x06 \x01(\x0b\x32\x0c.JMDIPFDJIAI\x12\x13\n\x0bPCFIAAJEOIJ\x18\x03 \x01(\r\x12\x13\n\x0bOEGJAILDLBK\x18\x02 \x01(\r\x12\x0c\n\x04guid\x18\x01 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.ECKACOBPKBL_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ECKACOBPKBL']._serialized_start=163
  _globals['_ECKACOBPKBL']._serialized_end=333
# @@protoc_insertion_point(module_scope)
