# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/EEINAMGKPJK.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/EEINAMGKPJK.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import NPPCJPHMHBM_pb2 as genshin_dot_packet_dot_proto_dot_NPPCJPHMHBM__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/EEINAMGKPJK.proto\x1a&genshin/packet/proto/NPPCJPHMHBM.proto\"E\n\x0b\x45\x45INAMGKPJK\x12!\n\x0bMMDAIFBDGLJ\x18\x07 \x01(\x0e\x32\x0c.NPPCJPHMHBM\x12\x13\n\x0bNKCOLNAJDCA\x18\x0e \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.EEINAMGKPJK_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EEINAMGKPJK']._serialized_start=82
  _globals['_EEINAMGKPJK']._serialized_end=151
# @@protoc_insertion_point(module_scope)
