# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/EJLNBCBFOGL.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/EJLNBCBFOGL.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import LIPHHIENHHK_pb2 as genshin_dot_packet_dot_proto_dot_LIPHHIENHHK__pb2
from genshin.packet.proto import IPENCEJBEEB_pb2 as genshin_dot_packet_dot_proto_dot_IPENCEJBEEB__pb2
from genshin.packet.proto import PCLLABLBNGA_pb2 as genshin_dot_packet_dot_proto_dot_PCLLABLBNGA__pb2
from genshin.packet.proto import EHGJONOCFDE_pb2 as genshin_dot_packet_dot_proto_dot_EHGJONOCFDE__pb2
from genshin.packet.proto import FJCOKOHBJIN_pb2 as genshin_dot_packet_dot_proto_dot_FJCOKOHBJIN__pb2
from genshin.packet.proto import CAJFFFBLLKB_pb2 as genshin_dot_packet_dot_proto_dot_CAJFFFBLLKB__pb2
from genshin.packet.proto import LOAACAFCPIF_pb2 as genshin_dot_packet_dot_proto_dot_LOAACAFCPIF__pb2
from genshin.packet.proto import KLEEBOCFJPI_pb2 as genshin_dot_packet_dot_proto_dot_KLEEBOCFJPI__pb2
from genshin.packet.proto import AJPMIIOMCDO_pb2 as genshin_dot_packet_dot_proto_dot_AJPMIIOMCDO__pb2
from genshin.packet.proto import KFPAKMBEGPE_pb2 as genshin_dot_packet_dot_proto_dot_KFPAKMBEGPE__pb2
from genshin.packet.proto import EIMACLGMLLC_pb2 as genshin_dot_packet_dot_proto_dot_EIMACLGMLLC__pb2
from genshin.packet.proto import PJIFOJFADLG_pb2 as genshin_dot_packet_dot_proto_dot_PJIFOJFADLG__pb2
from genshin.packet.proto import NAPNKPIHEBF_pb2 as genshin_dot_packet_dot_proto_dot_NAPNKPIHEBF__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/EJLNBCBFOGL.proto\x1a&genshin/packet/proto/LIPHHIENHHK.proto\x1a&genshin/packet/proto/IPENCEJBEEB.proto\x1a&genshin/packet/proto/PCLLABLBNGA.proto\x1a&genshin/packet/proto/EHGJONOCFDE.proto\x1a&genshin/packet/proto/FJCOKOHBJIN.proto\x1a&genshin/packet/proto/CAJFFFBLLKB.proto\x1a&genshin/packet/proto/LOAACAFCPIF.proto\x1a&genshin/packet/proto/KLEEBOCFJPI.proto\x1a&genshin/packet/proto/AJPMIIOMCDO.proto\x1a&genshin/packet/proto/KFPAKMBEGPE.proto\x1a&genshin/packet/proto/EIMACLGMLLC.proto\x1a&genshin/packet/proto/PJIFOJFADLG.proto\x1a&genshin/packet/proto/NAPNKPIHEBF.proto\"\xbb\x04\n\x0b\x45JLNBCBFOGL\x12!\n\x0bGFMEKOGIHJN\x18\x13 \x01(\x0b\x32\x0c.LIPHHIENHHK\x12\x13\n\x0b\x42IPADACDOFI\x18\x16 \x03(\t\x12!\n\x0b\x42IHMCIIFMIG\x18\x04 \x01(\x0b\x32\x0c.IPENCEJBEEB\x12!\n\x0bKHLGCIFJBCK\x18\t \x03(\x0b\x32\x0c.PCLLABLBNGA\x12!\n\x0bMGDFIJMHGND\x18\x05 \x03(\x0b\x32\x0c.EHGJONOCFDE\x12!\n\x0b\x42\x43KBKIDDFCD\x18\x17 \x03(\x0b\x32\x0c.FJCOKOHBJIN\x12\x13\n\x0b\x42\x46MMHKFPCJB\x18\x03 \x01(\t\x12!\n\x0b\x45MJHADALPLA\x18\x14 \x03(\x0b\x32\x0c.CAJFFFBLLKB\x12!\n\x0bIGDCOEIOOCG\x18\x15 \x01(\x0b\x32\x0c.LOAACAFCPIF\x12!\n\x0bICPMAKBNJNL\x18\x06 \x03(\x0b\x32\x0c.KLEEBOCFJPI\x12\x12\n\nlife_state\x18\x07 \x01(\r\x12\x13\n\x0b\x45\x43OCHKAPDAM\x18\x11 \x01(\r\x12\x13\n\x0bMCINIPFFCCD\x18\x12 \x01(\r\x12!\n\x0b\x42JDAMEMIGCC\x18\x01 \x01(\x0e\x32\x0c.AJPMIIOMCDO\x12\x19\n\x03npc\x18\x0c \x01(\x0b\x32\x0c.KFPAKMBEGPE\x12\x1c\n\x06gadget\x18\r \x01(\x0b\x32\x0c.EIMACLGMLLC\x12\x1d\n\x07monster\x18\x0b \x01(\x0b\x32\x0c.PJIFOJFADLG\x12\x1c\n\x06\x61vatar\x18\n \x01(\x0b\x32\x0c.NAPNKPIHEBF\x12\x13\n\x0b\x41GIDBEEINDE\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.EJLNBCBFOGL_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EJLNBCBFOGL']._serialized_start=563
  _globals['_EJLNBCBFOGL']._serialized_end=1134
# @@protoc_insertion_point(module_scope)
