# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/EKGJKEOBKBK.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/EKGJKEOBKBK.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import JOECDAOLNFD_pb2 as genshin_dot_packet_dot_proto_dot_JOECDAOLNFD__pb2
from genshin.packet.proto import IDLAEJGILNL_pb2 as genshin_dot_packet_dot_proto_dot_IDLAEJGILNL__pb2
from genshin.packet.proto import HFILDBLLMOP_pb2 as genshin_dot_packet_dot_proto_dot_HFILDBLLMOP__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/EKGJKEOBKBK.proto\x1a&genshin/packet/proto/JOECDAOLNFD.proto\x1a&genshin/packet/proto/IDLAEJGILNL.proto\x1a&genshin/packet/proto/HFILDBLLMOP.proto\"v\n\x0b\x45KGJKEOBKBK\x12!\n\x0bKFIIICLOLKG\x18\x04 \x01(\x0b\x32\x0c.JOECDAOLNFD\x12!\n\x0bNABHBHGBPON\x18\x01 \x01(\x0b\x32\x0c.IDLAEJGILNL\x12!\n\x0bGAFMCJBMFAE\x18\x0c \x01(\x0b\x32\x0c.HFILDBLLMOPb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.EKGJKEOBKBK_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EKGJKEOBKBK']._serialized_start=162
  _globals['_EKGJKEOBKBK']._serialized_end=280
# @@protoc_insertion_point(module_scope)
