from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class ELFNOFGGCIA(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    ELFNOFGGCIA_CUSTOM_DUNGEON_FINISH_PLAY_NORMAL: _ClassVar[ELFNOFGGCIA]
    ELFNOFGGCIA_CUSTOM_DUNGEON_FINISH_PLAY_TRY: _ClassVar[ELFNOFGGCIA]
    ELFNOFGGCIA_CUSTOM_DUNGEON_FINISH_EDIT_TRY: _ClassVar[ELFNOFGGCIA]
    ELFNOFGGCIA_CUSTOM_DUNGEON_FINISH_SELF_PLAY_NORMAL: _ClassVar[ELFNOFGGCIA]
ELFNOFGGCIA_CUSTOM_DUNGEON_FINISH_PLAY_NORMAL: ELFNOFGGCIA
ELFNOFGGCIA_CUSTOM_DUNGEON_FINISH_PLAY_TRY: ELFNOFGGCIA
ELFNOFGGCIA_CUSTOM_DUNGEON_FINISH_EDIT_TRY: ELFNOFGGCIA
ELFNOFGGCIA_CUSTOM_DUNGEON_FINISH_SELF_PLAY_NORMAL: ELFNOFGGCIA
