# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/ELHHMLEGPAH.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/ELHHMLEGPAH.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import Item_pb2 as genshin_dot_packet_dot_proto_dot_Item__pb2
from genshin.packet.proto import StoreType_pb2 as genshin_dot_packet_dot_proto_dot_StoreType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/ELHHMLEGPAH.proto\x1a\x1fgenshin/packet/proto/Item.proto\x1a$genshin/packet/proto/StoreType.proto\"G\n\x0b\x45LHHMLEGPAH\x12\x18\n\titem_list\x18\x0c \x03(\x0b\x32\x05.Item\x12\x1e\n\nstore_type\x18\n \x01(\x0e\x32\n.StoreTypeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.ELHHMLEGPAH_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELHHMLEGPAH']._serialized_start=113
  _globals['_ELHHMLEGPAH']._serialized_end=184
# @@protoc_insertion_point(module_scope)
