# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/EntityAuthorityInfo.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/EntityAuthorityInfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import AbilitySyncStateInfo_pb2 as genshin_dot_packet_dot_proto_dot_AbilitySyncStateInfo__pb2
from genshin.packet.proto import EntityRendererChangedInfo_pb2 as genshin_dot_packet_dot_proto_dot_EntityRendererChangedInfo__pb2
from genshin.packet.proto import SceneEntityAiInfo_pb2 as genshin_dot_packet_dot_proto_dot_SceneEntityAiInfo__pb2
from genshin.packet.proto import Vector_pb2 as genshin_dot_packet_dot_proto_dot_Vector__pb2
from genshin.packet.proto import AnimatorParameterValueInfoPair_pb2 as genshin_dot_packet_dot_proto_dot_AnimatorParameterValueInfoPair__pb2
from genshin.packet.proto import EntityClientExtraInfo_pb2 as genshin_dot_packet_dot_proto_dot_EntityClientExtraInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/EntityAuthorityInfo.proto\x1a/genshin/packet/proto/AbilitySyncStateInfo.proto\x1a\x34genshin/packet/proto/EntityRendererChangedInfo.proto\x1a,genshin/packet/proto/SceneEntityAiInfo.proto\x1a!genshin/packet/proto/Vector.proto\x1a\x39genshin/packet/proto/AnimatorParameterValueInfoPair.proto\x1a\x30genshin/packet/proto/EntityClientExtraInfo.proto\"\xa9\x02\n\x13\x45ntityAuthorityInfo\x12+\n\x0c\x61\x62ility_info\x18\x01 \x01(\x0b\x32\x15.AbilitySyncStateInfo\x12\x39\n\x15renderer_changed_info\x18\x02 \x01(\x0b\x32\x1a.EntityRendererChangedInfo\x12#\n\x07\x61i_info\x18\x03 \x01(\x0b\x32\x12.SceneEntityAiInfo\x12\x19\n\x08\x62orn_pos\x18\x04 \x01(\x0b\x32\x07.Vector\x12\x37\n\x0epose_para_list\x18\x05 \x03(\x0b\x32\x1f.AnimatorParameterValueInfoPair\x12\x31\n\x11\x63lient_extra_info\x18\x06 \x01(\x0b\x32\x16.EntityClientExtraInfoB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.EntityAuthorityInfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_ENTITYAUTHORITYINFO']._serialized_start=344
  _globals['_ENTITYAUTHORITYINFO']._serialized_end=641
# @@protoc_insertion_point(module_scope)
