# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/EntityAiKillSelfNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1genshin/packet/proto/EntityAiKillSelfNotify.proto\"+\n\x16\x45ntityAiKillSelfNotify\x12\x11\n\tentity_id\x18\x0c \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_ENTITYAIKILLSELFNOTIFY = DESCRIPTOR.message_types_by_name['EntityAiKillSelfNotify']
EntityAiKillSelfNotify = _reflection.GeneratedProtocolMessageType('EntityAiKillSelfNotify', (_message.Message,), {
  'DESCRIPTOR' : _ENTITYAIKILLSELFNOTIFY,
  '__module__' : 'genshin.packet.proto.EntityAiKillSelfNotify_pb2'
  # @@protoc_insertion_point(class_scope:EntityAiKillSelfNotify)
  })
_sym_db.RegisterMessage(EntityAiKillSelfNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _ENTITYAIKILLSELFNOTIFY._serialized_start=53
  _ENTITYAIKILLSELFNOTIFY._serialized_end=96
# @@protoc_insertion_point(module_scope)
