# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/EvtAvatarLockChairRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import Vector_pb2 as genshin_dot_packet_dot_proto_dot_Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0genshin/packet/proto/EvtAvatarLockChairRsp.proto\x1a!genshin/packet/proto/Vector.proto\"h\n\x15\x45vtAvatarLockChairRsp\x12\x10\n\x08\x63hair_id\x18\x0e \x01(\x04\x12\x11\n\tentity_id\x18\x0f \x01(\r\x12\x19\n\x08position\x18\x04 \x01(\x0b\x32\x07.Vector\x12\x0f\n\x07retcode\x18\x0c \x01(\x05\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_EVTAVATARLOCKCHAIRRSP = DESCRIPTOR.message_types_by_name['EvtAvatarLockChairRsp']
EvtAvatarLockChairRsp = _reflection.GeneratedProtocolMessageType('EvtAvatarLockChairRsp', (_message.Message,), {
  'DESCRIPTOR' : _EVTAVATARLOCKCHAIRRSP,
  '__module__' : 'genshin.packet.proto.EvtAvatarLockChairRsp_pb2'
  # @@protoc_insertion_point(class_scope:EvtAvatarLockChairRsp)
  })
_sym_db.RegisterMessage(EvtAvatarLockChairRsp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _EVTAVATARLOCKCHAIRRSP._serialized_start=87
  _EVTAVATARLOCKCHAIRRSP._serialized_end=191
# @@protoc_insertion_point(module_scope)
