# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/EvtAiSyncSkillCdNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import AiSkillCdInfo_pb2 as genshin_dot_packet_dot_proto_dot_AiSkillCdInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1genshin/packet/proto/EvtAiSyncSkillCdNotify.proto\x1a(genshin/packet/proto/AiSkillCdInfo.proto\"\x91\x01\n\x16\x45vtAiSyncSkillCdNotify\x12\x37\n\tai_cd_map\x18\x07 \x03(\x0b\x32$.EvtAiSyncSkillCdNotify.AiCdMapEntry\x1a>\n\x0c\x41iCdMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.AiSkillCdInfo:\x02\x38\x01\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_EVTAISYNCSKILLCDNOTIFY = DESCRIPTOR.message_types_by_name['EvtAiSyncSkillCdNotify']
_EVTAISYNCSKILLCDNOTIFY_AICDMAPENTRY = _EVTAISYNCSKILLCDNOTIFY.nested_types_by_name['AiCdMapEntry']
EvtAiSyncSkillCdNotify = _reflection.GeneratedProtocolMessageType('EvtAiSyncSkillCdNotify', (_message.Message,), {

  'AiCdMapEntry' : _reflection.GeneratedProtocolMessageType('AiCdMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _EVTAISYNCSKILLCDNOTIFY_AICDMAPENTRY,
    '__module__' : 'genshin.packet.proto.EvtAiSyncSkillCdNotify_pb2'
    # @@protoc_insertion_point(class_scope:EvtAiSyncSkillCdNotify.AiCdMapEntry)
    })
  ,
  'DESCRIPTOR' : _EVTAISYNCSKILLCDNOTIFY,
  '__module__' : 'genshin.packet.proto.EvtAiSyncSkillCdNotify_pb2'
  # @@protoc_insertion_point(class_scope:EvtAiSyncSkillCdNotify)
  })
_sym_db.RegisterMessage(EvtAiSyncSkillCdNotify)
_sym_db.RegisterMessage(EvtAiSyncSkillCdNotify.AiCdMapEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _EVTAISYNCSKILLCDNOTIFY_AICDMAPENTRY._options = None
  _EVTAISYNCSKILLCDNOTIFY_AICDMAPENTRY._serialized_options = b'8\001'
  _EVTAISYNCSKILLCDNOTIFY._serialized_start=96
  _EVTAISYNCSKILLCDNOTIFY._serialized_end=241
  _EVTAISYNCSKILLCDNOTIFY_AICDMAPENTRY._serialized_start=179
  _EVTAISYNCSKILLCDNOTIFY_AICDMAPENTRY._serialized_end=241
# @@protoc_insertion_point(module_scope)
