# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/EvtCostStaminaNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/genshin/packet/proto/EvtCostStaminaNotify.proto\">\n\x14\x45vtCostStaminaNotify\x12\x10\n\x08skill_id\x18\x06 \x01(\r\x12\x14\n\x0c\x63ost_stamina\x18\x0b \x01(\x02\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_EVTCOSTSTAMINANOTIFY = DESCRIPTOR.message_types_by_name['EvtCostStaminaNotify']
EvtCostStaminaNotify = _reflection.GeneratedProtocolMessageType('EvtCostStaminaNotify', (_message.Message,), {
  'DESCRIPTOR' : _EVTCOSTSTAMINANOTIFY,
  '__module__' : 'genshin.packet.proto.EvtCostStaminaNotify_pb2'
  # @@protoc_insertion_point(class_scope:EvtCostStaminaNotify)
  })
_sym_db.RegisterMessage(EvtCostStaminaNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _EVTCOSTSTAMINANOTIFY._serialized_start=51
  _EVTCOSTSTAMINANOTIFY._serialized_end=113
# @@protoc_insertion_point(module_scope)
