# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/EvtDestroyServerGadgetNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7genshin/packet/proto/EvtDestroyServerGadgetNotify.proto\"1\n\x1c\x45vtDestroyServerGadgetNotify\x12\x11\n\tentity_id\x18\x07 \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_EVTDESTROYSERVERGADGETNOTIFY = DESCRIPTOR.message_types_by_name['EvtDestroyServerGadgetNotify']
EvtDestroyServerGadgetNotify = _reflection.GeneratedProtocolMessageType('EvtDestroyServerGadgetNotify', (_message.Message,), {
  'DESCRIPTOR' : _EVTDESTROYSERVERGADGETNOTIFY,
  '__module__' : 'genshin.packet.proto.EvtDestroyServerGadgetNotify_pb2'
  # @@protoc_insertion_point(class_scope:EvtDestroyServerGadgetNotify)
  })
_sym_db.RegisterMessage(EvtDestroyServerGadgetNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _EVTDESTROYSERVERGADGETNOTIFY._serialized_start=59
  _EVTDESTROYSERVERGADGETNOTIFY._serialized_end=108
# @@protoc_insertion_point(module_scope)
