# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/ExpeditionAssistInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/genshin/packet/proto/ExpeditionAssistInfo.proto\"\x7f\n\x14\x45xpeditionAssistInfo\x12\x11\n\tonline_id\x18\x0e \x01(\t\x12\x13\n\x0b\x61ssist_time\x18\x01 \x01(\r\x12\x12\n\ncostume_id\x18\x06 \x01(\r\x12\x18\n\x10target_nick_name\x18\x04 \x01(\t\x12\x11\n\tavatar_id\x18\x0c \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_EXPEDITIONASSISTINFO = DESCRIPTOR.message_types_by_name['ExpeditionAssistInfo']
ExpeditionAssistInfo = _reflection.GeneratedProtocolMessageType('ExpeditionAssistInfo', (_message.Message,), {
  'DESCRIPTOR' : _EXPEDITIONASSISTINFO,
  '__module__' : 'genshin.packet.proto.ExpeditionAssistInfo_pb2'
  # @@protoc_insertion_point(class_scope:ExpeditionAssistInfo)
  })
_sym_db.RegisterMessage(ExpeditionAssistInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _EXPEDITIONASSISTINFO._serialized_start=51
  _EXPEDITIONASSISTINFO._serialized_end=178
# @@protoc_insertion_point(module_scope)
