# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/ExpeditionState.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*genshin/packet/proto/ExpeditionState.proto*\xa5\x01\n\x0f\x45xpeditionState\x12\x19\n\x15\x45XPEDITION_STATE_NONE\x10\x00\x12\x1c\n\x18\x45XPEDITION_STATE_STARTED\x10\x01\x12\x1d\n\x19\x45XPEDITION_STATE_FINISHED\x10\x02\x12\x1d\n\x19\x45XPEDITION_STATE_REWARDED\x10\x03\x12\x1b\n\x17\x45XPEDITION_STATE_LOCKED\x10\x04\x42\x16\n\x14org.sorapointa.protob\x06proto3')

_EXPEDITIONSTATE = DESCRIPTOR.enum_types_by_name['ExpeditionState']
ExpeditionState = enum_type_wrapper.EnumTypeWrapper(_EXPEDITIONSTATE)
EXPEDITION_STATE_NONE = 0
EXPEDITION_STATE_STARTED = 1
EXPEDITION_STATE_FINISHED = 2
EXPEDITION_STATE_REWARDED = 3
EXPEDITION_STATE_LOCKED = 4


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _EXPEDITIONSTATE._serialized_start=47
  _EXPEDITIONSTATE._serialized_end=212
# @@protoc_insertion_point(module_scope)
