from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class FBONNIGMEIP(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    FBONNIGMEIP_REPORT_REASON_NONE: _ClassVar[FBONNIGMEIP]
    FBONNIGMEIP_REPORT_REASON_DECEPTIVE_ADS: _ClassVar[FBONNIGMEIP]
    FBONNIGMEIP_REPORT_REASON_ABUSING: _ClassVar[FBONNIGMEIP]
    FBONNIGMEIP_REPORT_REASON_CHEAT: _ClassVar[FBONNIGMEIP]
    FBONNIGMEIP_REPORT_REASON_POLITICAL: _ClassVar[FBONNIGMEIP]
    FBONNIGMEIP_REPORT_REASON_OTHER: _ClassVar[FBONNIGMEIP]
    FBONNIGMEIP_REPORT_REASON_HOME: _ClassVar[FBONNIGMEIP]
FBONNIGMEIP_REPORT_REASON_NONE: FBONNIGMEIP
FBONNIGMEIP_REPORT_REASON_DECEPTIVE_ADS: FBONNIGMEIP
FBONNIGMEIP_REPORT_REASON_ABUSING: FBONNIGMEIP
FBONNIGMEIP_REPORT_REASON_CHEAT: FBONNIGMEIP
FBONNIGMEIP_REPORT_REASON_POLITICAL: FBONNIGMEIP
FBONNIGMEIP_REPORT_REASON_OTHER: FBONNIGMEIP
FBONNIGMEIP_REPORT_REASON_HOME: FBONNIGMEIP
