# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/FDJCEBEPFAD.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/FDJCEBEPFAD.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import CNHOEJPPNNM_pb2 as genshin_dot_packet_dot_proto_dot_CNHOEJPPNNM__pb2
from genshin.packet.proto import PCBPKGLMOAP_pb2 as genshin_dot_packet_dot_proto_dot_PCBPKGLMOAP__pb2
from genshin.packet.proto import KMLAIHINCLK_pb2 as genshin_dot_packet_dot_proto_dot_KMLAIHINCLK__pb2
from genshin.packet.proto import CBIAGEKFJBB_pb2 as genshin_dot_packet_dot_proto_dot_CBIAGEKFJBB__pb2
from genshin.packet.proto import FJLOAADFJOL_pb2 as genshin_dot_packet_dot_proto_dot_FJLOAADFJOL__pb2
from genshin.packet.proto import HBNHJHAMKDP_pb2 as genshin_dot_packet_dot_proto_dot_HBNHJHAMKDP__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/FDJCEBEPFAD.proto\x1a&genshin/packet/proto/CNHOEJPPNNM.proto\x1a&genshin/packet/proto/PCBPKGLMOAP.proto\x1a&genshin/packet/proto/KMLAIHINCLK.proto\x1a&genshin/packet/proto/CBIAGEKFJBB.proto\x1a&genshin/packet/proto/FJLOAADFJOL.proto\x1a&genshin/packet/proto/HBNHJHAMKDP.proto\"\xdf\x01\n\x0b\x46\x44JCEBEPFAD\x12!\n\x0bGAKCLBINMHF\x18\x0b \x01(\x0b\x32\x0c.CNHOEJPPNNM\x12!\n\x0b\x41NBALAJJOJB\x18\r \x01(\x0b\x32\x0c.PCBPKGLMOAP\x12!\n\x0b\x42PNEAPBAINE\x18\n \x01(\x0b\x32\x0c.KMLAIHINCLK\x12!\n\x0bPEMOIGKJAGH\x18\x0c \x01(\x0b\x32\x0c.CBIAGEKFJBB\x12!\n\x0bMCKCAKLECJF\x18\t \x01(\x0b\x32\x0c.FJLOAADFJOL\x12!\n\x0bKLJIDFJCLDA\x18\x0f \x01(\x0b\x32\x0c.HBNHJHAMKDPb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.FDJCEBEPFAD_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FDJCEBEPFAD']._serialized_start=283
  _globals['_FDJCEBEPFAD']._serialized_end=506
# @@protoc_insertion_point(module_scope)
