# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/FindHilichurlDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import FindHilichurlDayContentInfo_pb2 as genshin_dot_packet_dot_proto_dot_FindHilichurlDayContentInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2genshin/packet/proto/FindHilichurlDetailInfo.proto\x1a\x36genshin/packet/proto/FindHilichurlDayContentInfo.proto\"\xf6\x01\n\x17\x46indHilichurlDetailInfo\x12;\n\x15\x64\x61y_content_info_list\x18\x01 \x03(\x0b\x32\x1c.FindHilichurlDayContentInfo\x12\x1d\n\x15min_open_player_level\x18\x0c \x01(\r\x12\x1b\n\x13is_end_quest_accept\x18\x07 \x01(\x08\x12\x1a\n\x12\x63ontent_close_time\x18\x06 \x01(\r\x12\x19\n\x11is_content_closed\x18\t \x01(\x08\x12\x18\n\x10player_day_index\x18\x04 \x01(\r\x12\x11\n\tday_index\x18\x0f \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_FINDHILICHURLDETAILINFO = DESCRIPTOR.message_types_by_name['FindHilichurlDetailInfo']
FindHilichurlDetailInfo = _reflection.GeneratedProtocolMessageType('FindHilichurlDetailInfo', (_message.Message,), {
  'DESCRIPTOR' : _FINDHILICHURLDETAILINFO,
  '__module__' : 'genshin.packet.proto.FindHilichurlDetailInfo_pb2'
  # @@protoc_insertion_point(class_scope:FindHilichurlDetailInfo)
  })
_sym_db.RegisterMessage(FindHilichurlDetailInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _FINDHILICHURLDETAILINFO._serialized_start=111
  _FINDHILICHURLDETAILINFO._serialized_end=357
# @@protoc_insertion_point(module_scope)
