# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/FishingGallerySettleNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import FishingGallerySettleInfo_pb2 as genshin_dot_packet_dot_proto_dot_FishingGallerySettleInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5genshin/packet/proto/FishingGallerySettleNotify.proto\x1a\x33genshin/packet/proto/FishingGallerySettleInfo.proto\"r\n\x1a\x46ishingGallerySettleNotify\x12\x12\n\ngallery_id\x18\x06 \x01(\r\x12\x10\n\x08level_id\x18\x0f \x01(\r\x12.\n\x0bsettle_info\x18\r \x01(\x0b\x32\x19.FishingGallerySettleInfoB\x16\n\x14org.sorapointa.protob\x06proto3')



_FISHINGGALLERYSETTLENOTIFY = DESCRIPTOR.message_types_by_name['FishingGallerySettleNotify']
FishingGallerySettleNotify = _reflection.GeneratedProtocolMessageType('FishingGallerySettleNotify', (_message.Message,), {
  'DESCRIPTOR' : _FISHINGGALLERYSETTLENOTIFY,
  '__module__' : 'genshin.packet.proto.FishingGallerySettleNotify_pb2'
  # @@protoc_insertion_point(class_scope:FishingGallerySettleNotify)
  })
_sym_db.RegisterMessage(FishingGallerySettleNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _FISHINGGALLERYSETTLENOTIFY._serialized_start=110
  _FISHINGGALLERYSETTLENOTIFY._serialized_end=224
# @@protoc_insertion_point(module_scope)
