# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/FishInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#genshin/packet/proto/FishInfo.proto\"6\n\x08\x46ishInfo\x12\x12\n\nfree_count\x18\x0b \x01(\r\x12\x16\n\x0einto_bag_count\x18\x0c \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_FISHINFO = DESCRIPTOR.message_types_by_name['FishInfo']
FishInfo = _reflection.GeneratedProtocolMessageType('FishInfo', (_message.Message,), {
  'DESCRIPTOR' : _FISHINFO,
  '__module__' : 'genshin.packet.proto.FishInfo_pb2'
  # @@protoc_insertion_point(class_scope:FishInfo)
  })
_sym_db.RegisterMessage(FishInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _FISHINFO._serialized_start=39
  _FISHINFO._serialized_end=93
# @@protoc_insertion_point(module_scope)
