# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/FishBattleEndReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import FishBattleResult_pb2 as genshin_dot_packet_dot_proto_dot_FishBattleResult__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+genshin/packet/proto/FishBattleEndReq.proto\x1a+genshin/packet/proto/FishBattleResult.proto\"m\n\x10\x46ishBattleEndReq\x12\x16\n\x0emax_bonus_time\x18\x03 \x01(\r\x12(\n\rbattle_result\x18\n \x01(\x0e\x32\x11.FishBattleResult\x12\x17\n\x0fis_always_bonus\x18\x0b \x01(\x08\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_FISHBATTLEENDREQ = DESCRIPTOR.message_types_by_name['FishBattleEndReq']
FishBattleEndReq = _reflection.GeneratedProtocolMessageType('FishBattleEndReq', (_message.Message,), {
  'DESCRIPTOR' : _FISHBATTLEENDREQ,
  '__module__' : 'genshin.packet.proto.FishBattleEndReq_pb2'
  # @@protoc_insertion_point(class_scope:FishBattleEndReq)
  })
_sym_db.RegisterMessage(FishBattleEndReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _FISHBATTLEENDREQ._serialized_start=92
  _FISHBATTLEENDREQ._serialized_end=201
# @@protoc_insertion_point(module_scope)
