# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/FleurFairFallSettleInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import FallSettleInfo_pb2 as genshin_dot_packet_dot_proto_dot_FallSettleInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2genshin/packet/proto/FleurFairFallSettleInfo.proto\x1a)genshin/packet/proto/FallSettleInfo.proto\"V\n\x17\x46leurFairFallSettleInfo\x12$\n\x0bsettle_info\x18\x04 \x01(\x0b\x32\x0f.FallSettleInfo\x12\x15\n\ris_new_record\x18\n \x01(\x08\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_FLEURFAIRFALLSETTLEINFO = DESCRIPTOR.message_types_by_name['FleurFairFallSettleInfo']
FleurFairFallSettleInfo = _reflection.GeneratedProtocolMessageType('FleurFairFallSettleInfo', (_message.Message,), {
  'DESCRIPTOR' : _FLEURFAIRFALLSETTLEINFO,
  '__module__' : 'genshin.packet.proto.FleurFairFallSettleInfo_pb2'
  # @@protoc_insertion_point(class_scope:FleurFairFallSettleInfo)
  })
_sym_db.RegisterMessage(FleurFairFallSettleInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _FLEURFAIRFALLSETTLEINFO._serialized_start=97
  _FLEURFAIRFALLSETTLEINFO._serialized_end=183
# @@protoc_insertion_point(module_scope)
