# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/FlightActivityDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import FlightDailyRecord_pb2 as genshin_dot_packet_dot_proto_dot_FlightDailyRecord__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3genshin/packet/proto/FlightActivityDetailInfo.proto\x1a,genshin/packet/proto/FlightDailyRecord.proto\"\x83\x01\n\x18\x46lightActivityDetailInfo\x12\x19\n\x11preview_reward_id\x18\x0f \x01(\r\x12\x1d\n\x15min_open_player_level\x18\x0b \x01(\r\x12-\n\x11\x64\x61ily_record_list\x18\x01 \x03(\x0b\x32\x12.FlightDailyRecordB\x16\n\x14org.sorapointa.protob\x06proto3')



_FLIGHTACTIVITYDETAILINFO = DESCRIPTOR.message_types_by_name['FlightActivityDetailInfo']
FlightActivityDetailInfo = _reflection.GeneratedProtocolMessageType('FlightActivityDetailInfo', (_message.Message,), {
  'DESCRIPTOR' : _FLIGHTACTIVITYDETAILINFO,
  '__module__' : 'genshin.packet.proto.FlightActivityDetailInfo_pb2'
  # @@protoc_insertion_point(class_scope:FlightActivityDetailInfo)
  })
_sym_db.RegisterMessage(FlightActivityDetailInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _FLIGHTACTIVITYDETAILINFO._serialized_start=102
  _FLIGHTACTIVITYDETAILINFO._serialized_end=233
# @@protoc_insertion_point(module_scope)
