# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/FlightActivityRestartRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3genshin/packet/proto/FlightActivityRestartRsp.proto\"R\n\x18\x46lightActivityRestartRsp\x12\x10\n\x08group_id\x18\x0b \x01(\r\x12\x13\n\x0bschedule_id\x18\n \x01(\r\x12\x0f\n\x07retcode\x18\x0f \x01(\x05\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_FLIGHTACTIVITYRESTARTRSP = DESCRIPTOR.message_types_by_name['FlightActivityRestartRsp']
FlightActivityRestartRsp = _reflection.GeneratedProtocolMessageType('FlightActivityRestartRsp', (_message.Message,), {
  'DESCRIPTOR' : _FLIGHTACTIVITYRESTARTRSP,
  '__module__' : 'genshin.packet.proto.FlightActivityRestartRsp_pb2'
  # @@protoc_insertion_point(class_scope:FlightActivityRestartRsp)
  })
_sym_db.RegisterMessage(FlightActivityRestartRsp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _FLIGHTACTIVITYRESTARTRSP._serialized_start=55
  _FLIGHTACTIVITYRESTARTRSP._serialized_end=137
# @@protoc_insertion_point(module_scope)
