from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class FLMMANLPMNB(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    FLMMANLPMNB_SERVER_LOG_NONE: _ClassVar[FLMMANLPMNB]
    FLMMANLPMNB_SERVER_LOG_ABILITY: _ClassVar[FLMMANLPMNB]
    FLMMANLPMNB_SERVER_LOG_LEVEL: _ClassVar[FLMMANLPMNB]
    FLMMANLPMNB_SERVER_LOG_ENTITY: _ClassVar[FLMMANLPMNB]
    FLMMANLPMNB_SERVER_LOG_LUA: _ClassVar[FLMMANLPMNB]
    FLMMANLPMNB_SERVER_LOG_DAILYTASK: _ClassVar[FLMMANLPMNB]
FLMMANLPMNB_SERVER_LOG_NONE: FLMMANLPMNB
FLMMANLPMNB_SERVER_LOG_ABILITY: FLMMANLPMNB
FLMMANLPMNB_SERVER_LOG_LEVEL: FLMMANLPMNB
FLMMANLPMNB_SERVER_LOG_ENTITY: FLMMANLPMNB
FLMMANLPMNB_SERVER_LOG_LUA: FLMMANLPMNB
FLMMANLPMNB_SERVER_LOG_DAILYTASK: FLMMANLPMNB
