from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class FMBEGBMCCBC(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    FMBEGBMCCBC_NONE: _ClassVar[FMBEGBMCCBC]
    FMBEGBMCCBC_THEME: _ClassVar[FMBEGBMCCBC]
    FMBEGBMCCBC_FALLING: _ClassVar[FMBEGBMCCBC]
    FMBEGBMCCBC_TRACK: _ClassVar[FMBEGBMCCBC]
    FMBEGBMCCBC_CONNECTION: _ClassVar[FMBEGBMCCBC]
    FMBEGBMCCBC_FEVER: _ClassVar[FMBEGBMCCBC]
    FMBEGBMCCBC_BACKGROUND: _ClassVar[FMBEGBMCCBC]
    FMBEGBMCCBC_THEME_FOLLOW: _ClassVar[FMBEGBMCCBC]
    FMBEGBMCCBC_INSTRUMENT: _ClassVar[FMBEGBMCCBC]
FMBEGBMCCBC_NONE: FMBEGBMCCBC
FMBEGBMCCBC_THEME: FMBEGBMCCBC
FMBEGBMCCBC_FALLING: FMBEGBMCCBC
FMBEGBMCCBC_TRACK: FMBEGBMCCBC
FMBEGBMCCBC_CONNECTION: FMBEGBMCCBC
FMBEGBMCCBC_FEVER: FMBEGBMCCBC
FMBEGBMCCBC_BACKGROUND: FMBEGBMCCBC
FMBEGBMCCBC_THEME_FOLLOW: FMBEGBMCCBC
FMBEGBMCCBC_INSTRUMENT: FMBEGBMCCBC
