from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class FMFNEJNKFCJ(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    FMFNEJNKFCJ_ENTER_NONE: _ClassVar[FMFNEJNKFCJ]
    FMFNEJNKFCJ_ENTER_SELF: _ClassVar[FMFNEJNKFCJ]
    FMFNEJNKFCJ_ENTER_GOTO: _ClassVar[FMFNEJNKFCJ]
    FMFNEJNKFCJ_ENTER_JUMP: _ClassVar[FMFNEJNKFCJ]
    FMFNEJNKFCJ_ENTER_OTHER: _ClassVar[FMFNEJNKFCJ]
    FMFNEJNKFCJ_ENTER_BACK: _ClassVar[FMFNEJNKFCJ]
    FMFNEJNKFCJ_ENTER_DUNGEON: _ClassVar[FMFNEJNKFCJ]
    FMFNEJNKFCJ_ENTER_DUNGEON_REPLAY: _ClassVar[FMFNEJNKFCJ]
    FMFNEJNKFCJ_ENTER_GOTO_BY_PORTAL: _ClassVar[FMFNEJNKFCJ]
    FMFNEJNKFCJ_ENTER_SELF_HOME: _ClassVar[FMFNEJNKFCJ]
    FMFNEJNKFCJ_ENTER_OTHER_HOME: _ClassVar[FMFNEJNKFCJ]
    FMFNEJNKFCJ_ENTER_GOTO_RECREATE: _ClassVar[FMFNEJNKFCJ]
    FMFNEJNKFCJ_ENTER_GOTO_BY_TPL: _ClassVar[FMFNEJNKFCJ]
FMFNEJNKFCJ_ENTER_NONE: FMFNEJNKFCJ
FMFNEJNKFCJ_ENTER_SELF: FMFNEJNKFCJ
FMFNEJNKFCJ_ENTER_GOTO: FMFNEJNKFCJ
FMFNEJNKFCJ_ENTER_JUMP: FMFNEJNKFCJ
FMFNEJNKFCJ_ENTER_OTHER: FMFNEJNKFCJ
FMFNEJNKFCJ_ENTER_BACK: FMFNEJNKFCJ
FMFNEJNKFCJ_ENTER_DUNGEON: FMFNEJNKFCJ
FMFNEJNKFCJ_ENTER_DUNGEON_REPLAY: FMFNEJNKFCJ
FMFNEJNKFCJ_ENTER_GOTO_BY_PORTAL: FMFNEJNKFCJ
FMFNEJNKFCJ_ENTER_SELF_HOME: FMFNEJNKFCJ
FMFNEJNKFCJ_ENTER_OTHER_HOME: FMFNEJNKFCJ
FMFNEJNKFCJ_ENTER_GOTO_RECREATE: FMFNEJNKFCJ
FMFNEJNKFCJ_ENTER_GOTO_BY_TPL: FMFNEJNKFCJ
