# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/FPOEAODOHGO.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/FPOEAODOHGO.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import OLHEKLKENDN_pb2 as genshin_dot_packet_dot_proto_dot_OLHEKLKENDN__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/FPOEAODOHGO.proto\x1a&genshin/packet/proto/OLHEKLKENDN.proto\"\x84\x01\n\x0b\x46POEAODOHGO\x12!\n\x0b\x46GAEINCCKDK\x18\x0f \x01(\x0b\x32\x0c.OLHEKLKENDN\x12\x13\n\x0b\x46JAMCDJDJOA\x18\x05 \x01(\r\x12\x13\n\x0b\x43\x41JPBMIMDNG\x18\r \x01(\r\x12\x13\n\x0bNCCPPHNNPBF\x18\x02 \x01(\r\x12\x13\n\x0b\x43PBJLEFBPFM\x18\x0e \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.FPOEAODOHGO_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FPOEAODOHGO']._serialized_start=83
  _globals['_FPOEAODOHGO']._serialized_end=215
# @@protoc_insertion_point(module_scope)
