# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/GadgetPlayUidInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import ProfilePicture_pb2 as genshin_dot_packet_dot_proto_dot_ProfilePicture__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,genshin/packet/proto/GadgetPlayUidInfo.proto\x1a)genshin/packet/proto/ProfilePicture.proto\"\xa7\x01\n\x11GadgetPlayUidInfo\x12(\n\x0fprofile_picture\x18\x02 \x01(\x0b\x32\x0f.ProfilePicture\x12\x19\n\x11\x62\x61ttle_watcher_id\x18\x06 \x01(\r\x12\x0b\n\x03uid\x18\x07 \x01(\r\x12\x0c\n\x04icon\x18\x0e \x01(\r\x12\r\n\x05score\x18\x04 \x01(\r\x12\x10\n\x08nickname\x18\x03 \x01(\t\x12\x11\n\tonline_id\x18\x08 \x01(\tB\x16\n\x14org.sorapointa.protob\x06proto3')



_GADGETPLAYUIDINFO = DESCRIPTOR.message_types_by_name['GadgetPlayUidInfo']
GadgetPlayUidInfo = _reflection.GeneratedProtocolMessageType('GadgetPlayUidInfo', (_message.Message,), {
  'DESCRIPTOR' : _GADGETPLAYUIDINFO,
  '__module__' : 'genshin.packet.proto.GadgetPlayUidInfo_pb2'
  # @@protoc_insertion_point(class_scope:GadgetPlayUidInfo)
  })
_sym_db.RegisterMessage(GadgetPlayUidInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _GADGETPLAYUIDINFO._serialized_start=92
  _GADGETPLAYUIDINFO._serialized_end=259
# @@protoc_insertion_point(module_scope)
