# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/GalleryBalloonScoreNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4genshin/packet/proto/GalleryBalloonScoreNotify.proto\"\xa7\x01\n\x19GalleryBalloonScoreNotify\x12\x12\n\ngallery_id\x18\t \x01(\r\x12\x42\n\ruid_score_map\x18\x07 \x03(\x0b\x32+.GalleryBalloonScoreNotify.UidScoreMapEntry\x1a\x32\n\x10UidScoreMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_GALLERYBALLOONSCORENOTIFY = DESCRIPTOR.message_types_by_name['GalleryBalloonScoreNotify']
_GALLERYBALLOONSCORENOTIFY_UIDSCOREMAPENTRY = _GALLERYBALLOONSCORENOTIFY.nested_types_by_name['UidScoreMapEntry']
GalleryBalloonScoreNotify = _reflection.GeneratedProtocolMessageType('GalleryBalloonScoreNotify', (_message.Message,), {

  'UidScoreMapEntry' : _reflection.GeneratedProtocolMessageType('UidScoreMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _GALLERYBALLOONSCORENOTIFY_UIDSCOREMAPENTRY,
    '__module__' : 'genshin.packet.proto.GalleryBalloonScoreNotify_pb2'
    # @@protoc_insertion_point(class_scope:GalleryBalloonScoreNotify.UidScoreMapEntry)
    })
  ,
  'DESCRIPTOR' : _GALLERYBALLOONSCORENOTIFY,
  '__module__' : 'genshin.packet.proto.GalleryBalloonScoreNotify_pb2'
  # @@protoc_insertion_point(class_scope:GalleryBalloonScoreNotify)
  })
_sym_db.RegisterMessage(GalleryBalloonScoreNotify)
_sym_db.RegisterMessage(GalleryBalloonScoreNotify.UidScoreMapEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _GALLERYBALLOONSCORENOTIFY_UIDSCOREMAPENTRY._options = None
  _GALLERYBALLOONSCORENOTIFY_UIDSCOREMAPENTRY._serialized_options = b'8\001'
  _GALLERYBALLOONSCORENOTIFY._serialized_start=57
  _GALLERYBALLOONSCORENOTIFY._serialized_end=224
  _GALLERYBALLOONSCORENOTIFY_UIDSCOREMAPENTRY._serialized_start=174
  _GALLERYBALLOONSCORENOTIFY_UIDSCOREMAPENTRY._serialized_end=224
# @@protoc_insertion_point(module_scope)
