from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class GBNIDJGCPLJ(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    GBNIDJGCPLJ_CHANGE_ENERGY_NONE: _ClassVar[GBNIDJGCPLJ]
    GBNIDJGCPLJ_CHANGE_ENERGY_SKILL_START: _ClassVar[GBNIDJGCPLJ]
    GBNIDJGCPLJ_CHANGE_ENERGY_BALL: _ClassVar[GBNIDJGCPLJ]
    GBNIDJGCPLJ_CHANGE_ENERGY_QUEST: _ClassVar[GBNIDJGCPLJ]
    GBNIDJGCPLJ_CHANGE_ENERGY_ABILITY: _ClassVar[GBNIDJGCPLJ]
    GBNIDJGCPLJ_CHANGE_ENERGY_DIE: _ClassVar[GBNIDJGCPLJ]
    GBNIDJGCPLJ_CHANGE_ENERGY_SKILL_DEPOT: _ClassVar[GBNIDJGCPLJ]
GBNIDJGCPLJ_CHANGE_ENERGY_NONE: GBNIDJGCPLJ
GBNIDJGCPLJ_CHANGE_ENERGY_SKILL_START: GBNIDJGCPLJ
GBNIDJGCPLJ_CHANGE_ENERGY_BALL: GBNIDJGCPLJ
GBNIDJGCPLJ_CHANGE_ENERGY_QUEST: GBNIDJGCPLJ
GBNIDJGCPLJ_CHANGE_ENERGY_ABILITY: GBNIDJGCPLJ
GBNIDJGCPLJ_CHANGE_ENERGY_DIE: GBNIDJGCPLJ
GBNIDJGCPLJ_CHANGE_ENERGY_SKILL_DEPOT: GBNIDJGCPLJ
