# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/GetAllH5ActivityInfoReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2genshin/packet/proto/GetAllH5ActivityInfoReq.proto\"\x19\n\x17GetAllH5ActivityInfoReqB\x16\n\x14org.sorapointa.protob\x06proto3')



_GETALLH5ACTIVITYINFOREQ = DESCRIPTOR.message_types_by_name['GetAllH5ActivityInfoReq']
GetAllH5ActivityInfoReq = _reflection.GeneratedProtocolMessageType('GetAllH5ActivityInfoReq', (_message.Message,), {
  'DESCRIPTOR' : _GETALLH5ACTIVITYINFOREQ,
  '__module__' : 'genshin.packet.proto.GetAllH5ActivityInfoReq_pb2'
  # @@protoc_insertion_point(class_scope:GetAllH5ActivityInfoReq)
  })
_sym_db.RegisterMessage(GetAllH5ActivityInfoReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _GETALLH5ACTIVITYINFOREQ._serialized_start=54
  _GETALLH5ACTIVITYINFOREQ._serialized_end=79
# @@protoc_insertion_point(module_scope)
