# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/GetDungeonEntryExploreConditionRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import DungeonEntryCond_pb2 as genshin_dot_packet_dot_proto_dot_DungeonEntryCond__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=genshin/packet/proto/GetDungeonEntryExploreConditionRsp.proto\x1a+genshin/packet/proto/DungeonEntryCond.proto\"d\n\"GetDungeonEntryExploreConditionRsp\x12-\n\x12\x64ungeon_entry_cond\x18\x05 \x01(\x0b\x32\x11.DungeonEntryCond\x12\x0f\n\x07retcode\x18\x03 \x01(\x05\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_GETDUNGEONENTRYEXPLORECONDITIONRSP = DESCRIPTOR.message_types_by_name['GetDungeonEntryExploreConditionRsp']
GetDungeonEntryExploreConditionRsp = _reflection.GeneratedProtocolMessageType('GetDungeonEntryExploreConditionRsp', (_message.Message,), {
  'DESCRIPTOR' : _GETDUNGEONENTRYEXPLORECONDITIONRSP,
  '__module__' : 'genshin.packet.proto.GetDungeonEntryExploreConditionRsp_pb2'
  # @@protoc_insertion_point(class_scope:GetDungeonEntryExploreConditionRsp)
  })
_sym_db.RegisterMessage(GetDungeonEntryExploreConditionRsp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _GETDUNGEONENTRYEXPLORECONDITIONRSP._serialized_start=110
  _GETDUNGEONENTRYEXPLORECONDITIONRSP._serialized_end=210
# @@protoc_insertion_point(module_scope)
