# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/GetHomeLevelUpRewardReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2genshin/packet/proto/GetHomeLevelUpRewardReq.proto\"(\n\x17GetHomeLevelUpRewardReq\x12\r\n\x05level\x18\x0f \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_GETHOMELEVELUPREWARDREQ = DESCRIPTOR.message_types_by_name['GetHomeLevelUpRewardReq']
GetHomeLevelUpRewardReq = _reflection.GeneratedProtocolMessageType('GetHomeLevelUpRewardReq', (_message.Message,), {
  'DESCRIPTOR' : _GETHOMELEVELUPREWARDREQ,
  '__module__' : 'genshin.packet.proto.GetHomeLevelUpRewardReq_pb2'
  # @@protoc_insertion_point(class_scope:GetHomeLevelUpRewardReq)
  })
_sym_db.RegisterMessage(GetHomeLevelUpRewardReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _GETHOMELEVELUPREWARDREQ._serialized_start=54
  _GETHOMELEVELUPREWARDREQ._serialized_end=94
# @@protoc_insertion_point(module_scope)
