# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/GetInvestigationMonsterRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import InvestigationMonster_pb2 as genshin_dot_packet_dot_proto_dot_InvestigationMonster__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5genshin/packet/proto/GetInvestigationMonsterRsp.proto\x1a/genshin/packet/proto/InvestigationMonster.proto\"w\n\x1aGetInvestigationMonsterRsp\x12+\n\x0cmonster_list\x18\n \x03(\x0b\x32\x15.InvestigationMonster\x12\x0f\n\x07retcode\x18\x01 \x01(\x05\x12\x1b\n\x13Unk2700_DEMFDHNFBBJ\x18\x02 \x01(\x08\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_GETINVESTIGATIONMONSTERRSP = DESCRIPTOR.message_types_by_name['GetInvestigationMonsterRsp']
GetInvestigationMonsterRsp = _reflection.GeneratedProtocolMessageType('GetInvestigationMonsterRsp', (_message.Message,), {
  'DESCRIPTOR' : _GETINVESTIGATIONMONSTERRSP,
  '__module__' : 'genshin.packet.proto.GetInvestigationMonsterRsp_pb2'
  # @@protoc_insertion_point(class_scope:GetInvestigationMonsterRsp)
  })
_sym_db.RegisterMessage(GetInvestigationMonsterRsp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _GETINVESTIGATIONMONSTERRSP._serialized_start=106
  _GETINVESTIGATIONMONSTERRSP._serialized_end=225
# @@protoc_insertion_point(module_scope)
