# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/GetReunionPrivilegeInfoRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import ReunionPrivilegeInfo_pb2 as genshin_dot_packet_dot_proto_dot_ReunionPrivilegeInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5genshin/packet/proto/GetReunionPrivilegeInfoRsp.proto\x1a/genshin/packet/proto/ReunionPrivilegeInfo.proto\"\\\n\x1aGetReunionPrivilegeInfoRsp\x12\x0f\n\x07retcode\x18\x03 \x01(\x05\x12-\n\x0eprivilege_info\x18\x01 \x01(\x0b\x32\x15.ReunionPrivilegeInfoB\x16\n\x14org.sorapointa.protob\x06proto3')



_GETREUNIONPRIVILEGEINFORSP = DESCRIPTOR.message_types_by_name['GetReunionPrivilegeInfoRsp']
GetReunionPrivilegeInfoRsp = _reflection.GeneratedProtocolMessageType('GetReunionPrivilegeInfoRsp', (_message.Message,), {
  'DESCRIPTOR' : _GETREUNIONPRIVILEGEINFORSP,
  '__module__' : 'genshin.packet.proto.GetReunionPrivilegeInfoRsp_pb2'
  # @@protoc_insertion_point(class_scope:GetReunionPrivilegeInfoRsp)
  })
_sym_db.RegisterMessage(GetReunionPrivilegeInfoRsp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _GETREUNIONPRIVILEGEINFORSP._serialized_start=106
  _GETREUNIONPRIVILEGEINFORSP._serialized_end=198
# @@protoc_insertion_point(module_scope)
