# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/GetSceneAreaReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*genshin/packet/proto/GetSceneAreaReq.proto\"7\n\x0fGetSceneAreaReq\x12\x10\n\x08scene_id\x18\x04 \x01(\r\x12\x12\n\nbelong_uid\x18\x07 \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')



_GETSCENEAREAREQ = DESCRIPTOR.message_types_by_name['GetSceneAreaReq']
GetSceneAreaReq = _reflection.GeneratedProtocolMessageType('GetSceneAreaReq', (_message.Message,), {
  'DESCRIPTOR' : _GETSCENEAREAREQ,
  '__module__' : 'genshin.packet.proto.GetSceneAreaReq_pb2'
  # @@protoc_insertion_point(class_scope:GetSceneAreaReq)
  })
_sym_db.RegisterMessage(GetSceneAreaReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _GETSCENEAREAREQ._serialized_start=46
  _GETSCENEAREAREQ._serialized_end=101
# @@protoc_insertion_point(module_scope)
