# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/GiveUpRoguelikeDungeonCardReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8genshin/packet/proto/GiveUpRoguelikeDungeonCardReq.proto\"\x1f\n\x1dGiveUpRoguelikeDungeonCardReqB\x16\n\x14org.sorapointa.protob\x06proto3')



_GIVEUPROGUELIKEDUNGEONCARDREQ = DESCRIPTOR.message_types_by_name['GiveUpRoguelikeDungeonCardReq']
GiveUpRoguelikeDungeonCardReq = _reflection.GeneratedProtocolMessageType('GiveUpRoguelikeDungeonCardReq', (_message.Message,), {
  'DESCRIPTOR' : _GIVEUPROGUELIKEDUNGEONCARDREQ,
  '__module__' : 'genshin.packet.proto.GiveUpRoguelikeDungeonCardReq_pb2'
  # @@protoc_insertion_point(class_scope:GiveUpRoguelikeDungeonCardReq)
  })
_sym_db.RegisterMessage(GiveUpRoguelikeDungeonCardReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _GIVEUPROGUELIKEDUNGEONCARDREQ._serialized_start=60
  _GIVEUPROGUELIKEDUNGEONCARDREQ._serialized_end=91
# @@protoc_insertion_point(module_scope)
