# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/GJBCMIGGHEM.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/GJBCMIGGHEM.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import AvatarInfo_pb2 as genshin_dot_packet_dot_proto_dot_AvatarInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/GJBCMIGGHEM.proto\x1a%genshin/packet/proto/AvatarInfo.proto\"Y\n\x0bGJBCMIGGHEM\x12 \n\x0b\x45\x46\x43\x44\x45LGMMKG\x18\x0e \x03(\x0b\x32\x0b.AvatarInfo\x12\x13\n\x0bPMFOIANCCED\x18\x02 \x01(\r\x12\x13\n\x0b\x45JNINFFFKJP\x18\r \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.GJBCMIGGHEM_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GJBCMIGGHEM']._serialized_start=81
  _globals['_GJBCMIGGHEM']._serialized_end=170
# @@protoc_insertion_point(module_scope)
