# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/GMShowNavMeshReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import Vector_pb2 as genshin_dot_packet_dot_proto_dot_Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+genshin/packet/proto/GMShowNavMeshReq.proto\x1a!genshin/packet/proto/Vector.proto\"D\n\x10GMShowNavMeshReq\x12\x17\n\x06\x63\x65nter\x18\x01 \x01(\x0b\x32\x07.Vector\x12\x17\n\x06\x65xtent\x18\x05 \x01(\x0b\x32\x07.VectorB\x16\n\x14org.sorapointa.protob\x06proto3')



_GMSHOWNAVMESHREQ = DESCRIPTOR.message_types_by_name['GMShowNavMeshReq']
GMShowNavMeshReq = _reflection.GeneratedProtocolMessageType('GMShowNavMeshReq', (_message.Message,), {
  'DESCRIPTOR' : _GMSHOWNAVMESHREQ,
  '__module__' : 'genshin.packet.proto.GMShowNavMeshReq_pb2'
  # @@protoc_insertion_point(class_scope:GMShowNavMeshReq)
  })
_sym_db.RegisterMessage(GMShowNavMeshReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _GMSHOWNAVMESHREQ._serialized_start=82
  _GMSHOWNAVMESHREQ._serialized_end=150
# @@protoc_insertion_point(module_scope)
