# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/GroupLinkChangeNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import GroupLinkBundle_pb2 as genshin_dot_packet_dot_proto_dot_GroupLinkBundle__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0genshin/packet/proto/GroupLinkChangeNotify.proto\x1a*genshin/packet/proto/GroupLinkBundle.proto\"9\n\x15GroupLinkChangeNotify\x12 \n\x06\x62undle\x18\x08 \x01(\x0b\x32\x10.GroupLinkBundleB\x16\n\x14org.sorapointa.protob\x06proto3')



_GROUPLINKCHANGENOTIFY = DESCRIPTOR.message_types_by_name['GroupLinkChangeNotify']
GroupLinkChangeNotify = _reflection.GeneratedProtocolMessageType('GroupLinkChangeNotify', (_message.Message,), {
  'DESCRIPTOR' : _GROUPLINKCHANGENOTIFY,
  '__module__' : 'genshin.packet.proto.GroupLinkChangeNotify_pb2'
  # @@protoc_insertion_point(class_scope:GroupLinkChangeNotify)
  })
_sym_db.RegisterMessage(GroupLinkChangeNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _GROUPLINKCHANGENOTIFY._serialized_start=96
  _GROUPLINKCHANGENOTIFY._serialized_end=153
# @@protoc_insertion_point(module_scope)
