# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/GuestBeginEnterSceneNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5genshin/packet/proto/GuestBeginEnterSceneNotify.proto\";\n\x1aGuestBeginEnterSceneNotify\x12\x10\n\x08scene_id\x18\x08 \x01(\r\x12\x0b\n\x03uid\x18\x0f \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_GUESTBEGINENTERSCENENOTIFY = DESCRIPTOR.message_types_by_name['GuestBeginEnterSceneNotify']
GuestBeginEnterSceneNotify = _reflection.GeneratedProtocolMessageType('GuestBeginEnterSceneNotify', (_message.Message,), {
  'DESCRIPTOR' : _GUESTBEGINENTERSCENENOTIFY,
  '__module__' : 'genshin.packet.proto.GuestBeginEnterSceneNotify_pb2'
  # @@protoc_insertion_point(class_scope:GuestBeginEnterSceneNotify)
  })
_sym_db.RegisterMessage(GuestBeginEnterSceneNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _GUESTBEGINENTERSCENENOTIFY._serialized_start=57
  _GUESTBEGINENTERSCENENOTIFY._serialized_end=116
# @@protoc_insertion_point(module_scope)
