from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class HCKOGHGENIC(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    HCKOGHGENIC_DRAFT_FAIL_UNKNOWN: _ClassVar[HCKOGHGENIC]
    HCKOGHGENIC_DRAFT_ACTIVITY_NOT_OPEN: _ClassVar[HCKOGHGENIC]
    HCKOGHGENIC_DRAFT_ACTIVITY_PLAY_NOT_OPEN: _ClassVar[HCKOGHGENIC]
    HCKOGHGENIC_DRAFT_SCENE_NOT_MEET: _ClassVar[HCKOGHGENIC]
    HCKOGHGENIC_DRAFT_WORLD_NOT_MEET: _ClassVar[HCKOGHGENIC]
    HCKOGHGENIC_DRAFT_PLAY_LIMIT_NOT_MEET: _ClassVar[HCKOGHGENIC]
    HCKOGHGENIC_DRAFT_ACTIVITY_CONFIG_NOT_FOUND: _ClassVar[HCKOGHGENIC]
HCKOGHGENIC_DRAFT_FAIL_UNKNOWN: HCKOGHGENIC
HCKOGHGENIC_DRAFT_ACTIVITY_NOT_OPEN: HCKOGHGENIC
HCKOGHGENIC_DRAFT_ACTIVITY_PLAY_NOT_OPEN: HCKOGHGENIC
HCKOGHGENIC_DRAFT_SCENE_NOT_MEET: HCKOGHGENIC
HCKOGHGENIC_DRAFT_WORLD_NOT_MEET: HCKOGHGENIC
HCKOGHGENIC_DRAFT_PLAY_LIMIT_NOT_MEET: HCKOGHGENIC
HCKOGHGENIC_DRAFT_ACTIVITY_CONFIG_NOT_FOUND: HCKOGHGENIC
