from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class HDMDABCDAHK(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    HDMDABCDAHK_MATCH_NONE: _ClassVar[HDMDABCDAHK]
    HDMDABCDAHK_MATCH_FINISH: _ClassVar[HDMDABCDAHK]
    HDMDABCDAHK_MATCH_PLAYER_CANCEL: _ClassVar[HDMDABCDAHK]
    HDMDABCDAHK_MATCH_TIMEOUT: _ClassVar[HDMDABCDAHK]
    HDMDABCDAHK_MATCH_PLAYER_CONFIRM: _ClassVar[HDMDABCDAHK]
    HDMDABCDAHK_MATCH_FAILED: _ClassVar[HDMDABCDAHK]
    HDMDABCDAHK_MATCH_SYSTEM_ERROR: _ClassVar[HDMDABCDAHK]
    HDMDABCDAHK_MATCH_INTERRUPTED: _ClassVar[HDMDABCDAHK]
    HDMDABCDAHK_MATCH_MP_UNAVAILABLE: _ClassVar[HDMDABCDAHK]
    HDMDABCDAHK_MATCH_CONFIRM_TIMEOUT: _ClassVar[HDMDABCDAHK]
HDMDABCDAHK_MATCH_NONE: HDMDABCDAHK
HDMDABCDAHK_MATCH_FINISH: HDMDABCDAHK
HDMDABCDAHK_MATCH_PLAYER_CANCEL: HDMDABCDAHK
HDMDABCDAHK_MATCH_TIMEOUT: HDMDABCDAHK
HDMDABCDAHK_MATCH_PLAYER_CONFIRM: HDMDABCDAHK
HDMDABCDAHK_MATCH_FAILED: HDMDABCDAHK
HDMDABCDAHK_MATCH_SYSTEM_ERROR: HDMDABCDAHK
HDMDABCDAHK_MATCH_INTERRUPTED: HDMDABCDAHK
HDMDABCDAHK_MATCH_MP_UNAVAILABLE: HDMDABCDAHK
HDMDABCDAHK_MATCH_CONFIRM_TIMEOUT: HDMDABCDAHK
