# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/HHLNOFACOCA.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/HHLNOFACOCA.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import HFHJKHOPLMN_pb2 as genshin_dot_packet_dot_proto_dot_HFHJKHOPLMN__pb2
from genshin.packet.proto import LLCCBEANIFC_pb2 as genshin_dot_packet_dot_proto_dot_LLCCBEANIFC__pb2
from genshin.packet.proto import LFJLGOJMKEH_pb2 as genshin_dot_packet_dot_proto_dot_LFJLGOJMKEH__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/HHLNOFACOCA.proto\x1a&genshin/packet/proto/HFHJKHOPLMN.proto\x1a&genshin/packet/proto/LLCCBEANIFC.proto\x1a&genshin/packet/proto/LFJLGOJMKEH.proto\"\xa0\x01\n\x0bHHLNOFACOCA\x12!\n\x0bMEIKGBOLDGH\x18\x05 \x03(\x0b\x32\x0c.HFHJKHOPLMN\x12!\n\x0b\x46\x41GJDJIGLON\x18\t \x03(\x0b\x32\x0c.LLCCBEANIFC\x12\x13\n\x0b\x41\x42IMANELKOC\x18\x04 \x01(\r\x12!\n\x0bIMIOGMDOKCB\x18\x0b \x01(\x0e\x32\x0c.LFJLGOJMKEH\x12\x13\n\x0bOMENIAMEDCE\x18\x01 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.HHLNOFACOCA_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HHLNOFACOCA']._serialized_start=163
  _globals['_HHLNOFACOCA']._serialized_end=323
# @@protoc_insertion_point(module_scope)
