# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/HideAndSeekPlayerSetAvatarNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;genshin/packet/proto/HideAndSeekPlayerSetAvatarNotify.proto\"V\n HideAndSeekPlayerSetAvatarNotify\x12\x11\n\tavatar_id\x18\x02 \x01(\r\x12\x12\n\ncostume_id\x18\r \x01(\r\x12\x0b\n\x03uid\x18\x05 \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_HIDEANDSEEKPLAYERSETAVATARNOTIFY = DESCRIPTOR.message_types_by_name['HideAndSeekPlayerSetAvatarNotify']
HideAndSeekPlayerSetAvatarNotify = _reflection.GeneratedProtocolMessageType('HideAndSeekPlayerSetAvatarNotify', (_message.Message,), {
  'DESCRIPTOR' : _HIDEANDSEEKPLAYERSETAVATARNOTIFY,
  '__module__' : 'genshin.packet.proto.HideAndSeekPlayerSetAvatarNotify_pb2'
  # @@protoc_insertion_point(class_scope:HideAndSeekPlayerSetAvatarNotify)
  })
_sym_db.RegisterMessage(HideAndSeekPlayerSetAvatarNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _HIDEANDSEEKPLAYERSETAVATARNOTIFY._serialized_start=63
  _HIDEANDSEEKPLAYERSETAVATARNOTIFY._serialized_end=149
# @@protoc_insertion_point(module_scope)
