from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class HLPLMKKOGNK(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    HLPLMKKOGNK_UGC_REC_PARAM_TYPE_NONE: _ClassVar[HLPLMKKOGNK]
    HLPLMKKOGNK_UGC_REC_PARAM_TYPE_MUSIC_NOTE_LARGE: _ClassVar[HLPLMKKOGNK]
    HLPLMKKOGNK_UGC_REC_PARAM_TYPE_MUSIC_NOTE_LESS_EQUAL: _ClassVar[HLPLMKKOGNK]
    HLPLMKKOGNK_UGC_REC_PARAM_TYPE_MUSIC_NOTE_TAG: _ClassVar[HLPLMKKOGNK]
    HLPLMKKOGNK_UGC_REC_PARAM_TYPE_MUSIC_NAME: _ClassVar[HLPLMKKOGNK]
HLPLMKKOGNK_UGC_REC_PARAM_TYPE_NONE: HLPLMKKOGNK
HLPLMKKOGNK_UGC_REC_PARAM_TYPE_MUSIC_NOTE_LARGE: HLPLMKKOGNK
HLPLMKKOGNK_UGC_REC_PARAM_TYPE_MUSIC_NOTE_LESS_EQUAL: HLPLMKKOGNK
HLPLMKKOGNK_UGC_REC_PARAM_TYPE_MUSIC_NOTE_TAG: HLPLMKKOGNK
HLPLMKKOGNK_UGC_REC_PARAM_TYPE_MUSIC_NAME: HLPLMKKOGNK
