from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class HMBFCHKMEGD(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    HMBFCHKMEGD_NONE: _ClassVar[HMBFCHKMEGD]
    HMBFCHKMEGD_STARRED_DUNGEON: _ClassVar[HMBFCHKMEGD]
    HMBFCHKMEGD_STARRED_ROOM: _ClassVar[HMBFCHKMEGD]
    HMBFCHKMEGD_OWNER: _ClassVar[HMBFCHKMEGD]
    HMBFCHKMEGD_HISTORY: _ClassVar[HMBFCHKMEGD]
    HMBFCHKMEGD_SEARCH: _ClassVar[HMBFCHKMEGD]
    HMBFCHKMEGD_OFFICIAL: _ClassVar[HMBFCHKMEGD]
    HMBFCHKMEGD_TEMPLATE: _ClassVar[HMBFCHKMEGD]
HMBFCHKMEGD_NONE: HMBFCHKMEGD
HMBFCHKMEGD_STARRED_DUNGEON: HMBFCHKMEGD
HMBFCHKMEGD_STARRED_ROOM: HMBFCHKMEGD
HMBFCHKMEGD_OWNER: HMBFCHKMEGD
HMBFCHKMEGD_HISTORY: HMBFCHKMEGD
HMBFCHKMEGD_SEARCH: HMBFCHKMEGD
HMBFCHKMEGD_OFFICIAL: HMBFCHKMEGD
HMBFCHKMEGD_TEMPLATE: HMBFCHKMEGD
