# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/HOLHJCEKDKH.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/HOLHJCEKDKH.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import OADJBKDJNPL_pb2 as genshin_dot_packet_dot_proto_dot_OADJBKDJNPL__pb2
from genshin.packet.proto import MJPKECMOIGA_pb2 as genshin_dot_packet_dot_proto_dot_MJPKECMOIGA__pb2
from genshin.packet.proto import FGGKIFNGDON_pb2 as genshin_dot_packet_dot_proto_dot_FGGKIFNGDON__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/HOLHJCEKDKH.proto\x1a&genshin/packet/proto/OADJBKDJNPL.proto\x1a&genshin/packet/proto/MJPKECMOIGA.proto\x1a&genshin/packet/proto/FGGKIFNGDON.proto\"\xd2\x04\n\x0bHOLHJCEKDKH\x12!\n\x0b\x45OMNMODEDFD\x18\t \x01(\x0b\x32\x0c.OADJBKDJNPL\x12\"\n\x0b\x43\x45MLGAAHAOM\x18\xb8\x08 \x01(\x0b\x32\x0c.OADJBKDJNPL\x12\x32\n\x0bJGCKBJJGIAF\x18\x08 \x03(\x0b\x32\x1d.HOLHJCEKDKH.JGCKBJJGIAFEntry\x12!\n\x0b\x46HKNGCBGDJL\x18\x0f \x03(\x0b\x32\x0c.MJPKECMOIGA\x12!\n\x0b\x43JIHNOCINNM\x18\r \x01(\x0b\x32\x0c.FGGKIFNGDON\x12\x32\n\x0bLOKPPLOEOFM\x18\x02 \x03(\x0b\x32\x1d.HOLHJCEKDKH.LOKPPLOEOFMEntry\x12\x13\n\x0bGMGICOPOPFK\x18\x04 \x01(\r\x12\x13\n\x0b\x45JNINFFFKJP\x18\x03 \x01(\x05\x12\x13\n\x0b\x41LOOBPBNDDH\x18\x01 \x01(\r\x12\x13\n\x0bOLLLEIKDNAN\x18\x0b \x01(\r\x12\x13\n\x0b\x42LMGFJBAFKB\x18\n \x01(\r\x12\x13\n\x0bMJMLCOHBLPL\x18\x0e \x01(\r\x12\x13\n\x0b\x46\x44\x44\x45HDHBABM\x18\x0c \x01(\x08\x12\x13\n\x0bKCJGPLKNPCL\x18\x05 \x01(\x08\x12\x14\n\x0bMGCBKEMOADN\x18\xf5\x01 \x01(\r\x12\x13\n\x0bJLFGOPMDPDK\x18\x07 \x01(\r\x12\x13\n\x0bPEFKMBHJCDL\x18\x06 \x01(\r\x1a\x32\n\x10JGCKBJJGIAFEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x1a\x32\n\x10LOKPPLOEOFMEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.HOLHJCEKDKH_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HOLHJCEKDKH_JGCKBJJGIAFENTRY']._loaded_options = None
  _globals['_HOLHJCEKDKH_JGCKBJJGIAFENTRY']._serialized_options = b'8\001'
  _globals['_HOLHJCEKDKH_LOKPPLOEOFMENTRY']._loaded_options = None
  _globals['_HOLHJCEKDKH_LOKPPLOEOFMENTRY']._serialized_options = b'8\001'
  _globals['_HOLHJCEKDKH']._serialized_start=163
  _globals['_HOLHJCEKDKH']._serialized_end=757
  _globals['_HOLHJCEKDKH_JGCKBJJGIAFENTRY']._serialized_start=655
  _globals['_HOLHJCEKDKH_JGCKBJJGIAFENTRY']._serialized_end=705
  _globals['_HOLHJCEKDKH_LOKPPLOEOFMENTRY']._serialized_start=707
  _globals['_HOLHJCEKDKH_LOKPPLOEOFMENTRY']._serialized_end=757
# @@protoc_insertion_point(module_scope)
