# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/HomeGetOnlineStatusRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import OnlinePlayerInfo_pb2 as genshin_dot_packet_dot_proto_dot_OnlinePlayerInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1genshin/packet/proto/HomeGetOnlineStatusRsp.proto\x1a+genshin/packet/proto/OnlinePlayerInfo.proto\"V\n\x16HomeGetOnlineStatusRsp\x12+\n\x10player_info_list\x18\r \x03(\x0b\x32\x11.OnlinePlayerInfo\x12\x0f\n\x07retcode\x18\x07 \x01(\x05\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_HOMEGETONLINESTATUSRSP = DESCRIPTOR.message_types_by_name['HomeGetOnlineStatusRsp']
HomeGetOnlineStatusRsp = _reflection.GeneratedProtocolMessageType('HomeGetOnlineStatusRsp', (_message.Message,), {
  'DESCRIPTOR' : _HOMEGETONLINESTATUSRSP,
  '__module__' : 'genshin.packet.proto.HomeGetOnlineStatusRsp_pb2'
  # @@protoc_insertion_point(class_scope:HomeGetOnlineStatusRsp)
  })
_sym_db.RegisterMessage(HomeGetOnlineStatusRsp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _HOMEGETONLINESTATUSRSP._serialized_start=98
  _HOMEGETONLINESTATUSRSP._serialized_end=184
# @@protoc_insertion_point(module_scope)
