# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/HomeAvatarAllFinishRewardNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:genshin/packet/proto/HomeAvatarAllFinishRewardNotify.proto\"8\n\x1fHomeAvatarAllFinishRewardNotify\x12\x15\n\revent_id_list\x18\x07 \x03(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_HOMEAVATARALLFINISHREWARDNOTIFY = DESCRIPTOR.message_types_by_name['HomeAvatarAllFinishRewardNotify']
HomeAvatarAllFinishRewardNotify = _reflection.GeneratedProtocolMessageType('HomeAvatarAllFinishRewardNotify', (_message.Message,), {
  'DESCRIPTOR' : _HOMEAVATARALLFINISHREWARDNOTIFY,
  '__module__' : 'genshin.packet.proto.HomeAvatarAllFinishRewardNotify_pb2'
  # @@protoc_insertion_point(class_scope:HomeAvatarAllFinishRewardNotify)
  })
_sym_db.RegisterMessage(HomeAvatarAllFinishRewardNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _HOMEAVATARALLFINISHREWARDNOTIFY._serialized_start=62
  _HOMEAVATARALLFINISHREWARDNOTIFY._serialized_end=118
# @@protoc_insertion_point(module_scope)
