# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/HomeMarkPointSuiteData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1genshin/packet/proto/HomeMarkPointSuiteData.proto\"*\n\x16HomeMarkPointSuiteData\x12\x10\n\x08suite_id\x18\x01 \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')



_HOMEMARKPOINTSUITEDATA = DESCRIPTOR.message_types_by_name['HomeMarkPointSuiteData']
HomeMarkPointSuiteData = _reflection.GeneratedProtocolMessageType('HomeMarkPointSuiteData', (_message.Message,), {
  'DESCRIPTOR' : _HOMEMARKPOINTSUITEDATA,
  '__module__' : 'genshin.packet.proto.HomeMarkPointSuiteData_pb2'
  # @@protoc_insertion_point(class_scope:HomeMarkPointSuiteData)
  })
_sym_db.RegisterMessage(HomeMarkPointSuiteData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _HOMEMARKPOINTSUITEDATA._serialized_start=53
  _HOMEMARKPOINTSUITEDATA._serialized_end=95
# @@protoc_insertion_point(module_scope)
