# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/HomeEditCustomFurnitureReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import HomeCustomFurnitureInfo_pb2 as genshin_dot_packet_dot_proto_dot_HomeCustomFurnitureInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5genshin/packet/proto/HomeEditCustomFurnitureReq.proto\x1a\x32genshin/packet/proto/HomeCustomFurnitureInfo.proto\"U\n\x1aHomeEditCustomFurnitureReq\x12\x37\n\x15\x63ustom_furniture_info\x18\x0f \x01(\x0b\x32\x18.HomeCustomFurnitureInfoB\x16\n\x14org.sorapointa.protob\x06proto3')



_HOMEEDITCUSTOMFURNITUREREQ = DESCRIPTOR.message_types_by_name['HomeEditCustomFurnitureReq']
HomeEditCustomFurnitureReq = _reflection.GeneratedProtocolMessageType('HomeEditCustomFurnitureReq', (_message.Message,), {
  'DESCRIPTOR' : _HOMEEDITCUSTOMFURNITUREREQ,
  '__module__' : 'genshin.packet.proto.HomeEditCustomFurnitureReq_pb2'
  # @@protoc_insertion_point(class_scope:HomeEditCustomFurnitureReq)
  })
_sym_db.RegisterMessage(HomeEditCustomFurnitureReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _HOMEEDITCUSTOMFURNITUREREQ._serialized_start=109
  _HOMEEDITCUSTOMFURNITUREREQ._serialized_end=194
# @@protoc_insertion_point(module_scope)
