# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/HomeBlockArrangementInfo.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/HomeBlockArrangementInfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import HomeFurnitureData_pb2 as genshin_dot_packet_dot_proto_dot_HomeFurnitureData__pb2
from genshin.packet.proto import HomeBlockDotPattern_pb2 as genshin_dot_packet_dot_proto_dot_HomeBlockDotPattern__pb2
from genshin.packet.proto import HomeFurnitureGroupData_pb2 as genshin_dot_packet_dot_proto_dot_HomeFurnitureGroupData__pb2
from genshin.packet.proto import HomeNpcData_pb2 as genshin_dot_packet_dot_proto_dot_HomeNpcData__pb2
from genshin.packet.proto import HomeAnimalData_pb2 as genshin_dot_packet_dot_proto_dot_HomeAnimalData__pb2
from genshin.packet.proto import HomeFurnitureCustomSuiteData_pb2 as genshin_dot_packet_dot_proto_dot_HomeFurnitureCustomSuiteData__pb2
from genshin.packet.proto import HomeFurnitureSuiteData_pb2 as genshin_dot_packet_dot_proto_dot_HomeFurnitureSuiteData__pb2
from genshin.packet.proto import WeekendDjinnInfo_pb2 as genshin_dot_packet_dot_proto_dot_WeekendDjinnInfo__pb2
from genshin.packet.proto import HomeBlockFieldData_pb2 as genshin_dot_packet_dot_proto_dot_HomeBlockFieldData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3genshin/packet/proto/HomeBlockArrangementInfo.proto\x1a,genshin/packet/proto/HomeFurnitureData.proto\x1a.genshin/packet/proto/HomeBlockDotPattern.proto\x1a\x31genshin/packet/proto/HomeFurnitureGroupData.proto\x1a&genshin/packet/proto/HomeNpcData.proto\x1a)genshin/packet/proto/HomeAnimalData.proto\x1a\x37genshin/packet/proto/HomeFurnitureCustomSuiteData.proto\x1a\x31genshin/packet/proto/HomeFurnitureSuiteData.proto\x1a+genshin/packet/proto/WeekendDjinnInfo.proto\x1a-genshin/packet/proto/HomeBlockFieldData.proto\"\xd4\x04\n\x18HomeBlockArrangementInfo\x12\x15\n\rcomfort_value\x18\x01 \x01(\r\x12\x30\n\x14\x64\x65ploy_furniure_list\x18\x02 \x03(\x0b\x32\x12.HomeFurnitureData\x12.\n\x10\x64ot_pattern_list\x18\x03 \x03(\x0b\x32\x14.HomeBlockDotPattern\x12\x35\n\x19persistent_furniture_list\x18\x04 \x03(\x0b\x32\x12.HomeFurnitureData\x12\x35\n\x14\x66urniture_group_list\x18\x06 \x03(\x0b\x32\x17.HomeFurnitureGroupData\x12%\n\x0f\x64\x65ploy_npc_list\x18\x08 \x03(\x0b\x32\x0c.HomeNpcData\x12+\n\x12\x64\x65ploy_animal_list\x18\t \x03(\x0b\x32\x0f.HomeAnimalData\x12\x42\n\x1b\x66urniture_custom_suite_list\x18\n \x03(\x0b\x32\x1d.HomeFurnitureCustomSuiteData\x12\x35\n\x14\x66urniture_suite_list\x18\x0b \x03(\x0b\x32\x17.HomeFurnitureSuiteData\x12\x10\n\x08\x62lock_id\x18\x0c \x01(\r\x12\x13\n\x0bis_unlocked\x18\r \x01(\x08\x12\x32\n\x17weekend_djinn_info_list\x18\x0e \x03(\x0b\x32\x11.WeekendDjinnInfo\x12\'\n\nfield_list\x18\x0f \x03(\x0b\x32\x13.HomeBlockFieldDataB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.HomeBlockArrangementInfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_HOMEBLOCKARRANGEMENTINFO']._serialized_start=484
  _globals['_HOMEBLOCKARRANGEMENTINFO']._serialized_end=1080
# @@protoc_insertion_point(module_scope)
