# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/HomePlantInfoNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import HomePlantFieldData_pb2 as genshin_dot_packet_dot_proto_dot_HomePlantFieldData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/HomePlantInfoNotify.proto\x1a-genshin/packet/proto/HomePlantFieldData.proto\">\n\x13HomePlantInfoNotify\x12\'\n\nfield_list\x18\x04 \x03(\x0b\x32\x13.HomePlantFieldDataB\x16\n\x14org.sorapointa.protob\x06proto3')



_HOMEPLANTINFONOTIFY = DESCRIPTOR.message_types_by_name['HomePlantInfoNotify']
HomePlantInfoNotify = _reflection.GeneratedProtocolMessageType('HomePlantInfoNotify', (_message.Message,), {
  'DESCRIPTOR' : _HOMEPLANTINFONOTIFY,
  '__module__' : 'genshin.packet.proto.HomePlantInfoNotify_pb2'
  # @@protoc_insertion_point(class_scope:HomePlantInfoNotify)
  })
_sym_db.RegisterMessage(HomePlantInfoNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _HOMEPLANTINFONOTIFY._serialized_start=97
  _HOMEPLANTINFONOTIFY._serialized_end=159
# @@protoc_insertion_point(module_scope)
