# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/HomeUpdateFishFarmingInfoRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7genshin/packet/proto/HomeUpdateFishFarmingInfoRsp.proto\"/\n\x1cHomeUpdateFishFarmingInfoRsp\x12\x0f\n\x07retcode\x18\x04 \x01(\x05\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_HOMEUPDATEFISHFARMINGINFORSP = DESCRIPTOR.message_types_by_name['HomeUpdateFishFarmingInfoRsp']
HomeUpdateFishFarmingInfoRsp = _reflection.GeneratedProtocolMessageType('HomeUpdateFishFarmingInfoRsp', (_message.Message,), {
  'DESCRIPTOR' : _HOMEUPDATEFISHFARMINGINFORSP,
  '__module__' : 'genshin.packet.proto.HomeUpdateFishFarmingInfoRsp_pb2'
  # @@protoc_insertion_point(class_scope:HomeUpdateFishFarmingInfoRsp)
  })
_sym_db.RegisterMessage(HomeUpdateFishFarmingInfoRsp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _HOMEUPDATEFISHFARMINGINFORSP._serialized_start=59
  _HOMEUPDATEFISHFARMINGINFORSP._serialized_end=106
# @@protoc_insertion_point(module_scope)
