# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/HomeBlockArrangementInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import HomeAnimalData_pb2 as genshin_dot_packet_dot_proto_dot_HomeAnimalData__pb2
from genshin.packet.proto import HomeBlockDotPattern_pb2 as genshin_dot_packet_dot_proto_dot_HomeBlockDotPattern__pb2
from genshin.packet.proto import HomeBlockFieldData_pb2 as genshin_dot_packet_dot_proto_dot_HomeBlockFieldData__pb2
from genshin.packet.proto import HomeFurnitureData_pb2 as genshin_dot_packet_dot_proto_dot_HomeFurnitureData__pb2
from genshin.packet.proto import HomeFurnitureSuiteData_pb2 as genshin_dot_packet_dot_proto_dot_HomeFurnitureSuiteData__pb2
from genshin.packet.proto import HomeNpcData_pb2 as genshin_dot_packet_dot_proto_dot_HomeNpcData__pb2
from genshin.packet.proto import Unk2700_BIEMCDLIFOD_pb2 as genshin_dot_packet_dot_proto_dot_Unk2700__BIEMCDLIFOD__pb2
from genshin.packet.proto import Unk2700_GOHMLAFNBGF_pb2 as genshin_dot_packet_dot_proto_dot_Unk2700__GOHMLAFNBGF__pb2
from genshin.packet.proto import WeekendDjinnInfo_pb2 as genshin_dot_packet_dot_proto_dot_WeekendDjinnInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3genshin/packet/proto/HomeBlockArrangementInfo.proto\x1a)genshin/packet/proto/HomeAnimalData.proto\x1a.genshin/packet/proto/HomeBlockDotPattern.proto\x1a-genshin/packet/proto/HomeBlockFieldData.proto\x1a,genshin/packet/proto/HomeFurnitureData.proto\x1a\x31genshin/packet/proto/HomeFurnitureSuiteData.proto\x1a&genshin/packet/proto/HomeNpcData.proto\x1a.genshin/packet/proto/Unk2700_BIEMCDLIFOD.proto\x1a.genshin/packet/proto/Unk2700_GOHMLAFNBGF.proto\x1a+genshin/packet/proto/WeekendDjinnInfo.proto\"\xbf\x04\n\x18HomeBlockArrangementInfo\x12\x13\n\x0bis_unlocked\x18\x01 \x01(\x08\x12\x15\n\rcomfort_value\x18\x02 \x01(\r\x12+\n\x12\x64\x65ploy_animal_list\x18\x04 \x03(\x0b\x32\x0f.HomeAnimalData\x12\x31\n\x13Unk2700_HGIECHILOJL\x18\x05 \x03(\x0b\x32\x14.Unk2700_GOHMLAFNBGF\x12\x32\n\x17weekend_djinn_info_list\x18\r \x03(\x0b\x32\x11.WeekendDjinnInfo\x12\x35\n\x14\x66urniture_suite_list\x18\x0f \x03(\x0b\x32\x17.HomeFurnitureSuiteData\x12\'\n\nfield_list\x18\x03 \x03(\x0b\x32\x13.HomeBlockFieldData\x12%\n\x0f\x64\x65ploy_npc_list\x18\x0b \x03(\x0b\x32\x0c.HomeNpcData\x12.\n\x10\x64ot_pattern_list\x18\x07 \x03(\x0b\x32\x14.HomeBlockDotPattern\x12\x35\n\x19persistent_furniture_list\x18\t \x03(\x0b\x32\x12.HomeFurnitureData\x12\x30\n\x14\x64\x65ploy_furniure_list\x18\x0c \x03(\x0b\x32\x12.HomeFurnitureData\x12\x10\n\x08\x62lock_id\x18\x06 \x01(\r\x12\x31\n\x13Unk2700_KJGLLEEHBPF\x18\x0e \x03(\x0b\x32\x14.Unk2700_BIEMCDLIFODB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')



_HOMEBLOCKARRANGEMENTINFO = DESCRIPTOR.message_types_by_name['HomeBlockArrangementInfo']
HomeBlockArrangementInfo = _reflection.GeneratedProtocolMessageType('HomeBlockArrangementInfo', (_message.Message,), {
  'DESCRIPTOR' : _HOMEBLOCKARRANGEMENTINFO,
  '__module__' : 'genshin.packet.proto.HomeBlockArrangementInfo_pb2'
  # @@protoc_insertion_point(class_scope:HomeBlockArrangementInfo)
  })
_sym_db.RegisterMessage(HomeBlockArrangementInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _HOMEBLOCKARRANGEMENTINFO._serialized_start=472
  _HOMEBLOCKARRANGEMENTINFO._serialized_end=1047
# @@protoc_insertion_point(module_scope)
