# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/HomeSceneInitFinishReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1genshin/packet/proto/HomeSceneInitFinishReq.proto\"\x18\n\x16HomeSceneInitFinishReqB\x16\n\x14org.sorapointa.protob\x06proto3')



_HOMESCENEINITFINISHREQ = DESCRIPTOR.message_types_by_name['HomeSceneInitFinishReq']
HomeSceneInitFinishReq = _reflection.GeneratedProtocolMessageType('HomeSceneInitFinishReq', (_message.Message,), {
  'DESCRIPTOR' : _HOMESCENEINITFINISHREQ,
  '__module__' : 'genshin.packet.proto.HomeSceneInitFinishReq_pb2'
  # @@protoc_insertion_point(class_scope:HomeSceneInitFinishReq)
  })
_sym_db.RegisterMessage(HomeSceneInitFinishReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _HOMESCENEINITFINISHREQ._serialized_start=53
  _HOMESCENEINITFINISHREQ._serialized_end=77
# @@protoc_insertion_point(module_scope)
