# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/HPDPKLFDMCE.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/HPDPKLFDMCE.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import OMBEIFNNEDF_pb2 as genshin_dot_packet_dot_proto_dot_OMBEIFNNEDF__pb2
from genshin.packet.proto import DMNLIDHDPFP_pb2 as genshin_dot_packet_dot_proto_dot_DMNLIDHDPFP__pb2
from genshin.packet.proto import JKIKPOMKPPI_pb2 as genshin_dot_packet_dot_proto_dot_JKIKPOMKPPI__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/HPDPKLFDMCE.proto\x1a&genshin/packet/proto/OMBEIFNNEDF.proto\x1a&genshin/packet/proto/DMNLIDHDPFP.proto\x1a&genshin/packet/proto/JKIKPOMKPPI.proto\"\xfb\x04\n\x0bHPDPKLFDMCE\x12\"\n\x0bNAKJKGHBGEK\x18\xc9\n \x03(\x0b\x32\x0c.OMBEIFNNEDF\x12\"\n\x0b\x43IDOICMOOOF\x18\x96\x06 \x03(\x0b\x32\x0c.DMNLIDHDPFP\x12\x13\n\x0bJHJILCMEONH\x18\x0b \x03(\r\x12!\n\x0b\x43\x45MLGAAHAOM\x18\t \x01(\x0b\x32\x0c.JKIKPOMKPPI\x12\x13\n\x0b\x46LNHANIGGNH\x18\x07 \x03(\r\x12\x14\n\x0bGCEOEGFCOKF\x18\x90\x06 \x03(\r\x12\x13\n\x0bHGGEHLMHKMP\x18\x01 \x01(\r\x12\x13\n\x0bGPANFJLDFPA\x18\n \x01(\r\x12\x14\n\x0b\x43PKENJMJOOL\x18\xde\x04 \x01(\r\x12\x14\n\x0bLAHHPHHMGAO\x18\xf8\x0c \x01(\r\x12\x14\n\x0bGPAOIAMOGBI\x18\x8a\x0c \x01(\r\x12\x13\n\x0bKCENFCEBEHA\x18\x0f \x01(\r\x12\x14\n\x0bKEIFNIPDLLN\x18\xb9\x01 \x01(\r\x12\x13\n\x0b\x42LMGFJBAFKB\x18\x0c \x01(\r\x12\x13\n\x0b\x41GIONNFPBGO\x18\x02 \x01(\r\x12\x13\n\x0bGMJBHCJHICH\x18\x08 \x01(\r\x12\x14\n\x0bPPBJOHAMLEB\x18\x85\x01 \x01(\r\x12\x13\n\x0bHINJHJGKOGF\x18\x04 \x01(\r\x12\x13\n\x0b\x41\x45KAGEEBAAA\x18\r \x01(\r\x12\x13\n\x0bOCPKEIOBKPB\x18\x06 \x01(\r\x12\x14\n\x0b\x45\x44\x42OCMOIKKO\x18\xf2\x04 \x01(\r\x12\x14\n\x0bMGCBKEMOADN\x18\xd0\x07 \x01(\r\x12\x13\n\x0bPDNLMNIKEON\x18\x0e \x01(\r\x12\x14\n\x0b\x43\x42\x43GMJADEIO\x18\xd7\x0b \x01(\x08\x12\x14\n\x0bNMDOMOINJFH\x18\xeb\t \x01(\x08\x12\x13\n\x0bKCJGPLKNPCL\x18\x05 \x01(\x08\x12\x14\n\x0bILMBPEDBCGB\x18\xe4\x05 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.HPDPKLFDMCE_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HPDPKLFDMCE']._serialized_start=163
  _globals['_HPDPKLFDMCE']._serialized_end=798
# @@protoc_insertion_point(module_scope)
