from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class HPIIMHEOGNI(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    HPIIMHEOGNI_EFFIGY_CHALLENGE_V4_RESTART_END_REASON_NONE: _ClassVar[HPIIMHEOGNI]
    HPIIMHEOGNI_EFFIGY_CHALLENGE_V4_RESTART_END_REASON_TIMEOUT: _ClassVar[HPIIMHEOGNI]
    HPIIMHEOGNI_EFFIGY_CHALLENGE_V4_RESTART_END_REASON_REJECT: _ClassVar[HPIIMHEOGNI]
HPIIMHEOGNI_EFFIGY_CHALLENGE_V4_RESTART_END_REASON_NONE: HPIIMHEOGNI
HPIIMHEOGNI_EFFIGY_CHALLENGE_V4_RESTART_END_REASON_TIMEOUT: HPIIMHEOGNI
HPIIMHEOGNI_EFFIGY_CHALLENGE_V4_RESTART_END_REASON_REJECT: HPIIMHEOGNI
