# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/IDNCNDFCOIF.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/IDNCNDFCOIF.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/IDNCNDFCOIF.proto\"\xb5\x01\n\x0bIDNCNDFCOIF\x12\x13\n\x0bOHDENGDFNDP\x18\x08 \x01(\r\x12\x13\n\x0bPDEIHLEKAPJ\x18\x07 \x01(\r\x12\x13\n\x0bKHHINALFLHP\x18\x05 \x01(\r\x12\x13\n\x0b\x46\x43PECPMOGOJ\x18\t \x01(\r\x12\x13\n\x0bNMBONKFLLIE\x18\x03 \x01(\r\x12\x13\n\x0b\x43\x43LBEPHGCEK\x18\r \x01(\r\x12\x13\n\x0b\x44NHLMKMLPPB\x18\n \x01(\r\x12\x13\n\x0bPENJGIIJFPG\x18\x0e \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.IDNCNDFCOIF_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IDNCNDFCOIF']._serialized_start=43
  _globals['_IDNCNDFCOIF']._serialized_end=224
# @@protoc_insertion_point(module_scope)
