from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class IEBMAHKGIPD(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    IEBMAHKGIPD_NONE: _ClassVar[IEBMAHKGIPD]
    IEBMAHKGIPD_NORMAL: _ClassVar[IEBMAHKGIPD]
    IEBMAHKGIPD_CONDENSE: _ClassVar[IEBMAHKGIPD]
    IEBMAHKGIPD_REUNION_PRIVILEGE: _ClassVar[IEBMAHKGIPD]
    IEBMAHKGIPD_OP_ACTIVITY: _ClassVar[IEBMAHKGIPD]
    IEBMAHKGIPD_MATERIAL: _ClassVar[IEBMAHKGIPD]
IEBMAHKGIPD_NONE: IEBMAHKGIPD
IEBMAHKGIPD_NORMAL: IEBMAHKGIPD
IEBMAHKGIPD_CONDENSE: IEBMAHKGIPD
IEBMAHKGIPD_REUNION_PRIVILEGE: IEBMAHKGIPD
IEBMAHKGIPD_OP_ACTIVITY: IEBMAHKGIPD
IEBMAHKGIPD_MATERIAL: IEBMAHKGIPD
