# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/IGKLNNDNCMG.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/IGKLNNDNCMG.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import AvatarExpeditionState_pb2 as genshin_dot_packet_dot_proto_dot_AvatarExpeditionState__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/IGKLNNDNCMG.proto\x1a\x30genshin/packet/proto/AvatarExpeditionState.proto\"\x8e\x01\n\x0bIGKLNNDNCMG\x12\x13\n\x0bMIMEIGLBOPI\x18\x02 \x01(\r\x12+\n\x0b\x43\x44\x42\x46PFOJBIJ\x18\x01 \x01(\x0e\x32\x16.AvatarExpeditionState\x12\x13\n\x0bPGIIOIBNKKE\x18\x05 \x01(\x02\x12\x13\n\x0b\x43\x43HOPBCADIG\x18\x03 \x01(\r\x12\x13\n\x0b\x41\x45HJBEELKOO\x18\x04 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.IGKLNNDNCMG_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IGKLNNDNCMG']._serialized_start=93
  _globals['_IGKLNNDNCMG']._serialized_end=235
# @@protoc_insertion_point(module_scope)
