# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/IHADDLGIHGB.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/IHADDLGIHGB.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import GLIEDEHAIMN_pb2 as genshin_dot_packet_dot_proto_dot_GLIEDEHAIMN__pb2
from genshin.packet.proto import KIDIOMKHFMO_pb2 as genshin_dot_packet_dot_proto_dot_KIDIOMKHFMO__pb2
from genshin.packet.proto import KEEHOCBAHKG_pb2 as genshin_dot_packet_dot_proto_dot_KEEHOCBAHKG__pb2
from genshin.packet.proto import MCLDAELJNIO_pb2 as genshin_dot_packet_dot_proto_dot_MCLDAELJNIO__pb2
from genshin.packet.proto import MMPHDJFAPGK_pb2 as genshin_dot_packet_dot_proto_dot_MMPHDJFAPGK__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/IHADDLGIHGB.proto\x1a&genshin/packet/proto/GLIEDEHAIMN.proto\x1a&genshin/packet/proto/KIDIOMKHFMO.proto\x1a&genshin/packet/proto/KEEHOCBAHKG.proto\x1a&genshin/packet/proto/MCLDAELJNIO.proto\x1a&genshin/packet/proto/MMPHDJFAPGK.proto\"\xfe\x01\n\x0bIHADDLGIHGB\x12\x13\n\x0b\x45HAEACFBOOL\x18\x0f \x01(\r\x12\x32\n\x1bseek_furniture_gallery_info\x18\xfd\t \x01(\x0b\x32\x0c.GLIEDEHAIMN\x12+\n\x14\x62\x61lloon_gallery_info\x18\xc5\x0b \x01(\x0b\x32\x0c.KIDIOMKHFMO\x12&\n\x0fstake_play_info\x18\xa8\x0c \x01(\x0b\x32\x0c.KEEHOCBAHKG\x12%\n\x0e\x65xplosion_info\x18\xdc\x07 \x01(\x0b\x32\x0c.MCLDAELJNIO\x12*\n\x13racing_gallery_info\x18\xab\x01 \x01(\x0b\x32\x0c.MMPHDJFAPGKb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.IHADDLGIHGB_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IHADDLGIHGB']._serialized_start=243
  _globals['_IHADDLGIHGB']._serialized_end=497
# @@protoc_insertion_point(module_scope)
