# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/IIOLLKFCNED.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/IIOLLKFCNED.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import NDMDBGOJBGO_pb2 as genshin_dot_packet_dot_proto_dot_NDMDBGOJBGO__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/IIOLLKFCNED.proto\x1a&genshin/packet/proto/NDMDBGOJBGO.proto\"\xbf\x02\n\x0bIIOLLKFCNED\x12!\n\x0bOOCHMLBHNFH\x18\x0f \x03(\x0b\x32\x0c.NDMDBGOJBGO\x12\x32\n\x0b\x46OLOMOBDODM\x18\x04 \x03(\x0b\x32\x1d.IIOLLKFCNED.FOLOMOBDODMEntry\x12\x13\n\x0bHFGHIMOABBE\x18\t \x03(\r\x12\x32\n\x0bKJOGIDLLODK\x18\x01 \x03(\x0b\x32\x1d.IIOLLKFCNED.KJOGIDLLODKEntry\x12\x13\n\x0b\x46MMAKJKIIDN\x18\x05 \x01(\r\x12\x13\n\x0bJINLIBHHLND\x18\x0e \x01(\r\x1a\x32\n\x10\x46OLOMOBDODMEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x1a\x32\n\x10KJOGIDLLODKEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.IIOLLKFCNED_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IIOLLKFCNED_FOLOMOBDODMENTRY']._loaded_options = None
  _globals['_IIOLLKFCNED_FOLOMOBDODMENTRY']._serialized_options = b'8\001'
  _globals['_IIOLLKFCNED_KJOGIDLLODKENTRY']._loaded_options = None
  _globals['_IIOLLKFCNED_KJOGIDLLODKENTRY']._serialized_options = b'8\001'
  _globals['_IIOLLKFCNED']._serialized_start=83
  _globals['_IIOLLKFCNED']._serialized_end=402
  _globals['_IIOLLKFCNED_FOLOMOBDODMENTRY']._serialized_start=300
  _globals['_IIOLLKFCNED_FOLOMOBDODMENTRY']._serialized_end=350
  _globals['_IIOLLKFCNED_KJOGIDLLODKENTRY']._serialized_start=352
  _globals['_IIOLLKFCNED_KJOGIDLLODKENTRY']._serialized_end=402
# @@protoc_insertion_point(module_scope)
