from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class IKEMEBCAIIC(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    IKEMEBCAIIC_HIDE_AND_SEEK_STAGE_PREPARE: _ClassVar[IKEMEBCAIIC]
    IKEMEBCAIIC_HIDE_AND_SEEK_STAGE_PICK: _ClassVar[IKEMEBCAIIC]
    IKEMEBCAIIC_HIDE_AND_SEEK_STAGE_GAME: _ClassVar[IKEMEBCAIIC]
    IKEMEBCAIIC_HIDE_AND_SEEK_STAGE_HIDE: _ClassVar[IKEMEBCAIIC]
    IKEMEBCAIIC_HIDE_AND_SEEK_STAGE_SEEK: _ClassVar[IKEMEBCAIIC]
    IKEMEBCAIIC_HIDE_AND_SEEK_STAGE_SETTLE: _ClassVar[IKEMEBCAIIC]
IKEMEBCAIIC_HIDE_AND_SEEK_STAGE_PREPARE: IKEMEBCAIIC
IKEMEBCAIIC_HIDE_AND_SEEK_STAGE_PICK: IKEMEBCAIIC
IKEMEBCAIIC_HIDE_AND_SEEK_STAGE_GAME: IKEMEBCAIIC
IKEMEBCAIIC_HIDE_AND_SEEK_STAGE_HIDE: IKEMEBCAIIC
IKEMEBCAIIC_HIDE_AND_SEEK_STAGE_SEEK: IKEMEBCAIIC
IKEMEBCAIIC_HIDE_AND_SEEK_STAGE_SETTLE: IKEMEBCAIIC
