from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class IMGPEMFGOPF(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    IMGPEMFGOPF_PLAYER_DIE_NONE: _ClassVar[IMGPEMFGOPF]
    IMGPEMFGOPF_PLAYER_DIE_KILL_BY_MONSTER: _ClassVar[IMGPEMFGOPF]
    IMGPEMFGOPF_PLAYER_DIE_KILL_BY_GEAR: _ClassVar[IMGPEMFGOPF]
    IMGPEMFGOPF_PLAYER_DIE_FALL: _ClassVar[IMGPEMFGOPF]
    IMGPEMFGOPF_PLAYER_DIE_DRAWN: _ClassVar[IMGPEMFGOPF]
    IMGPEMFGOPF_PLAYER_DIE_ABYSS: _ClassVar[IMGPEMFGOPF]
    IMGPEMFGOPF_PLAYER_DIE_GM: _ClassVar[IMGPEMFGOPF]
    IMGPEMFGOPF_PLAYER_DIE_CLIMATE_COLD: _ClassVar[IMGPEMFGOPF]
    IMGPEMFGOPF_PLAYER_DIE_STORM_LIGHTING: _ClassVar[IMGPEMFGOPF]
    IMGPEMFGOPF_PLAYER_DIE_DIRTY_WATER_EROSION: _ClassVar[IMGPEMFGOPF]
    IMGPEMFGOPF_PLAYER_DIE_LIQUID_PHLOGISTON: _ClassVar[IMGPEMFGOPF]
IMGPEMFGOPF_PLAYER_DIE_NONE: IMGPEMFGOPF
IMGPEMFGOPF_PLAYER_DIE_KILL_BY_MONSTER: IMGPEMFGOPF
IMGPEMFGOPF_PLAYER_DIE_KILL_BY_GEAR: IMGPEMFGOPF
IMGPEMFGOPF_PLAYER_DIE_FALL: IMGPEMFGOPF
IMGPEMFGOPF_PLAYER_DIE_DRAWN: IMGPEMFGOPF
IMGPEMFGOPF_PLAYER_DIE_ABYSS: IMGPEMFGOPF
IMGPEMFGOPF_PLAYER_DIE_GM: IMGPEMFGOPF
IMGPEMFGOPF_PLAYER_DIE_CLIMATE_COLD: IMGPEMFGOPF
IMGPEMFGOPF_PLAYER_DIE_STORM_LIGHTING: IMGPEMFGOPF
IMGPEMFGOPF_PLAYER_DIE_DIRTY_WATER_EROSION: IMGPEMFGOPF
IMGPEMFGOPF_PLAYER_DIE_LIQUID_PHLOGISTON: IMGPEMFGOPF
