# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/InBattleMechanicusPickCardNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;genshin/packet/proto/InBattleMechanicusPickCardNotify.proto\"m\n InBattleMechanicusPickCardNotify\x12\x12\n\nplayer_uid\x18\x06 \x01(\r\x12\x10\n\x08group_id\x18\x07 \x01(\r\x12\x12\n\nplay_index\x18\x08 \x01(\r\x12\x0f\n\x07\x63\x61rd_id\x18\n \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_INBATTLEMECHANICUSPICKCARDNOTIFY = DESCRIPTOR.message_types_by_name['InBattleMechanicusPickCardNotify']
InBattleMechanicusPickCardNotify = _reflection.GeneratedProtocolMessageType('InBattleMechanicusPickCardNotify', (_message.Message,), {
  'DESCRIPTOR' : _INBATTLEMECHANICUSPICKCARDNOTIFY,
  '__module__' : 'genshin.packet.proto.InBattleMechanicusPickCardNotify_pb2'
  # @@protoc_insertion_point(class_scope:InBattleMechanicusPickCardNotify)
  })
_sym_db.RegisterMessage(InBattleMechanicusPickCardNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _INBATTLEMECHANICUSPICKCARDNOTIFY._serialized_start=63
  _INBATTLEMECHANICUSPICKCARDNOTIFY._serialized_end=172
# @@protoc_insertion_point(module_scope)
