from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class IOEOEIMKMJD(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    IOEOEIMKMJD_PROP_CHANGE_NONE: _ClassVar[IOEOEIMKMJD]
    IOEOEIMKMJD_PROP_CHANGE_STATUE_RECOVER: _ClassVar[IOEOEIMKMJD]
    IOEOEIMKMJD_PROP_CHANGE_ENERGY_BALL: _ClassVar[IOEOEIMKMJD]
    IOEOEIMKMJD_PROP_CHANGE_ABILITY: _ClassVar[IOEOEIMKMJD]
    IOEOEIMKMJD_PROP_CHANGE_LEVELUP: _ClassVar[IOEOEIMKMJD]
    IOEOEIMKMJD_PROP_CHANGE_ITEM: _ClassVar[IOEOEIMKMJD]
    IOEOEIMKMJD_PROP_CHANGE_AVATAR_CARD: _ClassVar[IOEOEIMKMJD]
    IOEOEIMKMJD_PROP_CHANGE_CITY_LEVELUP: _ClassVar[IOEOEIMKMJD]
    IOEOEIMKMJD_PROP_CHANGE_AVATAR_UPGRADE: _ClassVar[IOEOEIMKMJD]
    IOEOEIMKMJD_PROP_CHANGE_AVATAR_PROMOTE: _ClassVar[IOEOEIMKMJD]
    IOEOEIMKMJD_PROP_CHANGE_PLAYER_ADD_EXP: _ClassVar[IOEOEIMKMJD]
    IOEOEIMKMJD_PROP_CHANGE_FINISH_QUEST: _ClassVar[IOEOEIMKMJD]
    IOEOEIMKMJD_PROP_CHANGE_GM: _ClassVar[IOEOEIMKMJD]
    IOEOEIMKMJD_PROP_CHANGE_MANUAL_ADJUST_WORLD_LEVEL: _ClassVar[IOEOEIMKMJD]
IOEOEIMKMJD_PROP_CHANGE_NONE: IOEOEIMKMJD
IOEOEIMKMJD_PROP_CHANGE_STATUE_RECOVER: IOEOEIMKMJD
IOEOEIMKMJD_PROP_CHANGE_ENERGY_BALL: IOEOEIMKMJD
IOEOEIMKMJD_PROP_CHANGE_ABILITY: IOEOEIMKMJD
IOEOEIMKMJD_PROP_CHANGE_LEVELUP: IOEOEIMKMJD
IOEOEIMKMJD_PROP_CHANGE_ITEM: IOEOEIMKMJD
IOEOEIMKMJD_PROP_CHANGE_AVATAR_CARD: IOEOEIMKMJD
IOEOEIMKMJD_PROP_CHANGE_CITY_LEVELUP: IOEOEIMKMJD
IOEOEIMKMJD_PROP_CHANGE_AVATAR_UPGRADE: IOEOEIMKMJD
IOEOEIMKMJD_PROP_CHANGE_AVATAR_PROMOTE: IOEOEIMKMJD
IOEOEIMKMJD_PROP_CHANGE_PLAYER_ADD_EXP: IOEOEIMKMJD
IOEOEIMKMJD_PROP_CHANGE_FINISH_QUEST: IOEOEIMKMJD
IOEOEIMKMJD_PROP_CHANGE_GM: IOEOEIMKMJD
IOEOEIMKMJD_PROP_CHANGE_MANUAL_ADJUST_WORLD_LEVEL: IOEOEIMKMJD
