# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/ItemGivingRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(genshin/packet/proto/ItemGivingRsp.proto\"P\n\rItemGivingRsp\x12\x1b\n\x13Unk2700_MHIPHDFEOON\x18\x01 \x01(\r\x12\x11\n\tgiving_id\x18\r \x01(\r\x12\x0f\n\x07retcode\x18\x03 \x01(\x05\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')



_ITEMGIVINGRSP = DESCRIPTOR.message_types_by_name['ItemGivingRsp']
ItemGivingRsp = _reflection.GeneratedProtocolMessageType('ItemGivingRsp', (_message.Message,), {
  'DESCRIPTOR' : _ITEMGIVINGRSP,
  '__module__' : 'genshin.packet.proto.ItemGivingRsp_pb2'
  # @@protoc_insertion_point(class_scope:ItemGivingRsp)
  })
_sym_db.RegisterMessage(ItemGivingRsp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _ITEMGIVINGRSP._serialized_start=44
  _ITEMGIVINGRSP._serialized_end=124
# @@protoc_insertion_point(module_scope)
