# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/JBCFNMIAMOE.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/JBCFNMIAMOE.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import FKHEIDFJKDO_pb2 as genshin_dot_packet_dot_proto_dot_FKHEIDFJKDO__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/JBCFNMIAMOE.proto\x1a&genshin/packet/proto/FKHEIDFJKDO.proto\"\xd7\x01\n\x0bJBCFNMIAMOE\x12\x32\n\x0bJENACEPCGOF\x18\x01 \x03(\x0b\x32\x1d.JBCFNMIAMOE.JENACEPCGOFEntry\x12\x13\n\x0bLPGMAEHCBOB\x18\x02 \x03(\r\x12\x13\n\x0bHAEAOOFAJNG\x18\n \x01(\x08\x12\x13\n\x0bIKDAJELLEAI\x18\x04 \x01(\r\x12\x13\n\x0b\x44OMBDIMFFII\x18\x07 \x01(\r\x1a@\n\x10JENACEPCGOFEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.FKHEIDFJKDO:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.JBCFNMIAMOE_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JBCFNMIAMOE_JENACEPCGOFENTRY']._loaded_options = None
  _globals['_JBCFNMIAMOE_JENACEPCGOFENTRY']._serialized_options = b'8\001'
  _globals['_JBCFNMIAMOE']._serialized_start=83
  _globals['_JBCFNMIAMOE']._serialized_end=298
  _globals['_JBCFNMIAMOE_JENACEPCGOFENTRY']._serialized_start=234
  _globals['_JBCFNMIAMOE_JENACEPCGOFENTRY']._serialized_end=298
# @@protoc_insertion_point(module_scope)
