# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/JHKOBMAMNAB.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/JHKOBMAMNAB.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/JHKOBMAMNAB.proto\"\xb5\x01\n\x0bJHKOBMAMNAB\x12\x13\n\x0bHCJFDJHILAM\x18\x0e \x01(\x08\x12\x13\n\x0bOMENIAMEDCE\x18\x01 \x01(\x08\x12\x13\n\x0bODCMKOFFKKL\x18\x0c \x01(\r\x12\x13\n\x0bLCEAAMJMKJN\x18\x0f \x01(\r\x12\x13\n\x0b\x45HAEACFBOOL\x18\x04 \x01(\r\x12\x13\n\x0bGEFNMJHABGJ\x18\x03 \x01(\r\x12\x13\n\x0bPDBFCAEGFEG\x18\t \x01(\r\x12\x13\n\x0bPMLDNFNNJAM\x18\r \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.JHKOBMAMNAB_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JHKOBMAMNAB']._serialized_start=43
  _globals['_JHKOBMAMNAB']._serialized_end=224
# @@protoc_insertion_point(module_scope)
