# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/JIOFAJPCNAC.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/JIOFAJPCNAC.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import PCPKMBJDJAK_pb2 as genshin_dot_packet_dot_proto_dot_PCPKMBJDJAK__pb2
from genshin.packet.proto import IACMANPJHJI_pb2 as genshin_dot_packet_dot_proto_dot_IACMANPJHJI__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/JIOFAJPCNAC.proto\x1a&genshin/packet/proto/PCPKMBJDJAK.proto\x1a&genshin/packet/proto/IACMANPJHJI.proto\"\xa7\x01\n\x0bJIOFAJPCNAC\x12!\n\x0bGAAKALGOBCF\x18\x0c \x01(\x0e\x32\x0c.PCPKMBJDJAK\x12\x13\n\x0b\x45JNINFFFKJP\x18\x04 \x01(\x05\x12\x13\n\x0bGHLBJAHJEHF\x18\x07 \x01(\r\x12\x13\n\x0b\x44\x44JFGLFNGJC\x18\n \x01(\r\x12\x13\n\x0bOCKIBANLDMK\x18\x03 \x01(\r\x12!\n\x0bKGCONLDGJPG\x18\t \x01(\x0e\x32\x0c.IACMANPJHJIb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.JIOFAJPCNAC_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JIOFAJPCNAC']._serialized_start=123
  _globals['_JIOFAJPCNAC']._serialized_end=290
# @@protoc_insertion_point(module_scope)
