# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/JKBOBOHMEOE.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/JKBOBOHMEOE.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import HMBFCHKMEGD_pb2 as genshin_dot_packet_dot_proto_dot_HMBFCHKMEGD__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/JKBOBOHMEOE.proto\x1a&genshin/packet/proto/HMBFCHKMEGD.proto\"E\n\x0bJKBOBOHMEOE\x12\x13\n\x0bKPIOGBMLMEM\x18\x0c \x01(\t\x12!\n\x0bOOFABEHBCBH\x18\x02 \x01(\x0e\x32\x0c.HMBFCHKMEGDb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.JKBOBOHMEOE_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JKBOBOHMEOE']._serialized_start=82
  _globals['_JKBOBOHMEOE']._serialized_end=151
# @@protoc_insertion_point(module_scope)
