from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class JKEEPGBAAFH(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    JKEEPGBAAFH_FIREWORKS_LAUNCH_PARAM_NONE: _ClassVar[JKEEPGBAAFH]
    JKEEPGBAAFH_FIREWORKS_LAUNCH_PARAM_REPEAT: _ClassVar[JKEEPGBAAFH]
    JKEEPGBAAFH_FIREWORKS_LAUNCH_PARAM_INTEVAL: _ClassVar[JKEEPGBAAFH]
    JKEEPGBAAFH_FIREWORKS_LAUNCH_PARAM_DELAY: _ClassVar[JKEEPGBAAFH]
    JKEEPGBAAFH_FIREWORKS_LAUNCH_PARAM_ROUND_INTEVAL: _ClassVar[JKEEPGBAAFH]
    JKEEPGBAAFH_FIREWORKS_LAUNCH_PARAM_MAX: _ClassVar[JKEEPGBAAFH]
JKEEPGBAAFH_FIREWORKS_LAUNCH_PARAM_NONE: JKEEPGBAAFH
JKEEPGBAAFH_FIREWORKS_LAUNCH_PARAM_REPEAT: JKEEPGBAAFH
JKEEPGBAAFH_FIREWORKS_LAUNCH_PARAM_INTEVAL: JKEEPGBAAFH
JKEEPGBAAFH_FIREWORKS_LAUNCH_PARAM_DELAY: JKEEPGBAAFH
JKEEPGBAAFH_FIREWORKS_LAUNCH_PARAM_ROUND_INTEVAL: JKEEPGBAAFH
JKEEPGBAAFH_FIREWORKS_LAUNCH_PARAM_MAX: JKEEPGBAAFH
