from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class JMBBABGJLAM(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    JMBBABGJLAM_DUNGEON_CANDIDATE_TPLR_NORMAL: _ClassVar[JMBBABGJLAM]
    JMBBABGJLAM_DUNGEON_CANDIDATE_TPLR_DIE: _ClassVar[JMBBABGJLAM]
    JMBBABGJLAM_DUNGEON_CANDIDATE_TPLR_BE_KICK: _ClassVar[JMBBABGJLAM]
    JMBBABGJLAM_DUNGEON_CANDIDATE_DISCONNECT: _ClassVar[JMBBABGJLAM]
JMBBABGJLAM_DUNGEON_CANDIDATE_TPLR_NORMAL: JMBBABGJLAM
JMBBABGJLAM_DUNGEON_CANDIDATE_TPLR_DIE: JMBBABGJLAM
JMBBABGJLAM_DUNGEON_CANDIDATE_TPLR_BE_KICK: JMBBABGJLAM
JMBBABGJLAM_DUNGEON_CANDIDATE_DISCONNECT: JMBBABGJLAM
