from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class KAAPGMMGPOF(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    KAAPGMMGPOF_SALVAGE_PREVENT_STOP_NONE: _ClassVar[KAAPGMMGPOF]
    KAAPGMMGPOF_SALVAGE_PREVENT_STOP_SUCCESS: _ClassVar[KAAPGMMGPOF]
    KAAPGMMGPOF_SALVAGE_PREVENT_STOP_ARRIVAL: _ClassVar[KAAPGMMGPOF]
    KAAPGMMGPOF_SALVAGE_PREVENT_STOP_INTERRUPT: _ClassVar[KAAPGMMGPOF]
    KAAPGMMGPOF_SALVAGE_PREVENT_STOP_LEAVE: _ClassVar[KAAPGMMGPOF]
    KAAPGMMGPOF_SALVAGE_PREVENT_STOP_FULL: _ClassVar[KAAPGMMGPOF]
    KAAPGMMGPOF_SALVAGE_PREVENT_STOP_AWAY: _ClassVar[KAAPGMMGPOF]
KAAPGMMGPOF_SALVAGE_PREVENT_STOP_NONE: KAAPGMMGPOF
KAAPGMMGPOF_SALVAGE_PREVENT_STOP_SUCCESS: KAAPGMMGPOF
KAAPGMMGPOF_SALVAGE_PREVENT_STOP_ARRIVAL: KAAPGMMGPOF
KAAPGMMGPOF_SALVAGE_PREVENT_STOP_INTERRUPT: KAAPGMMGPOF
KAAPGMMGPOF_SALVAGE_PREVENT_STOP_LEAVE: KAAPGMMGPOF
KAAPGMMGPOF_SALVAGE_PREVENT_STOP_FULL: KAAPGMMGPOF
KAAPGMMGPOF_SALVAGE_PREVENT_STOP_AWAY: KAAPGMMGPOF
