from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class KABBEPLLGOJ(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    KABBEPLLGOJ_DEFAULT: _ClassVar[KABBEPLLGOJ]
    KABBEPLLGOJ_DIE: _ClassVar[KABBEPLLGOJ]
    KABBEPLLGOJ_SURRENDER: _ClassVar[KABBEPLLGOJ]
    KABBEPLLGOJ_DISCONNECTED: _ClassVar[KABBEPLLGOJ]
    KABBEPLLGOJ_ROUND_LIMIT: _ClassVar[KABBEPLLGOJ]
    KABBEPLLGOJ_GM: _ClassVar[KABBEPLLGOJ]
    KABBEPLLGOJ_NO_PLAYER: _ClassVar[KABBEPLLGOJ]
    KABBEPLLGOJ_GIVE_UP: _ClassVar[KABBEPLLGOJ]
    KABBEPLLGOJ_INIT_TIMEOUT: _ClassVar[KABBEPLLGOJ]
    KABBEPLLGOJ_EFFECT: _ClassVar[KABBEPLLGOJ]
    KABBEPLLGOJ_EXPIRE_TIMEOUT: _ClassVar[KABBEPLLGOJ]
KABBEPLLGOJ_DEFAULT: KABBEPLLGOJ
KABBEPLLGOJ_DIE: KABBEPLLGOJ
KABBEPLLGOJ_SURRENDER: KABBEPLLGOJ
KABBEPLLGOJ_DISCONNECTED: KABBEPLLGOJ
KABBEPLLGOJ_ROUND_LIMIT: KABBEPLLGOJ
KABBEPLLGOJ_GM: KABBEPLLGOJ
KABBEPLLGOJ_NO_PLAYER: KABBEPLLGOJ
KABBEPLLGOJ_GIVE_UP: KABBEPLLGOJ
KABBEPLLGOJ_INIT_TIMEOUT: KABBEPLLGOJ
KABBEPLLGOJ_EFFECT: KABBEPLLGOJ
KABBEPLLGOJ_EXPIRE_TIMEOUT: KABBEPLLGOJ
