from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class KBAIOMIOCCP(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    KBAIOMIOCCP_GCG_ZONE_INVALID: _ClassVar[KBAIOMIOCCP]
    KBAIOMIOCCP_GCG_ZONE_DECK: _ClassVar[KBAIOMIOCCP]
    KBAIOMIOCCP_GCG_ZONE_HAND: _ClassVar[KBAIOMIOCCP]
    KBAIOMIOCCP_GCG_ZONE_CHARACTER: _ClassVar[KBAIOMIOCCP]
    KBAIOMIOCCP_GCG_ZONE_MODIFY: _ClassVar[KBAIOMIOCCP]
    KBAIOMIOCCP_GCG_ZONE_SUMMON: _ClassVar[KBAIOMIOCCP]
    KBAIOMIOCCP_GCG_ZONE_ASSIST: _ClassVar[KBAIOMIOCCP]
    KBAIOMIOCCP_GCG_ZONE_ONSTAGE: _ClassVar[KBAIOMIOCCP]
    KBAIOMIOCCP_GCG_ZONE_RULE: _ClassVar[KBAIOMIOCCP]
KBAIOMIOCCP_GCG_ZONE_INVALID: KBAIOMIOCCP
KBAIOMIOCCP_GCG_ZONE_DECK: KBAIOMIOCCP
KBAIOMIOCCP_GCG_ZONE_HAND: KBAIOMIOCCP
KBAIOMIOCCP_GCG_ZONE_CHARACTER: KBAIOMIOCCP
KBAIOMIOCCP_GCG_ZONE_MODIFY: KBAIOMIOCCP
KBAIOMIOCCP_GCG_ZONE_SUMMON: KBAIOMIOCCP
KBAIOMIOCCP_GCG_ZONE_ASSIST: KBAIOMIOCCP
KBAIOMIOCCP_GCG_ZONE_ONSTAGE: KBAIOMIOCCP
KBAIOMIOCCP_GCG_ZONE_RULE: KBAIOMIOCCP
