from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class KBDONBEEIFA(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    KBDONBEEIFA_GCG_PERFORM_INVALID: _ClassVar[KBDONBEEIFA]
    KBDONBEEIFA_GCG_PERFORM_CARD_EXCHANGE: _ClassVar[KBDONBEEIFA]
    KBDONBEEIFA_GCG_PERFORM_FIRST_HAND: _ClassVar[KBDONBEEIFA]
    KBDONBEEIFA_GCG_PERFORM_REROLL: _ClassVar[KBDONBEEIFA]
    KBDONBEEIFA_GCG_PREFORM_COST_REVISE: _ClassVar[KBDONBEEIFA]
    KBDONBEEIFA_GCG_PERFORM_REDRAW: _ClassVar[KBDONBEEIFA]
    KBDONBEEIFA_GCG_PERFORM_HISTORY: _ClassVar[KBDONBEEIFA]
    KBDONBEEIFA_GCG_PERFORM_BEFORE_HENSHIN: _ClassVar[KBDONBEEIFA]
KBDONBEEIFA_GCG_PERFORM_INVALID: KBDONBEEIFA
KBDONBEEIFA_GCG_PERFORM_CARD_EXCHANGE: KBDONBEEIFA
KBDONBEEIFA_GCG_PERFORM_FIRST_HAND: KBDONBEEIFA
KBDONBEEIFA_GCG_PERFORM_REROLL: KBDONBEEIFA
KBDONBEEIFA_GCG_PREFORM_COST_REVISE: KBDONBEEIFA
KBDONBEEIFA_GCG_PERFORM_REDRAW: KBDONBEEIFA
KBDONBEEIFA_GCG_PERFORM_HISTORY: KBDONBEEIFA
KBDONBEEIFA_GCG_PERFORM_BEFORE_HENSHIN: KBDONBEEIFA
