from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class KFBHHDDEAGB(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    KFBHHDDEAGB_NONE: _ClassVar[KFBHHDDEAGB]
    KFBHHDDEAGB_DESTORY_VEHCILE: _ClassVar[KFBHHDDEAGB]
    KFBHHDDEAGB_ENTER_SCENE: _ClassVar[KFBHHDDEAGB]
    KFBHHDDEAGB_LEAVE_SCENE: _ClassVar[KFBHHDDEAGB]
    KFBHHDDEAGB_ACTIVE_VEHCILE: _ClassVar[KFBHHDDEAGB]
    KFBHHDDEAGB_ENTER_VEHICLE: _ClassVar[KFBHHDDEAGB]
    KFBHHDDEAGB_SPEED_CHECK: _ClassVar[KFBHHDDEAGB]
    KFBHHDDEAGB_GM: _ClassVar[KFBHHDDEAGB]
    KFBHHDDEAGB_USE_WIDGET_TP: _ClassVar[KFBHHDDEAGB]
    KFBHHDDEAGB_USE_WIDGET_NOT_TP: _ClassVar[KFBHHDDEAGB]
    KFBHHDDEAGB_GALLERY_VEHCILE_NOT_TP: _ClassVar[KFBHHDDEAGB]
    KFBHHDDEAGB_QUEST_EXEC: _ClassVar[KFBHHDDEAGB]
KFBHHDDEAGB_NONE: KFBHHDDEAGB
KFBHHDDEAGB_DESTORY_VEHCILE: KFBHHDDEAGB
KFBHHDDEAGB_ENTER_SCENE: KFBHHDDEAGB
KFBHHDDEAGB_LEAVE_SCENE: KFBHHDDEAGB
KFBHHDDEAGB_ACTIVE_VEHCILE: KFBHHDDEAGB
KFBHHDDEAGB_ENTER_VEHICLE: KFBHHDDEAGB
KFBHHDDEAGB_SPEED_CHECK: KFBHHDDEAGB
KFBHHDDEAGB_GM: KFBHHDDEAGB
KFBHHDDEAGB_USE_WIDGET_TP: KFBHHDDEAGB
KFBHHDDEAGB_USE_WIDGET_NOT_TP: KFBHHDDEAGB
KFBHHDDEAGB_GALLERY_VEHCILE_NOT_TP: KFBHHDDEAGB
KFBHHDDEAGB_QUEST_EXEC: KFBHHDDEAGB
