# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/KHPFEKNJDOF.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/KHPFEKNJDOF.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/KHPFEKNJDOF.proto\"\xdb\x02\n\x0bKHPFEKNJDOF\x12\x32\n\x0b\x43HEHPFEHBOP\x18\x0e \x03(\x0b\x32\x1d.KHPFEKNJDOF.CHEHPFEHBOPEntry\x12\x32\n\x0b\x43MKFFDOALEM\x18\r \x03(\x0b\x32\x1d.KHPFEKNJDOF.CMKFFDOALEMEntry\x12\x13\n\x0b\x44IFIMMMNJFO\x18\x0f \x01(\r\x12\x13\n\x0bMEOHEILLEBH\x18\x03 \x01(\r\x12\x13\n\x0bKNGJHMLLCNP\x18\x08 \x01(\r\x12\x13\n\x0b\x46\x44MKMFBOCLA\x18\t \x01(\r\x12\x13\n\x0bJPDBMDLEEEC\x18\n \x01(\r\x12\x13\n\x0bJFGGPGKHJCK\x18\x06 \x01(\r\x1a\x32\n\x10\x43HEHPFEHBOPEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x1a\x32\n\x10\x43MKFFDOALEMEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.KHPFEKNJDOF_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KHPFEKNJDOF_CHEHPFEHBOPENTRY']._loaded_options = None
  _globals['_KHPFEKNJDOF_CHEHPFEHBOPENTRY']._serialized_options = b'8\001'
  _globals['_KHPFEKNJDOF_CMKFFDOALEMENTRY']._loaded_options = None
  _globals['_KHPFEKNJDOF_CMKFFDOALEMENTRY']._serialized_options = b'8\001'
  _globals['_KHPFEKNJDOF']._serialized_start=43
  _globals['_KHPFEKNJDOF']._serialized_end=390
  _globals['_KHPFEKNJDOF_CHEHPFEHBOPENTRY']._serialized_start=288
  _globals['_KHPFEKNJDOF_CHEHPFEHBOPENTRY']._serialized_end=338
  _globals['_KHPFEKNJDOF_CMKFFDOALEMENTRY']._serialized_start=340
  _globals['_KHPFEKNJDOF_CMKFFDOALEMENTRY']._serialized_end=390
# @@protoc_insertion_point(module_scope)
