from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class KMHNIKBIOEE(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    KMHNIKBIOEE_IN_BATTLE_MECHANICUS_STAGE_NONE: _ClassVar[KMHNIKBIOEE]
    KMHNIKBIOEE_IN_BATTLE_MECHANICUS_STAGE_BUILD: _ClassVar[KMHNIKBIOEE]
    KMHNIKBIOEE_IN_BATTLE_MECHANICUS_STAGE_CARD_FLIP: _ClassVar[KMHNIKBIOEE]
    KMHNIKBIOEE_IN_BATTLE_MECHANICUS_STAGE_KILL: _ClassVar[KMHNIKBIOEE]
KMHNIKBIOEE_IN_BATTLE_MECHANICUS_STAGE_NONE: KMHNIKBIOEE
KMHNIKBIOEE_IN_BATTLE_MECHANICUS_STAGE_BUILD: KMHNIKBIOEE
KMHNIKBIOEE_IN_BATTLE_MECHANICUS_STAGE_CARD_FLIP: KMHNIKBIOEE
KMHNIKBIOEE_IN_BATTLE_MECHANICUS_STAGE_KILL: KMHNIKBIOEE
