# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/KPDDLJECBCJ.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/KPDDLJECBCJ.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import FNMJNFHDLFA_pb2 as genshin_dot_packet_dot_proto_dot_FNMJNFHDLFA__pb2
from genshin.packet.proto import DPOGEFJBHLG_pb2 as genshin_dot_packet_dot_proto_dot_DPOGEFJBHLG__pb2
from genshin.packet.proto import MJOGIGOMGJO_pb2 as genshin_dot_packet_dot_proto_dot_MJOGIGOMGJO__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/KPDDLJECBCJ.proto\x1a&genshin/packet/proto/FNMJNFHDLFA.proto\x1a&genshin/packet/proto/DPOGEFJBHLG.proto\x1a&genshin/packet/proto/MJOGIGOMGJO.proto\"v\n\x0bKPDDLJECBCJ\x12!\n\x0bLCEJJHALMMJ\x18\x08 \x01(\x0b\x32\x0c.FNMJNFHDLFA\x12!\n\x0bKCBLAFECKCH\x18\x02 \x01(\x0b\x32\x0c.DPOGEFJBHLG\x12!\n\x0b\x42KNEEJGDLNO\x18\x0f \x01(\x0b\x32\x0c.MJOGIGOMGJOb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.KPDDLJECBCJ_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KPDDLJECBCJ']._serialized_start=162
  _globals['_KPDDLJECBCJ']._serialized_end=280
# @@protoc_insertion_point(module_scope)
