from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class LFJLGOJMKEH(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LFJLGOJMKEH_GALLERY_STOP_NONE: _ClassVar[LFJLGOJMKEH]
    LFJLGOJMKEH_GALLERY_STOP_TIMEUP: _ClassVar[LFJLGOJMKEH]
    LFJLGOJMKEH_GALLERY_STOP_CLIENT_INTERRUPT: _ClassVar[LFJLGOJMKEH]
    LFJLGOJMKEH_GALLERY_STOP_LUA_INTERRUPT_SUCCESS: _ClassVar[LFJLGOJMKEH]
    LFJLGOJMKEH_GALLERY_STOP_LUA_INTERRUPT_FAIL: _ClassVar[LFJLGOJMKEH]
    LFJLGOJMKEH_GALLERY_STOP_OWNER_LEAVE_SCENE: _ClassVar[LFJLGOJMKEH]
    LFJLGOJMKEH_GALLERY_STOP_PLAY_INIT_FAILED: _ClassVar[LFJLGOJMKEH]
    LFJLGOJMKEH_GALLERY_STOP_OTHER_PLAYER_ENTER: _ClassVar[LFJLGOJMKEH]
    LFJLGOJMKEH_GALLERY_STOP_AVATAR_DIE: _ClassVar[LFJLGOJMKEH]
    LFJLGOJMKEH_GALLERY_STOP_FINISHED: _ClassVar[LFJLGOJMKEH]
    LFJLGOJMKEH_GALLERY_STOP_FUNGUS_ALL_DIE: _ClassVar[LFJLGOJMKEH]
    LFJLGOJMKEH_GALLERY_STOP_LIFE_COUNT_ZERO: _ClassVar[LFJLGOJMKEH]
    LFJLGOJMKEH_GALLERY_STOP_ACTIVITY_CLOSED: _ClassVar[LFJLGOJMKEH]
    LFJLGOJMKEH_GALLERY_STOP_LEAVE_REGION_FAIL: _ClassVar[LFJLGOJMKEH]
    LFJLGOJMKEH_GALLERY_STOP_HEART_BLOOD_USED_OUT: _ClassVar[LFJLGOJMKEH]
    LFJLGOJMKEH_GALLERY_STOP_GUARDIAN_STONE_DIE: _ClassVar[LFJLGOJMKEH]
LFJLGOJMKEH_GALLERY_STOP_NONE: LFJLGOJMKEH
LFJLGOJMKEH_GALLERY_STOP_TIMEUP: LFJLGOJMKEH
LFJLGOJMKEH_GALLERY_STOP_CLIENT_INTERRUPT: LFJLGOJMKEH
LFJLGOJMKEH_GALLERY_STOP_LUA_INTERRUPT_SUCCESS: LFJLGOJMKEH
LFJLGOJMKEH_GALLERY_STOP_LUA_INTERRUPT_FAIL: LFJLGOJMKEH
LFJLGOJMKEH_GALLERY_STOP_OWNER_LEAVE_SCENE: LFJLGOJMKEH
LFJLGOJMKEH_GALLERY_STOP_PLAY_INIT_FAILED: LFJLGOJMKEH
LFJLGOJMKEH_GALLERY_STOP_OTHER_PLAYER_ENTER: LFJLGOJMKEH
LFJLGOJMKEH_GALLERY_STOP_AVATAR_DIE: LFJLGOJMKEH
LFJLGOJMKEH_GALLERY_STOP_FINISHED: LFJLGOJMKEH
LFJLGOJMKEH_GALLERY_STOP_FUNGUS_ALL_DIE: LFJLGOJMKEH
LFJLGOJMKEH_GALLERY_STOP_LIFE_COUNT_ZERO: LFJLGOJMKEH
LFJLGOJMKEH_GALLERY_STOP_ACTIVITY_CLOSED: LFJLGOJMKEH
LFJLGOJMKEH_GALLERY_STOP_LEAVE_REGION_FAIL: LFJLGOJMKEH
LFJLGOJMKEH_GALLERY_STOP_HEART_BLOOD_USED_OUT: LFJLGOJMKEH
LFJLGOJMKEH_GALLERY_STOP_GUARDIAN_STONE_DIE: LFJLGOJMKEH
