from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class LJCNGNGDGPH(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LJCNGNGDGPH_GCG_PHASE_INVALID: _ClassVar[LJCNGNGDGPH]
    LJCNGNGDGPH_GCG_PHASE_START: _ClassVar[LJCNGNGDGPH]
    LJCNGNGDGPH_GCG_PHASE_DRAW: _ClassVar[LJCNGNGDGPH]
    LJCNGNGDGPH_GCG_PHASE_ON_STAGE: _ClassVar[LJCNGNGDGPH]
    LJCNGNGDGPH_GCG_PHASE_DICE: _ClassVar[LJCNGNGDGPH]
    LJCNGNGDGPH_GCG_PHASE_MAIN: _ClassVar[LJCNGNGDGPH]
    LJCNGNGDGPH_GCG_PHASE_END: _ClassVar[LJCNGNGDGPH]
    LJCNGNGDGPH_GCG_PHASE_DIE: _ClassVar[LJCNGNGDGPH]
    LJCNGNGDGPH_GCG_PHASE_FIN: _ClassVar[LJCNGNGDGPH]
    LJCNGNGDGPH_GCG_PHASE_PRE_MAIN: _ClassVar[LJCNGNGDGPH]
    LJCNGNGDGPH_GCG_PHASE_REROLL: _ClassVar[LJCNGNGDGPH]
    LJCNGNGDGPH_GCG_PHASE_REDRAW: _ClassVar[LJCNGNGDGPH]
    LJCNGNGDGPH_GCG_PHASE_DISCOVER: _ClassVar[LJCNGNGDGPH]
    LJCNGNGDGPH_GCG_PHASE_AUTO_BATTLE_CARD_START: _ClassVar[LJCNGNGDGPH]
    LJCNGNGDGPH_GCG_PHASE_AUTO_BATTLE_CARD_MAIN: _ClassVar[LJCNGNGDGPH]
    LJCNGNGDGPH_GCG_PHASE_AUTO_BATTLE_CARD_PRE_MAIN: _ClassVar[LJCNGNGDGPH]
LJCNGNGDGPH_GCG_PHASE_INVALID: LJCNGNGDGPH
LJCNGNGDGPH_GCG_PHASE_START: LJCNGNGDGPH
LJCNGNGDGPH_GCG_PHASE_DRAW: LJCNGNGDGPH
LJCNGNGDGPH_GCG_PHASE_ON_STAGE: LJCNGNGDGPH
LJCNGNGDGPH_GCG_PHASE_DICE: LJCNGNGDGPH
LJCNGNGDGPH_GCG_PHASE_MAIN: LJCNGNGDGPH
LJCNGNGDGPH_GCG_PHASE_END: LJCNGNGDGPH
LJCNGNGDGPH_GCG_PHASE_DIE: LJCNGNGDGPH
LJCNGNGDGPH_GCG_PHASE_FIN: LJCNGNGDGPH
LJCNGNGDGPH_GCG_PHASE_PRE_MAIN: LJCNGNGDGPH
LJCNGNGDGPH_GCG_PHASE_REROLL: LJCNGNGDGPH
LJCNGNGDGPH_GCG_PHASE_REDRAW: LJCNGNGDGPH
LJCNGNGDGPH_GCG_PHASE_DISCOVER: LJCNGNGDGPH
LJCNGNGDGPH_GCG_PHASE_AUTO_BATTLE_CARD_START: LJCNGNGDGPH
LJCNGNGDGPH_GCG_PHASE_AUTO_BATTLE_CARD_MAIN: LJCNGNGDGPH
LJCNGNGDGPH_GCG_PHASE_AUTO_BATTLE_CARD_PRE_MAIN: LJCNGNGDGPH
