from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class LMFOLODEJFA(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LMFOLODEJFA_CHANGE_HP_DEBTS_NONE: _ClassVar[LMFOLODEJFA]
    LMFOLODEJFA_CHANGE_HP_DEBTS_PAY: _ClassVar[LMFOLODEJFA]
    LMFOLODEJFA_CHANGE_HP_DEBTS_PAY_FINISH: _ClassVar[LMFOLODEJFA]
    LMFOLODEJFA_CHANGE_HP_DEBTS_CLEAR: _ClassVar[LMFOLODEJFA]
    LMFOLODEJFA_CHANGE_HP_DEBTS_REDUCE_ABILITY: _ClassVar[LMFOLODEJFA]
    LMFOLODEJFA_CHANGE_HP_DEBTS_ADD_ABILITY: _ClassVar[LMFOLODEJFA]
LMFOLODEJFA_CHANGE_HP_DEBTS_NONE: LMFOLODEJFA
LMFOLODEJFA_CHANGE_HP_DEBTS_PAY: LMFOLODEJFA
LMFOLODEJFA_CHANGE_HP_DEBTS_PAY_FINISH: LMFOLODEJFA
LMFOLODEJFA_CHANGE_HP_DEBTS_CLEAR: LMFOLODEJFA
LMFOLODEJFA_CHANGE_HP_DEBTS_REDUCE_ABILITY: LMFOLODEJFA
LMFOLODEJFA_CHANGE_HP_DEBTS_ADD_ABILITY: LMFOLODEJFA
