from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class LMJBPCIGOBK(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LMJBPCIGOBK_GADGET_BORN_NONE: _ClassVar[LMJBPCIGOBK]
    LMJBPCIGOBK_GADGET_BORN_IN_AIR: _ClassVar[LMJBPCIGOBK]
    LMJBPCIGOBK_GADGET_BORN_PLAYER: _ClassVar[LMJBPCIGOBK]
    LMJBPCIGOBK_GADGET_BORN_MONSTER_HIT: _ClassVar[LMJBPCIGOBK]
    LMJBPCIGOBK_GADGET_BORN_MONSTER_DIE: _ClassVar[LMJBPCIGOBK]
    LMJBPCIGOBK_GADGET_BORN_GADGET: _ClassVar[LMJBPCIGOBK]
    LMJBPCIGOBK_GADGET_BORN_GROUND: _ClassVar[LMJBPCIGOBK]
LMJBPCIGOBK_GADGET_BORN_NONE: LMJBPCIGOBK
LMJBPCIGOBK_GADGET_BORN_IN_AIR: LMJBPCIGOBK
LMJBPCIGOBK_GADGET_BORN_PLAYER: LMJBPCIGOBK
LMJBPCIGOBK_GADGET_BORN_MONSTER_HIT: LMJBPCIGOBK
LMJBPCIGOBK_GADGET_BORN_MONSTER_DIE: LMJBPCIGOBK
LMJBPCIGOBK_GADGET_BORN_GADGET: LMJBPCIGOBK
LMJBPCIGOBK_GADGET_BORN_GROUND: LMJBPCIGOBK
