from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class LPDKCJCMBFN(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    LPDKCJCMBFN_DUNGEON_ENTRY_REASON_NONE: _ClassVar[LPDKCJCMBFN]
    LPDKCJCMBFN_DUNGEON_ENTRY_REASON_LEVEL: _ClassVar[LPDKCJCMBFN]
    LPDKCJCMBFN_DUNGEON_ENTRY_REASON_QUEST: _ClassVar[LPDKCJCMBFN]
    LPDKCJCMBFN_DUNGEON_ENTRY_REASON_MULIPLE: _ClassVar[LPDKCJCMBFN]
LPDKCJCMBFN_DUNGEON_ENTRY_REASON_NONE: LPDKCJCMBFN
LPDKCJCMBFN_DUNGEON_ENTRY_REASON_LEVEL: LPDKCJCMBFN
LPDKCJCMBFN_DUNGEON_ENTRY_REASON_QUEST: LPDKCJCMBFN
LPDKCJCMBFN_DUNGEON_ENTRY_REASON_MULIPLE: LPDKCJCMBFN
