# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/LunaRiteTakeSacrificeRewardReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9genshin/packet/proto/LunaRiteTakeSacrificeRewardReq.proto\"@\n\x1eLunaRiteTakeSacrificeRewardReq\x12\x0f\n\x07\x61rea_id\x18\x0b \x01(\r\x12\r\n\x05index\x18\x03 \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_LUNARITETAKESACRIFICEREWARDREQ = DESCRIPTOR.message_types_by_name['LunaRiteTakeSacrificeRewardReq']
LunaRiteTakeSacrificeRewardReq = _reflection.GeneratedProtocolMessageType('LunaRiteTakeSacrificeRewardReq', (_message.Message,), {
  'DESCRIPTOR' : _LUNARITETAKESACRIFICEREWARDREQ,
  '__module__' : 'genshin.packet.proto.LunaRiteTakeSacrificeRewardReq_pb2'
  # @@protoc_insertion_point(class_scope:LunaRiteTakeSacrificeRewardReq)
  })
_sym_db.RegisterMessage(LunaRiteTakeSacrificeRewardReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _LUNARITETAKESACRIFICEREWARDREQ._serialized_start=61
  _LUNARITETAKESACRIFICEREWARDREQ._serialized_end=125
# @@protoc_insertion_point(module_scope)
