# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/LunchBoxData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'genshin/packet/proto/LunchBoxData.proto\"\x85\x01\n\x0cLunchBoxData\x12=\n\x11slot_material_map\x18\x03 \x03(\x0b\x32\".LunchBoxData.SlotMaterialMapEntry\x1a\x36\n\x14SlotMaterialMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_LUNCHBOXDATA = DESCRIPTOR.message_types_by_name['LunchBoxData']
_LUNCHBOXDATA_SLOTMATERIALMAPENTRY = _LUNCHBOXDATA.nested_types_by_name['SlotMaterialMapEntry']
LunchBoxData = _reflection.GeneratedProtocolMessageType('LunchBoxData', (_message.Message,), {

  'SlotMaterialMapEntry' : _reflection.GeneratedProtocolMessageType('SlotMaterialMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _LUNCHBOXDATA_SLOTMATERIALMAPENTRY,
    '__module__' : 'genshin.packet.proto.LunchBoxData_pb2'
    # @@protoc_insertion_point(class_scope:LunchBoxData.SlotMaterialMapEntry)
    })
  ,
  'DESCRIPTOR' : _LUNCHBOXDATA,
  '__module__' : 'genshin.packet.proto.LunchBoxData_pb2'
  # @@protoc_insertion_point(class_scope:LunchBoxData)
  })
_sym_db.RegisterMessage(LunchBoxData)
_sym_db.RegisterMessage(LunchBoxData.SlotMaterialMapEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _LUNCHBOXDATA_SLOTMATERIALMAPENTRY._options = None
  _LUNCHBOXDATA_SLOTMATERIALMAPENTRY._serialized_options = b'8\001'
  _LUNCHBOXDATA._serialized_start=44
  _LUNCHBOXDATA._serialized_end=177
  _LUNCHBOXDATA_SLOTMATERIALMAPENTRY._serialized_start=123
  _LUNCHBOXDATA_SLOTMATERIALMAPENTRY._serialized_end=177
# @@protoc_insertion_point(module_scope)
