# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/MailData.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/MailData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import MailTextContent_pb2 as genshin_dot_packet_dot_proto_dot_MailTextContent__pb2
from genshin.packet.proto import MailItem_pb2 as genshin_dot_packet_dot_proto_dot_MailItem__pb2
from genshin.packet.proto import MailCollectState_pb2 as genshin_dot_packet_dot_proto_dot_MailCollectState__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#genshin/packet/proto/MailData.proto\x1a*genshin/packet/proto/MailTextContent.proto\x1a#genshin/packet/proto/MailItem.proto\x1a+genshin/packet/proto/MailCollectState.proto\"\xa2\x02\n\x08MailData\x12\x0f\n\x07mail_id\x18\x01 \x01(\r\x12+\n\x11mail_text_content\x18\x04 \x01(\x0b\x32\x10.MailTextContent\x12\x1c\n\titem_list\x18\x07 \x03(\x0b\x32\t.MailItem\x12\x11\n\tsend_time\x18\x08 \x01(\r\x12\x13\n\x0b\x65xpire_time\x18\t \x01(\r\x12\x12\n\nimportance\x18\n \x01(\r\x12\x0f\n\x07is_read\x18\x0b \x01(\x08\x12\x19\n\x11is_attachment_got\x18\x0c \x01(\x08\x12\x11\n\tconfig_id\x18\r \x01(\r\x12\x15\n\rargument_list\x18\x0e \x03(\t\x12(\n\rcollect_state\x18\x0f \x01(\x0e\x32\x11.MailCollectStateB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.MailData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_MAILDATA']._serialized_start=166
  _globals['_MAILDATA']._serialized_end=456
# @@protoc_insertion_point(module_scope)
