# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/MassiveBoxInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import Vector_pb2 as genshin_dot_packet_dot_proto_dot_Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)genshin/packet/proto/MassiveBoxInfo.proto\x1a!genshin/packet/proto/Vector.proto\"\xa9\x01\n\x0eMassiveBoxInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tconfig_id\x18\x02 \x01(\r\x12\x17\n\x06\x63\x65nter\x18\x03 \x01(\x0b\x32\x07.Vector\x12\x18\n\x07\x65xtents\x18\x04 \x01(\x0b\x32\x07.Vector\x12\x13\n\x02up\x18\x05 \x01(\x0b\x32\x07.Vector\x12\x18\n\x07\x66orward\x18\x06 \x01(\x0b\x32\x07.Vector\x12\x16\n\x05right\x18\x07 \x01(\x0b\x32\x07.VectorB\x16\n\x14org.sorapointa.protob\x06proto3')



_MASSIVEBOXINFO = DESCRIPTOR.message_types_by_name['MassiveBoxInfo']
MassiveBoxInfo = _reflection.GeneratedProtocolMessageType('MassiveBoxInfo', (_message.Message,), {
  'DESCRIPTOR' : _MASSIVEBOXINFO,
  '__module__' : 'genshin.packet.proto.MassiveBoxInfo_pb2'
  # @@protoc_insertion_point(class_scope:MassiveBoxInfo)
  })
_sym_db.RegisterMessage(MassiveBoxInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _MASSIVEBOXINFO._serialized_start=81
  _MASSIVEBOXINFO._serialized_end=250
# @@protoc_insertion_point(module_scope)
