from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class MBIMHNFDGHN(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MBIMHNFDGHN_FORWARD_LOCAL: _ClassVar[MBIMHNFDGHN]
    MBIMHNFDGHN_FORWARD_TO_ALL: _ClassVar[MBIMHNFDGHN]
    MBIMHNFDGHN_FORWARD_TO_ALL_EXCEPT_CUR: _ClassVar[MBIMHNFDGHN]
    MBIMHNFDGHN_FORWARD_TO_HOST: _ClassVar[MBIMHNFDGHN]
    MBIMHNFDGHN_FORWARD_TO_ALL_GUEST: _ClassVar[MBIMHNFDGHN]
    MBIMHNFDGHN_FORWARD_TO_PEER: _ClassVar[MBIMHNFDGHN]
    MBIMHNFDGHN_FORWARD_TO_PEERS: _ClassVar[MBIMHNFDGHN]
    MBIMHNFDGHN_FORWARD_ONLY_SERVER: _ClassVar[MBIMHNFDGHN]
    MBIMHNFDGHN_FORWARD_TO_ALL_EXIST_EXCEPT_CUR: _ClassVar[MBIMHNFDGHN]
MBIMHNFDGHN_FORWARD_LOCAL: MBIMHNFDGHN
MBIMHNFDGHN_FORWARD_TO_ALL: MBIMHNFDGHN
MBIMHNFDGHN_FORWARD_TO_ALL_EXCEPT_CUR: MBIMHNFDGHN
MBIMHNFDGHN_FORWARD_TO_HOST: MBIMHNFDGHN
MBIMHNFDGHN_FORWARD_TO_ALL_GUEST: MBIMHNFDGHN
MBIMHNFDGHN_FORWARD_TO_PEER: MBIMHNFDGHN
MBIMHNFDGHN_FORWARD_TO_PEERS: MBIMHNFDGHN
MBIMHNFDGHN_FORWARD_ONLY_SERVER: MBIMHNFDGHN
MBIMHNFDGHN_FORWARD_TO_ALL_EXIST_EXCEPT_CUR: MBIMHNFDGHN
