from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class MHJJGCMMGLO(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MHJJGCMMGLO_COMPOUND_BOOST_TAKE_STATUS_NONE: _ClassVar[MHJJGCMMGLO]
    MHJJGCMMGLO_COMPOUND_BOOST_TAKE_STATUS_BOOST_ONLY: _ClassVar[MHJJGCMMGLO]
    MHJJGCMMGLO_COMPOUND_BOOST_TAKE_STATUS_BOOST_AND_TAKE: _ClassVar[MHJJGCMMGLO]
    MHJJGCMMGLO_COMPOUND_BOOST_TAKE_STATUS_BAG_FULL: _ClassVar[MHJJGCMMGLO]
MHJJGCMMGLO_COMPOUND_BOOST_TAKE_STATUS_NONE: MHJJGCMMGLO
MHJJGCMMGLO_COMPOUND_BOOST_TAKE_STATUS_BOOST_ONLY: MHJJGCMMGLO
MHJJGCMMGLO_COMPOUND_BOOST_TAKE_STATUS_BOOST_AND_TAKE: MHJJGCMMGLO
MHJJGCMMGLO_COMPOUND_BOOST_TAKE_STATUS_BAG_FULL: MHJJGCMMGLO
