from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class MIHBPFKEMJE(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MIHBPFKEMJE_REGION_SEARCH_NONE: _ClassVar[MIHBPFKEMJE]
    MIHBPFKEMJE_REGION_SEARCH_UNSTARTED: _ClassVar[MIHBPFKEMJE]
    MIHBPFKEMJE_REGION_SEARCH_STARTED: _ClassVar[MIHBPFKEMJE]
    MIHBPFKEMJE_REGION_SEARCH_WAIT_REWARD: _ClassVar[MIHBPFKEMJE]
    MIHBPFKEMJE_REGION_SEARCH_FINISHED: _ClassVar[MIHBPFKEMJE]
MIHBPFKEMJE_REGION_SEARCH_NONE: MIHBPFKEMJE
MIHBPFKEMJE_REGION_SEARCH_UNSTARTED: MIHBPFKEMJE
MIHBPFKEMJE_REGION_SEARCH_STARTED: MIHBPFKEMJE
MIHBPFKEMJE_REGION_SEARCH_WAIT_REWARD: MIHBPFKEMJE
MIHBPFKEMJE_REGION_SEARCH_FINISHED: MIHBPFKEMJE
