from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class MLHHGNPCLGK(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MLHHGNPCLGK_PACMAN_DUNGEON_STOP_NONE: _ClassVar[MLHHGNPCLGK]
    MLHHGNPCLGK_PACMAN_DUNGEON_STOP_SUCCESS: _ClassVar[MLHHGNPCLGK]
    MLHHGNPCLGK_PACMAN_DUNGEON_STOP_TIMEUP: _ClassVar[MLHHGNPCLGK]
    MLHHGNPCLGK_PACMAN_DUNGEON_STOP_CLIENT_INTERRUPT: _ClassVar[MLHHGNPCLGK]
    MLHHGNPCLGK_PACMAN_DUNGEON_STOP_CANCEL: _ClassVar[MLHHGNPCLGK]
    MLHHGNPCLGK_PACMAN_DUNGEON_STOP_ACTIVITY_CLOSED: _ClassVar[MLHHGNPCLGK]
    MLHHGNPCLGK_PACMAN_DUNGEON_STOP_FAIL: _ClassVar[MLHHGNPCLGK]
MLHHGNPCLGK_PACMAN_DUNGEON_STOP_NONE: MLHHGNPCLGK
MLHHGNPCLGK_PACMAN_DUNGEON_STOP_SUCCESS: MLHHGNPCLGK
MLHHGNPCLGK_PACMAN_DUNGEON_STOP_TIMEUP: MLHHGNPCLGK
MLHHGNPCLGK_PACMAN_DUNGEON_STOP_CLIENT_INTERRUPT: MLHHGNPCLGK
MLHHGNPCLGK_PACMAN_DUNGEON_STOP_CANCEL: MLHHGNPCLGK
MLHHGNPCLGK_PACMAN_DUNGEON_STOP_ACTIVITY_CLOSED: MLHHGNPCLGK
MLHHGNPCLGK_PACMAN_DUNGEON_STOP_FAIL: MLHHGNPCLGK
