from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class MNLILCBGKNG(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    MNLILCBGKNG_GCG_DICE_SIDE_INVALID: _ClassVar[MNLILCBGKNG]
    MNLILCBGKNG_GCG_DICE_SIDE_CRYO: _ClassVar[MNLILCBGKNG]
    MNLILCBGKNG_GCG_DICE_SIDE_HYDRO: _ClassVar[MNLILCBGKNG]
    MNLILCBGKNG_GCG_DICE_SIDE_PYRO: _ClassVar[MNLILCBGKNG]
    MNLILCBGKNG_GCG_DICE_SIDE_ELECTRO: _ClassVar[MNLILCBGKNG]
    MNLILCBGKNG_GCG_DICE_SIDE_GEO: _ClassVar[MNLILCBGKNG]
    MNLILCBGKNG_GCG_DICE_SIDE_DENDRO: _ClassVar[MNLILCBGKNG]
    MNLILCBGKNG_GCG_DICE_SIDE_ANEMO: _ClassVar[MNLILCBGKNG]
    MNLILCBGKNG_GCG_DICE_SIDE_PAIMON: _ClassVar[MNLILCBGKNG]
MNLILCBGKNG_GCG_DICE_SIDE_INVALID: MNLILCBGKNG
MNLILCBGKNG_GCG_DICE_SIDE_CRYO: MNLILCBGKNG
MNLILCBGKNG_GCG_DICE_SIDE_HYDRO: MNLILCBGKNG
MNLILCBGKNG_GCG_DICE_SIDE_PYRO: MNLILCBGKNG
MNLILCBGKNG_GCG_DICE_SIDE_ELECTRO: MNLILCBGKNG
MNLILCBGKNG_GCG_DICE_SIDE_GEO: MNLILCBGKNG
MNLILCBGKNG_GCG_DICE_SIDE_DENDRO: MNLILCBGKNG
MNLILCBGKNG_GCG_DICE_SIDE_ANEMO: MNLILCBGKNG
MNLILCBGKNG_GCG_DICE_SIDE_PAIMON: MNLILCBGKNG
