# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/MpPlayPrepareNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/MpPlayPrepareNotify.proto\"C\n\x13MpPlayPrepareNotify\x12\x12\n\nmp_play_id\x18\t \x01(\r\x12\x18\n\x10prepare_end_time\x18\x0b \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_MPPLAYPREPARENOTIFY = DESCRIPTOR.message_types_by_name['MpPlayPrepareNotify']
MpPlayPrepareNotify = _reflection.GeneratedProtocolMessageType('MpPlayPrepareNotify', (_message.Message,), {
  'DESCRIPTOR' : _MPPLAYPREPARENOTIFY,
  '__module__' : 'genshin.packet.proto.MpPlayPrepareNotify_pb2'
  # @@protoc_insertion_point(class_scope:MpPlayPrepareNotify)
  })
_sym_db.RegisterMessage(MpPlayPrepareNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _MPPLAYPREPARENOTIFY._serialized_start=50
  _MPPLAYPREPARENOTIFY._serialized_end=117
# @@protoc_insertion_point(module_scope)
