# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/MultistagePlayInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import HideAndSeekStageInfo_pb2 as genshin_dot_packet_dot_proto_dot_HideAndSeekStageInfo__pb2
from genshin.packet.proto import InBattleChessInfo_pb2 as genshin_dot_packet_dot_proto_dot_InBattleChessInfo__pb2
from genshin.packet.proto import InBattleFleurFairInfo_pb2 as genshin_dot_packet_dot_proto_dot_InBattleFleurFairInfo__pb2
from genshin.packet.proto import InBattleMechanicusInfo_pb2 as genshin_dot_packet_dot_proto_dot_InBattleMechanicusInfo__pb2
from genshin.packet.proto import IrodoriChessInfo_pb2 as genshin_dot_packet_dot_proto_dot_IrodoriChessInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-genshin/packet/proto/MultistagePlayInfo.proto\x1a/genshin/packet/proto/HideAndSeekStageInfo.proto\x1a,genshin/packet/proto/InBattleChessInfo.proto\x1a\x30genshin/packet/proto/InBattleFleurFairInfo.proto\x1a\x31genshin/packet/proto/InBattleMechanicusInfo.proto\x1a+genshin/packet/proto/IrodoriChessInfo.proto\"\xa1\x03\n\x12MultistagePlayInfo\x12\x12\n\nplay_index\x18\r \x01(\r\x12\x11\n\tplay_type\x18\x0b \x01(\r\x12\x12\n\nstage_type\x18\n \x01(\r\x12\x10\n\x08\x64uration\x18\x08 \x01(\r\x12\x10\n\x08group_id\x18\x0c \x01(\r\x12\x12\n\nbegin_time\x18\t \x01(\r\x12\x13\n\x0bstage_index\x18\x01 \x01(\r\x12\x33\n\x0fmechanicus_info\x18\xb6\n \x01(\x0b\x32\x17.InBattleMechanicusInfoH\x00\x12\x32\n\x0f\x66leur_fair_info\x18\xa8\x08 \x01(\x0b\x32\x16.InBattleFleurFairInfoH\x00\x12\x33\n\x12hide_and_seek_info\x18l \x01(\x0b\x32\x15.HideAndSeekStageInfoH\x00\x12)\n\nchess_info\x18\xde\r \x01(\x0b\x32\x12.InBattleChessInfoH\x00\x12\x30\n\x12irodori_chess_info\x18\x93\x04 \x01(\x0b\x32\x11.IrodoriChessInfoH\x00\x42\x08\n\x06\x64\x65tailB\x16\n\x14org.sorapointa.protob\x06proto3')



_MULTISTAGEPLAYINFO = DESCRIPTOR.message_types_by_name['MultistagePlayInfo']
MultistagePlayInfo = _reflection.GeneratedProtocolMessageType('MultistagePlayInfo', (_message.Message,), {
  'DESCRIPTOR' : _MULTISTAGEPLAYINFO,
  '__module__' : 'genshin.packet.proto.MultistagePlayInfo_pb2'
  # @@protoc_insertion_point(class_scope:MultistagePlayInfo)
  })
_sym_db.RegisterMessage(MultistagePlayInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _MULTISTAGEPLAYINFO._serialized_start=291
  _MULTISTAGEPLAYINFO._serialized_end=708
# @@protoc_insertion_point(module_scope)
