# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/MusicGameGetBeatmapReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import MusicGameUnknown2Enum_pb2 as genshin_dot_packet_dot_proto_dot_MusicGameUnknown2Enum__pb2
from genshin.packet.proto import MusicGameGetBeatmapReqType_pb2 as genshin_dot_packet_dot_proto_dot_MusicGameGetBeatmapReqType__pb2
from genshin.packet.proto import MusicGameUnknown1Enum_pb2 as genshin_dot_packet_dot_proto_dot_MusicGameUnknown1Enum__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1genshin/packet/proto/MusicGameGetBeatmapReq.proto\x1a\x30genshin/packet/proto/MusicGameUnknown2Enum.proto\x1a\x35genshin/packet/proto/MusicGameGetBeatmapReqType.proto\x1a\x30genshin/packet/proto/MusicGameUnknown1Enum.proto\"\xd2\x01\n\x16MusicGameGetBeatmapReq\x12-\n\runknown_enum1\x18\x01 \x01(\x0e\x32\x16.MusicGameUnknown1Enum\x12\x16\n\x0emusic_share_id\x18\n \x01(\x04\x12-\n\runknown_enum2\x18\x0c \x01(\x0e\x32\x16.MusicGameUnknown2Enum\x12\x13\n\x0b\x43\x44\x46OGGDLKNA\x18\x0f \x01(\x08\x12-\n\x08req_type\x18\x0b \x01(\x0e\x32\x1b.MusicGameGetBeatmapReqTypeB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')



_MUSICGAMEGETBEATMAPREQ = DESCRIPTOR.message_types_by_name['MusicGameGetBeatmapReq']
MusicGameGetBeatmapReq = _reflection.GeneratedProtocolMessageType('MusicGameGetBeatmapReq', (_message.Message,), {
  'DESCRIPTOR' : _MUSICGAMEGETBEATMAPREQ,
  '__module__' : 'genshin.packet.proto.MusicGameGetBeatmapReq_pb2'
  # @@protoc_insertion_point(class_scope:MusicGameGetBeatmapReq)
  })
_sym_db.RegisterMessage(MusicGameGetBeatmapReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _MUSICGAMEGETBEATMAPREQ._serialized_start=209
  _MUSICGAMEGETBEATMAPREQ._serialized_end=419
# @@protoc_insertion_point(module_scope)
