# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/NavMeshStatsNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import PbNavMeshStatsInfo_pb2 as genshin_dot_packet_dot_proto_dot_PbNavMeshStatsInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-genshin/packet/proto/NavMeshStatsNotify.proto\x1a-genshin/packet/proto/PbNavMeshStatsInfo.proto\"8\n\x12NavMeshStatsNotify\x12\"\n\x05infos\x18\x04 \x03(\x0b\x32\x13.PbNavMeshStatsInfoB\x16\n\x14org.sorapointa.protob\x06proto3')



_NAVMESHSTATSNOTIFY = DESCRIPTOR.message_types_by_name['NavMeshStatsNotify']
NavMeshStatsNotify = _reflection.GeneratedProtocolMessageType('NavMeshStatsNotify', (_message.Message,), {
  'DESCRIPTOR' : _NAVMESHSTATSNOTIFY,
  '__module__' : 'genshin.packet.proto.NavMeshStatsNotify_pb2'
  # @@protoc_insertion_point(class_scope:NavMeshStatsNotify)
  })
_sym_db.RegisterMessage(NavMeshStatsNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _NAVMESHSTATSNOTIFY._serialized_start=96
  _NAVMESHSTATSNOTIFY._serialized_end=152
# @@protoc_insertion_point(module_scope)
