from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class NDBDLEKNHMF(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    NDBDLEKNHMF_CODEX_NONE: _ClassVar[NDBDLEKNHMF]
    NDBDLEKNHMF_CODEX_QUEST: _ClassVar[NDBDLEKNHMF]
    NDBDLEKNHMF_CODEX_WEAPON: _ClassVar[NDBDLEKNHMF]
    NDBDLEKNHMF_CODEX_ANIMAL: _ClassVar[NDBDLEKNHMF]
    NDBDLEKNHMF_CODEX_MATERIAL: _ClassVar[NDBDLEKNHMF]
    NDBDLEKNHMF_CODEX_BOOKS: _ClassVar[NDBDLEKNHMF]
    NDBDLEKNHMF_CODEX_PUSHTIPS: _ClassVar[NDBDLEKNHMF]
    NDBDLEKNHMF_CODEX_VIEW: _ClassVar[NDBDLEKNHMF]
    NDBDLEKNHMF_CODEX_RELIQUARY: _ClassVar[NDBDLEKNHMF]
NDBDLEKNHMF_CODEX_NONE: NDBDLEKNHMF
NDBDLEKNHMF_CODEX_QUEST: NDBDLEKNHMF
NDBDLEKNHMF_CODEX_WEAPON: NDBDLEKNHMF
NDBDLEKNHMF_CODEX_ANIMAL: NDBDLEKNHMF
NDBDLEKNHMF_CODEX_MATERIAL: NDBDLEKNHMF
NDBDLEKNHMF_CODEX_BOOKS: NDBDLEKNHMF
NDBDLEKNHMF_CODEX_PUSHTIPS: NDBDLEKNHMF
NDBDLEKNHMF_CODEX_VIEW: NDBDLEKNHMF
NDBDLEKNHMF_CODEX_RELIQUARY: NDBDLEKNHMF
