from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class NFONHFAMDNE(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    NFONHFAMDNE_EDITOR: _ClassVar[NFONHFAMDNE]
    NFONHFAMDNE_IOS: _ClassVar[NFONHFAMDNE]
    NFONHFAMDNE_ANDROID: _ClassVar[NFONHFAMDNE]
    NFONHFAMDNE_PC: _ClassVar[NFONHFAMDNE]
    NFONHFAMDNE_PS4: _ClassVar[NFONHFAMDNE]
    NFONHFAMDNE_SERVER: _ClassVar[NFONHFAMDNE]
    NFONHFAMDNE_CLOUD_ANDROID: _ClassVar[NFONHFAMDNE]
    NFONHFAMDNE_CLOUD_IOS: _ClassVar[NFONHFAMDNE]
    NFONHFAMDNE_PS5: _ClassVar[NFONHFAMDNE]
    NFONHFAMDNE_CLOUD_WEB: _ClassVar[NFONHFAMDNE]
    NFONHFAMDNE_CLOUD_TV: _ClassVar[NFONHFAMDNE]
    NFONHFAMDNE_CLOUD_MAC: _ClassVar[NFONHFAMDNE]
    NFONHFAMDNE_CLOUD_PC: _ClassVar[NFONHFAMDNE]
    NFONHFAMDNE_CLOUD_THIRD_PARTY_MOBILE: _ClassVar[NFONHFAMDNE]
    NFONHFAMDNE_CLOUD_THIRD_PARTY_PC: _ClassVar[NFONHFAMDNE]
    NFONHFAMDNE_CLOUD_WEB_ANDROID: _ClassVar[NFONHFAMDNE]
    NFONHFAMDNE_CLOUD_WEB_IOS: _ClassVar[NFONHFAMDNE]
    NFONHFAMDNE_CLOUD_WEB_PC: _ClassVar[NFONHFAMDNE]
    NFONHFAMDNE_CLOUD_WEB_MAC: _ClassVar[NFONHFAMDNE]
    NFONHFAMDNE_CLOUD_WEB_TOUCH: _ClassVar[NFONHFAMDNE]
    NFONHFAMDNE_CLOUD_WEB_KEYBOARD: _ClassVar[NFONHFAMDNE]
    NFONHFAMDNE_XBOX_SCARLETT: _ClassVar[NFONHFAMDNE]
NFONHFAMDNE_EDITOR: NFONHFAMDNE
NFONHFAMDNE_IOS: NFONHFAMDNE
NFONHFAMDNE_ANDROID: NFONHFAMDNE
NFONHFAMDNE_PC: NFONHFAMDNE
NFONHFAMDNE_PS4: NFONHFAMDNE
NFONHFAMDNE_SERVER: NFONHFAMDNE
NFONHFAMDNE_CLOUD_ANDROID: NFONHFAMDNE
NFONHFAMDNE_CLOUD_IOS: NFONHFAMDNE
NFONHFAMDNE_PS5: NFONHFAMDNE
NFONHFAMDNE_CLOUD_WEB: NFONHFAMDNE
NFONHFAMDNE_CLOUD_TV: NFONHFAMDNE
NFONHFAMDNE_CLOUD_MAC: NFONHFAMDNE
NFONHFAMDNE_CLOUD_PC: NFONHFAMDNE
NFONHFAMDNE_CLOUD_THIRD_PARTY_MOBILE: NFONHFAMDNE
NFONHFAMDNE_CLOUD_THIRD_PARTY_PC: NFONHFAMDNE
NFONHFAMDNE_CLOUD_WEB_ANDROID: NFONHFAMDNE
NFONHFAMDNE_CLOUD_WEB_IOS: NFONHFAMDNE
NFONHFAMDNE_CLOUD_WEB_PC: NFONHFAMDNE
NFONHFAMDNE_CLOUD_WEB_MAC: NFONHFAMDNE
NFONHFAMDNE_CLOUD_WEB_TOUCH: NFONHFAMDNE
NFONHFAMDNE_CLOUD_WEB_KEYBOARD: NFONHFAMDNE
NFONHFAMDNE_XBOX_SCARLETT: NFONHFAMDNE
