# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/NKHBPGHFLNN.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/NKHBPGHFLNN.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/NKHBPGHFLNN.proto\"\x8b\x01\n\x0bNKHBPGHFLNN\x12\x13\n\x0b\x45PFPAMGGPHK\x18\x02 \x03(\x04\x12\x13\n\x0bIPBOJDIJFKE\x18\x08 \x03(\x04\x12\x13\n\x0b\x41LNMCFGJNPE\x18\n \x01(\x04\x12\x13\n\x0bOAJOOBGHAGM\x18\x05 \x01(\r\x12\x13\n\x0bOACIPABKFNP\x18\x0e \x01(\r\x12\x13\n\x0b\x45JNINFFFKJP\x18\x06 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.NKHBPGHFLNN_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NKHBPGHFLNN']._serialized_start=43
  _globals['_NKHBPGHFLNN']._serialized_end=182
# @@protoc_insertion_point(module_scope)
