from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class NKKKBOHMANL(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    NKKKBOHMANL_FOUNDATION_OP_NONE: _ClassVar[NKKKBOHMANL]
    NKKKBOHMANL_FOUNDATION_OP_BUILD: _ClassVar[NKKKBOHMANL]
    NKKKBOHMANL_FOUNDATION_OP_DEMOLITION: _ClassVar[NKKKBOHMANL]
    NKKKBOHMANL_FOUNDATION_OP_REBUILD: _ClassVar[NKKKBOHMANL]
    NKKKBOHMANL_FOUNDATION_OP_ROTATE: _ClassVar[NKKKBOHMANL]
    NKKKBOHMANL_FOUNDATION_OP_LOCK: _ClassVar[NKKKBOHMANL]
    NKKKBOHMANL_FOUNDATION_OP_UNLOCK: _ClassVar[NKKKBOHMANL]
NKKKBOHMANL_FOUNDATION_OP_NONE: NKKKBOHMANL
NKKKBOHMANL_FOUNDATION_OP_BUILD: NKKKBOHMANL
NKKKBOHMANL_FOUNDATION_OP_DEMOLITION: NKKKBOHMANL
NKKKBOHMANL_FOUNDATION_OP_REBUILD: NKKKBOHMANL
NKKKBOHMANL_FOUNDATION_OP_ROTATE: NKKKBOHMANL
NKKKBOHMANL_FOUNDATION_OP_LOCK: NKKKBOHMANL
NKKKBOHMANL_FOUNDATION_OP_UNLOCK: NKKKBOHMANL
