from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class NLOBHEMPBEM(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    NLOBHEMPBEM_GCG_GAME_NONE: _ClassVar[NLOBHEMPBEM]
    NLOBHEMPBEM_GCG_GAME_GM: _ClassVar[NLOBHEMPBEM]
    NLOBHEMPBEM_GCG_GAME_MATCH: _ClassVar[NLOBHEMPBEM]
    NLOBHEMPBEM_GCG_GAME_PVP: _ClassVar[NLOBHEMPBEM]
    NLOBHEMPBEM_GCG_GAME_TAVERN_CHALLENGE: _ClassVar[NLOBHEMPBEM]
    NLOBHEMPBEM_GCG_GAME_CONST_CHALLENGE: _ClassVar[NLOBHEMPBEM]
    NLOBHEMPBEM_GCG_GAME_WORLD_CHALLENGE: _ClassVar[NLOBHEMPBEM]
    NLOBHEMPBEM_GCG_GAME_BOSS_CHALLENGE: _ClassVar[NLOBHEMPBEM]
    NLOBHEMPBEM_GCG_GAME_WEEK_CHALLENGE: _ClassVar[NLOBHEMPBEM]
    NLOBHEMPBEM_GCG_GAME_BREAK_CHALLENGE: _ClassVar[NLOBHEMPBEM]
    NLOBHEMPBEM_GCG_GAME_QUEST: _ClassVar[NLOBHEMPBEM]
    NLOBHEMPBEM_GCG_GAME_GUIDE_GROUP: _ClassVar[NLOBHEMPBEM]
    NLOBHEMPBEM_GCG_GAME_OTHER: _ClassVar[NLOBHEMPBEM]
    NLOBHEMPBEM_GCG_GAME_ACTIVITY_JOURNEY: _ClassVar[NLOBHEMPBEM]
    NLOBHEMPBEM_GCG_GAME_PVE_ACTIVITY: _ClassVar[NLOBHEMPBEM]
    NLOBHEMPBEM_GCG_GAME_ARENA: _ClassVar[NLOBHEMPBEM]
    NLOBHEMPBEM_GCG_GAME_ACTIVITY_PVE_INFINITE: _ClassVar[NLOBHEMPBEM]
    NLOBHEMPBEM_GCG_GAME_ACTIVITY_PVE_PUZZLE: _ClassVar[NLOBHEMPBEM]
    NLOBHEMPBEM_GCG_GAME_ACTIVITY_PVE_AUTO_BATTLE_CARD: _ClassVar[NLOBHEMPBEM]
NLOBHEMPBEM_GCG_GAME_NONE: NLOBHEMPBEM
NLOBHEMPBEM_GCG_GAME_GM: NLOBHEMPBEM
NLOBHEMPBEM_GCG_GAME_MATCH: NLOBHEMPBEM
NLOBHEMPBEM_GCG_GAME_PVP: NLOBHEMPBEM
NLOBHEMPBEM_GCG_GAME_TAVERN_CHALLENGE: NLOBHEMPBEM
NLOBHEMPBEM_GCG_GAME_CONST_CHALLENGE: NLOBHEMPBEM
NLOBHEMPBEM_GCG_GAME_WORLD_CHALLENGE: NLOBHEMPBEM
NLOBHEMPBEM_GCG_GAME_BOSS_CHALLENGE: NLOBHEMPBEM
NLOBHEMPBEM_GCG_GAME_WEEK_CHALLENGE: NLOBHEMPBEM
NLOBHEMPBEM_GCG_GAME_BREAK_CHALLENGE: NLOBHEMPBEM
NLOBHEMPBEM_GCG_GAME_QUEST: NLOBHEMPBEM
NLOBHEMPBEM_GCG_GAME_GUIDE_GROUP: NLOBHEMPBEM
NLOBHEMPBEM_GCG_GAME_OTHER: NLOBHEMPBEM
NLOBHEMPBEM_GCG_GAME_ACTIVITY_JOURNEY: NLOBHEMPBEM
NLOBHEMPBEM_GCG_GAME_PVE_ACTIVITY: NLOBHEMPBEM
NLOBHEMPBEM_GCG_GAME_ARENA: NLOBHEMPBEM
NLOBHEMPBEM_GCG_GAME_ACTIVITY_PVE_INFINITE: NLOBHEMPBEM
NLOBHEMPBEM_GCG_GAME_ACTIVITY_PVE_PUZZLE: NLOBHEMPBEM
NLOBHEMPBEM_GCG_GAME_ACTIVITY_PVE_AUTO_BATTLE_CARD: NLOBHEMPBEM
