from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class OAMHIHBHIKN(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    OAMHIHBHIKN_NONE: _ClassVar[OAMHIHBHIKN]
    OAMHIHBHIKN_INIT: _ClassVar[OAMHIHBHIKN]
    OAMHIHBHIKN_LEVEL_REWARD: _ClassVar[OAMHIHBHIKN]
    OAMHIHBHIKN_CARD_COST: _ClassVar[OAMHIHBHIKN]
    OAMHIHBHIKN_CHANCE_EFFECT: _ClassVar[OAMHIHBHIKN]
    OAMHIHBHIKN_GM: _ClassVar[OAMHIHBHIKN]
    OAMHIHBHIKN_BONUS_REBATE: _ClassVar[OAMHIHBHIKN]
OAMHIHBHIKN_NONE: OAMHIHBHIKN
OAMHIHBHIKN_INIT: OAMHIHBHIKN
OAMHIHBHIKN_LEVEL_REWARD: OAMHIHBHIKN
OAMHIHBHIKN_CARD_COST: OAMHIHBHIKN
OAMHIHBHIKN_CHANCE_EFFECT: OAMHIHBHIKN
OAMHIHBHIKN_GM: OAMHIHBHIKN
OAMHIHBHIKN_BONUS_REBATE: OAMHIHBHIKN
