from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class OBBKCBAKKGH(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    OBBKCBAKKGH_FIREWORKS_REFORM_PARAM_NONE: _ClassVar[OBBKCBAKKGH]
    OBBKCBAKKGH_FIREWORKS_REFORM_PARAM_COLOR: _ClassVar[OBBKCBAKKGH]
    OBBKCBAKKGH_FIREWORKS_REFORM_PARAM_HEIGHT: _ClassVar[OBBKCBAKKGH]
    OBBKCBAKKGH_FIREWORKS_REFORM_PARAM_SIZE: _ClassVar[OBBKCBAKKGH]
    OBBKCBAKKGH_FIREWORKS_REFORM_PARAM_DENSITY: _ClassVar[OBBKCBAKKGH]
    OBBKCBAKKGH_FIREWORKS_REFORM_PARAM_ROTATION: _ClassVar[OBBKCBAKKGH]
OBBKCBAKKGH_FIREWORKS_REFORM_PARAM_NONE: OBBKCBAKKGH
OBBKCBAKKGH_FIREWORKS_REFORM_PARAM_COLOR: OBBKCBAKKGH
OBBKCBAKKGH_FIREWORKS_REFORM_PARAM_HEIGHT: OBBKCBAKKGH
OBBKCBAKKGH_FIREWORKS_REFORM_PARAM_SIZE: OBBKCBAKKGH
OBBKCBAKKGH_FIREWORKS_REFORM_PARAM_DENSITY: OBBKCBAKKGH
OBBKCBAKKGH_FIREWORKS_REFORM_PARAM_ROTATION: OBBKCBAKKGH
