# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/ObstacleInfo.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/ObstacleInfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import ShapeType_pb2 as genshin_dot_packet_dot_proto_dot_ShapeType__pb2
from genshin.packet.proto import MathQuaternion_pb2 as genshin_dot_packet_dot_proto_dot_MathQuaternion__pb2
from genshin.packet.proto import Vector3Int_pb2 as genshin_dot_packet_dot_proto_dot_Vector3Int__pb2
from genshin.packet.proto import Vector_pb2 as genshin_dot_packet_dot_proto_dot_Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'genshin/packet/proto/ObstacleInfo.proto\x1a$genshin/packet/proto/ShapeType.proto\x1a)genshin/packet/proto/MathQuaternion.proto\x1a%genshin/packet/proto/Vector3Int.proto\x1a!genshin/packet/proto/Vector.proto\"\x98\x01\n\x0cObstacleInfo\x12\x19\n\x05shape\x18\x04 \x01(\x0e\x32\n.ShapeType\x12!\n\x08rotation\x18\x05 \x01(\x0b\x32\x0f.MathQuaternion\x12\x1c\n\x07\x65xtents\x18\x06 \x01(\x0b\x32\x0b.Vector3Int\x12\x13\n\x0bobstacle_id\x18\x0c \x01(\x05\x12\x17\n\x06\x63\x65nter\x18\r \x01(\x0b\x32\x07.VectorB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.ObstacleInfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_OBSTACLEINFO']._serialized_start=199
  _globals['_OBSTACLEINFO']._serialized_end=351
# @@protoc_insertion_point(module_scope)
