# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/OFELNADBNKC.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/OFELNADBNKC.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import PPAICMKDNEI_pb2 as genshin_dot_packet_dot_proto_dot_PPAICMKDNEI__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/OFELNADBNKC.proto\x1a&genshin/packet/proto/PPAICMKDNEI.proto\"\x99\x01\n\x0bOFELNADBNKC\x12\x13\n\x0b\x45PFCIDIKLKG\x18\x04 \x01(\r\x12\x13\n\x0b\x41JMMAEEGJEA\x18\n \x01(\r\x12\x13\n\x0b\x43JPDFHODJGO\x18\t \x01(\r\x12!\n\x0bPOGDPFNPMDB\x18\x0b \x01(\x0e\x32\x0c.PPAICMKDNEI\x12\x13\n\x0bHLBECOIBPBP\x18\x08 \x01(\r\x12\x13\n\x0bMHENBJCACME\x18\x0f \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.OFELNADBNKC_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OFELNADBNKC']._serialized_start=83
  _globals['_OFELNADBNKC']._serialized_end=236
# @@protoc_insertion_point(module_scope)
