from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class OHJPBJBAFNJ(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    OHJPBJBAFNJ_WIND_FIELD_DUNGEON_FAIL_NONE: _ClassVar[OHJPBJBAFNJ]
    OHJPBJBAFNJ_WIND_FIELD_DUNGEON_FAIL_CANCEL: _ClassVar[OHJPBJBAFNJ]
    OHJPBJBAFNJ_WIND_FIELD_DUNGEON_FAIL_TIMEOUT: _ClassVar[OHJPBJBAFNJ]
    OHJPBJBAFNJ_WIND_FIELD_DUNGEON_FAIL_ALL_AVATAR_DIE: _ClassVar[OHJPBJBAFNJ]
    OHJPBJBAFNJ_WIND_FIELD_DUNGEON_FAIL_LUA_INTERRUPT: _ClassVar[OHJPBJBAFNJ]
OHJPBJBAFNJ_WIND_FIELD_DUNGEON_FAIL_NONE: OHJPBJBAFNJ
OHJPBJBAFNJ_WIND_FIELD_DUNGEON_FAIL_CANCEL: OHJPBJBAFNJ
OHJPBJBAFNJ_WIND_FIELD_DUNGEON_FAIL_TIMEOUT: OHJPBJBAFNJ
OHJPBJBAFNJ_WIND_FIELD_DUNGEON_FAIL_ALL_AVATAR_DIE: OHJPBJBAFNJ
OHJPBJBAFNJ_WIND_FIELD_DUNGEON_FAIL_LUA_INTERRUPT: OHJPBJBAFNJ
