# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/OIPLMJPLEBG.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/OIPLMJPLEBG.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/OIPLMJPLEBG.proto\"\x8b\x01\n\x0bOIPLMJPLEBG\x12\x13\n\x0b\x43\x42POHHKKBGO\x18\x07 \x01(\r\x12\x13\n\x0b\x44PDDFIJIOLN\x18\t \x01(\r\x12\x13\n\x0bHCMCEGIHLBA\x18\x04 \x01(\r\x12\x13\n\x0bOAICFBDHDHJ\x18\x03 \x01(\r\x12\x13\n\x0b\x43\x44GFMJBOFAA\x18\x05 \x01(\x02\x12\x13\n\x0bHADJFBNJMFO\x18\x0f \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.OIPLMJPLEBG_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OIPLMJPLEBG']._serialized_start=43
  _globals['_OIPLMJPLEBG']._serialized_end=182
# @@protoc_insertion_point(module_scope)
