from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class OJNEPIECHHJ(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    OJNEPIECHHJ_VISION_NONE: _ClassVar[OJNEPIECHHJ]
    OJNEPIECHHJ_VISION_MEET: _ClassVar[OJNEPIECHHJ]
    OJNEPIECHHJ_VISION_REBORN: _ClassVar[OJNEPIECHHJ]
    OJNEPIECHHJ_VISION_REPLACE: _ClassVar[OJNEPIECHHJ]
    OJNEPIECHHJ_VISION_WAYPOINT_REBORN: _ClassVar[OJNEPIECHHJ]
    OJNEPIECHHJ_VISION_MISS: _ClassVar[OJNEPIECHHJ]
    OJNEPIECHHJ_VISION_DIE: _ClassVar[OJNEPIECHHJ]
    OJNEPIECHHJ_VISION_GATHER_ESCAPE: _ClassVar[OJNEPIECHHJ]
    OJNEPIECHHJ_VISION_REFRESH: _ClassVar[OJNEPIECHHJ]
    OJNEPIECHHJ_VISION_TRANSPORT: _ClassVar[OJNEPIECHHJ]
    OJNEPIECHHJ_VISION_REPLACE_DIE: _ClassVar[OJNEPIECHHJ]
    OJNEPIECHHJ_VISION_REPLACE_NO_NOTIFY: _ClassVar[OJNEPIECHHJ]
    OJNEPIECHHJ_VISION_BORN: _ClassVar[OJNEPIECHHJ]
    OJNEPIECHHJ_VISION_PICKUP: _ClassVar[OJNEPIECHHJ]
    OJNEPIECHHJ_VISION_REMOVE: _ClassVar[OJNEPIECHHJ]
    OJNEPIECHHJ_VISION_CHANGE_COSTUME: _ClassVar[OJNEPIECHHJ]
    OJNEPIECHHJ_VISION_FISH_REFRESH: _ClassVar[OJNEPIECHHJ]
    OJNEPIECHHJ_VISION_FISH_BIG_SHOCK: _ClassVar[OJNEPIECHHJ]
    OJNEPIECHHJ_VISION_FISH_QTE_SUCC: _ClassVar[OJNEPIECHHJ]
    OJNEPIECHHJ_VISION_CAPTURE_DISAPPEAR: _ClassVar[OJNEPIECHHJ]
OJNEPIECHHJ_VISION_NONE: OJNEPIECHHJ
OJNEPIECHHJ_VISION_MEET: OJNEPIECHHJ
OJNEPIECHHJ_VISION_REBORN: OJNEPIECHHJ
OJNEPIECHHJ_VISION_REPLACE: OJNEPIECHHJ
OJNEPIECHHJ_VISION_WAYPOINT_REBORN: OJNEPIECHHJ
OJNEPIECHHJ_VISION_MISS: OJNEPIECHHJ
OJNEPIECHHJ_VISION_DIE: OJNEPIECHHJ
OJNEPIECHHJ_VISION_GATHER_ESCAPE: OJNEPIECHHJ
OJNEPIECHHJ_VISION_REFRESH: OJNEPIECHHJ
OJNEPIECHHJ_VISION_TRANSPORT: OJNEPIECHHJ
OJNEPIECHHJ_VISION_REPLACE_DIE: OJNEPIECHHJ
OJNEPIECHHJ_VISION_REPLACE_NO_NOTIFY: OJNEPIECHHJ
OJNEPIECHHJ_VISION_BORN: OJNEPIECHHJ
OJNEPIECHHJ_VISION_PICKUP: OJNEPIECHHJ
OJNEPIECHHJ_VISION_REMOVE: OJNEPIECHHJ
OJNEPIECHHJ_VISION_CHANGE_COSTUME: OJNEPIECHHJ
OJNEPIECHHJ_VISION_FISH_REFRESH: OJNEPIECHHJ
OJNEPIECHHJ_VISION_FISH_BIG_SHOCK: OJNEPIECHHJ
OJNEPIECHHJ_VISION_FISH_QTE_SUCC: OJNEPIECHHJ
OJNEPIECHHJ_VISION_CAPTURE_DISAPPEAR: OJNEPIECHHJ
