from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class OKACIFDIMDE(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    OKACIFDIMDE_SALVAGE_ESCORT_STOP_NONE: _ClassVar[OKACIFDIMDE]
    OKACIFDIMDE_SALVAGE_ESCORT_STOP_SUCCESS: _ClassVar[OKACIFDIMDE]
    OKACIFDIMDE_SALVAGE_ESCORT_STOP_DUMP: _ClassVar[OKACIFDIMDE]
    OKACIFDIMDE_SALVAGE_ESCORT_STOP_TIME: _ClassVar[OKACIFDIMDE]
    OKACIFDIMDE_SALVAGE_ESCORT_STOP_INTERRUPT: _ClassVar[OKACIFDIMDE]
    OKACIFDIMDE_SALVAGE_ESCORT_STOP_LEAVE: _ClassVar[OKACIFDIMDE]
    OKACIFDIMDE_SALVAGE_ESCORT_STOP_FULL: _ClassVar[OKACIFDIMDE]
OKACIFDIMDE_SALVAGE_ESCORT_STOP_NONE: OKACIFDIMDE
OKACIFDIMDE_SALVAGE_ESCORT_STOP_SUCCESS: OKACIFDIMDE
OKACIFDIMDE_SALVAGE_ESCORT_STOP_DUMP: OKACIFDIMDE
OKACIFDIMDE_SALVAGE_ESCORT_STOP_TIME: OKACIFDIMDE
OKACIFDIMDE_SALVAGE_ESCORT_STOP_INTERRUPT: OKACIFDIMDE
OKACIFDIMDE_SALVAGE_ESCORT_STOP_LEAVE: OKACIFDIMDE
OKACIFDIMDE_SALVAGE_ESCORT_STOP_FULL: OKACIFDIMDE
