from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class OLODDMHDDGC(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    OLODDMHDDGC_NONE: _ClassVar[OLODDMHDDGC]
    OLODDMHDDGC_GIVEUP: _ClassVar[OLODDMHDDGC]
    OLODDMHDDGC_TIMEOUT: _ClassVar[OLODDMHDDGC]
    OLODDMHDDGC_LEAVE_REGION: _ClassVar[OLODDMHDDGC]
    OLODDMHDDGC_LEAVE_SCENE: _ClassVar[OLODDMHDDGC]
    OLODDMHDDGC_CROSS_WEEK: _ClassVar[OLODDMHDDGC]
    OLODDMHDDGC_AVATAR_DIE: _ClassVar[OLODDMHDDGC]
OLODDMHDDGC_NONE: OLODDMHDDGC
OLODDMHDDGC_GIVEUP: OLODDMHDDGC
OLODDMHDDGC_TIMEOUT: OLODDMHDDGC
OLODDMHDDGC_LEAVE_REGION: OLODDMHDDGC
OLODDMHDDGC_LEAVE_SCENE: OLODDMHDDGC
OLODDMHDDGC_CROSS_WEEK: OLODDMHDDGC
OLODDMHDDGC_AVATAR_DIE: OLODDMHDDGC
