# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/OMHJKMMDJEO.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/OMHJKMMDJEO.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import LFBOPOGGBPM_pb2 as genshin_dot_packet_dot_proto_dot_LFBOPOGGBPM__pb2
from genshin.packet.proto import BNGCIFIKLLO_pb2 as genshin_dot_packet_dot_proto_dot_BNGCIFIKLLO__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/OMHJKMMDJEO.proto\x1a&genshin/packet/proto/LFBOPOGGBPM.proto\x1a&genshin/packet/proto/BNGCIFIKLLO.proto\"h\n\x0bOMHJKMMDJEO\x12\x13\n\x0bKNJFLAJMAJJ\x18\x03 \x03(\r\x12!\n\x0bPGEJGJMGGOG\x18\x0b \x03(\x0b\x32\x0c.LFBOPOGGBPM\x12!\n\x0bIGPHGEDLFLB\x18\x0c \x03(\x0b\x32\x0c.BNGCIFIKLLOb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.OMHJKMMDJEO_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OMHJKMMDJEO']._serialized_start=122
  _globals['_OMHJKMMDJEO']._serialized_end=226
# @@protoc_insertion_point(module_scope)
