# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/OneoffGatherPointDetectorDataNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import OneoffGatherPointDetectorData_pb2 as genshin_dot_packet_dot_proto_dot_OneoffGatherPointDetectorData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>genshin/packet/proto/OneoffGatherPointDetectorDataNotify.proto\x1a\x38genshin/packet/proto/OneoffGatherPointDetectorData.proto\"\xc4\x01\n#OneoffGatherPointDetectorDataNotify\x12N\n&oneoff_gather_point_detector_data_list\x18\x06 \x03(\x0b\x32\x1e.OneoffGatherPointDetectorData\"M\n\x05\x43mdId\x12\x08\n\x04NONE\x10\x00\x12\x13\n\x0f\x45NET_CHANNEL_ID\x10\x00\x12\x14\n\x10\x45NET_IS_RELIABLE\x10\x01\x12\x0b\n\x06\x43MD_ID\x10\xa6!\x1a\x02\x10\x01\x42\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')



_ONEOFFGATHERPOINTDETECTORDATANOTIFY = DESCRIPTOR.message_types_by_name['OneoffGatherPointDetectorDataNotify']
_ONEOFFGATHERPOINTDETECTORDATANOTIFY_CMDID = _ONEOFFGATHERPOINTDETECTORDATANOTIFY.enum_types_by_name['CmdId']
OneoffGatherPointDetectorDataNotify = _reflection.GeneratedProtocolMessageType('OneoffGatherPointDetectorDataNotify', (_message.Message,), {
  'DESCRIPTOR' : _ONEOFFGATHERPOINTDETECTORDATANOTIFY,
  '__module__' : 'genshin.packet.proto.OneoffGatherPointDetectorDataNotify_pb2'
  # @@protoc_insertion_point(class_scope:OneoffGatherPointDetectorDataNotify)
  })
_sym_db.RegisterMessage(OneoffGatherPointDetectorDataNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _ONEOFFGATHERPOINTDETECTORDATANOTIFY_CMDID._options = None
  _ONEOFFGATHERPOINTDETECTORDATANOTIFY_CMDID._serialized_options = b'\020\001'
  _ONEOFFGATHERPOINTDETECTORDATANOTIFY._serialized_start=125
  _ONEOFFGATHERPOINTDETECTORDATANOTIFY._serialized_end=321
  _ONEOFFGATHERPOINTDETECTORDATANOTIFY_CMDID._serialized_start=244
  _ONEOFFGATHERPOINTDETECTORDATANOTIFY_CMDID._serialized_end=321
# @@protoc_insertion_point(module_scope)
