# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/PathfindingPingNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0genshin/packet/proto/PathfindingPingNotify.proto\"\x17\n\x15PathfindingPingNotifyB\x16\n\x14org.sorapointa.protob\x06proto3')



_PATHFINDINGPINGNOTIFY = DESCRIPTOR.message_types_by_name['PathfindingPingNotify']
PathfindingPingNotify = _reflection.GeneratedProtocolMessageType('PathfindingPingNotify', (_message.Message,), {
  'DESCRIPTOR' : _PATHFINDINGPINGNOTIFY,
  '__module__' : 'genshin.packet.proto.PathfindingPingNotify_pb2'
  # @@protoc_insertion_point(class_scope:PathfindingPingNotify)
  })
_sym_db.RegisterMessage(PathfindingPingNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _PATHFINDINGPINGNOTIFY._serialized_start=52
  _PATHFINDINGPINGNOTIFY._serialized_end=75
# @@protoc_insertion_point(module_scope)
