# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/PBIIGBANBHC.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/PBIIGBANBHC.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import FGNHPFIDPCB_pb2 as genshin_dot_packet_dot_proto_dot_FGNHPFIDPCB__pb2
from genshin.packet.proto import KJIHGCIALOJ_pb2 as genshin_dot_packet_dot_proto_dot_KJIHGCIALOJ__pb2
from genshin.packet.proto import JAFNAFFNFLD_pb2 as genshin_dot_packet_dot_proto_dot_JAFNAFFNFLD__pb2
from genshin.packet.proto import DEIHIELEFEN_pb2 as genshin_dot_packet_dot_proto_dot_DEIHIELEFEN__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/PBIIGBANBHC.proto\x1a&genshin/packet/proto/FGNHPFIDPCB.proto\x1a&genshin/packet/proto/KJIHGCIALOJ.proto\x1a&genshin/packet/proto/JAFNAFFNFLD.proto\x1a&genshin/packet/proto/DEIHIELEFEN.proto\"\xe4\x02\n\x0bPBIIGBANBHC\x12!\n\x0bLEDMFIOGIFL\x18\x0b \x01(\x0b\x32\x0c.FGNHPFIDPCB\x12!\n\x0bHODDLOCGNOB\x18\x02 \x01(\x0b\x32\x0c.KJIHGCIALOJ\x12!\n\x0bMCMJNGOKOJI\x18\x0e \x03(\x0b\x32\x0c.JAFNAFFNFLD\x12!\n\x0bJPNOLKLOAFP\x18\t \x01(\x0b\x32\x0c.FGNHPFIDPCB\x12\x13\n\x0bNGBFPJFAPPE\x18\x06 \x01(\x04\x12\x13\n\x0bMFFPCLGBCDG\x18\x03 \x01(\r\x12!\n\x0bGMJAGIBJEAC\x18\x04 \x01(\x0e\x32\x0c.DEIHIELEFEN\x12\x13\n\x0b\x43HNBJMEFHHB\x18\r \x01(\r\x12\x13\n\x0bPCIAIKNILJF\x18\n \x01(\x08\x12\x13\n\x0b\x42HOJPBGGBNN\x18\x05 \x01(\x08\x12\x13\n\x0bOOJDCIKDBOK\x18\x08 \x01(\x08\x12\x13\n\x0bOHIGHGEANEC\x18\x01 \x01(\x05\x12\x13\n\x0bOHCNLAPPABO\x18\x0f \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.PBIIGBANBHC_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PBIIGBANBHC']._serialized_start=203
  _globals['_PBIIGBANBHC']._serialized_end=559
# @@protoc_insertion_point(module_scope)
