# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/PBIOIJNMCJO.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/PBIOIJNMCJO.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import BAADCBGPEFO_pb2 as genshin_dot_packet_dot_proto_dot_BAADCBGPEFO__pb2
from genshin.packet.proto import CMGOOOMLAIA_pb2 as genshin_dot_packet_dot_proto_dot_CMGOOOMLAIA__pb2
from genshin.packet.proto import KBAIOMIOCCP_pb2 as genshin_dot_packet_dot_proto_dot_KBAIOMIOCCP__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/PBIOIJNMCJO.proto\x1a&genshin/packet/proto/BAADCBGPEFO.proto\x1a&genshin/packet/proto/CMGOOOMLAIA.proto\x1a&genshin/packet/proto/KBAIOMIOCCP.proto\"v\n\x0bPBIOIJNMCJO\x12!\n\x0bLGFPFKPANPI\x18\x02 \x03(\x0b\x32\x0c.BAADCBGPEFO\x12!\n\x0bIMIOGMDOKCB\x18\r \x01(\x0e\x32\x0c.CMGOOOMLAIA\x12!\n\x0bJMLABOBCLDE\x18\x04 \x01(\x0e\x32\x0c.KBAIOMIOCCPb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.PBIOIJNMCJO_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PBIOIJNMCJO']._serialized_start=162
  _globals['_PBIOIJNMCJO']._serialized_end=280
# @@protoc_insertion_point(module_scope)
