# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/PBNavMeshTile.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import PBNavMeshPoly_pb2 as genshin_dot_packet_dot_proto_dot_PBNavMeshPoly__pb2
from genshin.packet.proto import Vector_pb2 as genshin_dot_packet_dot_proto_dot_Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(genshin/packet/proto/PBNavMeshTile.proto\x1a(genshin/packet/proto/PBNavMeshPoly.proto\x1a!genshin/packet/proto/Vector.proto\"E\n\rPBNavMeshTile\x12\x15\n\x04vecs\x18\x04 \x03(\x0b\x32\x07.Vector\x12\x1d\n\x05polys\x18\x08 \x03(\x0b\x32\x0e.PBNavMeshPolyB\x16\n\x14org.sorapointa.protob\x06proto3')



_PBNAVMESHTILE = DESCRIPTOR.message_types_by_name['PBNavMeshTile']
PBNavMeshTile = _reflection.GeneratedProtocolMessageType('PBNavMeshTile', (_message.Message,), {
  'DESCRIPTOR' : _PBNAVMESHTILE,
  '__module__' : 'genshin.packet.proto.PBNavMeshTile_pb2'
  # @@protoc_insertion_point(class_scope:PBNavMeshTile)
  })
_sym_db.RegisterMessage(PBNavMeshTile)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _PBNAVMESHTILE._serialized_start=121
  _PBNAVMESHTILE._serialized_end=190
# @@protoc_insertion_point(module_scope)
