from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class PCPKMBJDJAK(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    PCPKMBJDJAK_INTERACT_NONE: _ClassVar[PCPKMBJDJAK]
    PCPKMBJDJAK_INTERACT_PICK_ITEM: _ClassVar[PCPKMBJDJAK]
    PCPKMBJDJAK_INTERACT_GATHER: _ClassVar[PCPKMBJDJAK]
    PCPKMBJDJAK_INTERACT_OPEN_CHEST: _ClassVar[PCPKMBJDJAK]
    PCPKMBJDJAK_INTERACT_OPEN_STATUE: _ClassVar[PCPKMBJDJAK]
    PCPKMBJDJAK_INTERACT_CONSUM: _ClassVar[PCPKMBJDJAK]
    PCPKMBJDJAK_INTERACT_MP_PLAY_REWARD: _ClassVar[PCPKMBJDJAK]
    PCPKMBJDJAK_INTERACT_VIEW: _ClassVar[PCPKMBJDJAK]
    PCPKMBJDJAK_INTERACT_GENERAL_REWARD: _ClassVar[PCPKMBJDJAK]
    PCPKMBJDJAK_INTERACT_MIRACLE_RING: _ClassVar[PCPKMBJDJAK]
    PCPKMBJDJAK_INTERACT_FOUNDATION: _ClassVar[PCPKMBJDJAK]
    PCPKMBJDJAK_INTERACT_ECHO_SHELL: _ClassVar[PCPKMBJDJAK]
    PCPKMBJDJAK_INTERACT_HOME_GATHER: _ClassVar[PCPKMBJDJAK]
    PCPKMBJDJAK_INTERACT_ENV_ANIMAL: _ClassVar[PCPKMBJDJAK]
    PCPKMBJDJAK_INTERACT_QUEST_GADGET: _ClassVar[PCPKMBJDJAK]
    PCPKMBJDJAK_INTERACT_UI_INTERACT: _ClassVar[PCPKMBJDJAK]
    PCPKMBJDJAK_INTERACT_DESHRET_OBELISK: _ClassVar[PCPKMBJDJAK]
PCPKMBJDJAK_INTERACT_NONE: PCPKMBJDJAK
PCPKMBJDJAK_INTERACT_PICK_ITEM: PCPKMBJDJAK
PCPKMBJDJAK_INTERACT_GATHER: PCPKMBJDJAK
PCPKMBJDJAK_INTERACT_OPEN_CHEST: PCPKMBJDJAK
PCPKMBJDJAK_INTERACT_OPEN_STATUE: PCPKMBJDJAK
PCPKMBJDJAK_INTERACT_CONSUM: PCPKMBJDJAK
PCPKMBJDJAK_INTERACT_MP_PLAY_REWARD: PCPKMBJDJAK
PCPKMBJDJAK_INTERACT_VIEW: PCPKMBJDJAK
PCPKMBJDJAK_INTERACT_GENERAL_REWARD: PCPKMBJDJAK
PCPKMBJDJAK_INTERACT_MIRACLE_RING: PCPKMBJDJAK
PCPKMBJDJAK_INTERACT_FOUNDATION: PCPKMBJDJAK
PCPKMBJDJAK_INTERACT_ECHO_SHELL: PCPKMBJDJAK
PCPKMBJDJAK_INTERACT_HOME_GATHER: PCPKMBJDJAK
PCPKMBJDJAK_INTERACT_ENV_ANIMAL: PCPKMBJDJAK
PCPKMBJDJAK_INTERACT_QUEST_GADGET: PCPKMBJDJAK
PCPKMBJDJAK_INTERACT_UI_INTERACT: PCPKMBJDJAK
PCPKMBJDJAK_INTERACT_DESHRET_OBELISK: PCPKMBJDJAK
