# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/PEBFBDONHLO.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/PEBFBDONHLO.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import NFONHFAMDNE_pb2 as genshin_dot_packet_dot_proto_dot_NFONHFAMDNE__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/PEBFBDONHLO.proto\x1a&genshin/packet/proto/NFONHFAMDNE.proto\"E\n\x0bPEBFBDONHLO\x12!\n\x0b\x41NCFLFIPDEI\x18\x03 \x03(\x0e\x32\x0c.NFONHFAMDNE\x12\x13\n\x0bJHLBPPFGGPG\x18\t \x03(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.PEBFBDONHLO_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PEBFBDONHLO']._serialized_start=82
  _globals['_PEBFBDONHLO']._serialized_end=151
# @@protoc_insertion_point(module_scope)
