from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class PIDFNDLHKPG(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    PIDFNDLHKPG_QUEST_ABYSS_WAR_LEVEL_STATUS_NONE: _ClassVar[PIDFNDLHKPG]
    PIDFNDLHKPG_QUEST_ABYSS_WAR_LEVEL_STATUS_NOT_REFRESH: _ClassVar[PIDFNDLHKPG]
    PIDFNDLHKPG_QUEST_ABYSS_WAR_LEVEL_STATUS_READY_TO_ACCEPT: _ClassVar[PIDFNDLHKPG]
    PIDFNDLHKPG_QUEST_ABYSS_WAR_LEVEL_STATUS_RUNNING: _ClassVar[PIDFNDLHKPG]
    PIDFNDLHKPG_QUEST_ABYSS_WAR_LEVEL_STATUS_FINISH: _ClassVar[PIDFNDLHKPG]
    PIDFNDLHKPG_QUEST_ABYSS_WAR_LEVEL_STATUS_UNAVALIABLE: _ClassVar[PIDFNDLHKPG]
PIDFNDLHKPG_QUEST_ABYSS_WAR_LEVEL_STATUS_NONE: PIDFNDLHKPG
PIDFNDLHKPG_QUEST_ABYSS_WAR_LEVEL_STATUS_NOT_REFRESH: PIDFNDLHKPG
PIDFNDLHKPG_QUEST_ABYSS_WAR_LEVEL_STATUS_READY_TO_ACCEPT: PIDFNDLHKPG
PIDFNDLHKPG_QUEST_ABYSS_WAR_LEVEL_STATUS_RUNNING: PIDFNDLHKPG
PIDFNDLHKPG_QUEST_ABYSS_WAR_LEVEL_STATUS_FINISH: PIDFNDLHKPG
PIDFNDLHKPG_QUEST_ABYSS_WAR_LEVEL_STATUS_UNAVALIABLE: PIDFNDLHKPG
