from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class PIMMBIDLDCL(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    PIMMBIDLDCL_BRICK_BREAKER_STAGE_PREPARE: _ClassVar[PIMMBIDLDCL]
    PIMMBIDLDCL_BRICK_BREAKER_STAGE_PICK: _ClassVar[PIMMBIDLDCL]
    PIMMBIDLDCL_BRICK_BREAKER_STAGE_GAME: _ClassVar[PIMMBIDLDCL]
    PIMMBIDLDCL_BRICK_BREAKER_STAGE_PLAY: _ClassVar[PIMMBIDLDCL]
    PIMMBIDLDCL_BRICK_BREAKER_STAGE_SETTLE: _ClassVar[PIMMBIDLDCL]
PIMMBIDLDCL_BRICK_BREAKER_STAGE_PREPARE: PIMMBIDLDCL
PIMMBIDLDCL_BRICK_BREAKER_STAGE_PICK: PIMMBIDLDCL
PIMMBIDLDCL_BRICK_BREAKER_STAGE_GAME: PIMMBIDLDCL
PIMMBIDLDCL_BRICK_BREAKER_STAGE_PLAY: PIMMBIDLDCL
PIMMBIDLDCL_BRICK_BREAKER_STAGE_SETTLE: PIMMBIDLDCL
