# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/PingReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"genshin/packet/proto/PingReq.proto\"f\n\x07PingReq\x12\x13\n\x0b\x63lient_time\x18\x0c \x01(\r\x12\x0f\n\x07ue_time\x18\x0e \x01(\x02\x12\x17\n\x0ftotal_tick_time\x18\x06 \x01(\x01\x12\x0f\n\x07sc_data\x18\n \x01(\x0c\x12\x0b\n\x03seq\x18\x03 \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_PINGREQ = DESCRIPTOR.message_types_by_name['PingReq']
PingReq = _reflection.GeneratedProtocolMessageType('PingReq', (_message.Message,), {
  'DESCRIPTOR' : _PINGREQ,
  '__module__' : 'genshin.packet.proto.PingReq_pb2'
  # @@protoc_insertion_point(class_scope:PingReq)
  })
_sym_db.RegisterMessage(PingReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _PINGREQ._serialized_start=38
  _PINGREQ._serialized_end=140
# @@protoc_insertion_point(module_scope)
