# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/PlayerChatReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import ChatInfo_pb2 as genshin_dot_packet_dot_proto_dot_ChatInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(genshin/packet/proto/PlayerChatReq.proto\x1a#genshin/packet/proto/ChatInfo.proto\"A\n\rPlayerChatReq\x12\x12\n\nchannel_id\x18\r \x01(\r\x12\x1c\n\tchat_info\x18\x0f \x01(\x0b\x32\t.ChatInfoB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')



_PLAYERCHATREQ = DESCRIPTOR.message_types_by_name['PlayerChatReq']
PlayerChatReq = _reflection.GeneratedProtocolMessageType('PlayerChatReq', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERCHATREQ,
  '__module__' : 'genshin.packet.proto.PlayerChatReq_pb2'
  # @@protoc_insertion_point(class_scope:PlayerChatReq)
  })
_sym_db.RegisterMessage(PlayerChatReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _PLAYERCHATREQ._serialized_start=81
  _PLAYERCHATREQ._serialized_end=146
# @@protoc_insertion_point(module_scope)
