# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/PlayerOfferingData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-genshin/packet/proto/PlayerOfferingData.proto\"\x8e\x01\n\x12PlayerOfferingData\x12\x13\n\x0boffering_id\x18\x01 \x01(\r\x12\x19\n\x11is_first_interact\x18\x0f \x01(\x08\x12\r\n\x05level\x18\x0c \x01(\r\x12\x1f\n\x17taken_level_reward_list\x18\x08 \x03(\r\x12\x18\n\x10is_new_max_level\x18\x06 \x01(\x08\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_PLAYEROFFERINGDATA = DESCRIPTOR.message_types_by_name['PlayerOfferingData']
PlayerOfferingData = _reflection.GeneratedProtocolMessageType('PlayerOfferingData', (_message.Message,), {
  'DESCRIPTOR' : _PLAYEROFFERINGDATA,
  '__module__' : 'genshin.packet.proto.PlayerOfferingData_pb2'
  # @@protoc_insertion_point(class_scope:PlayerOfferingData)
  })
_sym_db.RegisterMessage(PlayerOfferingData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _PLAYEROFFERINGDATA._serialized_start=50
  _PLAYEROFFERINGDATA._serialized_end=192
# @@protoc_insertion_point(module_scope)
