# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/PlayerForceExitRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-genshin/packet/proto/PlayerForceExitRsp.proto\"%\n\x12PlayerForceExitRsp\x12\x0f\n\x07retcode\x18\x0f \x01(\x05\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_PLAYERFORCEEXITRSP = DESCRIPTOR.message_types_by_name['PlayerForceExitRsp']
PlayerForceExitRsp = _reflection.GeneratedProtocolMessageType('PlayerForceExitRsp', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERFORCEEXITRSP,
  '__module__' : 'genshin.packet.proto.PlayerForceExitRsp_pb2'
  # @@protoc_insertion_point(class_scope:PlayerForceExitRsp)
  })
_sym_db.RegisterMessage(PlayerForceExitRsp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _PLAYERFORCEEXITRSP._serialized_start=49
  _PLAYERFORCEEXITRSP._serialized_end=86
# @@protoc_insertion_point(module_scope)
