# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/PlayerSetPauseRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,genshin/packet/proto/PlayerSetPauseRsp.proto\"$\n\x11PlayerSetPauseRsp\x12\x0f\n\x07retcode\x18\x0f \x01(\x05\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_PLAYERSETPAUSERSP = DESCRIPTOR.message_types_by_name['PlayerSetPauseRsp']
PlayerSetPauseRsp = _reflection.GeneratedProtocolMessageType('PlayerSetPauseRsp', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERSETPAUSERSP,
  '__module__' : 'genshin.packet.proto.PlayerSetPauseRsp_pb2'
  # @@protoc_insertion_point(class_scope:PlayerSetPauseRsp)
  })
_sym_db.RegisterMessage(PlayerSetPauseRsp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _PLAYERSETPAUSERSP._serialized_start=48
  _PLAYERSETPAUSERSP._serialized_end=84
# @@protoc_insertion_point(module_scope)
