from genshin.packet.proto import AHECBKCPDAG_pb2 as _AHECBKCPDAG_pb2
from genshin.packet.proto import MIGELBLONGC_pb2 as _MIGELBLONGC_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Mapping as _Mapping, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class PlayerLoginReq(_message.Message):
    __slots__ = ("BDEDNFFOHPD", "LNPFFNMLLIC", "MHPFNLKCFOM", "EFAJIHMNOBK", "EHKMNCGLEME", "PJFPOHLMOMB", "JGNDADPBFCH", "INPDHDPNNPK", "OKABFCFIPNH", "INLBFFMLEBE", "FEGJGHPPIFB", "DFCDOOCDLBL", "IMEGEGIMALJ", "KCMILECJIOI", "MGKMJMICLGP", "NAMCLHNNACJ", "KIPGKKMDAKN", "PFJGLPFAAGA", "LBKDGOEFEBC", "HCBIFFMAGKG", "OHJNPJCKGEG", "KOPBIDKNAHN", "GPLGOEEHMFL", "DGPLJOJOBOJ", "LOCFGJPGDGO", "IJLHLCLLENE", "KFAOJIBGLGF", "MFDAJLKHGJE", "CEDHFFMBLBI", "LPMHBEOCJGD", "GHEJILPPKAL", "IJCDAKGLMBE", "ILIJHCPIFOK", "AJCGKKPCCGD", "DPNADJBAHEM", "EBMOBBBAIBC", "LLADMBNFOAM", "LAOGOCKBAAK", "GKJOEIENPDI", "CFNCNFABBBD", "JJDJDFCEFCK", "LDEPLPBKLJI", "NGIOMIKNNCL", "ILAHFKPDAGK", "GMOPLPFJNJA", "AMPEOPEOMAD", "EDMOCOCJPHH", "JNLGDEFHNDG", "FPLLNPMLAIG", "NGOMNPFNPLM", "JKEBNCDOHGP")
    BDEDNFFOHPD_FIELD_NUMBER: _ClassVar[int]
    LNPFFNMLLIC_FIELD_NUMBER: _ClassVar[int]
    MHPFNLKCFOM_FIELD_NUMBER: _ClassVar[int]
    EFAJIHMNOBK_FIELD_NUMBER: _ClassVar[int]
    EHKMNCGLEME_FIELD_NUMBER: _ClassVar[int]
    PJFPOHLMOMB_FIELD_NUMBER: _ClassVar[int]
    JGNDADPBFCH_FIELD_NUMBER: _ClassVar[int]
    INPDHDPNNPK_FIELD_NUMBER: _ClassVar[int]
    OKABFCFIPNH_FIELD_NUMBER: _ClassVar[int]
    INLBFFMLEBE_FIELD_NUMBER: _ClassVar[int]
    FEGJGHPPIFB_FIELD_NUMBER: _ClassVar[int]
    DFCDOOCDLBL_FIELD_NUMBER: _ClassVar[int]
    IMEGEGIMALJ_FIELD_NUMBER: _ClassVar[int]
    KCMILECJIOI_FIELD_NUMBER: _ClassVar[int]
    MGKMJMICLGP_FIELD_NUMBER: _ClassVar[int]
    NAMCLHNNACJ_FIELD_NUMBER: _ClassVar[int]
    KIPGKKMDAKN_FIELD_NUMBER: _ClassVar[int]
    PFJGLPFAAGA_FIELD_NUMBER: _ClassVar[int]
    LBKDGOEFEBC_FIELD_NUMBER: _ClassVar[int]
    HCBIFFMAGKG_FIELD_NUMBER: _ClassVar[int]
    OHJNPJCKGEG_FIELD_NUMBER: _ClassVar[int]
    KOPBIDKNAHN_FIELD_NUMBER: _ClassVar[int]
    GPLGOEEHMFL_FIELD_NUMBER: _ClassVar[int]
    DGPLJOJOBOJ_FIELD_NUMBER: _ClassVar[int]
    LOCFGJPGDGO_FIELD_NUMBER: _ClassVar[int]
    IJLHLCLLENE_FIELD_NUMBER: _ClassVar[int]
    KFAOJIBGLGF_FIELD_NUMBER: _ClassVar[int]
    MFDAJLKHGJE_FIELD_NUMBER: _ClassVar[int]
    CEDHFFMBLBI_FIELD_NUMBER: _ClassVar[int]
    LPMHBEOCJGD_FIELD_NUMBER: _ClassVar[int]
    GHEJILPPKAL_FIELD_NUMBER: _ClassVar[int]
    IJCDAKGLMBE_FIELD_NUMBER: _ClassVar[int]
    ILIJHCPIFOK_FIELD_NUMBER: _ClassVar[int]
    AJCGKKPCCGD_FIELD_NUMBER: _ClassVar[int]
    DPNADJBAHEM_FIELD_NUMBER: _ClassVar[int]
    EBMOBBBAIBC_FIELD_NUMBER: _ClassVar[int]
    LLADMBNFOAM_FIELD_NUMBER: _ClassVar[int]
    LAOGOCKBAAK_FIELD_NUMBER: _ClassVar[int]
    GKJOEIENPDI_FIELD_NUMBER: _ClassVar[int]
    CFNCNFABBBD_FIELD_NUMBER: _ClassVar[int]
    JJDJDFCEFCK_FIELD_NUMBER: _ClassVar[int]
    LDEPLPBKLJI_FIELD_NUMBER: _ClassVar[int]
    NGIOMIKNNCL_FIELD_NUMBER: _ClassVar[int]
    ILAHFKPDAGK_FIELD_NUMBER: _ClassVar[int]
    GMOPLPFJNJA_FIELD_NUMBER: _ClassVar[int]
    AMPEOPEOMAD_FIELD_NUMBER: _ClassVar[int]
    EDMOCOCJPHH_FIELD_NUMBER: _ClassVar[int]
    JNLGDEFHNDG_FIELD_NUMBER: _ClassVar[int]
    FPLLNPMLAIG_FIELD_NUMBER: _ClassVar[int]
    NGOMNPFNPLM_FIELD_NUMBER: _ClassVar[int]
    JKEBNCDOHGP_FIELD_NUMBER: _ClassVar[int]
    BDEDNFFOHPD: bytes
    LNPFFNMLLIC: str
    MHPFNLKCFOM: str
    EFAJIHMNOBK: str
    EHKMNCGLEME: str
    PJFPOHLMOMB: str
    JGNDADPBFCH: str
    INPDHDPNNPK: str
    OKABFCFIPNH: str
    INLBFFMLEBE: _AHECBKCPDAG_pb2.AHECBKCPDAG
    FEGJGHPPIFB: bytes
    DFCDOOCDLBL: bytes
    IMEGEGIMALJ: str
    KCMILECJIOI: _MIGELBLONGC_pb2.MIGELBLONGC
    MGKMJMICLGP: str
    NAMCLHNNACJ: str
    KIPGKKMDAKN: str
    PFJGLPFAAGA: str
    LBKDGOEFEBC: str
    HCBIFFMAGKG: str
    OHJNPJCKGEG: str
    KOPBIDKNAHN: str
    GPLGOEEHMFL: str
    DGPLJOJOBOJ: str
    LOCFGJPGDGO: str
    IJLHLCLLENE: str
    KFAOJIBGLGF: str
    MFDAJLKHGJE: str
    CEDHFFMBLBI: str
    LPMHBEOCJGD: int
    GHEJILPPKAL: int
    IJCDAKGLMBE: int
    ILIJHCPIFOK: int
    AJCGKKPCCGD: int
    DPNADJBAHEM: int
    EBMOBBBAIBC: int
    LLADMBNFOAM: int
    LAOGOCKBAAK: int
    GKJOEIENPDI: int
    CFNCNFABBBD: int
    JJDJDFCEFCK: int
    LDEPLPBKLJI: int
    NGIOMIKNNCL: bool
    ILAHFKPDAGK: bool
    GMOPLPFJNJA: bool
    AMPEOPEOMAD: int
    EDMOCOCJPHH: int
    JNLGDEFHNDG: int
    FPLLNPMLAIG: int
    NGOMNPFNPLM: int
    JKEBNCDOHGP: int
    def __init__(self, BDEDNFFOHPD: _Optional[bytes] = ..., LNPFFNMLLIC: _Optional[str] = ..., MHPFNLKCFOM: _Optional[str] = ..., EFAJIHMNOBK: _Optional[str] = ..., EHKMNCGLEME: _Optional[str] = ..., PJFPOHLMOMB: _Optional[str] = ..., JGNDADPBFCH: _Optional[str] = ..., INPDHDPNNPK: _Optional[str] = ..., OKABFCFIPNH: _Optional[str] = ..., INLBFFMLEBE: _Optional[_Union[_AHECBKCPDAG_pb2.AHECBKCPDAG, _Mapping]] = ..., FEGJGHPPIFB: _Optional[bytes] = ..., DFCDOOCDLBL: _Optional[bytes] = ..., IMEGEGIMALJ: _Optional[str] = ..., KCMILECJIOI: _Optional[_Union[_MIGELBLONGC_pb2.MIGELBLONGC, _Mapping]] = ..., MGKMJMICLGP: _Optional[str] = ..., NAMCLHNNACJ: _Optional[str] = ..., KIPGKKMDAKN: _Optional[str] = ..., PFJGLPFAAGA: _Optional[str] = ..., LBKDGOEFEBC: _Optional[str] = ..., HCBIFFMAGKG: _Optional[str] = ..., OHJNPJCKGEG: _Optional[str] = ..., KOPBIDKNAHN: _Optional[str] = ..., GPLGOEEHMFL: _Optional[str] = ..., DGPLJOJOBOJ: _Optional[str] = ..., LOCFGJPGDGO: _Optional[str] = ..., IJLHLCLLENE: _Optional[str] = ..., KFAOJIBGLGF: _Optional[str] = ..., MFDAJLKHGJE: _Optional[str] = ..., CEDHFFMBLBI: _Optional[str] = ..., LPMHBEOCJGD: _Optional[int] = ..., GHEJILPPKAL: _Optional[int] = ..., IJCDAKGLMBE: _Optional[int] = ..., ILIJHCPIFOK: _Optional[int] = ..., AJCGKKPCCGD: _Optional[int] = ..., DPNADJBAHEM: _Optional[int] = ..., EBMOBBBAIBC: _Optional[int] = ..., LLADMBNFOAM: _Optional[int] = ..., LAOGOCKBAAK: _Optional[int] = ..., GKJOEIENPDI: _Optional[int] = ..., CFNCNFABBBD: _Optional[int] = ..., JJDJDFCEFCK: _Optional[int] = ..., LDEPLPBKLJI: _Optional[int] = ..., NGIOMIKNNCL: bool = ..., ILAHFKPDAGK: bool = ..., GMOPLPFJNJA: bool = ..., AMPEOPEOMAD: _Optional[int] = ..., EDMOCOCJPHH: _Optional[int] = ..., JNLGDEFHNDG: _Optional[int] = ..., FPLLNPMLAIG: _Optional[int] = ..., NGOMNPFNPLM: _Optional[int] = ..., JKEBNCDOHGP: _Optional[int] = ...) -> None: ...
