# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/PlayerConfirmMatchReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import MatchType_pb2 as genshin_dot_packet_dot_proto_dot_MatchType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0genshin/packet/proto/PlayerConfirmMatchReq.proto\x1a$genshin/packet/proto/MatchType.proto\"J\n\x15PlayerConfirmMatchReq\x12\x1e\n\nmatch_type\x18\x0c \x01(\x0e\x32\n.MatchType\x12\x11\n\tis_agreed\x18\n \x01(\x08\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_PLAYERCONFIRMMATCHREQ = DESCRIPTOR.message_types_by_name['PlayerConfirmMatchReq']
PlayerConfirmMatchReq = _reflection.GeneratedProtocolMessageType('PlayerConfirmMatchReq', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERCONFIRMMATCHREQ,
  '__module__' : 'genshin.packet.proto.PlayerConfirmMatchReq_pb2'
  # @@protoc_insertion_point(class_scope:PlayerConfirmMatchReq)
  })
_sym_db.RegisterMessage(PlayerConfirmMatchReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _PLAYERCONFIRMMATCHREQ._serialized_start=90
  _PLAYERCONFIRMMATCHREQ._serialized_end=164
# @@protoc_insertion_point(module_scope)
