# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/PlayerReportRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*genshin/packet/proto/PlayerReportRsp.proto\"G\n\x0fPlayerReportRsp\x12\x0f\n\x07\x63\x64_time\x18\x0b \x01(\r\x12\x12\n\ntarget_uid\x18\x06 \x01(\r\x12\x0f\n\x07retcode\x18\x0c \x01(\x05\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_PLAYERREPORTRSP = DESCRIPTOR.message_types_by_name['PlayerReportRsp']
PlayerReportRsp = _reflection.GeneratedProtocolMessageType('PlayerReportRsp', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERREPORTRSP,
  '__module__' : 'genshin.packet.proto.PlayerReportRsp_pb2'
  # @@protoc_insertion_point(class_scope:PlayerReportRsp)
  })
_sym_db.RegisterMessage(PlayerReportRsp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _PLAYERREPORTRSP._serialized_start=46
  _PLAYERREPORTRSP._serialized_end=117
# @@protoc_insertion_point(module_scope)
