from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class PLJPIHNOCFC(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    PLJPIHNOCFC_ROGUE_DIARY_AVATAR_DISABLE_NONE: _ClassVar[PLJPIHNOCFC]
    PLJPIHNOCFC_ROGUE_DIARY_AVATAR_DISABLE_DEATH: _ClassVar[PLJPIHNOCFC]
    PLJPIHNOCFC_ROGUE_DIARY_AVATAR_DISABLE_TIRED: _ClassVar[PLJPIHNOCFC]
    PLJPIHNOCFC_ROGUE_DIARY_AVATAR_DISABLE_DUPLICATED: _ClassVar[PLJPIHNOCFC]
PLJPIHNOCFC_ROGUE_DIARY_AVATAR_DISABLE_NONE: PLJPIHNOCFC
PLJPIHNOCFC_ROGUE_DIARY_AVATAR_DISABLE_DEATH: PLJPIHNOCFC
PLJPIHNOCFC_ROGUE_DIARY_AVATAR_DISABLE_TIRED: PLJPIHNOCFC
PLJPIHNOCFC_ROGUE_DIARY_AVATAR_DISABLE_DUPLICATED: PLJPIHNOCFC
