from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class PMNJNCLEONJ(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    PMNJNCLEONJ_NONE: _ClassVar[PMNJNCLEONJ]
    PMNJNCLEONJ_CREATE_CONNECT: _ClassVar[PMNJNCLEONJ]
    PMNJNCLEONJ_START_GAME: _ClassVar[PMNJNCLEONJ]
    PMNJNCLEONJ_PING: _ClassVar[PMNJNCLEONJ]
    PMNJNCLEONJ_FINISH_GAME: _ClassVar[PMNJNCLEONJ]
    PMNJNCLEONJ_SNAP_SHOT: _ClassVar[PMNJNCLEONJ]
    PMNJNCLEONJ_ACTION: _ClassVar[PMNJNCLEONJ]
PMNJNCLEONJ_NONE: PMNJNCLEONJ
PMNJNCLEONJ_CREATE_CONNECT: PMNJNCLEONJ
PMNJNCLEONJ_START_GAME: PMNJNCLEONJ
PMNJNCLEONJ_PING: PMNJNCLEONJ
PMNJNCLEONJ_FINISH_GAME: PMNJNCLEONJ
PMNJNCLEONJ_SNAP_SHOT: PMNJNCLEONJ
PMNJNCLEONJ_ACTION: PMNJNCLEONJ
