from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class PPAICMKDNEI(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    PPAICMKDNEI_IN_BATTLE_MECHANICUS_CARD_CHALLENGE_NONE: _ClassVar[PPAICMKDNEI]
    PPAICMKDNEI_IN_BATTLE_MECHANICUS_CARD_CHALLENGE_ON_GOING: _ClassVar[PPAICMKDNEI]
    PPAICMKDNEI_IN_BATTLE_MECHANICUS_CARD_CHALLENGE_FAIL: _ClassVar[PPAICMKDNEI]
    PPAICMKDNEI_IN_BATTLE_MECHANICUS_CARD_CHALLENGE_SUCCESS: _ClassVar[PPAICMKDNEI]
PPAICMKDNEI_IN_BATTLE_MECHANICUS_CARD_CHALLENGE_NONE: PPAICMKDNEI
PPAICMKDNEI_IN_BATTLE_MECHANICUS_CARD_CHALLENGE_ON_GOING: PPAICMKDNEI
PPAICMKDNEI_IN_BATTLE_MECHANICUS_CARD_CHALLENGE_FAIL: PPAICMKDNEI
PPAICMKDNEI_IN_BATTLE_MECHANICUS_CARD_CHALLENGE_SUCCESS: PPAICMKDNEI
