# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/PSNBlackListNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import FriendBrief_pb2 as genshin_dot_packet_dot_proto_dot_FriendBrief__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-genshin/packet/proto/PSNBlackListNotify.proto\x1a&genshin/packet/proto/FriendBrief.proto\"9\n\x12PSNBlackListNotify\x12#\n\rpsn_blacklist\x18\x0b \x03(\x0b\x32\x0c.FriendBriefB\x16\n\x14org.sorapointa.protob\x06proto3')



_PSNBLACKLISTNOTIFY = DESCRIPTOR.message_types_by_name['PSNBlackListNotify']
PSNBlackListNotify = _reflection.GeneratedProtocolMessageType('PSNBlackListNotify', (_message.Message,), {
  'DESCRIPTOR' : _PSNBLACKLISTNOTIFY,
  '__module__' : 'genshin.packet.proto.PSNBlackListNotify_pb2'
  # @@protoc_insertion_point(class_scope:PSNBlackListNotify)
  })
_sym_db.RegisterMessage(PSNBlackListNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _PSNBLACKLISTNOTIFY._serialized_start=89
  _PSNBLACKLISTNOTIFY._serialized_end=146
# @@protoc_insertion_point(module_scope)
