# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/QuestUpdateQuestVarReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import QuestVarOp_pb2 as genshin_dot_packet_dot_proto_dot_QuestVarOp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1genshin/packet/proto/QuestUpdateQuestVarReq.proto\x1a%genshin/packet/proto/QuestVarOp.proto\"\x89\x01\n\x16QuestUpdateQuestVarReq\x12\x17\n\x0fparent_quest_id\x18\t \x01(\r\x12&\n\x11quest_var_op_list\x18\x04 \x03(\x0b\x32\x0b.QuestVarOp\x12\x10\n\x08quest_id\x18\x0b \x01(\r\x12\x1c\n\x14parent_quest_var_seq\x18\x01 \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_QUESTUPDATEQUESTVARREQ = DESCRIPTOR.message_types_by_name['QuestUpdateQuestVarReq']
QuestUpdateQuestVarReq = _reflection.GeneratedProtocolMessageType('QuestUpdateQuestVarReq', (_message.Message,), {
  'DESCRIPTOR' : _QUESTUPDATEQUESTVARREQ,
  '__module__' : 'genshin.packet.proto.QuestUpdateQuestVarReq_pb2'
  # @@protoc_insertion_point(class_scope:QuestUpdateQuestVarReq)
  })
_sym_db.RegisterMessage(QuestUpdateQuestVarReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _QUESTUPDATEQUESTVARREQ._serialized_start=93
  _QUESTUPDATEQUESTVARREQ._serialized_end=230
# @@protoc_insertion_point(module_scope)
