# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/QuestDestroyNpcRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-genshin/packet/proto/QuestDestroyNpcRsp.proto\"N\n\x12QuestDestroyNpcRsp\x12\x0e\n\x06npc_id\x18\x0c \x01(\r\x12\x17\n\x0fparent_quest_id\x18\x04 \x01(\r\x12\x0f\n\x07retcode\x18\x05 \x01(\x05\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_QUESTDESTROYNPCRSP = DESCRIPTOR.message_types_by_name['QuestDestroyNpcRsp']
QuestDestroyNpcRsp = _reflection.GeneratedProtocolMessageType('QuestDestroyNpcRsp', (_message.Message,), {
  'DESCRIPTOR' : _QUESTDESTROYNPCRSP,
  '__module__' : 'genshin.packet.proto.QuestDestroyNpcRsp_pb2'
  # @@protoc_insertion_point(class_scope:QuestDestroyNpcRsp)
  })
_sym_db.RegisterMessage(QuestDestroyNpcRsp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _QUESTDESTROYNPCRSP._serialized_start=49
  _QUESTDESTROYNPCRSP._serialized_end=127
# @@protoc_insertion_point(module_scope)
