# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: genshin/packet/proto/QuickUseWidgetReq.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'genshin/packet/proto/QuickUseWidgetReq.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import WidgetCreateLocationInfo_pb2 as genshin_dot_packet_dot_proto_dot_WidgetCreateLocationInfo__pb2
from genshin.packet.proto import WidgetCameraInfo_pb2 as genshin_dot_packet_dot_proto_dot_WidgetCameraInfo__pb2
from genshin.packet.proto import WidgetCreatorInfo_pb2 as genshin_dot_packet_dot_proto_dot_WidgetCreatorInfo__pb2
from genshin.packet.proto import WidgetThunderBirdFeatherInfo_pb2 as genshin_dot_packet_dot_proto_dot_WidgetThunderBirdFeatherInfo__pb2
from genshin.packet.proto import WidgetSorushInfo_pb2 as genshin_dot_packet_dot_proto_dot_WidgetSorushInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,genshin/packet/proto/QuickUseWidgetReq.proto\x1a\x33genshin/packet/proto/WidgetCreateLocationInfo.proto\x1a+genshin/packet/proto/WidgetCameraInfo.proto\x1a,genshin/packet/proto/WidgetCreatorInfo.proto\x1a\x37genshin/packet/proto/WidgetThunderBirdFeatherInfo.proto\x1a+genshin/packet/proto/WidgetSorushInfo.proto\"\xaf\x02\n\x11QuickUseWidgetReq\x12\x33\n\rlocation_info\x18\xe7\x04 \x01(\x0b\x32\x19.WidgetCreateLocationInfoH\x00\x12)\n\x0b\x63\x61mera_info\x18\xb4\x04 \x01(\x0b\x32\x11.WidgetCameraInfoH\x00\x12+\n\x0c\x63reator_info\x18\x89\x06 \x01(\x0b\x32\x12.WidgetCreatorInfoH\x00\x12\x43\n\x19thunder_bird_feather_info\x18\xc0\x02 \x01(\x0b\x32\x1d.WidgetThunderBirdFeatherInfoH\x00\x12)\n\x0bsorush_info\x18\x8d\x01 \x01(\x0b\x32\x11.WidgetSorushInfoH\x00\x12\x14\n\x0b\x45\x45JNPDEBBIK\x18\xa6\x06 \x01(\x08\x42\x07\n\x05paramB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'genshin.packet.proto.QuickUseWidgetReq_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _globals['_QUICKUSEWIDGETREQ']._serialized_start=295
  _globals['_QUICKUSEWIDGETREQ']._serialized_end=598
# @@protoc_insertion_point(module_scope)
