# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/RechargeRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&genshin/packet/proto/RechargeRsp.proto\"O\n\x0bRechargeRsp\x12\x0f\n\x07retcode\x18\x0c \x01(\x05\x12\x1b\n\x13Unk2700_FGENAOBDIEA\x18\x06 \x01(\x08\x12\x12\n\nproduct_id\x18\x02 \x01(\tB\x16\n\x14org.sorapointa.protob\x06proto3')



_RECHARGERSP = DESCRIPTOR.message_types_by_name['RechargeRsp']
RechargeRsp = _reflection.GeneratedProtocolMessageType('RechargeRsp', (_message.Message,), {
  'DESCRIPTOR' : _RECHARGERSP,
  '__module__' : 'genshin.packet.proto.RechargeRsp_pb2'
  # @@protoc_insertion_point(class_scope:RechargeRsp)
  })
_sym_db.RegisterMessage(RechargeRsp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _RECHARGERSP._serialized_start=42
  _RECHARGERSP._serialized_end=121
# @@protoc_insertion_point(module_scope)
