# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/RemoveBlacklistRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-genshin/packet/proto/RemoveBlacklistRsp.proto\"9\n\x12RemoveBlacklistRsp\x12\x0f\n\x07retcode\x18\x0c \x01(\x05\x12\x12\n\ntarget_uid\x18\x07 \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_REMOVEBLACKLISTRSP = DESCRIPTOR.message_types_by_name['RemoveBlacklistRsp']
RemoveBlacklistRsp = _reflection.GeneratedProtocolMessageType('RemoveBlacklistRsp', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEBLACKLISTRSP,
  '__module__' : 'genshin.packet.proto.RemoveBlacklistRsp_pb2'
  # @@protoc_insertion_point(class_scope:RemoveBlacklistRsp)
  })
_sym_db.RegisterMessage(RemoveBlacklistRsp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _REMOVEBLACKLISTRSP._serialized_start=49
  _REMOVEBLACKLISTRSP._serialized_end=106
# @@protoc_insertion_point(module_scope)
