# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/ReunionSettleNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/ReunionSettleNotify.proto\"\x15\n\x13ReunionSettleNotifyB\x16\n\x14org.sorapointa.protob\x06proto3')



_REUNIONSETTLENOTIFY = DESCRIPTOR.message_types_by_name['ReunionSettleNotify']
ReunionSettleNotify = _reflection.GeneratedProtocolMessageType('ReunionSettleNotify', (_message.Message,), {
  'DESCRIPTOR' : _REUNIONSETTLENOTIFY,
  '__module__' : 'genshin.packet.proto.ReunionSettleNotify_pb2'
  # @@protoc_insertion_point(class_scope:ReunionSettleNotify)
  })
_sym_db.RegisterMessage(ReunionSettleNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _REUNIONSETTLENOTIFY._serialized_start=50
  _REUNIONSETTLENOTIFY._serialized_end=71
# @@protoc_insertion_point(module_scope)
