# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/SceneRouteChangeNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import SceneRouteChangeInfo_pb2 as genshin_dot_packet_dot_proto_dot_SceneRouteChangeInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1genshin/packet/proto/SceneRouteChangeNotify.proto\x1a/genshin/packet/proto/SceneRouteChangeInfo.proto\"i\n\x16SceneRouteChangeNotify\x12\x10\n\x08scene_id\x18\x0c \x01(\r\x12\x12\n\nscene_time\x18\x0b \x01(\r\x12)\n\nroute_list\x18\x02 \x03(\x0b\x32\x15.SceneRouteChangeInfoB\x16\n\x14org.sorapointa.protob\x06proto3')



_SCENEROUTECHANGENOTIFY = DESCRIPTOR.message_types_by_name['SceneRouteChangeNotify']
SceneRouteChangeNotify = _reflection.GeneratedProtocolMessageType('SceneRouteChangeNotify', (_message.Message,), {
  'DESCRIPTOR' : _SCENEROUTECHANGENOTIFY,
  '__module__' : 'genshin.packet.proto.SceneRouteChangeNotify_pb2'
  # @@protoc_insertion_point(class_scope:SceneRouteChangeNotify)
  })
_sym_db.RegisterMessage(SceneRouteChangeNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _SCENEROUTECHANGENOTIFY._serialized_start=102
  _SCENEROUTECHANGENOTIFY._serialized_end=207
# @@protoc_insertion_point(module_scope)
