# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/SceneGalleryHandballInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import PlaceInfo_pb2 as genshin_dot_packet_dot_proto_dot_PlaceInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3genshin/packet/proto/SceneGalleryHandballInfo.proto\x1a$genshin/packet/proto/PlaceInfo.proto\"U\n\x18SceneGalleryHandballInfo\x12#\n\x0f\x62\x61ll_place_info\x18\t \x01(\x0b\x32\n.PlaceInfo\x12\x14\n\x0cis_have_ball\x18\x0f \x01(\x08\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_SCENEGALLERYHANDBALLINFO = DESCRIPTOR.message_types_by_name['SceneGalleryHandballInfo']
SceneGalleryHandballInfo = _reflection.GeneratedProtocolMessageType('SceneGalleryHandballInfo', (_message.Message,), {
  'DESCRIPTOR' : _SCENEGALLERYHANDBALLINFO,
  '__module__' : 'genshin.packet.proto.SceneGalleryHandballInfo_pb2'
  # @@protoc_insertion_point(class_scope:SceneGalleryHandballInfo)
  })
_sym_db.RegisterMessage(SceneGalleryHandballInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _SCENEGALLERYHANDBALLINFO._serialized_start=93
  _SCENEGALLERYHANDBALLINFO._serialized_end=178
# @@protoc_insertion_point(module_scope)
