# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/SceneGalleryVintageHuntingThirdStageInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCgenshin/packet/proto/SceneGalleryVintageHuntingThirdStageInfo.proto\"*\n(SceneGalleryVintageHuntingThirdStageInfoB\x16\n\x14org.sorapointa.protob\x06proto3')



_SCENEGALLERYVINTAGEHUNTINGTHIRDSTAGEINFO = DESCRIPTOR.message_types_by_name['SceneGalleryVintageHuntingThirdStageInfo']
SceneGalleryVintageHuntingThirdStageInfo = _reflection.GeneratedProtocolMessageType('SceneGalleryVintageHuntingThirdStageInfo', (_message.Message,), {
  'DESCRIPTOR' : _SCENEGALLERYVINTAGEHUNTINGTHIRDSTAGEINFO,
  '__module__' : 'genshin.packet.proto.SceneGalleryVintageHuntingThirdStageInfo_pb2'
  # @@protoc_insertion_point(class_scope:SceneGalleryVintageHuntingThirdStageInfo)
  })
_sym_db.RegisterMessage(SceneGalleryVintageHuntingThirdStageInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _SCENEGALLERYVINTAGEHUNTINGTHIRDSTAGEINFO._serialized_start=71
  _SCENEGALLERYVINTAGEHUNTINGTHIRDSTAGEINFO._serialized_end=113
# @@protoc_insertion_point(module_scope)
