# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/ScenePlayInviteResultNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6genshin/packet/proto/ScenePlayInviteResultNotify.proto\"D\n\x1bScenePlayInviteResultNotify\x12\x14\n\x0cis_all_argee\x18\x0b \x01(\x08\x12\x0f\n\x07play_id\x18\x0f \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_SCENEPLAYINVITERESULTNOTIFY = DESCRIPTOR.message_types_by_name['ScenePlayInviteResultNotify']
ScenePlayInviteResultNotify = _reflection.GeneratedProtocolMessageType('ScenePlayInviteResultNotify', (_message.Message,), {
  'DESCRIPTOR' : _SCENEPLAYINVITERESULTNOTIFY,
  '__module__' : 'genshin.packet.proto.ScenePlayInviteResultNotify_pb2'
  # @@protoc_insertion_point(class_scope:ScenePlayInviteResultNotify)
  })
_sym_db.RegisterMessage(ScenePlayInviteResultNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _SCENEPLAYINVITERESULTNOTIFY._serialized_start=58
  _SCENEPLAYINVITERESULTNOTIFY._serialized_end=126
# @@protoc_insertion_point(module_scope)
