# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/ScenePlayGuestReplyInviteRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7genshin/packet/proto/ScenePlayGuestReplyInviteRsp.proto\"R\n\x1cScenePlayGuestReplyInviteRsp\x12\x0f\n\x07retcode\x18\x06 \x01(\x05\x12\x10\n\x08is_agree\x18\x02 \x01(\x08\x12\x0f\n\x07play_id\x18\x08 \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_SCENEPLAYGUESTREPLYINVITERSP = DESCRIPTOR.message_types_by_name['ScenePlayGuestReplyInviteRsp']
ScenePlayGuestReplyInviteRsp = _reflection.GeneratedProtocolMessageType('ScenePlayGuestReplyInviteRsp', (_message.Message,), {
  'DESCRIPTOR' : _SCENEPLAYGUESTREPLYINVITERSP,
  '__module__' : 'genshin.packet.proto.ScenePlayGuestReplyInviteRsp_pb2'
  # @@protoc_insertion_point(class_scope:ScenePlayGuestReplyInviteRsp)
  })
_sym_db.RegisterMessage(ScenePlayGuestReplyInviteRsp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _SCENEPLAYGUESTREPLYINVITERSP._serialized_start=59
  _SCENEPLAYGUESTREPLYINVITERSP._serialized_end=141
# @@protoc_insertion_point(module_scope)
