# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/SceneGalleryIslandPartySailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import Unk2800_FMAOEPEBKHB_pb2 as genshin_dot_packet_dot_proto_dot_Unk2800__FMAOEPEBKHB__pb2
from genshin.packet.proto import Unk2800_IMLDGLIMODE_pb2 as genshin_dot_packet_dot_proto_dot_Unk2800__IMLDGLIMODE__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:genshin/packet/proto/SceneGalleryIslandPartySailInfo.proto\x1a.genshin/packet/proto/Unk2800_FMAOEPEBKHB.proto\x1a.genshin/packet/proto/Unk2800_IMLDGLIMODE.proto\"\xfb\x01\n\x1fSceneGalleryIslandPartySailInfo\x12\x1b\n\x13Unk2800_HKHENLCIFNN\x18\x0e \x01(\r\x12\x1b\n\x13Unk2800_NGPLGLLFGOG\x18\n \x01(\r\x12\x31\n\x13Unk2800_ENJGEFBCLOL\x18\x01 \x01(\x0e\x32\x14.Unk2800_FMAOEPEBKHB\x12\x1b\n\x13Unk2800_DNDKJOJCDBI\x18\x0b \x01(\r\x12\x0c\n\x04\x63oin\x18\x0f \x01(\r\x12#\n\x05stage\x18\x0c \x01(\x0e\x32\x14.Unk2800_IMLDGLIMODE\x12\x1b\n\x13Unk2800_GMOCMEFBGIP\x18\x08 \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_SCENEGALLERYISLANDPARTYSAILINFO = DESCRIPTOR.message_types_by_name['SceneGalleryIslandPartySailInfo']
SceneGalleryIslandPartySailInfo = _reflection.GeneratedProtocolMessageType('SceneGalleryIslandPartySailInfo', (_message.Message,), {
  'DESCRIPTOR' : _SCENEGALLERYISLANDPARTYSAILINFO,
  '__module__' : 'genshin.packet.proto.SceneGalleryIslandPartySailInfo_pb2'
  # @@protoc_insertion_point(class_scope:SceneGalleryIslandPartySailInfo)
  })
_sym_db.RegisterMessage(SceneGalleryIslandPartySailInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _SCENEGALLERYISLANDPARTYSAILINFO._serialized_start=159
  _SCENEGALLERYISLANDPARTYSAILINFO._serialized_end=410
# @@protoc_insertion_point(module_scope)
