# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/ServerGlobalValueChangeNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8genshin/packet/proto/ServerGlobalValueChangeNotify.proto\"S\n\x1dServerGlobalValueChangeNotify\x12\x11\n\tentity_id\x18\x06 \x01(\r\x12\r\n\x05value\x18\x0c \x01(\x02\x12\x10\n\x08key_hash\x18\r \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_SERVERGLOBALVALUECHANGENOTIFY = DESCRIPTOR.message_types_by_name['ServerGlobalValueChangeNotify']
ServerGlobalValueChangeNotify = _reflection.GeneratedProtocolMessageType('ServerGlobalValueChangeNotify', (_message.Message,), {
  'DESCRIPTOR' : _SERVERGLOBALVALUECHANGENOTIFY,
  '__module__' : 'genshin.packet.proto.ServerGlobalValueChangeNotify_pb2'
  # @@protoc_insertion_point(class_scope:ServerGlobalValueChangeNotify)
  })
_sym_db.RegisterMessage(ServerGlobalValueChangeNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _SERVERGLOBALVALUECHANGENOTIFY._serialized_start=60
  _SERVERGLOBALVALUECHANGENOTIFY._serialized_end=143
# @@protoc_insertion_point(module_scope)
