# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/ServerMassiveEntity.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import MassiveBoxInfo_pb2 as genshin_dot_packet_dot_proto_dot_MassiveBoxInfo__pb2
from genshin.packet.proto import MassiveGrassInfo_pb2 as genshin_dot_packet_dot_proto_dot_MassiveGrassInfo__pb2
from genshin.packet.proto import MassiveWaterInfo_pb2 as genshin_dot_packet_dot_proto_dot_MassiveWaterInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/ServerMassiveEntity.proto\x1a)genshin/packet/proto/MassiveBoxInfo.proto\x1a+genshin/packet/proto/MassiveGrassInfo.proto\x1a+genshin/packet/proto/MassiveWaterInfo.proto\"\x82\x02\n\x13ServerMassiveEntity\x12\x13\n\x0b\x65ntity_type\x18\x01 \x01(\r\x12\x11\n\tconfig_id\x18\x02 \x01(\r\x12\x12\n\nruntime_id\x18\x03 \x01(\r\x12\x19\n\x11\x61uthority_peer_id\x18\x04 \x01(\r\x12\x0e\n\x06obj_id\x18\x05 \x01(\x03\x12\'\n\nwater_info\x18\x06 \x01(\x0b\x32\x11.MassiveWaterInfoH\x00\x12\'\n\ngrass_info\x18\x07 \x01(\x0b\x32\x11.MassiveGrassInfoH\x00\x12#\n\x08\x62ox_info\x18\x08 \x01(\x0b\x32\x0f.MassiveBoxInfoH\x00\x42\r\n\x0b\x65ntity_infoB\x16\n\x14org.sorapointa.protob\x06proto3')



_SERVERMASSIVEENTITY = DESCRIPTOR.message_types_by_name['ServerMassiveEntity']
ServerMassiveEntity = _reflection.GeneratedProtocolMessageType('ServerMassiveEntity', (_message.Message,), {
  'DESCRIPTOR' : _SERVERMASSIVEENTITY,
  '__module__' : 'genshin.packet.proto.ServerMassiveEntity_pb2'
  # @@protoc_insertion_point(class_scope:ServerMassiveEntity)
  })
_sym_db.RegisterMessage(ServerMassiveEntity)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _SERVERMASSIVEENTITY._serialized_start=184
  _SERVERMASSIVEENTITY._serialized_end=442
# @@protoc_insertion_point(module_scope)
