# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/SetCoopChapterViewedReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2genshin/packet/proto/SetCoopChapterViewedReq.proto\"-\n\x17SetCoopChapterViewedReq\x12\x12\n\nchapter_id\x18\x02 \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_SETCOOPCHAPTERVIEWEDREQ = DESCRIPTOR.message_types_by_name['SetCoopChapterViewedReq']
SetCoopChapterViewedReq = _reflection.GeneratedProtocolMessageType('SetCoopChapterViewedReq', (_message.Message,), {
  'DESCRIPTOR' : _SETCOOPCHAPTERVIEWEDREQ,
  '__module__' : 'genshin.packet.proto.SetCoopChapterViewedReq_pb2'
  # @@protoc_insertion_point(class_scope:SetCoopChapterViewedReq)
  })
_sym_db.RegisterMessage(SetCoopChapterViewedReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _SETCOOPCHAPTERVIEWEDREQ._serialized_start=54
  _SETCOOPCHAPTERVIEWEDREQ._serialized_end=99
# @@protoc_insertion_point(module_scope)
