# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/SetWidgetSlotRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import WidgetSlotOp_pb2 as genshin_dot_packet_dot_proto_dot_WidgetSlotOp__pb2
from genshin.packet.proto import WidgetSlotTag_pb2 as genshin_dot_packet_dot_proto_dot_WidgetSlotTag__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+genshin/packet/proto/SetWidgetSlotRsp.proto\x1a\'genshin/packet/proto/WidgetSlotOp.proto\x1a(genshin/packet/proto/WidgetSlotTag.proto\"u\n\x10SetWidgetSlotRsp\x12 \n\x08tag_list\x18\x0f \x03(\x0e\x32\x0e.WidgetSlotTag\x12\x0f\n\x07retcode\x18\x06 \x01(\x05\x12\x13\n\x0bmaterial_id\x18\x01 \x01(\r\x12\x19\n\x02op\x18\x04 \x01(\x0e\x32\r.WidgetSlotOpB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')



_SETWIDGETSLOTRSP = DESCRIPTOR.message_types_by_name['SetWidgetSlotRsp']
SetWidgetSlotRsp = _reflection.GeneratedProtocolMessageType('SetWidgetSlotRsp', (_message.Message,), {
  'DESCRIPTOR' : _SETWIDGETSLOTRSP,
  '__module__' : 'genshin.packet.proto.SetWidgetSlotRsp_pb2'
  # @@protoc_insertion_point(class_scope:SetWidgetSlotRsp)
  })
_sym_db.RegisterMessage(SetWidgetSlotRsp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _SETWIDGETSLOTRSP._serialized_start=130
  _SETWIDGETSLOTRSP._serialized_end=247
# @@protoc_insertion_point(module_scope)
