# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/SpiceActivityDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import SpiceStage_pb2 as genshin_dot_packet_dot_proto_dot_SpiceStage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2genshin/packet/proto/SpiceActivityDetailInfo.proto\x1a%genshin/packet/proto/SpiceStage.proto\"z\n\x17SpiceActivityDetailInfo\x12\x1b\n\x13Unk2700_IGMHNDNGNPG\x18\x0f \x01(\r\x12%\n\x10spice_stage_list\x18\x07 \x03(\x0b\x32\x0b.SpiceStage\x12\x1b\n\x13Unk2700_KIAHJKGOLGO\x18\r \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_SPICEACTIVITYDETAILINFO = DESCRIPTOR.message_types_by_name['SpiceActivityDetailInfo']
SpiceActivityDetailInfo = _reflection.GeneratedProtocolMessageType('SpiceActivityDetailInfo', (_message.Message,), {
  'DESCRIPTOR' : _SPICEACTIVITYDETAILINFO,
  '__module__' : 'genshin.packet.proto.SpiceActivityDetailInfo_pb2'
  # @@protoc_insertion_point(class_scope:SpiceActivityDetailInfo)
  })
_sym_db.RegisterMessage(SpiceActivityDetailInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _SPICEACTIVITYDETAILINFO._serialized_start=93
  _SPICEACTIVITYDETAILINFO._serialized_end=215
# @@protoc_insertion_point(module_scope)
