# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/SumoRestartDungeonReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0genshin/packet/proto/SumoRestartDungeonReq.proto\"\x17\n\x15SumoRestartDungeonReqB\x16\n\x14org.sorapointa.protob\x06proto3')



_SUMORESTARTDUNGEONREQ = DESCRIPTOR.message_types_by_name['SumoRestartDungeonReq']
SumoRestartDungeonReq = _reflection.GeneratedProtocolMessageType('SumoRestartDungeonReq', (_message.Message,), {
  'DESCRIPTOR' : _SUMORESTARTDUNGEONREQ,
  '__module__' : 'genshin.packet.proto.SumoRestartDungeonReq_pb2'
  # @@protoc_insertion_point(class_scope:SumoRestartDungeonReq)
  })
_sym_db.RegisterMessage(SumoRestartDungeonReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _SUMORESTARTDUNGEONREQ._serialized_start=52
  _SUMORESTARTDUNGEONREQ._serialized_end=75
# @@protoc_insertion_point(module_scope)
