# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/TakeInvestigationRewardReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5genshin/packet/proto/TakeInvestigationRewardReq.proto\"(\n\x1aTakeInvestigationRewardReq\x12\n\n\x02id\x18\x05 \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_TAKEINVESTIGATIONREWARDREQ = DESCRIPTOR.message_types_by_name['TakeInvestigationRewardReq']
TakeInvestigationRewardReq = _reflection.GeneratedProtocolMessageType('TakeInvestigationRewardReq', (_message.Message,), {
  'DESCRIPTOR' : _TAKEINVESTIGATIONREWARDREQ,
  '__module__' : 'genshin.packet.proto.TakeInvestigationRewardReq_pb2'
  # @@protoc_insertion_point(class_scope:TakeInvestigationRewardReq)
  })
_sym_db.RegisterMessage(TakeInvestigationRewardReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _TAKEINVESTIGATIONREWARDREQ._serialized_start=57
  _TAKEINVESTIGATIONREWARDREQ._serialized_end=97
# @@protoc_insertion_point(module_scope)
