# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/TakeReunionSignInRewardRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import ReunionSignInInfo_pb2 as genshin_dot_packet_dot_proto_dot_ReunionSignInInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5genshin/packet/proto/TakeReunionSignInRewardRsp.proto\x1a,genshin/packet/proto/ReunionSignInInfo.proto\"W\n\x1aTakeReunionSignInRewardRsp\x12(\n\x0csign_in_info\x18\n \x01(\x0b\x32\x12.ReunionSignInInfo\x12\x0f\n\x07retcode\x18\x05 \x01(\x05\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_TAKEREUNIONSIGNINREWARDRSP = DESCRIPTOR.message_types_by_name['TakeReunionSignInRewardRsp']
TakeReunionSignInRewardRsp = _reflection.GeneratedProtocolMessageType('TakeReunionSignInRewardRsp', (_message.Message,), {
  'DESCRIPTOR' : _TAKEREUNIONSIGNINREWARDRSP,
  '__module__' : 'genshin.packet.proto.TakeReunionSignInRewardRsp_pb2'
  # @@protoc_insertion_point(class_scope:TakeReunionSignInRewardRsp)
  })
_sym_db.RegisterMessage(TakeReunionSignInRewardRsp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _TAKEREUNIONSIGNINREWARDRSP._serialized_start=103
  _TAKEREUNIONSIGNINREWARDRSP._serialized_end=190
# @@protoc_insertion_point(module_scope)
