# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/TowerDailyRewardProgressChangeNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?genshin/packet/proto/TowerDailyRewardProgressChangeNotify.proto\"Y\n$TowerDailyRewardProgressChangeNotify\x12\x16\n\x0e\x64\x61ily_floor_id\x18\x0f \x01(\r\x12\x19\n\x11\x64\x61ily_level_index\x18\t \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_TOWERDAILYREWARDPROGRESSCHANGENOTIFY = DESCRIPTOR.message_types_by_name['TowerDailyRewardProgressChangeNotify']
TowerDailyRewardProgressChangeNotify = _reflection.GeneratedProtocolMessageType('TowerDailyRewardProgressChangeNotify', (_message.Message,), {
  'DESCRIPTOR' : _TOWERDAILYREWARDPROGRESSCHANGENOTIFY,
  '__module__' : 'genshin.packet.proto.TowerDailyRewardProgressChangeNotify_pb2'
  # @@protoc_insertion_point(class_scope:TowerDailyRewardProgressChangeNotify)
  })
_sym_db.RegisterMessage(TowerDailyRewardProgressChangeNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _TOWERDAILYREWARDPROGRESSCHANGENOTIFY._serialized_start=67
  _TOWERDAILYREWARDPROGRESSCHANGENOTIFY._serialized_end=156
# @@protoc_insertion_point(module_scope)
