# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/TowerLevelRecord.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+genshin/packet/proto/TowerLevelRecord.proto\"A\n\x10TowerLevelRecord\x12\x1b\n\x13satisfied_cond_list\x18\r \x03(\r\x12\x10\n\x08level_id\x18\n \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_TOWERLEVELRECORD = DESCRIPTOR.message_types_by_name['TowerLevelRecord']
TowerLevelRecord = _reflection.GeneratedProtocolMessageType('TowerLevelRecord', (_message.Message,), {
  'DESCRIPTOR' : _TOWERLEVELRECORD,
  '__module__' : 'genshin.packet.proto.TowerLevelRecord_pb2'
  # @@protoc_insertion_point(class_scope:TowerLevelRecord)
  })
_sym_db.RegisterMessage(TowerLevelRecord)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _TOWERLEVELRECORD._serialized_start=47
  _TOWERLEVELRECORD._serialized_end=112
# @@protoc_insertion_point(module_scope)
