# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/UgcActivityDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import Unk2700_MMJJMKMHANL_pb2 as genshin_dot_packet_dot_proto_dot_Unk2700__MMJJMKMHANL__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0genshin/packet/proto/UgcActivityDetailInfo.proto\x1a.genshin/packet/proto/Unk2700_MMJJMKMHANL.proto\"\xa1\x01\n\x15UgcActivityDetailInfo\x12\x1b\n\x13Unk2700_GMICFADLAMC\x18\n \x01(\x08\x12\x1b\n\x13Unk2700_FDDCMGKDOCC\x18\x0c \x01(\r\x12\x31\n\x13Unk2700_ILCAPJBAFOI\x18\x05 \x03(\x0b\x32\x14.Unk2700_MMJJMKMHANL\x12\x1b\n\x13Unk2700_PNOCELCOFNK\x18\x0b \x01(\x08\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_UGCACTIVITYDETAILINFO = DESCRIPTOR.message_types_by_name['UgcActivityDetailInfo']
UgcActivityDetailInfo = _reflection.GeneratedProtocolMessageType('UgcActivityDetailInfo', (_message.Message,), {
  'DESCRIPTOR' : _UGCACTIVITYDETAILINFO,
  '__module__' : 'genshin.packet.proto.UgcActivityDetailInfo_pb2'
  # @@protoc_insertion_point(class_scope:UgcActivityDetailInfo)
  })
_sym_db.RegisterMessage(UgcActivityDetailInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UGCACTIVITYDETAILINFO._serialized_start=101
  _UGCACTIVITYDETAILINFO._serialized_end=262
# @@protoc_insertion_point(module_scope)
