# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk2700_FNHKFHGNLPP_ServerRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import Unk2700_GHHCCEHGKLH_pb2 as genshin_dot_packet_dot_proto_dot_Unk2700__GHHCCEHGKLH__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8genshin/packet/proto/Unk2700_FNHKFHGNLPP_ServerRsp.proto\x1a.genshin/packet/proto/Unk2700_GHHCCEHGKLH.proto\"c\n\x1dUnk2700_FNHKFHGNLPP_ServerRsp\x12\x31\n\x13Unk2700_BCIBEPMFLGN\x18\x08 \x03(\x0b\x32\x14.Unk2700_GHHCCEHGKLH\x12\x0f\n\x07retcode\x18\x0e \x01(\x05\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_UNK2700_FNHKFHGNLPP_SERVERRSP = DESCRIPTOR.message_types_by_name['Unk2700_FNHKFHGNLPP_ServerRsp']
Unk2700_FNHKFHGNLPP_ServerRsp = _reflection.GeneratedProtocolMessageType('Unk2700_FNHKFHGNLPP_ServerRsp', (_message.Message,), {
  'DESCRIPTOR' : _UNK2700_FNHKFHGNLPP_SERVERRSP,
  '__module__' : 'genshin.packet.proto.Unk2700_FNHKFHGNLPP_ServerRsp_pb2'
  # @@protoc_insertion_point(class_scope:Unk2700_FNHKFHGNLPP_ServerRsp)
  })
_sym_db.RegisterMessage(Unk2700_FNHKFHGNLPP_ServerRsp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK2700_FNHKFHGNLPP_SERVERRSP._serialized_start=108
  _UNK2700_FNHKFHGNLPP_SERVERRSP._serialized_end=207
# @@protoc_insertion_point(module_scope)
