# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk2800_JKLFAJKDLDG.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/Unk2800_JKLFAJKDLDG.proto\"9\n\x13Unk2800_JKLFAJKDLDG\x12\x10\n\x08quest_id\x18\r \x01(\r\x12\x10\n\x08point_id\x18\x06 \x01(\rB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')



_UNK2800_JKLFAJKDLDG = DESCRIPTOR.message_types_by_name['Unk2800_JKLFAJKDLDG']
Unk2800_JKLFAJKDLDG = _reflection.GeneratedProtocolMessageType('Unk2800_JKLFAJKDLDG', (_message.Message,), {
  'DESCRIPTOR' : _UNK2800_JKLFAJKDLDG,
  '__module__' : 'genshin.packet.proto.Unk2800_JKLFAJKDLDG_pb2'
  # @@protoc_insertion_point(class_scope:Unk2800_JKLFAJKDLDG)
  })
_sym_db.RegisterMessage(Unk2800_JKLFAJKDLDG)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _UNK2800_JKLFAJKDLDG._serialized_start=50
  _UNK2800_JKLFAJKDLDG._serialized_end=107
# @@protoc_insertion_point(module_scope)
