# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk2700_FEODEAEOOKE.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/Unk2700_FEODEAEOOKE.proto\"\'\n\x13Unk2700_FEODEAEOOKE\x12\x10\n\x08level_id\x18\x05 \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_UNK2700_FEODEAEOOKE = DESCRIPTOR.message_types_by_name['Unk2700_FEODEAEOOKE']
Unk2700_FEODEAEOOKE = _reflection.GeneratedProtocolMessageType('Unk2700_FEODEAEOOKE', (_message.Message,), {
  'DESCRIPTOR' : _UNK2700_FEODEAEOOKE,
  '__module__' : 'genshin.packet.proto.Unk2700_FEODEAEOOKE_pb2'
  # @@protoc_insertion_point(class_scope:Unk2700_FEODEAEOOKE)
  })
_sym_db.RegisterMessage(Unk2700_FEODEAEOOKE)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK2700_FEODEAEOOKE._serialized_start=50
  _UNK2700_FEODEAEOOKE._serialized_end=89
# @@protoc_insertion_point(module_scope)
