# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk2700_OHBMICGFIIK.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/Unk2700_OHBMICGFIIK.proto\"\x89\x01\n\x13Unk2700_OHBMICGFIIK\x12\x1b\n\x13Unk2700_DABMGCIOKCK\x18\x04 \x01(\r\x12\x1b\n\x13Unk2700_BKJABFANBIM\x18\x0c \x01(\r\x12\x1b\n\x13Unk2700_PGBNOPOIHIK\x18\x07 \x01(\r\x12\x1b\n\x13Unk2700_DJNLHEBADGE\x18\x02 \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_UNK2700_OHBMICGFIIK = DESCRIPTOR.message_types_by_name['Unk2700_OHBMICGFIIK']
Unk2700_OHBMICGFIIK = _reflection.GeneratedProtocolMessageType('Unk2700_OHBMICGFIIK', (_message.Message,), {
  'DESCRIPTOR' : _UNK2700_OHBMICGFIIK,
  '__module__' : 'genshin.packet.proto.Unk2700_OHBMICGFIIK_pb2'
  # @@protoc_insertion_point(class_scope:Unk2700_OHBMICGFIIK)
  })
_sym_db.RegisterMessage(Unk2700_OHBMICGFIIK)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK2700_OHBMICGFIIK._serialized_start=51
  _UNK2700_OHBMICGFIIK._serialized_end=188
# @@protoc_insertion_point(module_scope)
