# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk2700_HBOFACHAGIF_ServerNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import Unk2700_EKDHFFHMNCD_pb2 as genshin_dot_packet_dot_proto_dot_Unk2700__EKDHFFHMNCD__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;genshin/packet/proto/Unk2700_HBOFACHAGIF_ServerNotify.proto\x1a.genshin/packet/proto/Unk2700_EKDHFFHMNCD.proto\"\xcb\x01\n Unk2700_HBOFACHAGIF_ServerNotify\x12V\n\x13Unk2700_MEANPNKMDFG\x18\x02 \x03(\x0b\x32\x39.Unk2700_HBOFACHAGIF_ServerNotify.Unk2700MEANPNKMDFGEntry\x1aO\n\x17Unk2700MEANPNKMDFGEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.Unk2700_EKDHFFHMNCD:\x02\x38\x01\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_UNK2700_HBOFACHAGIF_SERVERNOTIFY = DESCRIPTOR.message_types_by_name['Unk2700_HBOFACHAGIF_ServerNotify']
_UNK2700_HBOFACHAGIF_SERVERNOTIFY_UNK2700MEANPNKMDFGENTRY = _UNK2700_HBOFACHAGIF_SERVERNOTIFY.nested_types_by_name['Unk2700MEANPNKMDFGEntry']
Unk2700_HBOFACHAGIF_ServerNotify = _reflection.GeneratedProtocolMessageType('Unk2700_HBOFACHAGIF_ServerNotify', (_message.Message,), {

  'Unk2700MEANPNKMDFGEntry' : _reflection.GeneratedProtocolMessageType('Unk2700MEANPNKMDFGEntry', (_message.Message,), {
    'DESCRIPTOR' : _UNK2700_HBOFACHAGIF_SERVERNOTIFY_UNK2700MEANPNKMDFGENTRY,
    '__module__' : 'genshin.packet.proto.Unk2700_HBOFACHAGIF_ServerNotify_pb2'
    # @@protoc_insertion_point(class_scope:Unk2700_HBOFACHAGIF_ServerNotify.Unk2700MEANPNKMDFGEntry)
    })
  ,
  'DESCRIPTOR' : _UNK2700_HBOFACHAGIF_SERVERNOTIFY,
  '__module__' : 'genshin.packet.proto.Unk2700_HBOFACHAGIF_ServerNotify_pb2'
  # @@protoc_insertion_point(class_scope:Unk2700_HBOFACHAGIF_ServerNotify)
  })
_sym_db.RegisterMessage(Unk2700_HBOFACHAGIF_ServerNotify)
_sym_db.RegisterMessage(Unk2700_HBOFACHAGIF_ServerNotify.Unk2700MEANPNKMDFGEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK2700_HBOFACHAGIF_SERVERNOTIFY_UNK2700MEANPNKMDFGENTRY._options = None
  _UNK2700_HBOFACHAGIF_SERVERNOTIFY_UNK2700MEANPNKMDFGENTRY._serialized_options = b'8\001'
  _UNK2700_HBOFACHAGIF_SERVERNOTIFY._serialized_start=112
  _UNK2700_HBOFACHAGIF_SERVERNOTIFY._serialized_end=315
  _UNK2700_HBOFACHAGIF_SERVERNOTIFY_UNK2700MEANPNKMDFGENTRY._serialized_start=236
  _UNK2700_HBOFACHAGIF_SERVERNOTIFY_UNK2700MEANPNKMDFGENTRY._serialized_end=315
# @@protoc_insertion_point(module_scope)
