# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk2700_LELADCCDNJH.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/Unk2700_LELADCCDNJH.proto\"\x8d\x01\n\x13Unk2700_LELADCCDNJH\x12\x1b\n\x13Unk2700_FACFKJKIBBO\x18\x01 \x01(\r\x12\n\n\x02id\x18\x02 \x01(\r\x12\x13\n\x0bis_finished\x18\x07 \x01(\x08\x12\x1b\n\x13Unk2700_MJDCFONLGKN\x18\t \x01(\x08\x12\x1b\n\x13Unk2700_AKAAHELAGHJ\x18\n \x01(\x08\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_UNK2700_LELADCCDNJH = DESCRIPTOR.message_types_by_name['Unk2700_LELADCCDNJH']
Unk2700_LELADCCDNJH = _reflection.GeneratedProtocolMessageType('Unk2700_LELADCCDNJH', (_message.Message,), {
  'DESCRIPTOR' : _UNK2700_LELADCCDNJH,
  '__module__' : 'genshin.packet.proto.Unk2700_LELADCCDNJH_pb2'
  # @@protoc_insertion_point(class_scope:Unk2700_LELADCCDNJH)
  })
_sym_db.RegisterMessage(Unk2700_LELADCCDNJH)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK2700_LELADCCDNJH._serialized_start=51
  _UNK2700_LELADCCDNJH._serialized_end=192
# @@protoc_insertion_point(module_scope)
