# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk2700_PFOLNOBIKFB.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/Unk2700_PFOLNOBIKFB.proto\"`\n\x13Unk2700_PFOLNOBIKFB\x12\x1b\n\x13Unk2700_PIDPNNOGBJB\x18\x04 \x01(\x08\x12\x1b\n\x13Unk2700_DCGOILIDPNK\x18\x03 \x01(\x08\x12\x0f\n\x07retcode\x18\x01 \x01(\x05\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_UNK2700_PFOLNOBIKFB = DESCRIPTOR.message_types_by_name['Unk2700_PFOLNOBIKFB']
Unk2700_PFOLNOBIKFB = _reflection.GeneratedProtocolMessageType('Unk2700_PFOLNOBIKFB', (_message.Message,), {
  'DESCRIPTOR' : _UNK2700_PFOLNOBIKFB,
  '__module__' : 'genshin.packet.proto.Unk2700_PFOLNOBIKFB_pb2'
  # @@protoc_insertion_point(class_scope:Unk2700_PFOLNOBIKFB)
  })
_sym_db.RegisterMessage(Unk2700_PFOLNOBIKFB)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK2700_PFOLNOBIKFB._serialized_start=50
  _UNK2700_PFOLNOBIKFB._serialized_end=146
# @@protoc_insertion_point(module_scope)
