# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk2700_NMJIMIKKIME.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import Unk2700_HJLFNKLPFBH_pb2 as genshin_dot_packet_dot_proto_dot_Unk2700__HJLFNKLPFBH__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/Unk2700_NMJIMIKKIME.proto\x1a.genshin/packet/proto/Unk2700_HJLFNKLPFBH.proto\"e\n\x13Unk2700_NMJIMIKKIME\x12\x1b\n\x13Unk2700_OKGKHPCMNMN\x18\t \x03(\r\x12\x31\n\x13Unk2700_ELOOIKFNJCG\x18\x0b \x03(\x0b\x32\x14.Unk2700_HJLFNKLPFBHB\x16\n\x14org.sorapointa.protob\x06proto3')



_UNK2700_NMJIMIKKIME = DESCRIPTOR.message_types_by_name['Unk2700_NMJIMIKKIME']
Unk2700_NMJIMIKKIME = _reflection.GeneratedProtocolMessageType('Unk2700_NMJIMIKKIME', (_message.Message,), {
  'DESCRIPTOR' : _UNK2700_NMJIMIKKIME,
  '__module__' : 'genshin.packet.proto.Unk2700_NMJIMIKKIME_pb2'
  # @@protoc_insertion_point(class_scope:Unk2700_NMJIMIKKIME)
  })
_sym_db.RegisterMessage(Unk2700_NMJIMIKKIME)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK2700_NMJIMIKKIME._serialized_start=98
  _UNK2700_NMJIMIKKIME._serialized_end=199
# @@protoc_insertion_point(module_scope)
