# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk2700_ICPNKAALJEP.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import Unk2700_KLJLJGJOBDI_pb2 as genshin_dot_packet_dot_proto_dot_Unk2700__KLJLJGJOBDI__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/Unk2700_ICPNKAALJEP.proto\x1a.genshin/packet/proto/Unk2700_KLJLJGJOBDI.proto\"W\n\x13Unk2700_ICPNKAALJEP\x12\x15\n\ris_new_record\x18\x08 \x01(\x08\x12)\n\x0bsettle_info\x18\x0e \x01(\x0b\x32\x14.Unk2700_KLJLJGJOBDIB\x16\n\x14org.sorapointa.protob\x06proto3')



_UNK2700_ICPNKAALJEP = DESCRIPTOR.message_types_by_name['Unk2700_ICPNKAALJEP']
Unk2700_ICPNKAALJEP = _reflection.GeneratedProtocolMessageType('Unk2700_ICPNKAALJEP', (_message.Message,), {
  'DESCRIPTOR' : _UNK2700_ICPNKAALJEP,
  '__module__' : 'genshin.packet.proto.Unk2700_ICPNKAALJEP_pb2'
  # @@protoc_insertion_point(class_scope:Unk2700_ICPNKAALJEP)
  })
_sym_db.RegisterMessage(Unk2700_ICPNKAALJEP)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK2700_ICPNKAALJEP._serialized_start=98
  _UNK2700_ICPNKAALJEP._serialized_end=185
# @@protoc_insertion_point(module_scope)
