# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk2700_KIHEEAGDGIL_ServerNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import Unk2700_DPPCDPBBABA_pb2 as genshin_dot_packet_dot_proto_dot_Unk2700__DPPCDPBBABA__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;genshin/packet/proto/Unk2700_KIHEEAGDGIL_ServerNotify.proto\x1a.genshin/packet/proto/Unk2700_DPPCDPBBABA.proto\"F\n Unk2700_KIHEEAGDGIL_ServerNotify\x12\"\n\x04info\x18\r \x01(\x0b\x32\x14.Unk2700_DPPCDPBBABAB\x16\n\x14org.sorapointa.protob\x06proto3')



_UNK2700_KIHEEAGDGIL_SERVERNOTIFY = DESCRIPTOR.message_types_by_name['Unk2700_KIHEEAGDGIL_ServerNotify']
Unk2700_KIHEEAGDGIL_ServerNotify = _reflection.GeneratedProtocolMessageType('Unk2700_KIHEEAGDGIL_ServerNotify', (_message.Message,), {
  'DESCRIPTOR' : _UNK2700_KIHEEAGDGIL_SERVERNOTIFY,
  '__module__' : 'genshin.packet.proto.Unk2700_KIHEEAGDGIL_ServerNotify_pb2'
  # @@protoc_insertion_point(class_scope:Unk2700_KIHEEAGDGIL_ServerNotify)
  })
_sym_db.RegisterMessage(Unk2700_KIHEEAGDGIL_ServerNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK2700_KIHEEAGDGIL_SERVERNOTIFY._serialized_start=111
  _UNK2700_KIHEEAGDGIL_SERVERNOTIFY._serialized_end=181
# @@protoc_insertion_point(module_scope)
