# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk2700_COGBIJAPDLE.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/Unk2700_COGBIJAPDLE.proto\"&\n\x13Unk2700_COGBIJAPDLE\x12\x0f\n\x07retcode\x18\x03 \x01(\x05\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_UNK2700_COGBIJAPDLE = DESCRIPTOR.message_types_by_name['Unk2700_COGBIJAPDLE']
Unk2700_COGBIJAPDLE = _reflection.GeneratedProtocolMessageType('Unk2700_COGBIJAPDLE', (_message.Message,), {
  'DESCRIPTOR' : _UNK2700_COGBIJAPDLE,
  '__module__' : 'genshin.packet.proto.Unk2700_COGBIJAPDLE_pb2'
  # @@protoc_insertion_point(class_scope:Unk2700_COGBIJAPDLE)
  })
_sym_db.RegisterMessage(Unk2700_COGBIJAPDLE)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK2700_COGBIJAPDLE._serialized_start=50
  _UNK2700_COGBIJAPDLE._serialized_end=88
# @@protoc_insertion_point(module_scope)
