# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk2700_BNABFJBODGE.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/Unk2700_BNABFJBODGE.proto\"l\n\x13Unk2700_BNABFJBODGE\x12\x10\n\x08stage_id\x18\x0c \x01(\r\x12\x10\n\x08skill_id\x18\x0b \x01(\r\x12\x14\n\x0c\x63hallenge_id\x18\n \x01(\r\x12\x1b\n\x13Unk2700_AIKKJGOLLHK\x18\r \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_UNK2700_BNABFJBODGE = DESCRIPTOR.message_types_by_name['Unk2700_BNABFJBODGE']
Unk2700_BNABFJBODGE = _reflection.GeneratedProtocolMessageType('Unk2700_BNABFJBODGE', (_message.Message,), {
  'DESCRIPTOR' : _UNK2700_BNABFJBODGE,
  '__module__' : 'genshin.packet.proto.Unk2700_BNABFJBODGE_pb2'
  # @@protoc_insertion_point(class_scope:Unk2700_BNABFJBODGE)
  })
_sym_db.RegisterMessage(Unk2700_BNABFJBODGE)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK2700_BNABFJBODGE._serialized_start=50
  _UNK2700_BNABFJBODGE._serialized_end=158
# @@protoc_insertion_point(module_scope)
