# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk2700_KLPINMKOEPE.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import Unk2700_IGJLOMCPLLE_pb2 as genshin_dot_packet_dot_proto_dot_Unk2700__IGJLOMCPLLE__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/Unk2700_KLPINMKOEPE.proto\x1a.genshin/packet/proto/Unk2700_IGJLOMCPLLE.proto\"Y\n\x13Unk2700_KLPINMKOEPE\x12\x0f\n\x07room_id\x18\x0f \x01(\r\x12\x31\n\x13Unk2700_ICMKKOMLHIH\x18\x04 \x03(\x0b\x32\x14.Unk2700_IGJLOMCPLLEB\x16\n\x14org.sorapointa.protob\x06proto3')



_UNK2700_KLPINMKOEPE = DESCRIPTOR.message_types_by_name['Unk2700_KLPINMKOEPE']
Unk2700_KLPINMKOEPE = _reflection.GeneratedProtocolMessageType('Unk2700_KLPINMKOEPE', (_message.Message,), {
  'DESCRIPTOR' : _UNK2700_KLPINMKOEPE,
  '__module__' : 'genshin.packet.proto.Unk2700_KLPINMKOEPE_pb2'
  # @@protoc_insertion_point(class_scope:Unk2700_KLPINMKOEPE)
  })
_sym_db.RegisterMessage(Unk2700_KLPINMKOEPE)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK2700_KLPINMKOEPE._serialized_start=98
  _UNK2700_KLPINMKOEPE._serialized_end=187
# @@protoc_insertion_point(module_scope)
