# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk2700_NAPLFKNOECD.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/Unk2700_NAPLFKNOECD.proto\"l\n\x13Unk2700_NAPLFKNOECD\x12\x0c\n\x04type\x18\x0f \x01(\r\x12\x1b\n\x13Unk2700_KJGKBENCNKF\x18\x0b \x01(\x02\x12\r\n\x05value\x18\x03 \x01(\x02\x12\x1b\n\x13Unk2700_POGMHNNJKDM\x18\n \x01(\x02\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_UNK2700_NAPLFKNOECD = DESCRIPTOR.message_types_by_name['Unk2700_NAPLFKNOECD']
Unk2700_NAPLFKNOECD = _reflection.GeneratedProtocolMessageType('Unk2700_NAPLFKNOECD', (_message.Message,), {
  'DESCRIPTOR' : _UNK2700_NAPLFKNOECD,
  '__module__' : 'genshin.packet.proto.Unk2700_NAPLFKNOECD_pb2'
  # @@protoc_insertion_point(class_scope:Unk2700_NAPLFKNOECD)
  })
_sym_db.RegisterMessage(Unk2700_NAPLFKNOECD)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK2700_NAPLFKNOECD._serialized_start=50
  _UNK2700_NAPLFKNOECD._serialized_end=158
# @@protoc_insertion_point(module_scope)
