# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk2700_EAAMIOAFNOD_ServerRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8genshin/packet/proto/Unk2700_EAAMIOAFNOD_ServerRsp.proto\"0\n\x1dUnk2700_EAAMIOAFNOD_ServerRsp\x12\x0f\n\x07retcode\x18\t \x01(\x05\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_UNK2700_EAAMIOAFNOD_SERVERRSP = DESCRIPTOR.message_types_by_name['Unk2700_EAAMIOAFNOD_ServerRsp']
Unk2700_EAAMIOAFNOD_ServerRsp = _reflection.GeneratedProtocolMessageType('Unk2700_EAAMIOAFNOD_ServerRsp', (_message.Message,), {
  'DESCRIPTOR' : _UNK2700_EAAMIOAFNOD_SERVERRSP,
  '__module__' : 'genshin.packet.proto.Unk2700_EAAMIOAFNOD_ServerRsp_pb2'
  # @@protoc_insertion_point(class_scope:Unk2700_EAAMIOAFNOD_ServerRsp)
  })
_sym_db.RegisterMessage(Unk2700_EAAMIOAFNOD_ServerRsp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK2700_EAAMIOAFNOD_SERVERRSP._serialized_start=60
  _UNK2700_EAAMIOAFNOD_SERVERRSP._serialized_end=108
# @@protoc_insertion_point(module_scope)
