# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk2700_JCOIDFNDHPB.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import Unk2700_HLHHNGHJLAO_pb2 as genshin_dot_packet_dot_proto_dot_Unk2700__HLHHNGHJLAO__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/Unk2700_JCOIDFNDHPB.proto\x1a.genshin/packet/proto/Unk2700_HLHHNGHJLAO.proto\"W\n\x13Unk2700_JCOIDFNDHPB\x12)\n\x0bsettle_info\x18\r \x01(\x0b\x32\x14.Unk2700_HLHHNGHJLAO\x12\x15\n\ris_new_record\x18\x0c \x01(\x08\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_UNK2700_JCOIDFNDHPB = DESCRIPTOR.message_types_by_name['Unk2700_JCOIDFNDHPB']
Unk2700_JCOIDFNDHPB = _reflection.GeneratedProtocolMessageType('Unk2700_JCOIDFNDHPB', (_message.Message,), {
  'DESCRIPTOR' : _UNK2700_JCOIDFNDHPB,
  '__module__' : 'genshin.packet.proto.Unk2700_JCOIDFNDHPB_pb2'
  # @@protoc_insertion_point(class_scope:Unk2700_JCOIDFNDHPB)
  })
_sym_db.RegisterMessage(Unk2700_JCOIDFNDHPB)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK2700_JCOIDFNDHPB._serialized_start=98
  _UNK2700_JCOIDFNDHPB._serialized_end=185
# @@protoc_insertion_point(module_scope)
