# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk3000_JFOGFMJDFFF.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/Unk3000_JFOGFMJDFFF.proto\"2\n\x13Unk3000_JFOGFMJDFFF\x12\x1b\n\x13Unk3000_ADJNBMKCHAA\x18\t \x01(\x08\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_UNK3000_JFOGFMJDFFF = DESCRIPTOR.message_types_by_name['Unk3000_JFOGFMJDFFF']
Unk3000_JFOGFMJDFFF = _reflection.GeneratedProtocolMessageType('Unk3000_JFOGFMJDFFF', (_message.Message,), {
  'DESCRIPTOR' : _UNK3000_JFOGFMJDFFF,
  '__module__' : 'genshin.packet.proto.Unk3000_JFOGFMJDFFF_pb2'
  # @@protoc_insertion_point(class_scope:Unk3000_JFOGFMJDFFF)
  })
_sym_db.RegisterMessage(Unk3000_JFOGFMJDFFF)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK3000_JFOGFMJDFFF._serialized_start=50
  _UNK3000_JFOGFMJDFFF._serialized_end=100
# @@protoc_insertion_point(module_scope)
