# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk3100_KLKDONEJEEG.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/Unk3100_KLKDONEJEEG.proto\"\x94\x03\n\x13Unk3100_KLKDONEJEEG\x12\x1b\n\x13Unk3100_EKPCGKFHODO\x18\x08 \x03(\r\x12\x1b\n\x13Unk3100_IFHHJEFBLNI\x18\x0c \x01(\r\x12\x1b\n\x13Unk3100_ENBGIALBGIN\x18\n \x03(\r\x12\x1b\n\x13Unk3100_FBGLNABGPMH\x18\x0b \x03(\r\x12\x1b\n\x13Unk3100_IOCOGKAIBEN\x18\t \x01(\r\x12\x1b\n\x13Unk3100_NMPJHOLLDGD\x18\x01 \x01(\r\x12I\n\x13Unk3100_CJIDDCFJDDJ\x18\x03 \x03(\x0b\x32,.Unk3100_KLKDONEJEEG.Unk3100CJIDDCFJDDJEntry\x12\x0f\n\x07retcode\x18\x07 \x01(\x05\x12\x1b\n\x13Unk3100_JCIBNDGDKPK\x18\x0e \x01(\r\x12\x1b\n\x13Unk3100_PKFCBGPFEOE\x18\x0f \x01(\r\x1a\x39\n\x17Unk3100CJIDDCFJDDJEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_UNK3100_KLKDONEJEEG = DESCRIPTOR.message_types_by_name['Unk3100_KLKDONEJEEG']
_UNK3100_KLKDONEJEEG_UNK3100CJIDDCFJDDJENTRY = _UNK3100_KLKDONEJEEG.nested_types_by_name['Unk3100CJIDDCFJDDJEntry']
Unk3100_KLKDONEJEEG = _reflection.GeneratedProtocolMessageType('Unk3100_KLKDONEJEEG', (_message.Message,), {

  'Unk3100CJIDDCFJDDJEntry' : _reflection.GeneratedProtocolMessageType('Unk3100CJIDDCFJDDJEntry', (_message.Message,), {
    'DESCRIPTOR' : _UNK3100_KLKDONEJEEG_UNK3100CJIDDCFJDDJENTRY,
    '__module__' : 'genshin.packet.proto.Unk3100_KLKDONEJEEG_pb2'
    # @@protoc_insertion_point(class_scope:Unk3100_KLKDONEJEEG.Unk3100CJIDDCFJDDJEntry)
    })
  ,
  'DESCRIPTOR' : _UNK3100_KLKDONEJEEG,
  '__module__' : 'genshin.packet.proto.Unk3100_KLKDONEJEEG_pb2'
  # @@protoc_insertion_point(class_scope:Unk3100_KLKDONEJEEG)
  })
_sym_db.RegisterMessage(Unk3100_KLKDONEJEEG)
_sym_db.RegisterMessage(Unk3100_KLKDONEJEEG.Unk3100CJIDDCFJDDJEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK3100_KLKDONEJEEG_UNK3100CJIDDCFJDDJENTRY._options = None
  _UNK3100_KLKDONEJEEG_UNK3100CJIDDCFJDDJENTRY._serialized_options = b'8\001'
  _UNK3100_KLKDONEJEEG._serialized_start=51
  _UNK3100_KLKDONEJEEG._serialized_end=455
  _UNK3100_KLKDONEJEEG_UNK3100CJIDDCFJDDJENTRY._serialized_start=398
  _UNK3100_KLKDONEJEEG_UNK3100CJIDDCFJDDJENTRY._serialized_end=455
# @@protoc_insertion_point(module_scope)
