# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk3000_GCBMILHPIKA.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/Unk3000_GCBMILHPIKA.proto\"\xf7\x01\n\x13Unk3000_GCBMILHPIKA\x12\x0f\n\x07retcode\x18\n \x01(\x05\x12\x45\n\x13Unk3000_EBIEGNHLMFP\x18\x05 \x03(\x0b\x32(.Unk3000_GCBMILHPIKA.Unk3000_PPGINNAFPIF\x1a\x87\x01\n\x13Unk3000_PPGINNAFPIF\x12\x1b\n\x13Unk3000_CLMLONOEHLB\x18\x07 \x01(\r\x12\x1b\n\x13Unk3000_HCAJDIBHKDG\x18\x0c \x01(\r\x12\x19\n\x11next_refresh_time\x18\x0e \x01(\r\x12\x1b\n\x13Unk3000_LOFNFMJFGNB\x18\x02 \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_UNK3000_GCBMILHPIKA = DESCRIPTOR.message_types_by_name['Unk3000_GCBMILHPIKA']
_UNK3000_GCBMILHPIKA_UNK3000_PPGINNAFPIF = _UNK3000_GCBMILHPIKA.nested_types_by_name['Unk3000_PPGINNAFPIF']
Unk3000_GCBMILHPIKA = _reflection.GeneratedProtocolMessageType('Unk3000_GCBMILHPIKA', (_message.Message,), {

  'Unk3000_PPGINNAFPIF' : _reflection.GeneratedProtocolMessageType('Unk3000_PPGINNAFPIF', (_message.Message,), {
    'DESCRIPTOR' : _UNK3000_GCBMILHPIKA_UNK3000_PPGINNAFPIF,
    '__module__' : 'genshin.packet.proto.Unk3000_GCBMILHPIKA_pb2'
    # @@protoc_insertion_point(class_scope:Unk3000_GCBMILHPIKA.Unk3000_PPGINNAFPIF)
    })
  ,
  'DESCRIPTOR' : _UNK3000_GCBMILHPIKA,
  '__module__' : 'genshin.packet.proto.Unk3000_GCBMILHPIKA_pb2'
  # @@protoc_insertion_point(class_scope:Unk3000_GCBMILHPIKA)
  })
_sym_db.RegisterMessage(Unk3000_GCBMILHPIKA)
_sym_db.RegisterMessage(Unk3000_GCBMILHPIKA.Unk3000_PPGINNAFPIF)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK3000_GCBMILHPIKA._serialized_start=51
  _UNK3000_GCBMILHPIKA._serialized_end=298
  _UNK3000_GCBMILHPIKA_UNK3000_PPGINNAFPIF._serialized_start=163
  _UNK3000_GCBMILHPIKA_UNK3000_PPGINNAFPIF._serialized_end=298
# @@protoc_insertion_point(module_scope)
