# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk3100_NNJNENGFHII.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/Unk3100_NNJNENGFHII.proto\"B\n\x13Unk3100_NNJNENGFHII\x12\x1b\n\x13Unk3100_BCHHFFJEJCD\x18\x05 \x01(\r\x12\x0e\n\x06\x63oin_c\x18\x0b \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_UNK3100_NNJNENGFHII = DESCRIPTOR.message_types_by_name['Unk3100_NNJNENGFHII']
Unk3100_NNJNENGFHII = _reflection.GeneratedProtocolMessageType('Unk3100_NNJNENGFHII', (_message.Message,), {
  'DESCRIPTOR' : _UNK3100_NNJNENGFHII,
  '__module__' : 'genshin.packet.proto.Unk3100_NNJNENGFHII_pb2'
  # @@protoc_insertion_point(class_scope:Unk3100_NNJNENGFHII)
  })
_sym_db.RegisterMessage(Unk3100_NNJNENGFHII)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK3100_NNJNENGFHII._serialized_start=50
  _UNK3100_NNJNENGFHII._serialized_end=116
# @@protoc_insertion_point(module_scope)
