# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk3000_LLBHCMKJJHB.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import Vector_pb2 as genshin_dot_packet_dot_proto_dot_Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/Unk3000_LLBHCMKJJHB.proto\x1a!genshin/packet/proto/Vector.proto\"b\n\x13Unk3000_LLBHCMKJJHB\x12\x10\n\x08scene_id\x18\x05 \x01(\r\x12\x14\n\x03pos\x18\t \x01(\x0b\x32\x07.Vector\x12\x10\n\x08group_id\x18\x07 \x01(\r\x12\x11\n\tconfig_id\x18\x03 \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_UNK3000_LLBHCMKJJHB = DESCRIPTOR.message_types_by_name['Unk3000_LLBHCMKJJHB']
Unk3000_LLBHCMKJJHB = _reflection.GeneratedProtocolMessageType('Unk3000_LLBHCMKJJHB', (_message.Message,), {
  'DESCRIPTOR' : _UNK3000_LLBHCMKJJHB,
  '__module__' : 'genshin.packet.proto.Unk3000_LLBHCMKJJHB_pb2'
  # @@protoc_insertion_point(class_scope:Unk3000_LLBHCMKJJHB)
  })
_sym_db.RegisterMessage(Unk3000_LLBHCMKJJHB)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK3000_LLBHCMKJJHB._serialized_start=85
  _UNK3000_LLBHCMKJJHB._serialized_end=183
# @@protoc_insertion_point(module_scope)
