# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk3000_GDKMIBFADKD.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import Vector_pb2 as genshin_dot_packet_dot_proto_dot_Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/Unk3000_GDKMIBFADKD.proto\x1a!genshin/packet/proto/Vector.proto\"X\n\x13Unk3000_GDKMIBFADKD\x12\r\n\x05index\x18\x08 \x01(\x03\x12\x0c\n\x04\x61rea\x18\x05 \x01(\x05\x12$\n\x13Unk3000_AOEGLPPFIFD\x18\x01 \x01(\x0b\x32\x07.VectorB\x16\n\x14org.sorapointa.protob\x06proto3')



_UNK3000_GDKMIBFADKD = DESCRIPTOR.message_types_by_name['Unk3000_GDKMIBFADKD']
Unk3000_GDKMIBFADKD = _reflection.GeneratedProtocolMessageType('Unk3000_GDKMIBFADKD', (_message.Message,), {
  'DESCRIPTOR' : _UNK3000_GDKMIBFADKD,
  '__module__' : 'genshin.packet.proto.Unk3000_GDKMIBFADKD_pb2'
  # @@protoc_insertion_point(class_scope:Unk3000_GDKMIBFADKD)
  })
_sym_db.RegisterMessage(Unk3000_GDKMIBFADKD)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK3000_GDKMIBFADKD._serialized_start=85
  _UNK3000_GDKMIBFADKD._serialized_end=173
# @@protoc_insertion_point(module_scope)
