# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk3100_ADOMNIEPKEK.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/Unk3100_ADOMNIEPKEK.proto\"-\n\x13Unk3100_ADOMNIEPKEK\x12\x16\n\x0e\x65ntity_id_list\x18\x07 \x03(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_UNK3100_ADOMNIEPKEK = DESCRIPTOR.message_types_by_name['Unk3100_ADOMNIEPKEK']
Unk3100_ADOMNIEPKEK = _reflection.GeneratedProtocolMessageType('Unk3100_ADOMNIEPKEK', (_message.Message,), {
  'DESCRIPTOR' : _UNK3100_ADOMNIEPKEK,
  '__module__' : 'genshin.packet.proto.Unk3100_ADOMNIEPKEK_pb2'
  # @@protoc_insertion_point(class_scope:Unk3100_ADOMNIEPKEK)
  })
_sym_db.RegisterMessage(Unk3100_ADOMNIEPKEK)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK3100_ADOMNIEPKEK._serialized_start=50
  _UNK3100_ADOMNIEPKEK._serialized_end=95
# @@protoc_insertion_point(module_scope)
