# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk3100_LDKPEAGMAGH.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/Unk3100_LDKPEAGMAGH.proto\"&\n\x13Unk3100_LDKPEAGMAGH\x12\x0f\n\x07retcode\x18\x01 \x01(\x05\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_UNK3100_LDKPEAGMAGH = DESCRIPTOR.message_types_by_name['Unk3100_LDKPEAGMAGH']
Unk3100_LDKPEAGMAGH = _reflection.GeneratedProtocolMessageType('Unk3100_LDKPEAGMAGH', (_message.Message,), {
  'DESCRIPTOR' : _UNK3100_LDKPEAGMAGH,
  '__module__' : 'genshin.packet.proto.Unk3100_LDKPEAGMAGH_pb2'
  # @@protoc_insertion_point(class_scope:Unk3100_LDKPEAGMAGH)
  })
_sym_db.RegisterMessage(Unk3100_LDKPEAGMAGH)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK3100_LDKPEAGMAGH._serialized_start=50
  _UNK3100_LDKPEAGMAGH._serialized_end=88
# @@protoc_insertion_point(module_scope)
