# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/Unk3000_AHNHHIOAHBC.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.genshin/packet/proto/Unk3000_AHNHHIOAHBC.proto*\xaf\x01\n\x13Unk3000_AHNHHIOAHBC\x12\x1c\n\x18Unk3000_AHNHHIOAHBC_NONE\x10\x00\x12+\n\'Unk3000_AHNHHIOAHBC_Unk3000_IKCFCMNEEAO\x10\x01\x12+\n\'Unk3000_AHNHHIOAHBC_Unk3000_BCPDDCDJHHA\x10\x02\x12 \n\x1cUnk3000_AHNHHIOAHBC_FINISHED\x10\x03\x42\x16\n\x14org.sorapointa.protob\x06proto3')

_UNK3000_AHNHHIOAHBC = DESCRIPTOR.enum_types_by_name['Unk3000_AHNHHIOAHBC']
Unk3000_AHNHHIOAHBC = enum_type_wrapper.EnumTypeWrapper(_UNK3000_AHNHHIOAHBC)
Unk3000_AHNHHIOAHBC_NONE = 0
Unk3000_AHNHHIOAHBC_Unk3000_IKCFCMNEEAO = 1
Unk3000_AHNHHIOAHBC_Unk3000_BCPDDCDJHHA = 2
Unk3000_AHNHHIOAHBC_FINISHED = 3


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _UNK3000_AHNHHIOAHBC._serialized_start=51
  _UNK3000_AHNHHIOAHBC._serialized_end=226
# @@protoc_insertion_point(module_scope)
