# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/UseMiracleRingReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import Vector_pb2 as genshin_dot_packet_dot_proto_dot_Vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,genshin/packet/proto/UseMiracleRingReq.proto\x1a!genshin/packet/proto/Vector.proto\"\xd3\x01\n\x11UseMiracleRingReq\x12\x1c\n\x14miracle_ring_op_type\x18\r \x01(\r\x12\x14\n\x03pos\x18\x08 \x01(\x0b\x32\x07.Vector\x12\x14\n\x03rot\x18\x07 \x01(\x0b\x32\x07.Vector\"t\n\x11MiracleRingOpType\x12\x1d\n\x19MIRACLE_RING_OP_TYPE_NONE\x10\x00\x12\x1e\n\x1aMIRACLE_RING_OP_TYPE_PLACE\x10\x01\x12 \n\x1cMIRACLE_RING_OP_TYPE_RETRACT\x10\x02\x42\x16\n\x14org.sorapointa.protob\x06proto3')



_USEMIRACLERINGREQ = DESCRIPTOR.message_types_by_name['UseMiracleRingReq']
_USEMIRACLERINGREQ_MIRACLERINGOPTYPE = _USEMIRACLERINGREQ.enum_types_by_name['MiracleRingOpType']
UseMiracleRingReq = _reflection.GeneratedProtocolMessageType('UseMiracleRingReq', (_message.Message,), {
  'DESCRIPTOR' : _USEMIRACLERINGREQ,
  '__module__' : 'genshin.packet.proto.UseMiracleRingReq_pb2'
  # @@protoc_insertion_point(class_scope:UseMiracleRingReq)
  })
_sym_db.RegisterMessage(UseMiracleRingReq)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _USEMIRACLERINGREQ._serialized_start=84
  _USEMIRACLERINGREQ._serialized_end=295
  _USEMIRACLERINGREQ_MIRACLERINGOPTYPE._serialized_start=179
  _USEMIRACLERINGREQ_MIRACLERINGOPTYPE._serialized_end=295
# @@protoc_insertion_point(module_scope)
