# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/VisionType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%genshin/packet/proto/VisionType.proto*\xb0\x04\n\nVisionType\x12\x14\n\x10VISION_TYPE_NONE\x10\x00\x12\x14\n\x10VISION_TYPE_MEET\x10\x01\x12\x16\n\x12VISION_TYPE_REBORN\x10\x02\x12\x17\n\x13VISION_TYPE_REPLACE\x10\x03\x12\x1f\n\x1bVISION_TYPE_WAYPOINT_REBORN\x10\x04\x12\x14\n\x10VISION_TYPE_MISS\x10\x05\x12\x13\n\x0fVISION_TYPE_DIE\x10\x06\x12\x1d\n\x19VISION_TYPE_GATHER_ESCAPE\x10\x07\x12\x17\n\x13VISION_TYPE_REFRESH\x10\x08\x12\x19\n\x15VISION_TYPE_TRANSPORT\x10\t\x12\x1b\n\x17VISION_TYPE_REPLACE_DIE\x10\n\x12!\n\x1dVISION_TYPE_REPLACE_NO_NOTIFY\x10\x0b\x12\x14\n\x10VISION_TYPE_BORN\x10\x0c\x12\x16\n\x12VISION_TYPE_PICKUP\x10\r\x12\x16\n\x12VISION_TYPE_REMOVE\x10\x0e\x12\x1e\n\x1aVISION_TYPE_CHANGE_COSTUME\x10\x0f\x12\x1c\n\x18VISION_TYPE_FISH_REFRESH\x10\x10\x12\x1e\n\x1aVISION_TYPE_FISH_BIG_SHOCK\x10\x11\x12\x1d\n\x19VISION_TYPE_FISH_QTE_SUCC\x10\x12\x12#\n\x1fVISION_TYPE_Unk2700_EPFKMOIPADB\x10\x13\x42\x16\n\x14org.sorapointa.protob\x06proto3')

_VISIONTYPE = DESCRIPTOR.enum_types_by_name['VisionType']
VisionType = enum_type_wrapper.EnumTypeWrapper(_VISIONTYPE)
VISION_TYPE_NONE = 0
VISION_TYPE_MEET = 1
VISION_TYPE_REBORN = 2
VISION_TYPE_REPLACE = 3
VISION_TYPE_WAYPOINT_REBORN = 4
VISION_TYPE_MISS = 5
VISION_TYPE_DIE = 6
VISION_TYPE_GATHER_ESCAPE = 7
VISION_TYPE_REFRESH = 8
VISION_TYPE_TRANSPORT = 9
VISION_TYPE_REPLACE_DIE = 10
VISION_TYPE_REPLACE_NO_NOTIFY = 11
VISION_TYPE_BORN = 12
VISION_TYPE_PICKUP = 13
VISION_TYPE_REMOVE = 14
VISION_TYPE_CHANGE_COSTUME = 15
VISION_TYPE_FISH_REFRESH = 16
VISION_TYPE_FISH_BIG_SHOCK = 17
VISION_TYPE_FISH_QTE_SUCC = 18
VISION_TYPE_Unk2700_EPFKMOIPADB = 19


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _VISIONTYPE._serialized_start=42
  _VISIONTYPE._serialized_end=602
# @@protoc_insertion_point(module_scope)
