# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/WidgetCreatorInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from genshin.packet.proto import WidgetCreateLocationInfo_pb2 as genshin_dot_packet_dot_proto_dot_WidgetCreateLocationInfo__pb2
from genshin.packet.proto import WidgetCreatorOpType_pb2 as genshin_dot_packet_dot_proto_dot_WidgetCreatorOpType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,genshin/packet/proto/WidgetCreatorInfo.proto\x1a\x33genshin/packet/proto/WidgetCreateLocationInfo.proto\x1a.genshin/packet/proto/WidgetCreatorOpType.proto\"\x7f\n\x11WidgetCreatorInfo\x12%\n\x07op_type\x18\n \x01(\x0e\x32\x14.WidgetCreatorOpType\x12\x11\n\tentity_id\x18\x01 \x01(\r\x12\x30\n\rlocation_info\x18\x0c \x01(\x0b\x32\x19.WidgetCreateLocationInfoB\x1b\n\x19\x65mu.grasscutter.net.protob\x06proto3')



_WIDGETCREATORINFO = DESCRIPTOR.message_types_by_name['WidgetCreatorInfo']
WidgetCreatorInfo = _reflection.GeneratedProtocolMessageType('WidgetCreatorInfo', (_message.Message,), {
  'DESCRIPTOR' : _WIDGETCREATORINFO,
  '__module__' : 'genshin.packet.proto.WidgetCreatorInfo_pb2'
  # @@protoc_insertion_point(class_scope:WidgetCreatorInfo)
  })
_sym_db.RegisterMessage(WidgetCreatorInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031emu.grasscutter.net.proto'
  _WIDGETCREATORINFO._serialized_start=149
  _WIDGETCREATORINFO._serialized_end=276
# @@protoc_insertion_point(module_scope)
