# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genshin/packet/proto/WorldRoutineTypeCloseNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6genshin/packet/proto/WorldRoutineTypeCloseNotify.proto\"3\n\x1bWorldRoutineTypeCloseNotify\x12\x14\n\x0croutine_type\x18\x07 \x01(\rB\x16\n\x14org.sorapointa.protob\x06proto3')



_WORLDROUTINETYPECLOSENOTIFY = DESCRIPTOR.message_types_by_name['WorldRoutineTypeCloseNotify']
WorldRoutineTypeCloseNotify = _reflection.GeneratedProtocolMessageType('WorldRoutineTypeCloseNotify', (_message.Message,), {
  'DESCRIPTOR' : _WORLDROUTINETYPECLOSENOTIFY,
  '__module__' : 'genshin.packet.proto.WorldRoutineTypeCloseNotify_pb2'
  # @@protoc_insertion_point(class_scope:WorldRoutineTypeCloseNotify)
  })
_sym_db.RegisterMessage(WorldRoutineTypeCloseNotify)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024org.sorapointa.proto'
  _WORLDROUTINETYPECLOSENOTIFY._serialized_start=58
  _WORLDROUTINETYPECLOSENOTIFY._serialized_end=109
# @@protoc_insertion_point(module_scope)
